import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {Game} from '../src/engine.js';
import {HEROES,WEAPON,LIMITS} from '../src/content.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=path.join(root,'test-results');await fs.mkdir(output,{recursive:true});
const artifact=path.join(root,'dist/AstraNocturne.html'),html=await fs.readFile(artifact,'utf8');
assert.equal(html.includes('__NOCTURNE_TEST__'),false,'production must have no test controls');
assert.ok(Buffer.byteLength(html)<8*1024*1024,'single-file mobile payload budget');
const browser=await chromium.launch({headless:true});const errors=[],requests=[];
const pageFor=async(viewport)=>{const context=await browser.newContext({viewport,deviceScaleFactor:1,hasTouch:true,offline:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.route('**/*',r=>/^https?:/.test(r.request().url())?r.abort():r.continue());return {page,context};};
const noOverflow=async(page)=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflows horizontally');
const start=async(page,url)=>{await page.goto(url);await page.locator('[data-action="start"]').waitFor();await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.fonts.check('17px Nocturne','별빛 정원')),true,'embedded Korean font loads');};
const proof=async(page,name)=>{await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});};
try{
  // These checks boot the actual committed artifact, without instrumentation.
  for(const [width,height] of [[390,844],[360,640],[320,568],[844,390],[1280,900]]){
    const {page,context}=await pageFor({width,height});await start(page,pathToFileURL(artifact).href);await noOverflow(page);
    assert.equal(await page.locator('.hero-pick').count(),9);for(const id of ['jasmine','cinderella','silver_rabbit']){await page.locator(`[data-action="select-hero"][data-value="${id}"]`).click();assert.equal(await page.locator(`[data-action="select-hero"][data-value="${id}"]`).getAttribute('aria-pressed'),'true');}
    await proof(page,`home-${width}x${height}`);const dock=await page.locator('.lobby-dock').boundingBox(),launch=await page.locator('.launch .primary').boundingBox();assert.ok(dock.y+dock.height<=height+1);assert.ok(launch.y>=dock.y&&launch.y+launch.height<=dock.y+dock.height);assert.equal(await page.locator('.nav .menu-art').count(),4);
    await page.locator('[data-action="run-mode"][data-value="endless"]').click();assert.equal(await page.locator('[data-action="run-mode"][data-value="endless"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('.launch .primary').textContent(),/끝없는 밤/);
    await page.reload();await page.locator('[data-action="start"]').waitFor();assert.equal(await page.locator('[data-action="run-mode"][data-value="endless"]').getAttribute('aria-pressed'),'true','run mode persists');await page.locator('[data-action="run-mode"][data-value="expedition"]').click();assert.equal(await page.locator('.stage-pick .duration').count(),3);assert.match(await page.locator('.stage-pick .duration').first().textContent(),/2분/);
    await page.locator('[data-action="tab"][data-value="library"]').click();await page.locator('[data-action="detail"][data-value="rumi"]').click();assert.match(await page.locator('.dialog-content').textContent(),/맨발/);await page.keyboard.press('Escape');assert.equal(await page.locator('[role="dialog"]').count(),0);
    await page.locator('[data-action="library-tab"][data-value="weapons"]').click();await page.locator('[data-action="detail"][data-value="star"]').click();assert.match(await page.locator('.dialog-content').textContent(),/천 갈래 프리즘/);await page.locator('[data-action="close"]').first().click();
    await page.locator('[data-action="library-tab"][data-value="recipes"]').click();assert.equal(await page.locator('.recipe-card').count(),14);assert.equal(await page.locator('.bond-card').count(),4);await noOverflow(page);await proof(page,`recipes-${width}x${height}`);
    await page.locator('[data-action="library-tab"][data-value="secrets"]').click();assert.equal(await page.locator('.secret-card').count(),4);assert.equal(await page.locator('.awakening-list article').count(),3);await noOverflow(page);await proof(page,`secrets-${width}x${height}`);
    await page.locator('[data-action="settings"]').click();assert.equal(await page.locator('select').count(),0,'settings use designed tiles');
    const fixed=page.locator('[role="radio"][data-value="fixed"]');await fixed.click();assert.equal(await fixed.getAttribute('aria-checked'),'true');await fixed.press('ArrowRight');assert.equal(await page.locator('[role="radio"][data-value="floating"]').getAttribute('aria-checked'),'true');
    await page.locator('[role="radio"][data-value="economy"]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.profile.v1')).settings.quality),'economy');await page.locator('[role="radio"][data-value="auto"]').click();await proof(page,`settings-${width}x${height}`);await page.locator('[data-action="close"]').first().click();
    if(width===390){await page.locator('[data-action="fullscreen"]').click();await page.waitForFunction(()=>!!document.fullscreenElement);assert.equal(await page.locator('[data-action="fullscreen"]').getAttribute('aria-pressed'),'true');await page.keyboard.press('f');await page.waitForFunction(()=>!document.fullscreenElement);}
    await page.locator('[data-action="tab"][data-value="home"]').click();await page.locator('[data-action="start"]').click();await page.locator('#battle-canvas').waitFor();await page.waitForTimeout(100);
    const begin=await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.run.v1')).player);
    const box=await page.locator('#battle-canvas').boundingBox(),session=await context.newCDPSession(page);const x=Math.round(box.x+box.width*.35),y=Math.round(box.y+box.height*.6);
    await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+65,y:y-20,id:1}]});await page.waitForTimeout(350);
    assert.equal(await page.locator('#joystick').evaluate(el=>el.classList.contains('active')),true);
    const dash=await page.locator('[data-action="dash"]').boundingBox();assert.ok(dash.x+dash.width/2>width*.65,'dash belongs to the right thumb');await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x+65,y:y-20,id:1},{x:Math.round(dash.x+dash.width/2),y:Math.round(dash.y+dash.height/2),id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{x:Math.round(dash.x+dash.width/2),y:Math.round(dash.y+dash.height/2),id:2}]});await page.waitForTimeout(80);assert.equal(await page.locator('#joystick').evaluate(el=>el.classList.contains('active')),true,'second finger must preserve movement');
    await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.locator('#joystick').evaluate(el=>el.classList.contains('active')),false);
    await page.locator('[data-action="pause"]').click();const moved=await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.run.v1')).player);assert.ok(Math.hypot(moved.x-begin.x,moved.y-begin.y)>15,'real touch movement');
    await page.locator('[data-action="leave"]').click();assert.equal(await page.locator('[data-action="resume"]').count(),1);await page.locator('[data-action="resume"]').click();await page.locator('[data-action="pause"]').click();const resumed=await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.run.v1')).player);assert.ok(Math.hypot(resumed.x-moved.x,resumed.y-moved.y)<5,'resume preserves position');await proof(page,`pause-${width}x${height}`);const footer=await page.locator('.pause-dialog .dialog-footer').boundingBox();assert.ok(footer.y+footer.height<=height,'pause actions stay reachable');assert.equal(await page.locator('.pause-actions .menu-art').count(),4);await page.locator('[data-action="pause-tab"][data-value="equipment"]').click();assert.ok(await page.locator('.pause-gear .item-art').count()>0);await page.locator('[data-action="pause-tab"][data-value="growth"]').click();await page.locator('[data-action="pause-tab"][data-value="overview"]').click();await noOverflow(page);await page.locator('[data-action="unpause"]').click();await page.keyboard.down('ArrowLeft');await page.waitForTimeout(220);await page.keyboard.up('ArrowLeft');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.locator('[data-action="unpause"]').waitFor();const keyboardMoved=await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.run.v1')));assert.ok(keyboardMoved.player.x<resumed.x-15,'keyboard movement');assert.equal(keyboardMoved.mode,'paused','window blur safely pauses and saves');await page.reload();await page.locator('[data-action="resume"]').waitFor();await page.locator('[data-action="resume"]').click();await page.locator('#battle-canvas').waitFor();await context.close();
    console.log(`PASS actual offline artifact ${width}x${height}: touch, multi-touch, codex, pause, resume`);
  }
  // A temporary copy exposes App only for endgame/rare-state browser fixtures.
  // Assets, CSS, actual engine/UI source and release controls remain identical.
  const bundled=await build({entryPoints:[path.join(root,'src/app.js')],bundle:true,write:false,format:'iife',target:['es2020'],minify:true,charset:'utf8',plugins:[{name:'test-only-app-reference',setup(b){b.onLoad({filter:/survivor[\\/]src[\\/]app\.js$/},async args=>({contents:(await fs.readFile(args.path,'utf8')).replace('const app=new App();','const app=new App();globalThis.__NOCTURNE_TEST__=app;'),loader:'js'}));}}]});
  const temp=await fs.mkdtemp(path.join(os.tmpdir(),'nocturne-browser-'));const testFile=path.join(temp,'game.html');const scriptStart=html.lastIndexOf('<script>'),scriptEnd=html.lastIndexOf('</script>');await fs.writeFile(testFile,html.slice(0,scriptStart+8)+bundled.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+html.slice(scriptEnd));
  const {page,context}=await pageFor({width:390,height:844});await start(page,pathToFileURL(testFile).href);
  await page.locator('[data-action="start"]').click();
  // Exercise the actual App loop, renderer pose and camera with synthetic display
  // timestamps. Simulation is still 60 Hz, including frames with zero steps.
  const motion=await page.evaluate(()=>{
    const a=globalThis.__NOCTURNE_TEST__,r=a.renderer,original=a.frame,savedGame=a.game,results=[],raf=globalThis.requestAnimationFrame,settings=r.settings;
    globalThis.requestAnimationFrame=()=>0;r.settings={...settings,motion:true,quality:'high'};
    for(const hz of [60,90,120,144])for(const jitter of [false,true]){
      const g=new savedGame.constructor({seed:5});g.introSpawned=true;g.spawnTimer=1000;g.eliteTimer=1000;g.weapons[0].timer=1000;
      a.game=g;a.keys=new Set(['KeyD']);a.accum=0;r.camera={x:800,y:800};r.cameraTarget=undefined;r.fx=[];r.shake=0;
      let timestamp=performance.now()+1000;a.lastTime=timestamp;let lastX=null,lastScreen=null,stalls=0,reversals=0,idle=0,maxError=0;
      for(let frame=0;frame<hz;frame++){
        const dt=(jitter?[.8,1.25,.95,1][frame%4]:1)/hz;timestamp+=dt*1000;original.call(a,timestamp);
        const x=r.pose.x,screen=x-r.camera.x;if(!r.walking)idle++;
        if(frame>3){if(x<=lastX)stalls++;if(screen<=lastScreen)reversals++;maxError=Math.max(maxError,Math.abs((x-lastX)/dt-175));}lastX=x;lastScreen=screen;
      }
      const before=JSON.stringify(g.snapshot());r.render(g,1/hz,{x:1,y:0},a.accum/(1/60));results.push({hz,jitter,stalls,reversals,idle,maxError,pure:before===JSON.stringify(g.snapshot())});
    }
    globalThis.requestAnimationFrame=raf;a.game=savedGame;a.keys.clear();a.accum=0;a.lastTime=0;r.settings=settings;r.camera={x:savedGame.player.x,y:savedGame.player.y};r.cameraTarget=undefined;return results;
  });
  for(const sample of motion){assert.equal(sample.stalls,0,JSON.stringify(sample));assert.equal(sample.reversals,0,JSON.stringify(sample));assert.equal(sample.idle,0,JSON.stringify(sample));assert.ok(sample.maxError<1e-5,JSON.stringify(sample));assert.equal(sample.pure,true,'render does not mutate combat');}
  await fs.writeFile(path.join(output,'motion-hz.json'),JSON.stringify(motion,null,2)+'\n');console.log('PASS actual App + Renderer movement/camera at 60/90/120/144 Hz and irregular frame intervals');
  await page.evaluate(()=>{const app=globalThis.__NOCTURNE_TEST__;app.game.gainXP(80);});await page.locator('[data-action="choice"]').first().waitFor();await proof(page,'level-choice');
  const time=await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.time);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.time),time,'choice freezes combat');
  const beforeRecipe=await page.evaluate(()=>JSON.stringify(globalThis.__NOCTURNE_TEST__.game.options));
  await page.locator('.dialog [data-action="recipes"]').click();await page.locator('[data-action="track-recipe"][data-value="sun"]').click();await proof(page,'battle-recipe-map');assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.time),time);
  const quality=await page.evaluate(()=>{const app=globalThis.__NOCTURNE_TEST__,r=app.renderer,before=JSON.stringify(app.game.snapshot());r.settings.quality='auto';for(let i=0;i<95;i++)r.observeFrame(18,35);const low=r.autoTier;for(let i=0;i<370;i++)r.observeFrame(2,16);return {low,high:r.autoTier,same:before===JSON.stringify(app.game.snapshot()),cache:r.cache.size};});assert.equal(quality.low,0);assert.equal(quality.high,1);assert.equal(quality.same,true,'quality must never alter combat');
  await page.locator('[data-action="recipe-back"]').click();assert.equal(await page.evaluate(()=>JSON.stringify(globalThis.__NOCTURNE_TEST__.game.options)),beforeRecipe);assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.focusRecipe),'sun');
  const rolls=await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.rerolls);await page.locator('[data-action="reroll"]').click();assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.rerolls),rolls-1);
  await page.locator('[data-action="banish-menu"]').click();await page.locator('[data-action="banish"]:not([disabled])').first().click();assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.banishes),1);
  for(let i=0;i<10&&await page.locator('[data-action="choice"]').count();i++)await page.locator('[data-action="choice"]').first().click();
  await page.evaluate(()=>{const a=globalThis.__NOCTURNE_TEST__,g=new a.game.constructor({runMode:'endless',seed:35});g.introSpawned=true;g.spawnTimer=1000;g.eliteTimer=1000;g.weapons[0].timer=1000;g.encounters=[{id:g.uid++,kind:'lantern',x:800,y:800,life:40,progress:2.99,used:false,title:'등불',secret:'portal'}];a.launch(g);});
  await page.locator('[data-action="encounter"].visible').waitFor();await proof(page,'hidden-altar');await page.locator('[data-action="encounter"]').click();await page.locator('[data-action="encounter-choice"]').first().waitFor();await proof(page,'hidden-bargain');
  const bargain=await page.evaluate(()=>({time:globalThis.__NOCTURNE_TEST__.game.time,hp:globalThis.__NOCTURNE_TEST__.game.player.maxHp}));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.time),bargain.time);
  await page.reload();await page.locator('[data-action="resume"]').click();await page.locator('[data-action="encounter-choice"]').first().waitFor();assert.equal(await page.locator('[data-action="encounter-choice"]').count(),3,'pending hidden choice survives reload');
  await page.locator('[data-action="encounter-choice"]').first().click();assert.ok(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.secrets.includes('portal')));assert.ok(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.player.maxHp)<bargain.hp);assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.profile.v1')).discoveries.includes('portal')));
  await page.keyboard.press('Shift');await page.locator('#dash-label').getByText('문으로 돌아가기').waitFor();await proof(page,'hidden-portal');await page.locator('[data-action="pause"]').click();await page.locator('[data-action="leave"]').click();await page.locator('[data-action="resume"]').click();assert.ok(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.portal));assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.runMode),'endless');
  const snapshot=new Game({hero:'snow_rabbit',seed:10}).snapshot();snapshot.time=90;snapshot.level=23;snapshot.need=1000; // Isolate the crowded skill/treasure fixture from unrelated XP choices.
snapshot.player.charge=100;snapshot.player.x=760;snapshot.player.y=730;
  snapshot.weapons=[['frost',6],['ember',5],['dream',4],['storm',5],['sun',4],['flower',5]].map(([id,level])=>({id,level,evolved:false,timer:.01,damage:1000}));snapshot.relics=[{id:'frost',level:2},{id:'seed',level:2},{id:'ember',level:2},{id:'lantern',level:1}];
  const g=Game.restore(snapshot);for(let i=0;i<65;i++){const a=i*Math.PI*2/65,d=110+(i%5)*24;g.spawnEnemy(i%7===0?'beetle':i%11===0?'moth':'wisp',{x:g.player.x+Math.cos(a)*d,y:g.player.y+Math.sin(a)*d,hp:220,maxHp:220});}g.spawnEnemy('boss',{x:g.player.x+100,y:g.player.y-200,hp:4500,maxHp:4500,name:'밤의 파수꾼'});g.bossesSpawned=2;
  await page.evaluate(data=>{const app=globalThis.__NOCTURNE_TEST__;const restored=app.game.constructor.restore(data);app.launch(restored);},g.snapshot());await page.waitForTimeout(300);await proof(page,'mobile-horde');await page.locator('[data-action="skill"]').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.skilled),1);await proof(page,'frozen-world');
  await page.evaluate(()=>{const a=globalThis.__NOCTURNE_TEST__;a.game.mode='playing';a.game.weapons[0].level=6;a.game.openTreasure();});await page.locator('[data-action="claim-treasure"]').waitFor();await proof(page,'evolution-treasure');const evolvedId=await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.treasure.id);assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.treasure.type),'evolution');await page.locator('[data-action="claim-treasure"]').click();assert.equal(await page.evaluate(id=>globalThis.__NOCTURNE_TEST__.game.weapons.find(w=>w.id===id).evolved,evolvedId),true);
  await page.locator('[data-action="pause"]').click();await page.locator('[data-action="settings"]').click();await page.locator('[data-action="toggle"][data-value="effects"]').click();assert.equal(await page.locator('[data-value="effects"]').getAttribute('aria-checked'),'false');await page.keyboard.press('Escape');await page.locator('[data-action="unpause"]').waitFor();assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.mode),'paused');await page.locator('[data-action="unpause"]').click();await page.keyboard.press('Shift');assert.ok(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.dashes)>0);
  // Finish through a real damage event, including the final boss / chest race.
  await page.evaluate(()=>{const a=globalThis.__NOCTURNE_TEST__,g=a.game;g.mode='playing';g.pending=0;g.options=[];const boss=g.spawnEnemy('boss',{x:g.player.x,y:g.player.y,hp:1,maxHp:1,final:true,name:'마지막 그림자'});g.hit(boss,10000,'frost');});await page.locator('[data-action="result-home"]').waitFor();await proof(page,'victory-result');const crystals=await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.profile.crystals);assert.ok(crystals>0);assert.equal(await page.evaluate(()=>localStorage.getItem('astra.nocturne.run.v1')),null);assert.equal(await page.locator('[data-action="retry"]').isEnabled(),true,'retry remains available after a successful settlement');
  await page.locator('[data-action="result-home"]').click();await page.locator('[data-action="tab"][data-value="growth"]').click();const before=await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.profile.crystals);await page.locator('[data-action="buy-meta"][data-value="power"]').click();assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.profile.meta.power),1);assert.ok(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.profile.crystals)<before);await proof(page,'memories');await page.locator('[data-action="tab"][data-value="records"]').click();await proof(page,'journal');
  const storedCrystals=await page.evaluate(()=>JSON.parse(localStorage.getItem('astra.nocturne.profile.v1')).crystals);
  await page.evaluate(()=>{const a=globalThis.__NOCTURNE_TEST__;a.launch();const persistent=localStorage;a.storage.storage={getItem:key=>persistent.getItem(key),setItem(key,value){if(key==='astra.nocturne.profile.v1')throw new DOMException('quota','QuotaExceededError');persistent.setItem(key,value);},removeItem:key=>persistent.removeItem(key)};a.game.kills=120;a.game.finish(false);});
  await page.locator('[data-action="result-home"]').waitFor();assert.ok(await page.locator('.storage-notice').getByText(/원정 기록/).isVisible());
  const failedSettlement=await page.evaluate(()=>({memory:globalThis.__NOCTURNE_TEST__.profile.crystals,persisted:JSON.parse(localStorage.getItem('astra.nocturne.profile.v1')).crystals,run:localStorage.getItem('astra.nocturne.run.v1')}));assert.ok(failedSettlement.memory>storedCrystals);assert.equal(failedSettlement.persisted,storedCrystals);assert.ok(failedSettlement.run);
  const retry=page.locator('[data-action="retry"]'),retryDisabled=await retry.isDisabled();await retry.dispatchEvent('click');assert.equal(await page.evaluate(()=>localStorage.getItem('astra.nocturne.run.v1')),failedSettlement.run,'retry must not overwrite the recoverable expedition');assert.equal(retryDisabled,true,'retry is disabled until settlement can be saved');
  await page.reload();await page.locator('[data-action="resume"]').waitFor();assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.profile.crystals),storedCrystals);
  // Every hero, cardinal direction and skill is exercised by the actual renderer.
  for(const h of HEROES){const run=new Game({hero:h.id,seed:14});run.player.charge=100;run.spawnEnemy('beetle',{x:840,y:820,hp:5000,maxHp:5000,damage:0});await page.evaluate(data=>{const a=globalThis.__NOCTURNE_TEST__;if(!a.game)a.launch();a.launch(a.game.constructor.restore(data));},run.snapshot());assert.equal(await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.hero),h.id);
    await page.evaluate(async()=>{await Promise.all(globalThis.__NOCTURNE_TEST__.art.pending.values());});assert.ok(await page.evaluate(()=>Object.keys(globalThis.__NOCTURNE_TEST__.art.images).filter(id=>id.startsWith('walk-')).length)<=2,'only two recent walking sheets are decoded');
    await page.evaluate(()=>{const a=globalThis.__NOCTURNE_TEST__;a.game.castSkill();a.game.player.facing=0;});await page.waitForTimeout(60);await proof(page,'hero-'+h.id);for(const direction of [1,2,3])await page.evaluate(dir=>{const a=globalThis.__NOCTURNE_TEST__;a.game.player.facing=dir;a.renderer.render(a.game,1/60);},direction);
  }
  for(let index=3;index<9;index++){
    const kind=await page.evaluate(index=>{const a=globalThis.__NOCTURNE_TEST__,g=new a.game.constructor({hero:'rumi',runMode:'endless',seed:123});g.time=g.duration+(index-2)*60;g.bossesSpawned=index;g.director(.01);const boss=g.enemies.find(e=>e.boss);g.bossAttack(boss);a.launch(g);g.mode='paused';a.renderer.render(g,0);a.updateHUD();return boss.bossKind;},index);
    await proof(page,'ordeal-'+kind);
    await page.evaluate(()=>{const a=globalThis.__NOCTURNE_TEST__;a.game.mode='playing';a.pause();});
    await page.locator('[data-action="leave"]').click();await page.locator('[data-action="resume"]').click();
    const restored=await page.evaluate(()=>globalThis.__NOCTURNE_TEST__.game.enemies.find(e=>e.boss));assert.equal(restored.bossKind,kind);assert.ok(restored.overrun>0,'overtime survives real save/resume');
  }
  const work=await page.evaluate(()=>{
    const a=globalThis.__NOCTURNE_TEST__,g=new a.game.constructor({seed:78});
    for(const id of ['blade','ember','flower','frost','storm'])g.applyOption({type:'weapon',id});for(const w of g.weapons){w.level=6;w.evolved=true;}
    for(let i=0;i<260;i++){const angle=i*Math.PI*2/260,r=90+(i%8)*24;g.spawnEnemy(i%4===0?'beetle':i%4===1?'moth':i%4===2?'stalker':'wisp',{x:800+Math.cos(angle)*r,y:800+Math.sin(angle)*r,hp:100000,maxHp:100000,damage:0,speed:1});}
    const renderer=a.renderer,settings=renderer.settings;renderer.settings={...settings,effects:true,numbers:true};const start=performance.now();
    for(let frame=0;frame<90;frame++){g.step(1/60);renderer.events(g.drainEvents());renderer.render(g,1/60);}
    const meanWorkMs=(performance.now()-start)/90;renderer.settings=settings;
    return{frames:90,meanWorkMs:+meanWorkMs.toFixed(2),enemies:g.enemies.length,shots:g.shots.length,fields:g.fields.length,hazards:g.hazards.length};
  });
  assert.equal(work.enemies,LIMITS.enemies);for(const key of ['shots','fields','hazards'])assert.ok(work[key]<=LIMITS[key]);assert.ok(Number.isFinite(work.meanWorkMs));
  await fs.writeFile(path.join(output,'render-work.json'),JSON.stringify(work,null,2)+'\n');console.log('PASS crowded renderer work sample (cloud CPU, not phone FPS): '+JSON.stringify(work));
  // Storage denial / corrupted run still allow a new expedition.
  const denied=await browser.newContext({viewport:{width:360,height:640},offline:true});await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked storage');}}));const deniedPage=await denied.newPage();deniedPage.on('pageerror',e=>errors.push(e.message));await start(deniedPage,pathToFileURL(artifact).href);await deniedPage.locator('[data-action="start"]').click();await deniedPage.locator('#battle-canvas').waitFor();await deniedPage.locator('[data-action="pause"]').click();await deniedPage.locator('[data-action="leave"]').click();assert.equal(await deniedPage.locator('.pause-dialog').count(),1,'failed save keeps the run open');assert.ok(await deniedPage.locator('.save-status.unsaved').count());await denied.close();
  await context.close();await fs.rm(temp,{recursive:true,force:true});assert.deepEqual(requests,[],'release must not request external resources');assert.deepEqual(errors,[],'runtime errors');
  console.log('PASS rare states: choice, reroll, banish, crowded combat, skill, evolution, reward, growth, all guardians, blocked storage');
}finally{await browser.close();}
