import {HERO,HEROES,ARTIFACT,ARTIFACTS,RARITY,RARITIES,DEFAULT_DECK,CHAPTERS,BOSSES,BOSS_ORDER,BLESSING,TUNING as T,QUOTES} from './content.js';
import {calendar,duplicateCost,enhanceMultiplier,specialMultiplier,levelCost,heroMultiplier,combatPower,dispatchSlots,dispatchReward,relicTier,relicThreshold,relicRates,idleReward,HOUR} from './economy.js';
import {ProfileStore,available,away,teamPower} from './profile.js';
import {createBattle,resumeBattle,autoPlay,clearedRounds} from './battle.js';
import * as E from './combat/engine.js';
import {Art,Renderer} from './combat/render.js';
import {Sound} from './combat/audio.js';
import {icon} from './icons.js';

const $=id=>document.getElementById(id),storage={getItem:k=>window.localStorage.getItem(k),setItem:(k,v)=>window.localStorage.setItem(k,v)};
const store=new ProfileStore(storage),art=new Art(),sound=new Sound();
const p=()=>store.value,now=()=>Math.max(Date.now(),p().clockAt),fmt=n=>Number.isFinite(n)?n>=100000?new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(n):Math.floor(n).toLocaleString('ko-KR'):'—';
const pct=n=>(n*100).toFixed(n<.001?3:2)+'%';
let screen='home',collection='hero',rarity='all',ownedOnly=false,banner='normal',mode='main',cycle=Math.floor(p().cleared/9),
  modal=null,modalInfo=null,previousFocus=null,toastTimer,run=null,renderer=null,speed=1,paused=false,selected=-1,pointer=null,
  lastFrame=0,accumulator=0,autoIn=0,saveIn=0,uiIn=0,previousPhase='',lastResult=null;
const media=window.__GARDEN_MEDIA__||{};
const fallback=id=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128"><circle cx="64" cy="64" r="40" fill="${HERO[id]?.color||'#abc8b4'}"/><text x="64" y="80" text-anchor="middle" fill="#fff" font-size="38">✦</text></svg>`);
const picture=(id,full=false)=>media[(full?'figure:':'portrait:')+id]||media['relic:'+id]||fallback(id);
const image=(id,full=false,cls='')=>`<img class="${cls}" src="${picture(id,full)}" alt="${HERO[id]?.name||ARTIFACT[id]?.name||'별빛'}" draggable="false">`;
const rarityStyle=r=>`--rarity:${RARITY[r].color};--tint:${({C:'#e5ece3',R:'#e4eef3',SR:'#eee5f2',UR:'#f6ecd6'})[r]}`;
const badge=r=>`<span class="badge" style="${rarityStyle(r)}">${r}</span>`;
function toast(text){if(!text)return;clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2800);}
function settings(){sound.enabled=p().settings.sound;sound.music=p().settings.sound;sound.setVolume(.2);$('app').dataset.reduced=String(p().settings.reduced||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches);if(renderer)renderer.reduced=$('app').dataset.reduced==='true';}
function wallet(){const profile=p();$('dreams').textContent=fmt(profile.dreams);$('dust').textContent=fmt(profile.dust);$('save-warning').hidden=!store.broken&&!store.conflict;$('save-warning').textContent=store.warning||'다른 창에서 저장이 바뀌었어요. 이 창을 새로고침해 주세요.';settings();}
function act(action,args={},showToast=true){const result=store.transact(action,args,now());wallet();if(!result.ok||showToast)toast(result.message);return result;}
function nav(){const ready=p().dispatches.some(d=>d.end<=now());$('navigation').innerHTML=[['home','정원'],['collection','수집'],['adventure','모험'],['summon','소환'],['dispatch','파견']].map(([id,name])=>`<button class="nav-item" data-nav="${id}" ${screen===id?'aria-current="page"':''}>${icon(id)}<span>${name}</span>${id==='dispatch'&&ready?'<i class="dot"></i>':''}</button>`).join('');$('navigation').hidden=screen==='battle'||screen==='draft';}
function render(){$('app').dataset.screen=screen;wallet();nav();$('content').scrollTop=0;if(screen==='battle')return renderBattle();if(screen==='draft')return renderDraft();const templates={home:home,collection:renderCollection,adventure:adventure,summon:renderSummon,dispatch:renderDispatch};$('content').innerHTML=(templates[screen]||home)();}
const heading=(en,title,right='')=>`<div class="page-heading"><div><span class="eyebrow">${en}</span><h1>${title}</h1></div>${right}</div>`;
function five(ids,empty=true){return `<div class="five-line">${Array.from({length:5},(_,i)=>ids[i]?`<button class="team-slot" data-hero="${ids[i]}" aria-label="${HERO[ids[i]].name} 정보"><span class="portrait" style="border-color:${RARITY[HERO[ids[i]].rarity].color}">${image(ids[i])}</span><small>${HERO[ids[i]].name}</small></button>`:`<button class="team-slot" data-action="team" aria-label="${i+1}번째 동료 선택"><span class="portrait draft-dot">＋</span><small>동료 선택</small></button>`).join('')}</div>`;}
function home(){
  const profile=p(),hero=HERO[profile.partner],c=calendar(now()),quote=(QUOTES[hero.id]||['오늘도 당신의 정원에 별이 자라고 있어.','함께 떠날 준비가 됐어요.'])[profile.heroes[hero.id].bond%2],stage=Math.min(45,profile.cleared+1),idle=idleReward(profile,now()),daily=profile.daily.day===c.day?profile.daily:{claimed:[]};
  return `<section class="scene" aria-label="${hero.name}과 함께하는 정원"><div class="scene-title"><span class="eyebrow">A LITTLE STAR, EVERY DAY</span><h1>별이 머무는 정원</h1></div><button class="season-note" data-action="season"><span>${c.month} · 이달의 수호자</span><b>${HERO[c.guardian].name} ✦ UR</b></button>${image(hero.id,true,'scene-partner')}<p class="dialogue">“${quote}”</p><div class="partner-label"><strong>${hero.name}</strong><small>${hero.title} · 마음 ${profile.heroes[hero.id].bond}</small></div><div class="partner-actions"><button class="glass-button" data-action="pet">${profile.petDay===c.day?'인사 완료':'인사 · ◆ 40'}</button><button class="glass-button" data-action="partner" aria-label="파트너 변경">⇄</button></div></section>
    <section class="home-body"><div class="section-label"><h3>오늘의 다섯 동료</h3><button data-action="team">편성 · ${fmt(teamPower(profile))} CP ›</button></div>${five(profile.deck)}
    <button class="primary depart" data-action="${profile.active?'resume':'prepare'}" data-stage="${stage}">${icon('adventure')}<span>${profile.active?'진행 중인 원정 이어가기':profile.cleared===45?'별길 다시 걷기':'다음 별길로 출발'}<small>${profile.active?profile.active.mode==='weekly'?'이번 주의 별빛 드래프트':profile.active.mode==='monthly'?'이번 달의 보스 챌린지':`${profile.active.stage}번째 별길`:`${CHAPTERS[stage-1].name} · ${BOSSES[BOSS_ORDER[(stage-1)%9]].name}`}</small></span><em>${String(stage).padStart(2,'0')} ›</em></button>
    <div class="card idle-card">${icon('leaf')}<div><strong>정원이 모은 별가루 <b id="idle-total">${fmt(idle)}</b></strong><small>시간당 ${14+profile.cleared*2}개 · 최대 20시간</small><div class="progress"><span id="idle-progress" style="width:${Math.min(100,(now()-profile.idleAt)/(20*HOUR)*100)}%"></span></div></div><button class="secondary" data-action="idle" ${idle<1?'disabled':''}>수령</button></div>
    <div class="quiet-row"><span>별길 ${profile.cleared}/45 · 수집 ${HEROES.filter(h=>profile.heroes[h.id].owned).length}/30</span><button data-action="daily">오늘의 발자국 ${daily.claimed.length}/3 ›</button></div></section>`;
}
function card(id,kind='hero',receipt=null){const h=kind==='hero'?HERO[id]:ARTIFACT[id],e=kind==='hero'?p().heroes[id]:p().relics[id],ready=e.owned&&e.copies>=duplicateCost(e.enhance);return `<button class="hero-card ${!e.owned?'locked':''}" data-${kind==='hero'?'hero':'relic'}="${id}" data-rarity="${h.rarity}" style="${rarityStyle(h.rarity)}" aria-label="${h.name}, ${h.rarity}, ${e.owned?'보유':'미보유'}">${badge(h.rarity)}<span class="status">${receipt?(receipt.fresh?'NEW':'중복 +1'):e.owned?`+${e.enhance}`:''}</span>${image(id)}<strong>${h.name}</strong><small class="${kind==='hero'&&away(p(),id)?'away':ready?'ready':''}">${receipt?receipt.fresh?'새로운 만남':'강화 재료로 보관':!e.owned?h.hidden?'해당 월 시즌 소환':'소환에서 만날 수 있어요':kind==='hero'&&away(p(),id)?'별길 파견 중':ready?'강화 가능 ✦':kind==='hero'?`Lv.${e.level} · ${fmt(combatPower(id,e))} CP`:`중복 ${e.copies}/${duplicateCost(e.enhance)}`}</small></button>`;}
function renderCollection(){const list=collection==='hero'?HEROES:ARTIFACTS,table=collection==='hero'?p().heroes:p().relics,filtered=list.filter(h=>(rarity==='all'||h.rarity===rarity)&&(!ownedOnly||table[h.id].owned)),count=list.filter(h=>table[h.id].owned).length;return `<section class="page">${heading('MY LITTLE CONSTELLATION','별의 도감',`<span class="count">${String(count).padStart(2,'0')}<small> / ${list.length}</small></span>`)}<div class="segmented"><button data-collection="hero" aria-pressed="${collection==='hero'}">동료</button><button data-collection="relic" aria-pressed="${collection==='relic'}">유물 · 장착 ${p().equipped.length}/3</button></div><div class="filters">${['all',...RARITIES].map(r=>`<button data-filter="${r}" aria-pressed="${rarity===r}">${r==='all'?'전체':r}</button>`).join('')}<button class="owned-toggle" data-action="owned" aria-pressed="${ownedOnly}">보유만</button></div><div class="collection-grid">${filtered.map(h=>card(h.id,collection)).join('')||'<p class="empty">이 자리에 새로운 별이 자랄 거예요.<br>다른 등급이나 전체 도감을 확인해 주세요.</p>'}</div><p class="collection-foot">같은 동료와 유물을 만나면 강화 재료로 보관돼요.</p></section>`;}
function heroDetail(id){const h=HERO[id],e=p().heroes[id];if(!h)return;const mult=heroMultiplier(e),enh=duplicateCost(e.enhance),lvl=levelCost(e.level),isAway=away(p(),id);show(h.name,'COMPANION · '+h.rarity,`<div class="detail-hero" style="${rarityStyle(h.rarity)}">${image(id,true)}<div>${badge(h.rarity)}<h3>${h.title}</h3><small>${h.role}</small><small>${h.hidden?'이달의 수호자 · 시즌 한정':''}${isAway?' · 파견 중':''}</small></div></div>
      <div class="metrics"><div class="metric"><small>전투력</small><b>${e.owned?fmt(combatPower(id,e)):'—'}</b></div><div class="metric"><small>레벨</small><b>${e.owned?e.level:'—'}</b></div><div class="metric"><small>강화</small><b>+${e.enhance}</b></div></div><div class="ability"><h3>일반 공격 · ${h.role.split(' · ')[1]} / ${e.owned?(h.damage*mult).toFixed(1):h.damage} 위력</h3><p>${h.trait.text}</p></div><div class="ability"><h3>${h.skill.name} · 별빛 ${h.skill.cost}</h3><p>${h.skill.text}</p></div>
      ${e.owned?`<div class="growth-row"><div><strong>레벨 성장 · 기본 위력 +4%</strong><small>Lv.${e.level} → ${e.level+1} · 별가루 ${fmt(lvl)}개</small></div><button class="primary" data-level="${id}" ${p().dust<lvl||p().active?'disabled':''}>성장</button></div><div class="growth-row"><div><strong>중복 강화 · 기본 위력 +10%</strong><small>중복 ${fmt(e.copies)} / ${fmt(enh)}장 · +${e.enhance} → +${e.enhance+1}</small></div><button class="secondary" data-enhance="${id}" ${e.copies<enh||p().active?'disabled':''}>강화</button></div><p class="fineprint">현재 위력 배율 ${mult.toFixed(2)}배. 강화는 기본 위력에 매회 10%를 더합니다. 제어·지원 효과는 별도 ${((specialMultiplier(e.enhance)-1)*100).toFixed(1)}% 보정을 받으며 최대 15%에 접근해요. 범위·발동 조건은 유지돼요.</p>${p().active?'<p class="fineprint">진행 중인 원정을 마치면 성장을 이어갈 수 있어요.</p>':''}`:`<p class="empty">${h.hidden?`매월 한 수호자만 시즌 소환에서 등장해요.<br>이달의 수호자: ${HERO[calendar(now()).guardian].name}`:`${h.rarity} 등급 동료 소환에서 만나세요.`}</p>`}`,
      e.owned?`<div class="dialog-buttons"><button class="secondary" data-set-partner="${id}">${p().partner===id?'현재 파트너':'정원 파트너로'}</button><button class="primary" data-action="team" ${isAway?'disabled':''}>편성 확인</button></div>`:`<button class="primary wide" data-action="go-summon">소환으로</button>`,'hero',id);}
function relicDetail(id){const a=ARTIFACT[id],e=p().relics[id],cost=duplicateCost(e.enhance);show(a.name,'RELIC · '+a.rarity,`<div class="detail-hero">${image(id)}<div>${badge(a.rarity)}<h3>${a.name}</h3><small>${p().equipped.includes(id)?'장착 중':'유물'} · 강화 +${e.enhance}</small></div></div><div class="ability"><h3>원정 효과</h3><p>${a.text}</p></div>${e.owned?`<div class="growth-row"><div><strong>동일 유물 강화</strong><small>중복 ${e.copies}/${cost}개 · 원정 위력 기본 +${(e.enhance*2).toFixed(0)}% → +${((e.enhance+1)*2).toFixed(0)}%</small></div><button class="secondary" data-enhance-relic="${id}" ${e.copies<cost||p().active?'disabled':''}>강화</button></div><p class="fineprint">장착한 유물만 강화 보정을 줍니다. 기존 고유 효과는 유지하고, 강화마다 원정 전체 위력을 2% 더해요. 등급별 고유 효과 수치는 추후 조정할 수 있습니다.</p>`:'<p class="empty">유물 소환에서 발견할 수 있어요.<br>소환을 거듭할수록 높은 등급의 확률이 자라요.</p>'}`,e.owned?`<button class="primary wide" data-equip="${id}" ${p().active?'disabled':''}>${p().equipped.includes(id)?'장착 해제':'원정 유물로 장착'} · ${p().equipped.length}/3</button>`:`<button class="primary wide" data-action="go-relic-summon">유물 소환으로</button>`,'relic',id);}
function adventure(){const next=Math.min(45,p().cleared+1);cycle=Math.min(4,Math.max(0,cycle));const stageRows=CHAPTERS.slice(cycle*9,cycle*9+9).map(c=>`<button class="stage-row ${c.stage===next?'current':''}" data-prepare-stage="${c.stage}" ${c.stage>p().cleared+1?'disabled':''}><span class="stage-number">${String(c.stage).padStart(2,'0')}</span><div><strong>${BOSSES[c.bosses[0]].name}</strong><small>${c.name} · 6웨이브 · 보스 2회</small></div><span class="stage-status">${c.stage<=p().cleared?'클리어 ✓':c.stage===next?'도전 ›':'잠김'}</span></button>`).join('');return `<section class="page">${heading('FOLLOW YOUR STARS','별길 모험',`<button class="secondary" data-action="records">기록</button>`)}<div class="segmented">${[['main','메인 별길'],['weekly','주간 드래프트'],['monthly','월간 보스']].map(([id,name])=>`<button data-mode="${id}" aria-pressed="${mode===id}">${name}</button>`).join('')}</div>${mode==='main'?`<div class="chapter-banner"><span class="eyebrow">CYCLE ${cycle+1} · 9 GUARDIANS</span><h2>같은 별, 더 먼 여정</h2><p>${p().cleared}/45 클리어 · 파견 보상 +${p().cleared*5}%<br>다음 파견 슬롯 ${p().cleared<36?9*(Math.floor(p().cleared/9)+1)+'스테이지':'모두 해금'}</p><span class="big-cycle">${cycle+1}</span></div><div class="cycle-tabs">${Array.from({length:5},(_,i)=>`<button data-cycle="${i}" aria-pressed="${cycle===i}">${i*9+1}–${i*9+9}</button>`).join('')}</div><div class="stage-list">${stageRows}</div>`:modeCard(mode)}</section>`;}
function modeCard(kind){const weekly=kind==='weekly',used=p()[kind]===calendar(now())[weekly?'week':'month'],unlocked=p().cleared>=3;return `<div class="card mode-card ${kind}"><span class="mode-watermark">${weekly?'✧':'♛'}</span><span class="tag">${weekly?'주 1회 · 월요일 00:00 갱신':'월 1회 · 매월 1일 00:00 갱신'}</span><h2>${weekly?'운명이 고르는 다섯 별':'아홉 수호자의 끝없는 도전'}</h2><p>${weekly?'보유한 모든 동료 중 두 선택지에서 하나씩 고르세요. 다섯 동료로 완성한 팀이 빠르게 강해지는 적의 물결을 돌파합니다. 라운드 제한은 35초입니다.':'매 웨이브 보스만 한 명 등장합니다. 30초 안에 격파해 다음 보스에게 도전하세요. 범위 공격보다 단일 대상 화력과 약화 효과가 빛나는 원정이에요.'}</p><div class="metrics"><div class="metric"><small>입장</small><b>${used?'사용':'1회'}</b></div><div class="metric"><small>적 HP / 라운드</small><b>×${weekly?'1.85':'1.72'}</b></div><div class="metric"><small>라운드 보상</small><b>◆ ${weekly?'60':'50'}</b></div></div><p>${weekly?'기본 보상 120 + 클리어 라운드당 60':'기본 보상 150 + 격파 보스당 50'} 꿈의결정.<br>파견 중인 동료는 참여할 수 없어요. 중단 후 같은 원정을 이어갈 수 있어요.</p><button class="primary wide" data-action="prepare-mode" ${!unlocked||used||p().active?'disabled':''}>${!unlocked?'메인 3스테이지에서 열려요':used?'이번 기간의 입장 완료':weekly?'주간 드래프트 준비':'보스 챌린지 준비'}</button><p class="fineprint">모든 기간은 한국·일본 시간(UTC+9) 기준입니다. 입장을 확정하면 이번 기간의 1회를 사용해요.</p></div>`;}
function renderSummon(){const c=calendar(now()),featured=banner==='season'?c.guardian:banner==='relic'?'broken_clock':'snow_rabbit',tier=relicTier(p().relicDraws),remaining=relicThreshold(tier+1)-p().relicDraws,cost=banner==='relic'?T.relicDrawCost:T.heroDrawCost;return `<section class="page">${heading('A NEW LITTLE MIRACLE','별의 소환')}<div class="segmented">${[['normal','일반 소환'],['season','시즌 소환'],['relic','유물 소환']].map(([id,name])=>`<button data-banner="${id}" aria-pressed="${banner===id}">${name}</button>`).join('')}</div><div class="summon-banner ${banner}"><span class="eyebrow">${banner==='season'?c.month+' · SEASON GUARDIAN':banner==='relic'?'LITTLE TREASURES':'EVERY STAR HAS A STORY'}</span><h2>${banner==='season'?HERO[featured].name:banner==='relic'?'기억을 담은 유물':'새로운 동료와<br>첫 인사'}</h2><p>${banner==='season'?'이번 달, 별길을 지키는<br>단 한 명의 수호자.<br>기적은 UR의 모습으로.':banner==='relic'?`발견 ${fmt(p().relicDraws)}회 · 아틀리에 ${tier}단계<br>다음 단계까지 ${fmt(remaining)}회<br>반복 발견은 강화 재료로.`:'24명의 동료와<br>여섯 시즌 수호자.<br>작은 인연부터,<br>오래 기다려 온 기적까지.'}</p>${image(featured,banner!=='relic','banner-figure')}<span class="banner-rarity">${badge(banner==='season'?'UR':banner==='relic'?'UR':'C')}${banner==='season'?' · 시즌 한정':''}</span></div>
    ${banner==='relic'?`<div class="progress"><span style="width:${100*(p().relicDraws-relicThreshold(tier))/(relicThreshold(tier+1)-relicThreshold(tier))}%"></span></div>`:''}
    <div class="summon-actions"><button class="secondary" data-draw="1">1회 소환<small>◆ ${cost}</small></button><button class="primary gold-button" data-draw="10">10회 소환<small>◆ ${cost*10}</small></button></div><div class="summon-meta"><button data-action="rates">확률 · 획득 안내 ›</button><button data-action="history">소환 기록 ${Math.min(50,p().history.length)} ›</button></div>
    <div class="card"><div class="section-label"><h3>${banner==='relic'?'발견 확률이 함께 자라요':'모든 만남은 성장으로'}</h3>${icon('summon')}</div><p class="subtext">${banner==='relic'?'첫 단계는 C 96%. 발견을 거듭할수록 R·SR·UR 확률이 높아져요. 다음 단계 요구 횟수는 계속 커집니다.':'신규 동료는 도감에, 같은 동료는 전용 강화 재료에 보관돼요. SR은 차곡차곡, UR은 긴 여정의 목표로 만나세요.'}</p></div></section>`;}
function rates(){const c=calendar(now()),rates=banner==='relic'?relicRates(p().relicDraws):T.heroRates;let rows=RARITIES.map((r,i)=>`<div class="rate-row"><span>${badge(r)} ${RARITY[r].name}</span><b>${pct(rates[i])}</b></div>`).join('');if(banner==='season')rows+=`<div class="rate-row"><span>일반 UR 6종 합계</span><b>0.100%</b></div><div class="rate-row"><span>UR · ${HERO[c.guardian].name}</span><b>0.100%</b></div>`;
  show('소환 확률과 규칙','SUMMON DETAILS',`<p class="subtext">${banner==='relic'?`유물 아틀리에 ${relicTier(p().relicDraws)}단계 · 누적 ${fmt(p().relicDraws)}회`:'동료 1회당 확률 · 등급 내 6종은 동일 확률'}</p>${rows}<p class="fineprint">${banner==='season'?'UR 총 0.2% 중 일반 UR 몫 0.1%, 이달의 수호자 몫 0.1%입니다. 다른 달 수호자는 등장하지 않아요.':'일반 동료 소환에는 히든 수호자가 등장하지 않아요.'}<br>1회와 10회의 단일 확률은 같습니다. 확정 등급·천장은 없어요. 10회 소환 중 유물 단계가 바뀌면 다음 1회부터 새 확률을 적용해요.<br>꿈의결정 가격: 동료 100, 유물 80개. 중복은 해당 대상의 강화 재료 1개로 저장됩니다.</p><details><summary>등급별 획득 대상</summary>${(banner==='relic'?ARTIFACTS:HEROES.filter(h=>!h.hidden||banner==='season'&&h.id===c.guardian)).map(h=>`<div class="rate-row"><span>${h.name}</span>${badge(h.rarity)}</div>`).join('')}</details>`,`<button class="primary wide" data-action="close">확인</button>`,'rates');}
function draw(count){const result=act('draw',{banner,count},false);if(!result.ok)return;render();const best=result.items.reduce((a,b)=>RARITIES.indexOf((HERO[b.id]||ARTIFACT[b.id]).rarity)>RARITIES.indexOf((HERO[a.id]||ARTIFACT[a.id]).rarity)?b:a);show('새로운 별이 도착했어요','SUMMON RESULT · '+(HERO[best.id]||ARTIFACT[best.id]).rarity,`<p class="reveal-caption">${result.items.filter(i=>i.fresh).length}개의 새로운 만남 · 꿈의결정 ${result.cost}개 사용</p><div class="reveal-grid ${count===1?'single':''}">${result.items.map((item,i)=>card(item.id,banner==='relic'?'relic':'hero',item).replace('style="','style="animation-delay:'+i*.035+'s;')).join('')}</div>`,`<div class="dialog-buttons"><button class="secondary" data-action="go-collection">도감에서 보기</button><button class="primary" data-action="close">정원에 초대 완료</button></div>`,'draw');}
function renderDispatch(){const count=dispatchSlots(p().cleared),cards=Array.from({length:4},(_,slot)=>{const d=p().dispatches.find(x=>x.slot===slot);if(slot>=count)return `<div class="card dispatch-card locked"><div class="lock-content"><span>별길 파견 ${slot+1} · ${9*(slot+1)}스테이지 클리어</span>${icon('lock')}</div></div>`;if(!d)return `<div class="card dispatch-card"><div class="dispatch-card-top"><span class="dispatch-slot-number">0${slot+1}</span><div><h3>새로운 별길이 기다려요</h3><small>동료 1명 · 20시간 · 전투 참여 불가</small></div>${icon('dispatch')}</div><button class="secondary" data-dispatch-slot="${slot}" ${p().active?'disabled':''}>파견할 동료 선택</button></div>`;const done=d.end<=now();return `<div class="card dispatch-card"><div class="dispatch-card-top">${image(d.hero,true)}<div><h3>${HERO[d.hero].name}</h3><small>꿈의결정 ◆ ${d.reward}개<br><span data-timer="${d.end}">${done?'귀환 완료 · 수령 대기':duration(d.end-now())+' 남음'}</span></small></div><span class="dispatch-slot-number">0${slot+1}</span></div><div class="progress"><span style="width:${Math.min(100,(now()-d.start)/(d.end-d.start)*100)}%"></span></div><button class="${done?'primary':'secondary'}" data-claim-dispatch="${slot}" ${!done||p().active?'disabled':''}>${done?'동료와 보상 맞이하기':'별길을 여행 중이에요'}</button></div>`;}).join('');return `<section class="page">${heading('STARS ON A JOURNEY','별길 파견')}<div class="dispatch-overview"><div class="metric"><small>열린 별길</small><b>${count} / 4</b></div><div class="metric"><small>메인 클리어 보너스</small><b>+${p().cleared*5}%</b></div></div><p class="subtext" style="margin-bottom:18px">동료의 전투력에 맞춰 꿈의결정을 모아 옵니다.<br>전투에 남을 동료 5명을 확보한 뒤 파견할 수 있어요.</p>${cards}<p class="fineprint">9·18·27·36스테이지에서 슬롯이 하나씩 열려요. 보상은 출발할 때의 전투력과 클리어 수로 확정하며, 정원을 닫아도 시간이 흐릅니다.</p></section>`;}
function duration(ms){const seconds=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function chooseDispatch(slot){const free=available(p());show('파견할 동료','EXPEDITION · 20 HOURS',`<p class="subtext">원정을 마치고 보상을 받을 때까지 전투에 참여하지 않아요. 편성에 있던 동료는 남아 있는 동료로 자동 교체됩니다.</p><div class="choose-list" style="margin-top:14px">${free.map(id=>`<button class="choose-row" data-send="${id}" data-slot="${slot}" ${free.length<=5?'disabled':''}>${image(id)}<div><strong>${HERO[id].name}</strong><small>${fmt(combatPower(id,p().heroes[id]))} CP · 파견 보상 ◆ ${dispatchReward(combatPower(id,p().heroes[id]),p().cleared)}</small></div><em>출발 ›</em></button>`).join('')}</div>${free.length<=5?'<p class="fineprint">현재 전투 가능 동료가 5명이에요. 소환에서 새로운 동료를 만난 뒤 파견하세요.</p>':''}`,`<button class="secondary wide" data-action="close">돌아가기</button>`,'dispatch',slot);}
let editingDeck=[],teamReturn=null;
function team(edit=false){if(!edit){teamReturn=modal==='prepare'?modalInfo:null;editingDeck=[...p().deck];}show('다섯 동료의 편성','FIVE STARS, ONE JOURNEY',`${five(editingDeck).replaceAll('data-hero','data-team-pick').replaceAll(' 정보"',' 편성 해제"').replaceAll('data-action="team"','data-action="focus-team"')}<p class="fineprint">서로 다른 동료 5명. 선택한 동료를 다시 누르면 해제합니다.</p><div class="choose-list" style="margin-top:15px">${HEROES.filter(h=>p().heroes[h.id].owned).map(h=>`<button class="choose-row" data-team-pick="${h.id}" aria-pressed="${editingDeck.includes(h.id)}" ${away(p(),h.id)||p().active?'disabled':''}>${image(h.id)}<div><strong>${h.name} ${badge(h.rarity)}</strong><small>${away(p(),h.id)?'파견 중 · 귀환 보상 수령 후 참여':`${h.role} · ${fmt(combatPower(h.id,p().heroes[h.id]))} CP`}</small></div><em>${editingDeck.includes(h.id)?'✓':'＋'}</em></button>`).join('')}</div>`,`<button class="primary wide" data-action="save-team" ${editingDeck.length!==5||p().active?'disabled':''}>${editingDeck.length} / 5명 · 편성 확정</button>`,'team');}
function partners(){show('정원의 파트너','THE STAR CLOSEST TO YOU',`<div class="collection-grid">${HEROES.filter(h=>p().heroes[h.id].owned).map(h=>`<button class="hero-card" data-set-partner="${h.id}" data-rarity="${h.rarity}" style="${rarityStyle(h.rarity)}">${badge(h.rarity)}${image(h.id)}<strong>${h.name}</strong><small>${p().partner===h.id?'함께하는 중 ✓':'정원에서 만나기'}</small></button>`).join('')}</div>`,`<button class="secondary wide" data-action="close">돌아가기</button>`,'partners');}
function prepare(stage=Math.min(45,p().cleared+1),kind='main'){if(p().active){toast('진행 중인 원정을 먼저 이어가 주세요.');return;}const c=CHAPTERS[stage-1];show(kind==='main'?`${stage}번째 별길`:kind==='weekly'?'주간 드래프트':'월간 보스 챌린지','EXPEDITION PREPARATION',`${kind==='main'?`<div class="chapter-banner"><span class="eyebrow">CYCLE ${c.cycle}</span><h2>${BOSSES[c.bosses[0]].name}</h2><p>6웨이브 · 3/6웨이브에 같은 보스가 등장해요.<br>${stage>p().cleared?'첫 클리어 꿈의결정 ◆ '+(160+10*stage):'다시 걷는 별길 · 별가루 보상'}</p></div>`:modeCard(kind).replace(/<button[\s\S]*?<\/button>/,'')}<h3 style="font-size:14px;margin:16px 0 10px">${kind==='weekly'?'드래프트 대상: 보유한 모든 전투 가능 동료':'함께 떠날 다섯 동료'}</h3>${five(p().deck)}<p class="fineprint">현재 전투력 ${fmt(teamPower(p()))} CP · 유물 ${p().equipped.map(id=>ARTIFACT[id].name).join(', ')||'장착 없음'}</p>${kind==='weekly'?'<p class="fineprint">두 선택지에서 하나씩 총 5번 선택합니다. 처음 5명만 보유했다면 마지막 동료는 같은 캐릭터의 두 전술 중에서 선택해요.</p>':''}`,`<div class="dialog-buttons"><button class="secondary" data-action="team">편성 변경</button><button class="primary" data-begin="${kind}" data-stage="${stage}" ${p().deck.length!==5?'disabled':''}>${kind==='weekly'?'주간 입장 · 선택 시작':kind==='monthly'?'월간 1회 입장':'별길로 출발'}</button></div>`,'prepare',{stage,kind});}
function begin(kind,stage){const result=act('begin',{mode:kind,stage},false);if(!result.ok)return;close();if(kind==='weekly'){screen='draft';render();}else startBattle();}
function renderDraft(){const a=p().active;if(a?.mode!=='weekly'){screen='home';render();return;}if(a.draft.length===5){startBattle();return;}$('content').innerHTML=`<section class="page">${heading('WEEKLY · DRAFT '+(a.draft.length+1)+'/5','운명의 두 갈래')}<p class="subtext">전체 보유 풀에서 만난 두 동료.<br>지금 팀에 더 어울리는 한 명을 선택하세요.</p><div class="draft-selected">${Array.from({length:5},(_,i)=>a.draft[i]?image(a.draft[i]):'<span class="draft-dot">✦</span>').join('')}</div><div class="draft-options">${a.offers.map((o,i)=>`<button class="draft-card" data-draft="${i}" style="${rarityStyle(HERO[o.id].rarity)}">${badge(HERO[o.id].rarity)}${image(o.id,true)}<h3>${HERO[o.id].name}</h3><small>${HERO[o.id].role}</small><b>${fmt(combatPower(o.id,p().heroes[o.id]))} CP</b><span class="boon">${o.boon==='focus'?'집중 전술 · 원정 위력 +5%':'별빛 전술 · 시작 별빛 +4'}</span></button>`).join('')}</div><p class="draft-help">선택은 저장됩니다. 정원을 닫아도 이어갈 수 있어요.<br>남은 후보가 한 명이면 같은 동료의 두 전술을 고릅니다.</p></section>`;}
function resume(){close();const a=p().active;if(!a)return;if(a.mode==='weekly'&&a.draft.length<5){screen='draft';render();}else startBattle(true);}
function startBattle(resume=false){clearTimeout(toastTimer);$('toast').hidden=true;const saved=resume?resumeBattle(p()):null;if(resume&&p().active.run&&!saved){toast('원정 저장을 복원할 수 없어요. 백업을 확인해 주세요.');return;}run=saved||createBattle(p());if(!run)return;screen='battle';paused=false;selected=-1;accumulator=0;autoIn=0;saveIn=0;previousPhase='';close();render();if(!store.saveRun(E.serialize(run)))storagePause();sound.unlock();}
function renderBattle(){if(!run)return;$('content').innerHTML=`<section class="battle"><div class="battle-top"><div><strong>${run.mode==='main'?`${run.chapter+1}번째 · ${CHAPTERS[run.chapter].name}`:run.mode==='weekly'?'주간 별빛 드래프트':'월간 수호자 챌린지'}</strong><small id="wave-label"></small></div><button data-action="speed" aria-label="전투 속도">${speed}×</button><button id="pause-button" data-action="pause" aria-label="전투 일시정지">Ⅱ</button><button data-action="leave" aria-label="정원으로 돌아가 원정 저장">⌂</button></div><div class="battle-metrics"><span>♥ <b id="health"></b></span><span>골드 <b id="gold"></b></span><span>✦ <b id="gauge"></b></span><span id="battle-time"></span></div><div class="arena-wrap"><canvas id="arena" tabindex="0" aria-label="5행 5열 전장. 방향키로 칸을 고르고 Enter로 선택 또는 이동하세요."></canvas><p id="battle-notice" class="battle-notice" hidden></p></div><div class="skills">${run.deck.map(id=>`<button class="skill-button" data-skill="${id}" aria-label="${HERO[id].name}의 ${HERO[id].skill.name}">${image(id)}<small>${HERO[id].skill.cost}✦</small></button>`).join('')}</div><div class="battle-controls"><button class="primary" data-action="summon-battle">동료 소환 <span id="summon-cost"></span></button><button class="secondary" data-action="training">훈련</button><button class="secondary" data-action="auto" aria-pressed="${p().settings.auto}">자동 ${p().settings.auto?'ON':'OFF'}</button></div><div id="unit-panel" class="unit-panel" hidden></div><p class="battle-hint">동료를 다른 동료로 끌어 합성 · 빈칸으로 이동<br>자동: 소환·합성·훈련·보스 스킬 보조 / 모든 직접 조작 가능</p></section>`;renderer=new Renderer($('arena'),art);settings();bindArena();updateBattle();}
function updateBattle(){if(screen!=='battle'||!run)return;$('health').textContent=run.health;$('gold').textContent=fmt(run.gold);$('gauge').textContent=Math.floor(run.gauge);$('battle-time').textContent=duration(run.time*1000);$('wave-label').textContent=run.mode==='main'?`물결 ${run.wave} / 6 · ${run.wave===3||run.wave===6?'보스 물결':'동료를 모으는 시간'}`:`라운드 ${run.wave} · 클리어 ${clearedRounds(run)} · 남은 ${Math.max(0,Math.ceil((run.mode==='monthly'?30:35)-run.waveTime))}초`;$('summon-cost').textContent=E.summonCost(run)?E.summonCost(run)+' G':'무료';$('pause-button').textContent=paused?'▶':'Ⅱ';for(const b of document.querySelectorAll('[data-skill]')){const ready=run.gauge>=HERO[b.dataset.skill].skill.cost&&!!E.bestUnit(run,b.dataset.skill);b.disabled=!ready||paused||!['combat','intermission'].includes(run.phase);b.classList.toggle('ready',ready);}
  const notice=$('battle-notice'),boss=run.enemies.find(e=>e.boss&&e.hp>0);notice.hidden=!run.telegraph&&!boss;notice.textContent=run.telegraph?.text||(boss?`${BOSSES[boss.boss].name} · 체력 ${Math.ceil(boss.hp/boss.maxHp*100)}%`:'');updateUnit();}
function updateUnit(){const panel=$('unit-panel');if(!panel)return;const u=run.board[selected];panel.hidden=!u;renderer.selected=u?selected:-1;if(!u)return;const stat=E.combatStats(run,u,selected),h=HERO[u.hero];panel.innerHTML=`<div class="unit-panel-top"><strong>${h.name} · ${u.rank}성</strong><small>위력 ${fmt(stat.damage)} · ${stat.interval.toFixed(2)}초</small></div><div class="unit-actions"><button data-action="target">목표 ${({first:'선두',boss:'보스',strong:'강적',last:'후미'})[u.priority]}</button><button data-sell="${selected}">회수 +${Math.round(6*Math.pow(1.7,u.rank-1))} G</button><button data-action="deselect">선택 닫기</button></div>`;}
function battleCommand(result){if(!result?.ok)toast(result?.reason);if(!store.saveRun(E.serialize(run)))storagePause();updateBattle();}
function bindArena(){const canvas=$('arena');const point=e=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left)*720/b.width,y:(e.clientY-b.top)*780/b.height};};canvas.addEventListener('pointerdown',e=>{if(paused||modal||pointer||e.button!==0)return;const at=point(e);pointer={id:e.pointerId,at,index:E.cellAt(at.x,at.y),drag:false};try{canvas.setPointerCapture(e.pointerId);}catch{}e.preventDefault();sound.unlock();});canvas.addEventListener('pointermove',e=>{if(pointer?.id!==e.pointerId)return;const at=point(e),u=run.board[pointer.index];if(u&&(pointer.drag||Math.hypot(at.x-pointer.at.x,at.y-pointer.at.y)>12)){pointer.drag=true;renderer.drag={hero:u.hero,uid:u.uid,x:at.x,y:at.y};renderer.hover=E.cellAt(at.x,at.y);}});canvas.addEventListener('pointerup',e=>{if(pointer?.id!==e.pointerId)return;const at=point(e),index=E.cellAt(at.x,at.y);if(!paused&&!modal&&index>=0){if(pointer.drag){battleCommand(E.move(run,pointer.index,index));selected=index;}else activate(index);}pointer=null;renderer.drag=null;renderer.hover=-1;updateUnit();});canvas.addEventListener('pointercancel',()=>{pointer=null;renderer.drag=null;renderer.hover=-1;});let keyboard=12;canvas.addEventListener('keydown',e=>{if(paused||modal)return;const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-5,ArrowDown:5}[e.key];if(delta){e.preventDefault();keyboard=Math.max(0,Math.min(24,keyboard+delta));renderer.selected=keyboard;toast(`${Math.floor(keyboard/5)+1}행 ${keyboard%5+1}열 · ${run.board[keyboard]?HERO[run.board[keyboard].hero].name:'빈칸'}`);}if(e.key==='Enter'||e.key===' '){e.preventDefault();activate(keyboard);}});}
function activate(index){if(selected>=0&&selected!==index&&run.board[selected]){battleCommand(E.move(run,selected,index));selected=index;}else selected=selected===index?-1:index;updateUnit();}
function training(){show('원정 중 훈련','BATTLE TRAINING',`<p class="subtext">이번 원정에서만 적용됩니다. 위력 +28%/회, 최대 5회.</p><div class="choose-list" style="margin-top:15px">${run.deck.map(id=>`<button class="choose-row" data-train="${id}" ${run.upgrades[id]>=5||run.gold<E.upgradeCost(run,id)?'disabled':''}>${image(id)}<div><strong>${HERO[id].name}</strong><small>훈련 ${run.upgrades[id]}/5</small></div><em>${run.upgrades[id]>=5?'완료':E.upgradeCost(run,id)+' G'}</em></button>`).join('')}</div>`,`<button class="primary wide" data-action="close">전장으로</button>`,'training');}
function reward(){show('별길의 작은 선물','WAVE '+run.wave+' COMPLETE',`<p class="subtext">다음 물결에 함께할 축복 하나를 선택하세요.</p><div class="reward-options" style="margin-top:16px">${run.reward.map(id=>`<button class="reward-option" data-reward="${id}"><strong>${BLESSING[id].name}</strong><small>${BLESSING[id].text}</small></button>`).join('')}</div>`,'','reward');}
function settle(abandon=false){if(!run||!p().active)return;const snapshot={won:!abandon&&run.phase==='victory',round:clearedRounds(run),stage:run.chapter+1,mode:run.mode,damage:run.stats.damage,kills:run.stats.kills,seconds:run.time,byHero:{...run.stats.byHero}};const result=act('settle',{token:p().active.token,won:snapshot.won,round:snapshot.round},false);if(!result.ok){storagePause();return;}lastResult={...snapshot,reward:result.reward};run=null;renderer=null;screen='adventure';mode=snapshot.mode;cycle=Math.min(4,Math.floor(p().cleared/9));close();render();showResult(lastResult);}
function showResult(r){const mvp=Object.entries(r.byHero).sort((a,b)=>b[1]-a[1])[0];show(r.won?'별길에 새 별이 피었어요':r.mode==='main'?'다음에는 더 멀리':'오늘의 도전을 기록했어요','EXPEDITION RESULT',`<div class="battle-result">${r.won?'별길 클리어 ✦':r.mode==='main'?'함께 다시 준비해요':'도전 '+r.round+'라운드'}</div><p class="reveal-caption">${r.mode==='main'?r.stage+'번째 별길':r.mode==='weekly'?'이번 주의 드래프트':'이번 달의 수호자 챌린지'}</p><div class="result-stat"><span>꿈의결정</span><b>◆ +${r.reward}</b></div><div class="result-stat"><span>처치 / 피해량</span><b>${r.kills} / ${fmt(r.damage)}</b></div><div class="result-stat"><span>원정 시간</span><b>${duration(r.seconds*1000)}</b></div>${mvp?`<div class="result-mvp">${image(mvp[0],true)}<div><strong>오늘의 빛 · ${HERO[mvp[0]].name}</strong><small>기여 피해 ${fmt(mvp[1])} · ${Math.round(mvp[1]/Math.max(1,r.damage)*100)}%</small></div></div>`:''}<p class="subtext">${r.won?`파견 보상 +${p().cleared*5}%. ${p().cleared%9===0&&p().cleared<=36?'새로운 파견 슬롯이 열렸어요!':'다음 별길도 동료와 함께하세요.'}`:r.mode==='main'?'정원의 별가루로 동료를 성장시키거나 편성과 전투 배치를 바꿔 보세요.':'전체 수집 풀과 유물, 단일 대상 조합을 성장시켜 다음 도전에서 더 멀리 나아가세요.'}</p>`,`<div class="dialog-buttons"><button class="secondary" data-action="go-collection">동료 성장</button><button class="primary" data-action="close">기록을 안고 돌아가기</button></div>`,'result');}
function storagePause(){paused=true;toast('원정을 저장하지 못했어요. 진행을 멈췄습니다. 저장 공간을 확인해 주세요.');wallet();}
function leave(){paused=true;show('원정을 잠시 맡겨 둘까요?','KEEP YOUR JOURNEY',`<p class="subtext">현재 배치와 물결을 저장하고 정원으로 돌아갑니다. 주간·월간 원정은 같은 입장으로 이어갈 수 있어요.</p><button class="quiet-retire" data-action="retire">이번 원정을 여기서 마치기</button>`,`<div class="dialog-buttons"><button class="secondary" data-action="return-battle">전장으로</button><button class="primary" data-action="save-leave">저장 후 정원으로</button></div>`,'leave');}
function showSettings(){show('정원의 설정','GARDEN SETTINGS',`${[['sound','음악과 효과음','동작을 누른 뒤 조용한 별빛 음악이 시작돼요.'],['auto','전투 자동 보조','소환·합성·훈련·스킬을 보조합니다. 직접 조작도 가능해요.'],['reduced','연출 줄이기','배경 호흡·화면 흔들림을 줄이고 위험 예고는 유지해요.']].map(([id,title,text])=>`<div class="settings-row"><div><strong>${title}</strong><small>${text}</small></div><button class="toggle" data-setting="${id}" aria-pressed="${p().settings[id]}">${p().settings[id]?'ON':'OFF'}</button></div>`).join('')}<div class="settings-actions"><button class="secondary" data-action="export">정원 백업 저장</button><button class="secondary" data-action="import">백업 불러오기</button></div><p class="fineprint">기록은 이 브라우저에 저장됩니다. 파일을 옮길 때 백업을 함께 가져가 주세요.<br>같은 저장 공간을 두 창에서 수정하면 변경을 감지한 창은 멈춥니다. 오프라인 테스트 버전의 시간은 기기 시계를 사용해요.</p>`,`<button class="primary wide" data-action="close">정원으로</button>`,'settings');}
function daily(){const c=calendar(now()),d=p().daily.day===c.day?p().daily:{claimed:[],combat:false,draw:false,dispatch:false};show('오늘의 작은 발자국','DAILY GARDEN',`<p class="subtext">매일 00:00(UTC+9), 세 가지 작은 목표가 새로 열려요.</p>${[['combat','원정 1회 마치기',60],['draw','동료 또는 유물 소환',30],['dispatch','파견 동료 맞이하기',30]].map(([id,name,value])=>`<div class="daily-row"><div><strong>${name}</strong><small>꿈의결정 ◆ ${value}</small></div><button class="${d[id]&&!d.claimed.includes(id)?'primary':'secondary'}" data-daily="${id}" ${!d[id]||d.claimed.includes(id)?'disabled':''}>${d.claimed.includes(id)?'수령 완료':d[id]?'보상 받기':'진행 중'}</button></div>`).join('')}`,`<button class="secondary wide" data-action="close">정원으로</button>`,'daily');}
function show(title,kicker,body,footer='',kind='generic',info=null){const scroll=modal===kind&&modalInfo===info?$('sheet-body').scrollTop:0;if(!modal)previousFocus=document.activeElement;modal=kind;modalInfo=info;$('sheet-title').textContent=title;$('sheet-kicker').textContent=kicker;$('sheet-body').innerHTML=body;$('sheet-footer').innerHTML=footer;$('overlay').hidden=false;$('app').setAttribute('aria-hidden','true');if('inert' in $('app'))$('app').inert=true;$('sheet-body').scrollTop=scroll;$('sheet').focus();}
function close(){if(!modal)return;const wasLeave=modal==='leave';modal=null;modalInfo=null;if(wasLeave)paused=false;$('overlay').hidden=true;$('app').removeAttribute('aria-hidden');if('inert' in $('app'))$('app').inert=false;if(previousFocus?.isConnected)previousFocus.focus();else $('content').focus();}
function history(){show('이어진 만남의 기록','LAST 50 SUMMONS',p().history.map(h=>`<div class="history-row">${image(h.id)}<div><strong>${(HERO[h.id]||ARTIFACT[h.id]).name} · ${h.fresh?'첫 만남':'중복 재료 +1'}</strong><small>${calendar(h.at).day} · ${h.banner==='normal'?'일반':h.banner==='season'?'시즌':'유물'}</small></div>${badge((HERO[h.id]||ARTIFACT[h.id]).rarity)}</div>`).join('')||'<p class="empty">첫 만남을 기다리고 있어요.</p>',`<button class="secondary wide" data-action="close">돌아가기</button>`,'history');}
function records(){show('별길에 남긴 기록','YOUR JOURNEY',p().results.map(r=>`<div class="rate-row"><span>${r.mode==='main'?r.stage+'번째 별길':r.mode==='weekly'?'주간 드래프트':'월간 보스'}<br><small>${calendar(r.at).day} · ${r.won?'클리어':r.round+'라운드'}</small></span><b>◆ ${r.reward}</b></div>`).join('')||'<p class="empty">첫 원정의 발자국을 기다려요.</p>',`<button class="secondary wide" data-action="close">돌아가기</button>`,'records');}
function exportBackup(){const blob=new Blob([JSON.stringify(p(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`StarGarden-${calendar(now()).day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('정원 백업을 저장했어요.');}
document.addEventListener('click',e=>{
  const button=e.target.closest('button');if(!button||button.disabled)return;const d=button.dataset;sound.click();
  if(d.nav){if(screen==='battle'){leave();return;}close();screen=d.nav;render();return;}
  if(d.hero){heroDetail(d.hero);return;}if(d.relic){relicDetail(d.relic);return;}
  if(d.collection){collection=d.collection;rarity='all';render();return;}if(d.filter){rarity=d.filter;render();return;}
  if(d.banner){banner=d.banner;render();return;}if(d.mode){mode=d.mode;render();return;}if(d.cycle){cycle=Number(d.cycle);render();return;}
  if(d.prepareStage){prepare(Number(d.prepareStage));return;}if(d.begin){begin(d.begin,Number(d.stage));return;}
  if(d.draw){draw(Number(d.draw));return;}if(d.level){if(act('level',{id:d.level}).ok)heroDetail(d.level);return;}
  if(d.enhance||d.enhanceRelic){const id=d.enhance||d.enhanceRelic;if(act('enhance',{id,kind:d.enhance?'hero':'relic'}).ok)(d.enhance?heroDetail:relicDetail)(id);return;}
  if(d.equip){if(act('equip',{id:d.equip}).ok)relicDetail(d.equip);return;}
  if(d.setPartner){if(act('partner',{id:d.setPartner},false).ok){close();if(screen==='home')render();toast(`${HERO[d.setPartner].name}이 정원에서 기다려요.`);}return;}
  if(d.teamPick){const i=editingDeck.indexOf(d.teamPick);if(i>=0)editingDeck.splice(i,1);else if(editingDeck.length<5)editingDeck.push(d.teamPick);else{toast('함께할 동료는 다섯 명이에요. 한 명을 먼저 해제해 주세요.');return;}team(true);return;}
  if(d.dispatchSlot){chooseDispatch(Number(d.dispatchSlot));return;}if(d.send){if(act('dispatch',{id:d.send,slot:Number(d.slot)}).ok){close();render();}return;}
  if(d.claimDispatch){if(act('claimDispatch',{slot:Number(d.claimDispatch)}).ok)render();return;}if(d.draft){if(act('draft',{index:Number(d.draft)},false).ok)render();return;}
  if(d.skill){battleCommand(E.cast(run,d.skill));return;}if(d.train){battleCommand(E.upgrade(run,d.train));training();return;}if(d.sell){battleCommand(E.sell(run,Number(d.sell)));return;}if(d.reward){battleCommand(E.chooseReward(run,d.reward));close();previousPhase='';return;}
  if(d.setting){if(act('setting',{id:d.setting,value:!p().settings[d.setting]},false).ok)showSettings();return;}if(d.daily){if(act('daily',{id:d.daily}).ok)daily();return;}
  const actions={close:()=>{if(modal==='reward')return;close();},settings:showSettings,partner:partners,team:()=>team(),'focus-team':()=>document.querySelector('#sheet-body .choose-list')?.scrollIntoView({behavior:'smooth',block:'start'}),rates,history,records,daily,
    owned:()=>{ownedOnly=!ownedOnly;render();},pet:()=>{if(act('pet').ok)render();},idle:()=>{if(act('idle').ok)render();},
    season:()=>{banner='season';screen='summon';render();},prepare:()=>prepare(Number(d.stage)),
    'prepare-mode':()=>prepare(Math.min(45,p().cleared+1),mode),resume,
    'save-team':()=>{if(act('deck',{ids:editingDeck}).ok){const back=teamReturn;teamReturn=null;close();render();if(back)prepare(back.stage,back.kind);}},
    'go-summon':()=>{close();screen='summon';banner='normal';render();},'go-relic-summon':()=>{close();screen='summon';banner='relic';render();},
    'go-collection':()=>{close();screen='collection';render();},speed:()=>{speed=speed===1?2:1;button.textContent=speed+'×';},pause:()=>{paused=!paused;updateBattle();},
    'summon-battle':()=>battleCommand(E.summon(run)),training,auto:()=>{if(act('setting',{id:'auto',value:!p().settings.auto},false).ok){button.textContent='자동 '+(p().settings.auto?'ON':'OFF');button.setAttribute('aria-pressed',p().settings.auto);}},
    target:()=>{E.cycleTarget(run,selected);battleCommand({ok:true});},deselect:()=>{selected=-1;updateUnit();},leave,
    retire:()=>show('이 원정을 마칠까요?','EXPEDITION RETIRE',`<p class="subtext">완료한 ${clearedRounds(run)}라운드까지 정산합니다. 메인 첫 클리어 보상은 없으며, 주간·월간 입장은 돌려받지 않습니다.</p>`,`<div class="dialog-buttons"><button class="secondary" data-action="return-battle">전장으로</button><button class="primary" data-action="confirm-retire">기록하고 마치기</button></div>`,'retire'),'confirm-retire':()=>settle(true),'return-battle':()=>{close();paused=false;},'save-leave':()=>{if(store.saveRun(E.serialize(run))){close();screen='home';run=null;renderer=null;render();}else storagePause();},
    export:exportBackup,import:()=>{if(run&&p().active){toast('진행 중인 전투를 저장하고 정원에서 불러와 주세요.');return;}$('backup-input').click();},
  };actions[d.action]?.();
});
$('backup-input').addEventListener('change',async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>2*1024*1024){toast('백업 파일은 2MB 이하여야 해요.');return;}try{const raw=await file.text();if(!JSON.parse(raw)){toast('백업을 확인해 주세요.');return;}show('이 백업으로 정원을 복원할까요?','RESTORE YOUR GARDEN',`<p class="subtext">현재 정원 기록을 선택한 백업으로 바꿉니다. 현재 기록이 필요하면 먼저 백업을 저장하세요.</p>`,`<div class="dialog-buttons"><button class="secondary" data-action="export">현재 기록 백업</button><button id="confirm-import" class="primary">백업으로 복원</button></div>`,'import');$('confirm-import').onclick=()=>{const result=store.import(raw);toast(result.ok?'정원을 복원했어요.':result.message);if(result.ok){close();screen='home';run=null;render();}};}catch{toast('백업 파일을 읽을 수 없어요.');}});
document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape'){if(modal!=='reward'){close();}e.preventDefault();}if(e.key==='Tab'){const buttons=Array.from($('sheet').querySelectorAll('button:not(:disabled),summary,[tabindex="0"]')).filter(b=>b.offsetParent!==null),first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('sheet'))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===$('sheet'))){e.preventDefault();first?.focus();}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(run&&!store.saveRun(E.serialize(run)))storagePause();sound.suspend();lastFrame=0;accumulator=0;}else{lastFrame=0;if(!paused)sound.unlock();}});
window.addEventListener('pagehide',()=>{if(run)store.saveRun(E.serialize(run));});
window.addEventListener('storage',e=>{if(e.key==='astra.star-garden.test.v1'&&e.newValue!==store.raw){store.conflict=true;paused=true;wallet();}});
function frame(time){const dt=lastFrame?Math.min(.1,(time-lastFrame)/1000):0;lastFrame=time;if(run&&screen==='battle'&&!document.hidden){if(!paused&&!modal){accumulator+=dt*speed;let ticks=0;while(accumulator>=.05&&ticks++<5){E.step(run,.05);autoIn+=.05;if(p().settings.auto&&autoIn>=.32){autoPlay(run);autoIn=0;}accumulator-=.05;}saveIn+=dt;uiIn+=dt;for(const e of run.events.splice(0)){renderer.event(e);sound.event(e);}if(saveIn>2){saveIn=0;if(!store.saveRun(E.serialize(run)))storagePause();}if(uiIn>.18){uiIn=0;updateBattle();}sound.battle=true;sound.boss=run.enemies.some(e=>e.boss);if(run.phase!==previousPhase){previousPhase=run.phase;if(run.phase==='reward'&&!p().settings.auto){if(!store.saveRun(E.serialize(run)))storagePause();reward();}if(['victory','defeat'].includes(run.phase))settle();}}
    if(run)renderer.draw(run,dt);
  }else sound.battle=false;requestAnimationFrame(frame);}
setInterval(()=>{if(screen==='dispatch'&&!modal){const ended=p().dispatches.some(d=>d.end<=now()&&document.querySelector(`[data-claim-dispatch="${d.slot}"]`)?.disabled);if(ended)render();else for(const node of document.querySelectorAll('[data-timer]'))node.textContent=Number(node.dataset.timer)<=now()?'귀환 완료 · 수령 대기':duration(Number(node.dataset.timer)-now())+' 남음';}if(screen==='home'&&!modal&&$('idle-total')){$('idle-total').textContent=fmt(idleReward(p(),now()));$('idle-progress').style.width=Math.min(100,(now()-p().idleAt)/(20*HOUR)*100)+'%';const button=document.querySelector('[data-action="idle"]');if(button)button.disabled=idleReward(p(),now())<1;}},1000);
for(const img of document.querySelectorAll('img'))img.onerror=()=>{img.src=fallback('star_boy');};
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement&&!e.target.dataset.fallback){e.target.dataset.fallback='1';e.target.src=fallback('star_boy');}},true);
document.documentElement.style.setProperty('--garden',`url("${window.__ASTRA_ASSETS__?.garden||'./assets/merge/garden.webp'}")`);
art.ready.then(()=>{if(art.failed.length)toast('일부 그림은 별빛 표식으로 표시합니다.');});
render();requestAnimationFrame(frame);
// Read-only diagnostics for offline QA. Mutations use real buttons or fixtures
// written to isolated browser storage before boot, never a production cheat UI.
window.STAR_GARDEN={get profile(){return p();},get battle(){return run;},get screen(){return screen;}};
