import {SaveStore} from './core/save.js';
import {exportSave} from './core/migrations.js';
import {clone,hash} from './core/rng.js';
import {HOUR,Q,totalStage} from './core/state.js';
import {settleAccrual} from './core/clock.js';
import {HEROES,HERO,COMPANIONS,COMPANION,BOSSES,BOSS,ARTIFACTS,MEMORIES,STYLES,GATES,balance} from './data/catalog.js';
import {SCENES,SCENE} from './data/scenes.js';
import {snapshot,baseStats} from './systems/growth.js';
import {unlocked,homeLine} from './systems/bond.js';
import {poolMemories,tierRank} from './systems/gacha.js';
import {gateAvailable,library} from './systems/learning.js';
import {expeditionEncounter,bossEncounter} from './combat/encounter.js';
import {simulateBattle} from './combat/engine.js';
import {analyzeDefeat} from './combat/analysis.js';
import {adventureLoadout,adventureEncounter} from './systems/adventure.js';
import {shell,seasonView,sceneList} from './ui/views.js';
import {ART,landscape} from './ui/art.js';
import {esc,fmt,duration,button as btn,icon,art,progress,costs,badge} from './ui/html.js';
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog'),toastElement=document.querySelector('#toast');
const ui={tab:'home',expeditionMode:'lanes',collectionMode:'companion',bondMode:'hero',line:null,busy:false};
let store,s,toastTimer,revealTimer,battleFrame,battle=null,sceneState=null,quizFeedback='',viewerBack=null,lastFocus=null,audioCtx=null;
const uid=()=>globalThis.crypto?.randomUUID?.()||'cmd-'+Date.now()+'-'+Math.random();
const state=()=>store.state;
function toast(message){toastElement.textContent=message;toastElement.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastElement.classList.remove('visible'),4000);}
function render(){s=state();document.documentElement.style.setProperty('--body-scale',s.ui.textScale);document.body.classList.toggle('reduced-motion',s.ui.reducedMotion);document.body.classList.toggle('decor-frame',s.decor.includes('frame'));document.body.classList.toggle('decor-desk',s.decor.includes('desk')||s.decor.includes('s01-120'));document.body.classList.toggle('decor-album',s.decor.includes('album'));const y=window.scrollY;app.innerHTML=shell(s,ui,store);window.scrollTo(0,y);}
function modal(title,body,{className='',subtitle='',preserve=false}={}){if(!dialog.open){lastFocus=document.activeElement;dialog.showModal();}dialog.className=className;dialog.innerHTML='<header class="dialog-head"><div><h2 id="dialog-title">'+esc(title)+'</h2>'+(subtitle?'<small>'+esc(subtitle)+'</small>':'')+'</div>'+btn('close',icon('close')+'<span class="sr-only">닫기</span>',{},'icon-button close-dialog')+'</header>'+body;if(!preserve)dialog.scrollTop=0;dialog.querySelector('button')?.focus({preventScroll:true});}
function closeDialog(){if(ui.advancing)ui.cancelAdvance=true;clearTimeout(revealTimer);cancelAnimationFrame(battleFrame);if(battle)battle.cancelled=true;battle=null;dialog.close();lastFocus?.focus?.({preventScroll:true});}
async function command(type,data={}){let result;try{result=await store.dispatch({id:uid(),type,...data});}catch(error){if(error.message!=='REVISION_CONFLICT'||!['tick','homeLine'].includes(type))throw error;const record=await store.readRecord();store.state=record.state;result=await store.dispatch({id:uid(),type,...data});}s=state();if(!ui.advancing&&['level','gear','mastery','battle','summon','exchange','scene'].includes(type)){ui.line=await store.dispatch({id:uid(),type:'homeLine',recentType:type});render();}return result;}
function playTone(tier){if(s.ui.muted)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const oscillator=audioCtx.createOscillator(),gain=audioCtx.createGain(),now=audioCtx.currentTime;oscillator.type='sine';oscillator.frequency.value=[392,440,523.25,659.25,783.99][tier];gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.12*s.ui.volume,now+.02);gain.gain.exponentialRampToValueAtTime(.001,now+.35);oscillator.connect(gain);gain.connect(audioCtx.destination);oscillator.start();oscillator.stop(now+.36);}catch{}}
function changeTab(tab){ui.tab=tab;render();window.scrollTo({top:0,behavior:'instant'});}
function showViewer(id,back=null){if(!ART[id])return;viewerBack=back;const meta=ART[id];modal(meta.name||id,'<div class="viewer-stage"><div class="art art-viewer" style="--ratio:'+meta.width+'/'+meta.height+'">'+art(id,'viewer').replace(/^<figure[^>]*>|<\/figure>$/g,'')+'</div></div><div class="viewer-tools"><label for="art-zoom">확대</label><input id="art-zoom" type="range" min="1" max="3" step=".25" value="1"><span id="zoom-value" class="small">1×</span>'+btn('viewerReset','전체 보기',{},'secondary')+'</div>',{className:'viewer',subtitle:'원본 비율 · '+meta.width+' × '+meta.height});}
function memory(id){const m=MEMORIES.find(x=>x.id===id),owned=s.memories.includes(id),pool=poolMemories(s),can=pool.includes(id);modal(m.name,'<div class="dialog-body"><div class="card-art-button" role="button" tabindex="0" data-action="viewer" data-art="'+id+'" aria-label="그림 확대">'+art(id,'memory',m.name)+'</div><p class="art-caption">'+(owned?'보유한 기억 · 전투 성능 효과 없음':'미보유 기억 미리보기')+'</p><p class="small">'+esc(m.type==='bond'?'해당 영웅 관계 210 장면 읽기':m.type==='special'?m.acquisition:m.acquisition==='season_track_240'?'시즌 240점 · 활동 24일':'현재 '+(can?'열려 있는':'닫힌')+' 소환/선택 풀')+'</p><div class="dialog-actions">'+(owned?btn('homeArt','홈에 놓기',{item:id},'primary')+btn('viewer','전체 그림',{art:id},'secondary'):can?btn('exchange','가루 200',{pool:'memory',item:id,method:'dust'},'primary',s.wallets.memoryDust<200)+btn('exchange','선택권 1장',{pool:'memory',item:id,method:'selector'},'secondary',s.wallets.memorySelectors<1):'')+'</div>'+(!owned&&can?btn('pinMemory','다음 수집 목표로 고정',{item:id},'quiet wide'):'')+'</div>');}
function companion(id){const c=COMPANION[id],v=s.companions[id],assigned=HEROES.find(h=>s.heroes[h.id].companions.includes(id));modal(c.name,'<div class="dialog-body"><div class="columns"><div>'+art(id,'memory',c.name)+'</div><div><div class="row">'+badge(v.owned?'보유 · 랭크 '+v.rank:'미보유',v.owned?'teal':'lock')+'</div><h3 class="section">곁에서 돕는 힘</h3><p>'+c.passive+'</p><h4 class="section">지원 · '+c.cooldown+'초</h4><p>'+c.active+'</p><p class="small muted section">'+(assigned?assigned.name+'에게 배속 중':'현재 배속하지 않았어요')+'</p>'+(v.owned?btn('rank','랭크 상승 · 토큰 '+(balance.summon.companion.rankCosts[v.rank]||0),{companion:id},'secondary wide',v.rank>=5||s.wallets.bondTokens<(balance.summon.companion.rankCosts[v.rank]||0)):'<div class="stack section">'+btn('exchange','인연토큰 120',{pool:'companion',item:id,method:'token'},'primary',s.wallets.bondTokens<120)+btn('exchange','동료 선택권 1장',{pool:'companion',item:id,method:'selector'},'secondary',s.wallets.companionSelectors<1)+'</div>')+'</div></div><section class="section"><h3>개인 기록</h3>'+sceneList(s,SCENES.filter(c=>c.category==='companion'&&c.actors.includes(id)))+'</section>'+(id==='time_magician'&&s.memories.includes('trauma')?btn('memory','트라우마 · 같은 인물의 기억',{memory:'trauma'},'secondary wide section'):'')+'</div>');}
function assignDialog(hero,slot){modal('함께 갈 동료','<div class="dialog-body"><p class="small muted">다른 영웅에게 배속된 동료는 현재 자리의 동료와 교대해요.</p><div class="stack">'+COMPANIONS.filter(c=>s.companions[c.id].owned).map(c=>{const owner=HEROES.find(h=>s.heroes[h.id].companions.includes(c.id));return btn('assign',art(c.id,'avatar',c.name)+'<span><strong>'+c.name+'</strong><small>'+c.passive+' · '+(owner?owner.name+' 배속':'대기')+'</small></span>',{hero,slot,companion:c.id},'support-slot');}).join('')+btn('assign','이 자리 비우기',{hero,slot,companion:''},'secondary')+'</div></div>');}
function equipDialog(hero){modal('이번 길의 유물','<div class="dialog-body"><div class="stack">'+ARTIFACTS.filter(a=>s.artifacts[a.id]).map(a=>btn('equipArtifact','<strong>'+a.name+' · 등급 '+s.artifacts[a.id]+'</strong><small>'+a.effect+'</small>',{hero,artifact:a.id},'event-choice')).join('')+btn('equipArtifact','유물 해제',{hero,artifact:''},'secondary')+'</div><p class="small muted section">같은 유물은 한 영웅만 사용해요. 다른 영웅에게 있으면 서로 교대합니다.</p></div>');}
function showScene(id,index=0){const c=SCENE[id];if(!c||!unlocked(s,c))throw Error('아직 열리지 않은 이야기예요.');sceneState={id,index};const line=c.lines[index],speaker=HERO[line.speaker]?.name||COMPANION[line.speaker]?.name||'기록';modal(c.title,'<div class="scene-picture" role="button" tabindex="0" data-action="sceneViewer" data-art="'+c.artId+'" aria-label="장면 전체 보기">'+art(c.artId,'scene',c.title)+'</div><div class="dialogue"><div class="speaker">'+esc(speaker)+'</div><p class="dialogue-line">'+esc(line.text)+'</p>'+(index===c.lines.length-1?'<div class="scene-choices">'+c.choices.map((choice,i)=>btn('sceneFinish',choice.text,{scene:id,choice:i},'secondary')).join('')+'</div>':'')+'<div class="scene-footer"><span>'+(index+1)+' / '+c.lines.length+'</span><div>'+btn('sceneSkip',s.readScenes.includes(id)?'읽기 마치기':'나중에 읽기',{scene:id},'quiet')+(index<c.lines.length-1?btn('sceneNext','다음 '+icon('arrow'),{},'primary'):'')+'</div></div></div>',{className:'scene-dialog',subtitle:s.readScenes.includes(id)?'앨범에서 다시 읽기':'새 이야기'});}
function showReceipt(receipt){
 const chestNames={wood:'나무',silver:'은빛',gold:'금빛',star:'별빛',wooden:'나무'};
 modal('돌아온 시간','<div class="dialog-body"><div class="receipt"><div class="seal">'+icon('check')+'</div><h2>수령 완료</h2><p class="muted">'+duration(receipt.duration)+' 동안 다섯 영웅이 모았어요.</p></div><div class="receipt-grid">'+['xp','gold','forgeOre'].map((k,i)=>'<span><small>'+['EXP','골드','광석'][i]+'</small><strong>'+fmt(receipt.base[k])+'</strong></span>').join('')+'</div>'+
 (receipt.chest?'<div class="receipt-extra">'+(chestNames[receipt.chest]||receipt.chest)+' 귀환 상자 · '+(Object.values(receipt.bonus).some(v=>v>0)?Object.entries(receipt.bonus).map(([k,v])=>(k==='xp'?'EXP':k==='gold'?'골드':'광석')+' +'+fmt(v)).join(' · '):'기본 보상은 전액 지급되었어요.')+'</div>':'')+
 (receipt.grace.xp||receipt.grace.gold?'<div class="receipt-extra">원정의 가호 · EXP +'+fmt(receipt.grace.xp)+' · 골드 +'+fmt(receipt.grace.gold)+'</div>':'')+
 (receipt.comeback.xp?'<div class="receipt-extra">복귀의 응원 · EXP +'+fmt(receipt.comeback.xp)+' · 골드 +'+fmt(receipt.comeback.gold)+'</div>':'')+
 '<p class="small muted">'+(store.mode==='memory'?'기본 보상은 현재 창에만 유지돼요. 종료 전에 백업해 주세요.':'기본 보상은 이미 저장되었어요.')+' 귀환의 별은 원하는 날 선택하는 추가 선물입니다.</p><div class="paper section"><div class="row between"><h3>귀환의 별</h3>'+badge('하루 1회','gold')+'</div><p class="small muted">강의를 읽고 문법 한 문제. 수령 구간의 최대 4시간분 EXP·골드를 한 번 더 받아요.</p><div class="dialog-actions">'+btn('close','기본 보상으로 충분해요',{},'secondary')+btn('gate','강의부터 읽기',{gate:'return'},'primary',!gateAvailable(s,'return',s.lastTrustedLogicalMs))+'</div></div></div>');playTone(2);
}
function showQuiz(){const c=s.gates.challenge;if(!c||c.answered)return;const q=c.question,g=GATES[c.gate];if(q.kind==='grammar'&&!c.lectureRead){modal(g.name+' · 먼저 읽는 강의','<div class="dialog-body"><p class="notice">관련 강의를 먼저 읽은 뒤 문제를 풀어요. 틀려도 보너스와 재화가 줄지 않으며, 다시 고를 수 있어요.</p><h3 class="lecture-title section">'+esc(q.lecture.title)+'</h3><div class="lecture">'+esc(q.lecture.content)+'</div><div class="dialog-actions">'+btn('close','나중에 읽기',{},'secondary')+btn('lecture','강의를 읽었어요 · 문제 보기',{challenge:c.id},'primary')+'</div></div>');return;}
 modal(g.name,'<div class="dialog-body"><p class="small muted">'+esc(g.description)+' · 하루 한 번 선택</p><div class="quiz-question">'+esc(q.prompt)+'</div><div class="quiz-options">'+q.options.map((option,i)=>btn('answer',String.fromCharCode(65+i)+'. '+esc(option),{index:i,challenge:c.id},'quiz-option')).join('')+'</div>'+(quizFeedback?'<div class="quiz-feedback">'+esc(quizFeedback)+'</div>':'')+(q.lecture?btn('reviewLecture','강의 다시 읽기',{},'quiet section'):'')+'<p class="small muted section">오답에는 비용이 없어요. 설명을 보고 다시 선택해 주세요.</p></div>');}
function showProbabilities(pool){const mem=pool==='memory',cfg=balance.summon[pool],names={white:'흰빛',bronze:'청동',silver:'은빛',gold:'금빛',star:'별빛'};modal('확률과 선택 보장','<div class="dialog-body"><div class="table-wrap"><table><thead><tr><th>단계</th><th>확률</th><th>내용</th></tr></thead><tbody>'+cfg.resultTiers.map(t=>'<tr><td>'+names[t.id]+'</td><td>'+(t.chance*100).toFixed(0)+'%</td><td>'+(t.id==='star'?'완성 '+(mem?'기억':'동료'):(mem?'기억가루 ':'인연토큰 ')+(t.memoryDust||t.bondTokens))+'</td></tr>').join('')+'</tbody></table></div><p class="section">'+(mem?'현재 시즌이 열려 있을 때 완성 기억의 40%는 시즌 2종 균등, 60%는 상시 5종 균등입니다. 아카이브 기간은 상시 5종 균등입니다.':'완성 동료는 24종 균등입니다. 첫 10회까지 초기 5명 이외의 새 동료를 못 만났으면 10번째에 새 동료를 보장합니다.')+'</p><p>누적 '+cfg.selectorEveryDraws+'회마다 원하는 대상을 고르는 선택권을 지급합니다. 완성품이 나와도 누적 횟수는 초기화하지 않아요.</p><p>중복 완성품은 '+(mem?'기억가루 60':'인연토큰 20')+'개. 지정 교환은 '+(mem?'기억가루 200':'인연토큰 120')+'개입니다. 추가 소환도 같은 확률과 누적 규칙을 씁니다.</p><p class="notice">연출은 실제 결과 순서로 올라갑니다. 가장 높은 결과가 마지막에 공개되며, 희귀 결과가 없으면 희귀 연출을 보여주지 않습니다.</p></div>');}
const tierColors={white:'#b9c5cd',bronze:'#ba8864',silver:'#cad7e8',gold:'#e1b75e',star:'#bdd9cf'},tierNames={white:'흰빛',bronze:'청동',silver:'은빛',gold:'금빛',star:'별빛'};
function summonReveal(batchId,index=0){clearTimeout(revealTimer);const b=s.gacha.batches.find(b=>b.id===batchId);if(!b)return;if(b.revealed){summonSummary(b);return;}const sorted=[...b.results].sort((a,b)=>tierRank[a.tier]-tierRank[b.tier]||a.index-b.index),r=sorted[index],isMemory=b.pool==='memory',name=r.item?(isMemory?MEMORIES.find(x=>x.id===r.item)?.name:COMPANION[r.item]?.name):(isMemory?'기억가루':'인연토큰')+' '+r.amount;
 modal('별빛이 남긴 선물','<div class="summon-stage"><div class="reveal-count">'+(index+1)+' / '+b.count+'</div><div class="summon-result-card" style="--tier-color:'+tierColors[r.tier]+'">'+(r.item?art(r.item,'memory',name):'<div class="summon-material">'+icon('gem')+'<b>'+r.amount+'</b></div>')+'</div><div class="tier-track">'+Object.keys(tierRank).map(t=>'<i class="'+(tierRank[t]<=tierRank[r.tier]?'active':'')+'" style="background:'+tierColors[t]+'"></i>').join('')+'</div><div class="summon-caption"><small>'+tierNames[r.tier]+(r.guarantee?' · 첫 동료 보장':'')+'</small><h3>'+esc(name)+'</h3><small>'+(r.item?r.duplicate?'이미 보유 · '+(isMemory?'기억가루 60':'인연토큰 20'):'새로운 '+(isMemory?'기억':'동행'):'모아서 원하는 대상을 고를 수 있어요')+'</small></div>'+btn('summonSkip','모두 펼치기',{batch:batchId},'secondary',false).replace('class="secondary"','class="secondary" style="color:white;border-color:#8099a4;background:transparent"')+'</div>',{subtitle:store.mode==='memory'?'현재 창에만 유지돼요. 종료 전 백업해 주세요.':'결과와 보상은 이미 안전하게 저장했어요'});
 playTone(tierRank[r.tier]);if(r.tier==='star'&&s.ui.vibration)navigator.vibrate?.(30);
 revealTimer=setTimeout(async()=>{try{if(index+1<sorted.length)summonReveal(batchId,index+1);else{await command('reveal',{batchId});summonSummary(s.gacha.batches.find(x=>x.id===batchId));}}catch(error){toast(error.message);}},s.ui.reducedMotion?100:800);
}
function summonSummary(b){clearTimeout(revealTimer);modal('함께할 별을 만났어요','<div class="dialog-body"><div class="summon-summary">'+b.results.map(r=>'<div class="summary-item" style="border-bottom:3px solid '+tierColors[r.tier]+'">'+(r.item?art(r.item,'avatar',b.pool==='memory'?MEMORIES.find(m=>m.id===r.item)?.name:COMPANION[r.item]?.name):icon('gem'))+'<strong>'+esc(r.item?b.pool==='memory'?MEMORIES.find(m=>m.id===r.item)?.name:COMPANION[r.item]?.name:r.amount+(b.pool==='memory'?' 가루':' 토큰'))+'</strong><span>'+tierNames[r.tier]+(r.duplicate?' · 중복':'')+'</span></div>').join('')+'</div><p class="small muted section">누적 '+s.gacha.counts[b.pool]+'회 · 보유 선택권 '+s.wallets[b.pool+'Selectors']+'장</p>'+
 (b.count===10?'<div class="paper section"><h3>별빛의 잔향</h3><p class="small muted">소환진에 남은 별빛으로 한 장 더. 숙어 한 문제를 풀면 같은 확률로 정상 소환하며 누적 횟수도 +1됩니다.</p>'+btn('gate',gateAvailable(s,'echo',s.lastTrustedLogicalMs,b.id)?'+1회 추가 소환':'오늘의 잔향을 사용했어요',{gate:'echo',batch:b.id},'primary wide section',!gateAvailable(s,'echo',s.lastTrustedLogicalMs,b.id))+'</div>':'')+'<div class="dialog-actions">'+btn('close','앨범으로 돌아가기',{},'secondary')+'</div></div>');}
const effectNames={normal:'기본 공격',burn:'작열',poison:'중독',divine:'디바인',blind:'암흑',slow:'둔화',corrosion:'부식',weaken:'약화',analysis:'분석',exposed:'노출',curse:'저주'};
const effectName=id=>HEROES.flatMap(h=>h.skills).find(x=>x.id===id)?.name||COMPANION[id]?.name||effectNames[id]||id;
function startBattle(heroId,encounter,adventure=false){const loadout=adventure?adventureLoadout(s):snapshot(s,heroId),result=simulateBattle(loadout,encounter);battle={result,tick:-10,eventIndex:0,frameIndex:0,speed:1,paused:false,last:null,adventure,cancelled:false};battleUI();battleFrame=requestAnimationFrame(battleLoop);}
function battleUI(){const r=battle.result,h=HERO[r.loadout.heroId],e=r.encounter;modal(e.name,'<div class="battle-hud"><div><span>'+h.name+' · Lv. '+r.loadout.level+'</span><span id="hero-hp-label" style="float:right">HP</span>'+progress(1,1,'영웅 HP','hp')+progress(50,100,'영웅 MP','mp')+'<small id="mp-label">MP 50</small></div><div><span>'+e.name+'</span><span id="enemy-hp-label" style="float:right">HP</span>'+progress(1,1,'적 HP','hp')+'<small id="enemy-state">공격 준비</small></div></div><div class="battle-arena"><div class="battle-warning" role="status"></div><div class="combatants"><div class="combatant hero">'+art('archive_'+h.id+'_01','battle',h.name)+'<span class="battle-label">'+h.name+'</span></div><div class="combatant enemy">'+(e.bossId?art(e.bossId,'battle',e.name):'<div class="enemy-sigil '+(e.gate?'gate':'')+'"><div class="sigil-shape">'+icon(e.gate?'hero':'star')+'</div></div>')+'<span class="battle-label">'+e.name+'</span></div></div><div class="battle-floating"></div><div class="battle-cue"></div><div class="battle-clock">0.0s</div></div><div class="battle-supports">'+r.loadout.companions.map((id,i)=>'<div class="support-live" data-support="'+id+'">'+(id?art(id,'avatar',COMPANION[id].name)+'<span>'+COMPANION[id].name+'<br><small>지원 '+(i?'7':'3')+'초 뒤</small></span>':'<span class="muted">빈 지원 자리</span>')+'</div>').join('')+'</div><div class="battle-controls">'+[1,2,4].map(speed=>btn('battleSpeed',speed+'×',{speed},'secondary')).join('')+btn('battlePause','일시정지',{},'secondary')+btn('battleFinish','결과 보기',{},'primary')+'</div>',{className:'battle-dialog',subtitle:(battle.adventure?'모험':e.kind==='boss'?'보스 티어 '+e.tier:'원정 '+e.stage+'단계')+' · 같은 편성의 결과는 항상 같아요'});}
function battleLoop(now){if(!battle||battle.cancelled)return;const b=battle,r=b.result,dt=b.last===null?0:Math.min(100,now-b.last);b.last=now;if(!b.paused)b.tick+=dt*.02*b.speed;const tick=Math.max(0,b.tick);
 if(b.tick>=0){while(b.eventIndex<r.events.length&&r.events[b.eventIndex].tick<=tick)renderBattleEvent(r.events[b.eventIndex++]);while(b.frameIndex<r.frames.length-1&&r.frames[b.frameIndex+1].tick<=tick)b.frameIndex++;const f=r.frames[b.frameIndex];if(f&&f.tick<=tick&&(b.lastHUDTick===undefined||f.tick-b.lastHUDTick>=2||f.tick===r.elapsedTicks)){b.lastHUDTick=f.tick;setBar('영웅 HP',f.hp,r.heroMaxHP);setBar('영웅 MP',f.mp,100);setBar('적 HP',f.enemyHP,r.enemyMaxHP);document.querySelector('#hero-hp-label').textContent=fmt(f.hp);document.querySelector('#enemy-hp-label').textContent=fmt(f.enemyHP);document.querySelector('#mp-label').textContent='MP '+fmt(f.mp)+' · '+(f.shield?'보호막 '+fmt(f.shield):'');document.querySelector('#enemy-state').textContent=f.exposed?'노출 · 피해 증가':f.defense?'방어 중 · 피해 감소':(f.statuses||[]).map(effectName).join(' · ')||'공격 준비';document.querySelector('.battle-warning').textContent=f.warning;document.querySelector('.combatant.hero').classList.toggle('guarded',f.shield>0);}document.querySelector('.battle-clock').textContent=(Math.min(tick,r.elapsedTicks)/20).toFixed(1)+'s';}
 if(b.tick>r.elapsedTicks+14){finishBattle().catch(error=>toast(error.message));return;}battleFrame=requestAnimationFrame(battleLoop);}
function setBar(label,value,max){const el=dialog.querySelector('[aria-label="'+label+'"]');el?.setAttribute('aria-valuemax',max);el?.setAttribute('aria-valuenow',Math.round(value));if(el)el.firstElementChild.style.width=Math.max(0,value/max*100)+'%';}
function renderBattleEvent(e){const reduced=s.ui.reducedMotion;if(['hit','dot','miss','heal','shield'].includes(e.type)){const actor=dialog.querySelector('.combatant.'+(e.target==='hero'?'hero':'enemy'));if(!reduced){actor?.classList.remove('struck');void actor?.offsetWidth;actor?.classList.add('struck');}
 const container=dialog.querySelector('.battle-floating');if(container&&container.children.length<(reduced?2:24)){const el=document.createElement('span');el.className='damage-number'+(e.crit?' critical':'');el.style.left=e.target==='hero'?'24%':'70%';el.textContent=e.type==='miss'?'회피':e.type==='heal'?'+'+fmt(e.value):e.type==='shield'?'보호막':(e.crit?'✦ ':'')+fmt(e.value);container.append(el);setTimeout(()=>el.remove(),650);}}
 if(e.type==='ultimate'&&!reduced){const fx=document.createElement('div');fx.className='ultimate-fx fx-'+battle.result.loadout.heroId;dialog.querySelector('.battle-arena')?.append(fx);setTimeout(()=>fx.remove(),700);}if(['skill','ultimate','support'].includes(e.type)){const cue=dialog.querySelector('.battle-cue');if(cue){cue.textContent=(e.type==='support'?'지원 · ':e.type==='ultimate'?'궁극 · ':'')+effectName(e.label);cue.classList.remove('on');void cue.offsetWidth;cue.classList.add('on');}const actor=dialog.querySelector('.combatant.hero');if(!reduced){actor?.classList.remove('attacking');void actor?.offsetWidth;actor?.classList.add('attacking');}if(e.type==='support'){const el=dialog.querySelector('[data-support="'+e.label+'"]');el?.classList.add('active');setTimeout(()=>el?.classList.remove('active'),700);}}}
async function finishBattle(){if(!battle||battle.finishing)return;battle.finishing=true;cancelAnimationFrame(battleFrame);const b=battle,r=b.result;try{await command(b.adventure?'adventureBattle':'battle',{result:r});battle=null;showBattleResult(r,b.adventure);}catch(error){battle=null;modal('전투를 기록하지 못했어요','<div class="dialog-body"><p>'+esc(error.message)+'</p>'+btn('close','돌아가기',{},'primary')+'</div>');}}
function showBattleResult(r,adventure=false){const win=r.winner==='hero',astea=r.encounter.bossId==='astea';modal(win?'다음 길이 열렸어요':astea?'별빛을 하나 더 모았어요':'다음 한 걸음을 준비하며','<div class="dialog-body"><div class="receipt"><div class="seal">'+icon(win?'star':'hero')+'</div><h2>'+(astea?'아스테아 기여 '+r.score.toFixed(3):win?'승리':'잠시 쉬어가요')+'</h2><p class="muted">'+HERO[r.loadout.heroId].name+' · '+(r.elapsedTicks/20).toFixed(1)+'초</p></div><div class="result-comparison"><span><small>영웅 남은 HP</small><strong>'+Math.ceil(r.heroHP/r.heroMaxHP*100)+'%</strong></span><span><small>상대 남은 HP</small><strong>'+Math.ceil(r.enemyHP/r.enemyMaxHP*100)+'%</strong></span></div>'+
 (adventure?'<p>'+(s.adventure.finished?'여덟 걸음의 모험을 마쳤어요. '+(s.adventure.practice?'이번에는 연습 기록입니다.':'탐험배지 한 개를 받았어요.'):win?'다음 길에서 유물과 사건을 골라보세요.':'같은 시드의 길을 다시 걸을 수 있어요. 성장 자원은 잃지 않았습니다.')+'</p>':astea?'<p>각 영웅의 최고 점수만 보관해 합산합니다. 3.5로 관문을 열고, 5.0으로 완성할 수 있어요.</p>':win?'<p class="small muted">첫 승리와 새 원정 단계가 저장되었습니다.</p>':'<p class="small muted">실제 전투 기록을 바탕으로 지금 할 수 있는 변화를 찾아보세요.</p>')+
 '<details class="section"><summary>피해와 기술 기록</summary><div class="battle-log">'+Object.entries(r.damageBySource).map(([id,n])=>'<div>'+esc(effectName(id))+' · '+fmt(n)+'</div>').join('')+'</div><div class="small muted">최종 기록 '+r.replayDigest+'</div></details><div class="dialog-actions">'+btn('close',adventure?'모험 지도로':'돌아가기',{},'secondary')+(!win&&!adventure&&!astea?btn('analysis','돌파 분석',{hero:r.loadout.heroId},'primary'):win&&!adventure&&r.encounter.kind==='expedition'&&r.encounter.stage<1200?btn('battle','다음 단계',{hero:r.loadout.heroId},'primary'):'')+'</div></div>');}
async function advanceOne(heroId,limit=30){let wins=0,last;for(let i=0;i<limit&&!ui.cancelAdvance&&s.heroes[heroId].stage<1200;i++){const e=expeditionEncounter(heroId,s.heroes[heroId].stage+1);last=simulateBattle(snapshot(s,heroId),e,undefined,{trace:false});await command('battle',{result:last});if(last.winner!=='hero')break;wins++;if(i%5===0)await new Promise(r=>setTimeout(r,0));}return {heroId,wins,last};}
async function showAnalysis(){const r=s.lastResult;if(!r)return;modal('돌파 분석','<div class="dialog-body"><p>현재 편성으로 가능한 변화들을 직접 전투에 대입하고 있어요.</p></div>');const analysis=await analyzeDefeat(s,r.loadout.heroId,r.encounter);ui.analysis=analysis;modal('다음 한 걸음의 차이','<div class="dialog-body"><p class="notice">현재 자원과 보유한 동료만 확인합니다. 최대 8개 후보를 실제 전투와 같은 규칙으로 비교했어요.</p><p class="section">현재 상대 잔여 HP <strong>'+Math.ceil(analysis.baseline.enemyHP/analysis.baseline.enemyMaxHP*100)+'%</strong></p>'+analysis.results.map((a,i)=>'<article class="analysis-item"><div class="row between"><h4>'+esc(a.name)+'</h4>'+badge(a.result.winner==='hero'?'돌파 확인':'상대 HP '+Math.ceil(a.result.enemyHP/a.result.enemyMaxHP*100)+'%',a.result.winner==='hero'?'teal':'')+'</div><p>'+costs(a.cost)+(a.affordable?' · 현재 가능':' · 자원 수집 필요')+'</p>'+btn('applyAnalysis','이 변화 적용',{index:i},'secondary',!a.affordable)+'</article>').join('')+'<p class="small muted section">'+(analysis.actionable?'현재 가능한 추천: '+analysis.actionable.name:'지금 가능한 변화만으로 더 나은 결과를 확인하지 못했어요. 원정 수익을 모은 뒤 다시 살펴보세요.')+'</p></div>');}
function bossInfo(id,tier){const b=BOSS[id];modal(b.name,'<div class="dialog-body"><div class="columns"><div>'+art(id,'memory',b.name)+'</div><div><h3>티어 '+tier+' · '+HERO[s.ui.hero].name+'</h3><p class="section">'+b.pattern+'</p><p class="notice section">'+b.counterplay+'</p><p class="small muted section">첫 도전은 횟수 제한이나 비용이 없어요. 완료 티어의 흔적 연구에만 연구권을 씁니다.</p>'+btn('bossBattle','이 편성으로 도전',{boss:id,tier,hero:s.ui.hero},'primary wide section')+'</div></div></div>');}
function settings(){modal('오래 머물기 위한 설정','<div class="dialog-body"><div class="notice"><strong>저장 상태 · '+(store.mode==='indexedDB'?'기기 저장':store.mode==='localStorage'?'호환 저장':'임시 메모리')+'</strong><br>'+(store.mode==='memory'?'자동 저장할 수 없어요. 창을 닫기 전에 백업을 내려받아 주세요.':'매 행동의 결과를 저장한 뒤 표시하고 있어요. 가끔 파일 백업도 보관해 주세요.')+(store.recovered?'<br>이전 정상 백업으로 복구했어요.':'')+'</div><div class="row section">'+btn('export','백업 내려받기',{},'primary')+btn('import','백업 가져오기',{},'secondary')+btn('previousBackups','이전 저장 복구',{},'quiet')+'</div><input type="file" id="save-file" accept=".json,application/json" hidden>'+[['muted','소리 끄기','소환 효과음에 적용'],['reducedMotion','연출 줄이기','흔들림과 빠른 전환을 줄여요'],['vibration','짧은 진동','지원 기기에서 별빛 소환 결과에만']].map(([key,name,sub])=>'<label class="settings-row"><span>'+name+'<small>'+sub+'</small></span><input type="checkbox" data-setting="'+key+'" '+(s.ui[key]?'checked':'')+'></label>').join('')+'<label class="settings-row"><span>음량</span><input type="range" min="0" max="1" step=".05" value="'+s.ui.volume+'" data-setting="volume"></label><label class="settings-row"><span>글자 크기</span><input type="range" min=".9" max="1.3" step=".1" value="'+s.ui.textScale+'" data-setting="textScale"></label><div class="settings-row"><span>홈 기억 표시<small>선택한 대표 영웅 원본으로 돌아가기</small></span>'+btn('homeArt','기본 그림',{item:''},'secondary')+'</div><p class="small muted section">별의 동행 1.0.0 · 일일 갱신 UTC+9 05:00<br>다른 게임의 저장 공간과 분리되어 있습니다.<br>임시 브라우저 데이터 삭제 시 저장도 지워질 수 있으므로 파일 백업을 권장합니다.</p></div>');}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function handle(action,d,target){
 switch(action){
 case 'tab':closeDialog();changeTab(d.tab);break;
 case 'close':if(dialog.classList.contains('viewer')&&viewerBack){const back=viewerBack;viewerBack=null;back();}else closeDialog();break;
 case 'viewer':showViewer(d.art);break;
 case 'viewerReset':dialog.querySelector('#art-zoom').value='1';setZoom(1);break;
 case 'sceneViewer':{const {id,index}=sceneState;showViewer(d.art,()=>showScene(id,index));break;}
 case 'heroSelect':await command('settings',{values:{hero:d.hero}});ui.line=null;await command('homeArt',{itemId:null});break;
 case 'goHero':if(d.hero)await command('settings',{values:{hero:d.hero}});changeTab('hero');break;
 case 'goBoss':ui.expeditionMode='boss';changeTab('expedition');break;
 case 'goMemories':ui.collectionMode='memory';changeTab('collection');break;
 case 'expMode':ui.expeditionMode=d.mode;render();break;
 case 'bondMode':ui.bondMode=d.mode;render();break;
 case 'collectionMode':ui.collectionMode=d.mode;render();break;
 case 'claim':showReceipt(await command('claim'));break;
 case 'level':{const before=baseStats(snapshot(s,d.hero));const r=await command('level',{heroId:d.hero,count:+d.count});const after=baseStats(snapshot(s,d.hero));toast(HERO[d.hero].name+' 레벨 +'+r.levels+' · ATK +'+((after.atk/before.atk-1)*100).toFixed(1)+'%');playTone(1);break;}
 case 'gear':{const r=await command('gear',{heroId:d.hero,slot:d.slot,count:+d.count});toast('강화 +'+r.levels+(r.great?' · 대성공 '+r.great+'회 · 광석 '+r.refund+' 환급':''));playTone(1);break;}
 case 'gearChoice':await command('gearChoice',{heroId:d.hero,slot:d.slot,value:+d.value});toast('장비 효과를 바꿨어요.');break;
 case 'mastery':{const r=await command('mastery',{heroId:d.hero});toast('숙련 '+r.node+' · ATK·MATK가 성장했어요.');break;}
 case 'style':await command('style',{heroId:d.hero,value:+d.value});toast(STYLES[d.hero][+d.value]+' 스타일');break;
 case 'tacticsPreset':{const order=d.preset==='survival'?[0,1,2]:d.preset==='burst'?[2,1,0]:[];await command('tactics',{heroId:d.hero,tactics:{...s.heroes[d.hero].tactics,preset:d.preset,order:order.map(i=>HERO[d.hero].skills[i].id)}});break;}
 case 'skillFirst':{const h=s.heroes[d.hero],all=h.tactics.order.length?h.tactics.order:HERO[d.hero].skills.map(x=>x.id);await command('tactics',{heroId:d.hero,tactics:{...h.tactics,order:[d.skill,...all.filter(id=>id!==d.skill)]}});break;}
 case 'savePreset':case 'loadPreset':await command(action,{heroId:d.hero,slot:d.slot});toast(action==='savePreset'?'편성을 기록했어요.':'기록한 편성을 불러왔어요.');break;
 case 'assignDialog':assignDialog(d.hero,+d.slot);break;
 case 'assign':await command('assign',{heroId:d.hero,slot:+d.slot,companionId:d.companion||null});closeDialog();toast('지원 편성을 바꿨어요.');break;
 case 'equipDialog':equipDialog(d.hero);break;
 case 'equipArtifact':await command('equipArtifact',{heroId:d.hero,artifactId:d.artifact||null});closeDialog();break;
 case 'interactDialog':modal('어떤 이야기를 나눌까요?','<div class="dialog-body">'+art(d.hero,'scene')+'<p class="section">어떤 주제를 골라도 관계가 12점 쌓여요.</p><div class="stack section">'+['오늘 지나온 길','잠깐의 휴식','다음에 하고 싶은 일'].map((label,i)=>btn('interact',label,{hero:d.hero,choice:i},'secondary')).join('')+'</div></div>');break;
 case 'interact':await command('interact',{heroId:d.hero});closeDialog();toast(HERO[d.hero].name+'과 시간을 나눴어요. 관계 +12');break;
 case 'gift':await command('gift',{heroId:d.hero});toast('마음이 담긴 선물을 전했어요. 관계 +4');break;
 case 'scene':showScene(d.scene);break;
 case 'sceneNext':showScene(sceneState.id,sceneState.index+1);break;
 case 'sceneFinish':case 'sceneSkip':{const r=await command('scene',{sceneId:d.scene,skip:action==='sceneSkip'});closeDialog();if(r.rewardId){modal('함께한 시간이 그림으로 남았어요.','<div class="dialog-body">'+art(r.rewardId,'memory')+'<div class="dialog-actions">'+btn('memory','기억 자세히 보기',{memory:r.rewardId},'primary')+btn('close','돌아가기',{},'secondary')+'</div></div>');}else toast('앨범에 이야기를 남겼어요.');break;}
 case 'companion':companion(d.companion);break;
 case 'memory':memory(d.memory);break;
 case 'rank':await command('rank',{companionId:d.companion});companion(d.companion);toast('동료 랭크가 올랐어요.');break;
 case 'exchange':await command('exchange',{pool:d.pool,itemId:d.item,method:d.method});d.pool==='memory'?memory(d.item):companion(d.item);toast('원하는 별을 만났어요.');break;
 case 'selectorTokens':await command('selectorTokens',{pool:'companion'});toast('인연토큰 120개를 받았어요.');break;
 case 'pinMemory':await command('pinMemory',{itemId:d.item});toast('다음 목표로 정했어요.');closeDialog();break;
 case 'homeArt':await command('homeArt',{itemId:d.item||null});closeDialog();changeTab('home');break;
 case 'summon':{const b=await command('summon',{pool:d.pool,count:+d.count});summonReveal(b.id);break;}
 case 'resumeSummon':summonReveal(d.batch);break;
 case 'summonSkip':clearTimeout(revealTimer);await command('reveal',{batchId:d.batch});summonSummary(s.gacha.batches.find(b=>b.id===d.batch));break;
 case 'probabilities':showProbabilities(d.pool);break;
 case 'gate':await command('gate',{gate:d.gate,batchId:d.batch});quizFeedback='';showQuiz();break;
 case 'lecture':await command('lecture',{challengeId:d.challenge});showQuiz();break;
 case 'reviewLecture':{const q=s.gates.challenge.question;modal(q.lecture.title,'<div class="dialog-body"><div class="lecture">'+esc(q.lecture.content)+'</div>'+btn('backQuiz','문제로 돌아가기',{},'primary wide section')+'</div>');break;}
 case 'backQuiz':showQuiz();break;
 case 'answer':{const q=s.gates.challenge.question,gate=s.gates.challenge.gate,r=await command('answer',{challengeId:d.challenge,answer:q.options[+d.index]});if(!r.correct){quizFeedback='괜찮아요. 설명을 읽고 다시 골라주세요.\n'+r.explanation;showQuiz();}else if(gate==='echo')summonReveal(r.reward.id);else{modal('별빛이 마음에 닿았어요.','<div class="dialog-body"><div class="receipt"><div class="seal">'+icon('star')+'</div><h2>'+(gate==='grace'?'원정의 가호 발동':'귀환의 별 수령')+'</h2></div><p class="section">'+(gate==='grace'?'지금부터 30분 동안 다섯 원정의 EXP·골드가 두 배로 쌓여요. 창을 닫아도 괜찮고, 내일 돌아와도 추가분이 보관됩니다.':'EXP +'+fmt(r.reward.xp)+' · 골드 +'+fmt(r.reward.gold)+'가 별도로 지급되었어요.')+'</p><div class="quiz-feedback">'+esc(q.explanation)+'</div>'+btn('close','돌아가기',{},'primary wide section')+'</div>');}break;}
 case 'learningReview':modal('다시 펼치는 학습 기록','<div class="dialog-body"><p>학습 '+s.learning.total+'회 · 정답 '+s.learning.correct+'회</p>'+s.learning.mistakes.map(q=>'<div class="paper section"><h3>'+esc(q.prompt)+'</h3><p>'+esc(q.answer)+'</p><p class="small">'+esc(q.explanation)+'</p></div>').join('')+(s.learning.mistakes.length?'':'<p class="muted section">보관된 오답이 없어요.</p>')+'</div>');break;
 case 'battle':closeDialog();startBattle(d.hero,expeditionEncounter(d.hero,s.heroes[d.hero].stage+1));break;
 case 'battleSpeed':if(battle){battle.speed=+d.speed;toast(d.speed+'배 관전');}break;
 case 'battlePause':if(battle){battle.paused=!battle.paused;target.textContent=battle.paused?'계속 보기':'일시정지';}break;
 case 'battleFinish':await finishBattle();break;
 case 'advance':case 'advanceAll':{ui.advancing=true;ui.cancelAdvance=false;modal('원정의 발걸음','<div class="dialog-body"><p>현재 편성으로 다음 단계를 확인하고 있어요.</p><p class="small muted">승리할 때만 앞으로 나아갑니다.</p></div>');const results=[];try{for(const h of action==='advanceAll'?HEROES:[HERO[d.hero]]){if(ui.cancelAdvance)break;results.push(await advanceOne(h.id));}}finally{ui.advancing=false;}render();modal('원정 기록','<div class="dialog-body">'+results.map(r=>'<div class="settings-row"><span>'+HERO[r.heroId].name+'</span><strong>'+r.wins+'단계 전진 · '+s.heroes[r.heroId].stage+'단계</strong></div>').join('')+'<p class="small muted section">한 번에 영웅마다 최대 30단계를 확인해요. 모두 승리한 영웅은 다시 돌파를 눌러 이어갈 수 있어요. 패배한 영웅은 훈련과 분석으로 다음 변화를 찾아보세요.</p><div class="dialog-actions">'+btn('close','원정으로',{},'secondary')+(s.lastResult?.winner==='enemy'?btn('analysis','마지막 전투 분석',{},'primary'):'')+'</div></div>');break;}
 case 'analysis':await showAnalysis();break;
 case 'applyAnalysis':{const candidate=ui.analysis.results[+d.index];await command(candidate.command.type,candidate.command);closeDialog();changeTab('hero');toast(candidate.name+' 적용. 다음 도전에서 확인해 보세요.');break;}
 case 'bossInfo':bossInfo(d.boss,+d.tier);break;
 case 'bossBattle':startBattle(d.hero,bossEncounter(d.boss,+d.tier));break;
 case 'research':{const r=await command('research',{bossId:d.boss});toast('흔적 '+r.amount+'개'+(r.spark?' · 발견의 불꽃!':''));break;}
 case 'artifact':await command('artifact',{artifactId:d.artifact});toast('유물의 힘이 열렸어요. 영웅에게 배속할 수 있어요.');break;
 case 'traceDecor':await command('traceDecor',{bossId:d.boss});toast('장식 토큰을 얻었어요.');break;
 case 'adventureStart':await command('adventureStart',{heroId:d.hero});break;
 case 'adventureEvent':await command('adventureEvent',{choice:+d.choice});break;
 case 'adventureRelic':await command('adventureRelic',{itemId:d.item});break;
 case 'adventureBattle':startBattle(s.adventure.heroId,adventureEncounter(s),true);break;
 case 'adventureAbandon':await command('adventureAbandon');toast('이번 길을 마쳤어요. 같은 시드로 다시 걸을 수 있어요.');break;
 case 'buyDecor':await command('buyDecor',{itemId:d.item});toast('거점에 작은 기념을 놓았어요.');break;
 case 'season':modal('별빛 아래의 휴식','<div class="dialog-body">'+seasonView(s)+'</div>');break;
 case 'maintain':await command('maintain');if(dialog.open)modal('별빛 아래의 휴식','<div class="dialog-body">'+seasonView(s)+'</div>');toast('오늘의 정비를 기록했어요.');break;
 case 'butterfly':{const r=await command('butterfly');toast('15분분 EXP·골드'+(r.golden?' + 동료권 1장':'')+'를 받았어요.');break;}
 case 'letter':{const r=await command('letter');modal(HERO[r.actor].name+'의 편지','<div class="dialog-body">'+art('bond_'+r.actor+'_01','scene')+'<p class="section">'+esc(homeLine({...s,ui:{...s.ui,hero:r.actor}},Date.now(),'').text)+'</p><p class="small muted section">출발할 때의 정상 수익 20분분 EXP·골드를 받았어요.</p>'+btn('close','편지를 접어두기',{},'primary wide section')+'</div>');break;}
 case 'settings':settings();break;
 case 'export':download(exportSave(s),'AstralCompanions-'+new Date().toISOString().slice(0,10)+'.json');toast('현재 기록을 백업했어요.');break;
 case 'import':document.querySelector('#save-file').click();break;
 case 'confirmImport':await store.restore(ui.importText);s=state();ui.importText=null;ui.line=null;closeDialog();render();toast('백업을 불러왔어요.');break;
 case 'previousBackups':{const r=await store.readRecord();ui.backups=r?.previous||[];modal('이전 정상 저장','<div class="dialog-body"><p>가져오기 전의 기록도 두 개까지 남겨둡니다.</p><div class="stack section">'+ui.backups.map((text,i)=>btn('restorePrevious',(i+1)+'번째 이전 기록',{index:i},'secondary')).join('')+'</div></div>');break;}
 case 'restorePrevious':ui.importText=ui.backups[+d.index];confirmImport();break;
 case 'resetClock':await command('resetClock');toast('이전 저장 시점부터 다시 시간이 흐릅니다.');break;
 case 'tutorial':await command('tutorial');closeDialog();toast('오늘의 첫 활동을 기록했어요. 다섯 영웅은 지금도 원정 중이에요.');break;
 }
}
function setZoom(value){const container=dialog.querySelector('.viewer-stage'),image=container.querySelector('.art');container.classList.toggle('zoomed',value>1);image.style.width=value*100+'%';dialog.querySelector('#zoom-value').textContent=value+'×';}
function confirmImport(){modal('이 기록으로 이어갈까요?','<div class="dialog-body"><p>현재 진행은 이전 저장으로 보관한 뒤, 선택한 백업의 진행으로 이어갑니다.</p><div class="dialog-actions">'+btn('close','취소',{},'secondary')+btn('confirmImport','백업으로 이어가기',{},'primary')+'</div></div>');}
document.addEventListener('click',async event=>{const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const action=target.dataset.action;if(ui.busy&&!['close','viewer','battlePause','battleSpeed'].includes(action))return;const wasBusy=ui.busy;try{ui.busy=true;await handle(action,target.dataset,target);}catch(error){if(error.message==='REVISION_CONFLICT'){const r=await store.readRecord();store.state=r.state;render();toast('다른 탭의 최신 기록을 가져왔어요. 행동을 다시 선택해 주세요.');}else toast(error.message||'동작을 마치지 못했어요.');}finally{ui.busy=wasBusy;}});
document.addEventListener('visibilitychange',()=>{if(store&&!document.hidden&&!ui.busy)command('tick').catch(error=>toast('저장 확인: '+error.message));});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role=button]')){e.preventDefault();e.target.click();}});
document.addEventListener('change',async e=>{const key=e.target.dataset.setting;try{if(key==='hold')await command('tactics',{heroId:s.ui.hero,tactics:{...s.heroes[s.ui.hero].tactics,hold:e.target.checked}});else if(key){await command('settings',{values:{[key]:e.target.type==='checkbox'?e.target.checked:+e.target.value}});}if(e.target.id==='save-file'){const file=e.target.files[0];if(!file)return;if(file.size>2097152)throw Error('최대 2 MiB 백업만 가져올 수 있어요.');ui.importText=await file.text();const {validateAndMigrate}=await import('./core/migrations.js');validateAndMigrate(ui.importText);confirmImport();}}catch(error){toast(error.message);}});
document.addEventListener('input',e=>{if(e.target.id==='art-zoom')setZoom(+e.target.value);});
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.closest('.art')?.classList.add('failed');e.target.closest('.art')?.querySelector('.image-fallback')?.removeAttribute('hidden');console.error('Artwork failed:',e.target.closest('.art')?.dataset.art);}},true);
dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
function liveClock(){if(!s||ui.tab!=='home')return;const preview=clone(s);settleAccrual(preview,Math.max(s.lastTrustedLogicalMs,Date.now()+s.clockOffsetMs));const a=preview.accrual;for(const key of ['xp','gold','forgeOre','duration']){const el=app.querySelector('[data-live="'+key+'"]');if(el)el.textContent=key==='duration'?duration(a.duration):fmt(a.pending[key]/Q);}}
async function boot(){try{store=await new SaveStore().open();store.listeners.add(()=>{if(s&&s.ui.hero!==state().ui.hero)ui.line=null;if(!ui.advancing)render();});await command('tick');ui.line=await command('homeLine');render();if(!s.ui.tutorialDone){modal('별의 동행에 오신 것을 환영해요.','<div class="dialog-body">'+art('archive_lumi_01','scene','루미')+'<h3 class="section">다섯 영웅, 다섯 갈래의 시간</h3><p class="section">창을 닫아도 모두가 원정 수익을 모읍니다. 돌아오면 보상을 받고, 한 사람을 성장시키고, 짧은 이야기를 함께 읽어보세요.</p><p class="small muted">접속 첫날이 짧아도 괜찮도록 오늘의 활동은 안내를 마치면 기록됩니다. 선택 학습 보너스는 하루 세 종류이며 기본 보상과 분리되어 있어요.</p>'+btn('tutorial','우리의 첫날 시작하기',{},'primary wide section')+'</div>');}setInterval(()=>{if(!ui.busy&&!battle)command('tick').catch(error=>toast('저장 확인: '+error.message));},15000);setInterval(liveClock,1000);
 Object.defineProperty(window,'__ASTRAL_TEST__',{value:{state:()=>clone(state()),store,simulateBattle,snapshot,ui,render,showViewer,showScene,views:{seasonView},getBattle:()=>battle},configurable:false});
 }catch(error){app.innerHTML='<div class="boot"><h1>기록을 열지 못했어요.</h1><p>'+esc(error.message)+'</p><p>기존 저장은 지우지 않았습니다.</p></div>';console.error(error);}}
boot();
