import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { Game } from './engine.js';
import { HEROES, DUNGEONS } from './content.js';
import { DIFFICULTIES } from './meta.js';

const root=new URL('./',import.meta.url),round=n=>Math.round(n*10)/10;
const tick=(game,seconds)=>{for(let i=0;i<Math.round(seconds*60);i++)game.update(1/60);};
function fixture(hero,weapon=0,power=3,gap=200,artifacts=[]) {
  const game=new Game({hero,weapon,mode:'normal',height:900,seed:41,artifacts});
  game.phase='boss';game.power=power;game.player.invincible=1e6;
  game.player.x=game.player.targetX=225;game.player.y=game.player.targetY=400;
  game.spawnEnemy(225,400-gap,{hp:1e9,r:38,speed:0,fire:1e6,image:0});
  return game;
}
function dps(hero,weapon,power,gap=200) {
  const game=fixture(hero,weapon,power,gap);tick(game,3);
  const before=game.stats.damage;tick(game,15);
  return round((game.stats.damage-before)/15);
}
function bombSample(hero,artifacts=[]) {
  const game=fixture(hero,0,3,200,artifacts);
  const fire=game.fire.bind(game),damage=game.damage.bind(game);
  let direct=0,transformed=0;
  // Isolate the ultimate from the simultaneous ordinary weapon. Time's
  // replacement projectiles count as bomb damage and finish their flight.
  game.fire=dt=>{if(hero===8&&game.bombTime>0&&!game.artifacts.has('sun'))fire(dt);};
  game.damage=(enemy,amount,x,y,kind)=>{
    const before=game.stats.damage;damage(enemy,amount,x,y,kind);
    if(kind==='bomb') {if(game.stats.bombs&&game.bombElapsed>0&&hero===8&&!game.artifacts.has('sun'))transformed+=game.stats.damage-before;else direct+=game.stats.damage-before;}
  };
  game.player.invincible=0;game.bomb();
  const duration=game.bombDuration,invincibility=game.bombInvincibility;
  tick(game,duration+3);
  return {damage:round(direct),transformedDamage:round(transformed),duration,invincibility};
}
const heroes=HEROES.map((hero,index)=>({
  id:hero.id,radius:hero.radius||5,speed:hero.speed||1250,powerRequirement:[0,7].includes(index)?4:3,
  modes:DIFFICULTIES.map(mode=>{const g=new Game({hero:index,mode:mode.id,artifacts:[]});return {id:mode.id,lives:g.player.lives,maxLife:g.maxLife,bombs:g.bombs,maxBombs:g.maxBombs};}),
  weapons:hero.weapons.map((weapon,i)=>({id:weapon.id,dps:Object.fromEntries([1,3,5].map(power=>[power,dps(index,i,power)])),closeDps:dps(index,i,3,80)})),
  bomb:bombSample(index)
}));
// A transparent engineering index, not a measured human clear rate. Mechanics
// carry explicit editorial weights; combat quantities come from the live engine.
const mechanicWeights=[2,4,6,7,9,12,15,6,10,8,7,9];
const stages=DUNGEONS.flatMap(dungeon=>dungeon.rooms.map((name,room)=>({
  dungeon:dungeon.id,room,name,mechanicWeight:mechanicWeights[dungeon.id],
  modes:Object.fromEntries(DIFFICULTIES.map(mode=>{
    const g=new Game({stage:dungeon.id,mode:mode.id,artifacts:[]});g.startStage(dungeon.id,room);
    g.spawnEnemy(225,200,{hp:38+g.level*10,r:19,speed:0,fire:1e6,image:0});
    const enemyHp=g.enemies[0].maxHp;
    let gateHp=0;if(room===1){g.spawnSentinel();gateHp=g.enemies.find(e=>e.miniboss).maxHp;}if(room===2){g.spawnBoss();gateHp=g.boss.maxHp;}
    const shotSpeed=(105+g.level*14)*mode.speed,shotInterval=2.9*mode.interval;
    const raw=12*Math.log2(1+enemyHp/40)+9*Math.log2(1+gateHp/1000)+g.stage.duration/4+shotSpeed/12+10/shotInterval+mechanicWeights[dungeon.id];
    return [mode.id,{enemyHp:round(enemyHp),gateHp:round(gateHp),waveSeconds:round(g.stage.duration),shotSpeed:round(shotSpeed),shotInterval:round(shotInterval),raw:round(raw),rawExact:raw}];
  }))
})));
const rawValues=stages.flatMap(stage=>Object.values(stage.modes).map(mode=>mode.rawExact));
const min=Math.min(...rawValues),max=Math.max(...rawValues);
for(const stage of stages)for(const mode of Object.values(stage.modes)){mode.score=1+Math.round(99*(mode.rawExact-min)/(max-min));delete mode.rawExact;}
const sources={};
for(const file of ['engine.js','content.js','meta.js','generate-manual.mjs'])sources[file]=createHash('sha256').update((await fs.readFile(new URL(file,root),'utf8')).replace(/\r\n/g,'\n')).digest('hex');
const data={schema:1,sources,fixture:{hz:60,seed:41,warmupSeconds:3,sampleSeconds:15,targetRadius:38,standardGap:200,closeGap:80,artifacts:[]},scoreRange:{min,max},heroes,corona:bombSample(0,['sun']),stages};
const text='// Generated by generate-manual.mjs from the live combat engine. Do not edit manually.\nexport const MANUAL_BALANCE = '+JSON.stringify(data,null,2)+';\n';
const destination=new URL('manual-data.js',root);
if(process.argv.includes('--check')) {
  if((await fs.readFile(destination,'utf8')).replace(/\r\n/g,'\n')!==text)throw new Error('Manual balance data is stale. Run node shooter/generate-manual.mjs.');
  console.log('Manual balance data matches: 9 heroes, 18 weapons, 36 stages × 4 difficulties.');
} else {await fs.writeFile(destination,text);console.log('Generated manual balance data: 9 heroes, 18 weapons, 144 difficulty scores.');}
