// Generated by generate-manual.mjs from the live combat engine. Do not edit manually.
export const MANUAL_BALANCE = {
  "schema": 1,
  "sources": {
    "engine.js": "a8010e04c05cc5e131a1857840445e5bb0ceac3115a1209b83fb6a7c3fccdb63",
    "content.js": "be6e71935cd0a15123597c4c18c33ff7c29498c3e85ffd5d0e32ba676f1ce66e",
    "meta.js": "abef31ef07b45874d7a1c52c3bec0afd5eba314e1bf86783866c9fca47ee78d0",
    "generate-manual.mjs": "5fc603b3abe4d7df126e0f7c0649c9b1c777a5014bacc7368ad059603781d1ee"
  },
  "fixture": {
    "hz": 60,
    "seed": 41,
    "warmupSeconds": 3,
    "sampleSeconds": 15,
    "targetRadius": 38,
    "standardGap": 200,
    "closeGap": 80,
    "artifacts": []
  },
  "scoreRange": {
    "min": 28.964654091096214,
    "max": 140.4884612900981
  },
  "heroes": [
    {
      "id": "rumi",
      "radius": 5,
      "speed": 1250,
      "powerRequirement": 4,
      "modes": [
        {
          "id": "easy",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 3,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "homing",
          "dps": {
            "1": 116.4,
            "3": 244.5,
            "5": 419.1
          },
          "closeDps": 244.5
        },
        {
          "id": "laser",
          "dps": {
            "1": 272.1,
            "3": 381,
            "5": 489.8
          },
          "closeDps": 381
        }
      ],
      "bomb": {
        "damage": 1058,
        "transformedDamage": 0,
        "duration": 4,
        "invincibility": 4
      }
    },
    {
      "id": "luna",
      "radius": 5,
      "speed": 1250,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 3,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "dagger",
          "dps": {
            "1": 214.6,
            "3": 300.4,
            "5": 386.2
          },
          "closeDps": 300.4
        },
        {
          "id": "melee",
          "dps": {
            "1": 171.2,
            "3": 239.6,
            "5": 308.1
          },
          "closeDps": 351.4
        }
      ],
      "bomb": {
        "damage": 1300,
        "transformedDamage": 0,
        "duration": 2,
        "invincibility": 2
      }
    },
    {
      "id": "zeke",
      "radius": 6,
      "speed": 1100,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 3,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "spread",
          "dps": {
            "1": 317.6,
            "3": 552.8,
            "5": 710.7
          },
          "closeDps": 606.8
        },
        {
          "id": "lance",
          "dps": {
            "1": 228,
            "3": 319.2,
            "5": 410.4
          },
          "closeDps": 319.2
        }
      ],
      "bomb": {
        "damage": 1248,
        "transformedDamage": 0,
        "duration": 3,
        "invincibility": 3
      }
    },
    {
      "id": "jasmine",
      "radius": 5,
      "speed": 1250,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 3,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "chain",
          "dps": {
            "1": 143.3,
            "3": 200.7,
            "5": 258
          },
          "closeDps": 200.7
        },
        {
          "id": "petal",
          "dps": {
            "1": 244.9,
            "3": 342.8,
            "5": 440.8
          },
          "closeDps": 342.8
        }
      ],
      "bomb": {
        "damage": 773,
        "transformedDamage": 0,
        "duration": 3,
        "invincibility": 3
      }
    },
    {
      "id": "snow",
      "radius": 4,
      "speed": 1250,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 3,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 3,
          "maxLife": 3,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "frost",
          "dps": {
            "1": 170.4,
            "3": 238.6,
            "5": 306.7
          },
          "closeDps": 238.6
        },
        {
          "id": "snowflake",
          "dps": {
            "1": 119.1,
            "3": 166.7,
            "5": 214.3
          },
          "closeDps": 166.7
        }
      ],
      "bomb": {
        "damage": 1058,
        "transformedDamage": 0,
        "duration": 3,
        "invincibility": 3
      }
    },
    {
      "id": "cinderella",
      "radius": 5,
      "speed": 1250,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 5,
          "maxLife": 5,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 4,
          "maxLife": 5,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "glass",
          "dps": {
            "1": 303.4,
            "3": 424.7,
            "5": 546.1
          },
          "closeDps": 431.4
        },
        {
          "id": "midnight",
          "dps": {
            "1": 278.7,
            "3": 390.2,
            "5": 501.7
          },
          "closeDps": 395.5
        }
      ],
      "bomb": {
        "damage": 1305,
        "transformedDamage": 0,
        "duration": 3,
        "invincibility": 3
      }
    },
    {
      "id": "night",
      "radius": 4,
      "speed": 1250,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 4,
          "maxLife": 4,
          "bombs": 4,
          "maxBombs": 6
        },
        {
          "id": "normal",
          "lives": 3,
          "maxLife": 4,
          "bombs": 4,
          "maxBombs": 6
        },
        {
          "id": "hard",
          "lives": 3,
          "maxLife": 3,
          "bombs": 4,
          "maxBombs": 6
        },
        {
          "id": "abyss",
          "lives": 3,
          "maxLife": 3,
          "bombs": 4,
          "maxBombs": 6
        }
      ],
      "weapons": [
        {
          "id": "nightfall",
          "dps": {
            "1": 194.8,
            "3": 272.7,
            "5": 350.6
          },
          "closeDps": 272.7
        },
        {
          "id": "dreamfield",
          "dps": {
            "1": 128.9,
            "3": 180.4,
            "5": 232
          },
          "closeDps": 181.4
        }
      ],
      "bomb": {
        "damage": 1900,
        "transformedDamage": 0,
        "duration": 3,
        "invincibility": 3
      }
    },
    {
      "id": "sisters",
      "radius": 6,
      "speed": 1250,
      "powerRequirement": 4,
      "modes": [
        {
          "id": "easy",
          "lives": 5,
          "maxLife": 5,
          "bombs": 4,
          "maxBombs": 6
        },
        {
          "id": "normal",
          "lives": 4,
          "maxLife": 5,
          "bombs": 4,
          "maxBombs": 6
        },
        {
          "id": "hard",
          "lives": 4,
          "maxLife": 4,
          "bombs": 4,
          "maxBombs": 6
        },
        {
          "id": "abyss",
          "lives": 4,
          "maxLife": 4,
          "bombs": 4,
          "maxBombs": 6
        }
      ],
      "weapons": [
        {
          "id": "promise",
          "dps": {
            "1": 237.3,
            "3": 332.3,
            "5": 427.2
          },
          "closeDps": 332.3
        },
        {
          "id": "haven",
          "dps": {
            "1": 240.8,
            "3": 337.1,
            "5": 433.4
          },
          "closeDps": 337.1
        }
      ],
      "bomb": {
        "damage": 1058,
        "transformedDamage": 0,
        "duration": 3,
        "invincibility": 3
      }
    },
    {
      "id": "time",
      "radius": 5,
      "speed": 1250,
      "powerRequirement": 3,
      "modes": [
        {
          "id": "easy",
          "lives": 5,
          "maxLife": 5,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "normal",
          "lives": 4,
          "maxLife": 5,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "hard",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        },
        {
          "id": "abyss",
          "lives": 4,
          "maxLife": 4,
          "bombs": 3,
          "maxBombs": 5
        }
      ],
      "weapons": [
        {
          "id": "rewind",
          "dps": {
            "1": 202.9,
            "3": 284.1,
            "5": 365.3
          },
          "closeDps": 284.1
        },
        {
          "id": "orbit",
          "dps": {
            "1": 322.4,
            "3": 451.4,
            "5": 580.3
          },
          "closeDps": 451.4
        }
      ],
      "bomb": {
        "damage": 80,
        "transformedDamage": 7980,
        "duration": 10,
        "invincibility": 2
      }
    }
  ],
  "corona": {
    "damage": 2000,
    "transformedDamage": 0,
    "duration": 1,
    "invincibility": 1
  },
  "stages": [
    {
      "dungeon": 0,
      "room": 0,
      "name": "제국의 외곽",
      "mechanicWeight": 2,
      "modes": {
        "easy": {
          "enemyHp": 35.6,
          "gateHp": 0,
          "waveSeconds": 25,
          "shotSpeed": 81.9,
          "shotInterval": 3.5,
          "raw": 29,
          "score": 1
        },
        "normal": {
          "enemyHp": 48.9,
          "gateHp": 0,
          "waveSeconds": 25,
          "shotSpeed": 105,
          "shotInterval": 2.9,
          "raw": 34.3,
          "score": 6
        },
        "hard": {
          "enemyHp": 66.4,
          "gateHp": 0,
          "waveSeconds": 25,
          "shotSpeed": 125,
          "shotInterval": 2.4,
          "raw": 39.8,
          "score": 11
        },
        "abyss": {
          "enemyHp": 86.3,
          "gateHp": 0,
          "waveSeconds": 25,
          "shotSpeed": 133.4,
          "shotInterval": 2.1,
          "raw": 43.9,
          "score": 14
        }
      }
    },
    {
      "dungeon": 0,
      "room": 1,
      "name": "프리즘 관문",
      "mechanicWeight": 2,
      "modes": {
        "easy": {
          "enemyHp": 39.8,
          "gateHp": 1447.2,
          "waveSeconds": 30,
          "shotSpeed": 81.9,
          "shotInterval": 3.5,
          "raw": 42.8,
          "score": 13
        },
        "normal": {
          "enemyHp": 54.8,
          "gateHp": 1990.7,
          "waveSeconds": 30,
          "shotSpeed": 105,
          "shotInterval": 2.9,
          "raw": 50.9,
          "score": 20
        },
        "hard": {
          "enemyHp": 74.4,
          "gateHp": 2700.5,
          "waveSeconds": 30,
          "shotSpeed": 125,
          "shotInterval": 2.4,
          "raw": 59.3,
          "score": 28
        },
        "abyss": {
          "enemyHp": 96.7,
          "gateHp": 3780.7,
          "waveSeconds": 30,
          "shotSpeed": 133.4,
          "shotInterval": 2.1,
          "raw": 66.9,
          "score": 35
        }
      }
    },
    {
      "dungeon": 0,
      "room": 2,
      "name": "인조 신의 실험실",
      "mechanicWeight": 2,
      "modes": {
        "easy": {
          "enemyHp": 44.1,
          "gateHp": 4303.7,
          "waveSeconds": 35,
          "shotSpeed": 81.9,
          "shotInterval": 3.5,
          "raw": 55,
          "score": 24
        },
        "normal": {
          "enemyHp": 60.7,
          "gateHp": 5920.2,
          "waveSeconds": 35,
          "shotSpeed": 105,
          "shotInterval": 2.9,
          "raw": 64,
          "score": 32
        },
        "hard": {
          "enemyHp": 82.3,
          "gateHp": 8030.9,
          "waveSeconds": 35,
          "shotSpeed": 125,
          "shotInterval": 2.4,
          "raw": 73.3,
          "score": 40
        },
        "abyss": {
          "enemyHp": 107,
          "gateHp": 12849.4,
          "waveSeconds": 35,
          "shotSpeed": 133.4,
          "shotInterval": 2.1,
          "raw": 83.2,
          "score": 49
        }
      }
    },
    {
      "dungeon": 1,
      "room": 0,
      "name": "장미의 회랑",
      "mechanicWeight": 4,
      "modes": {
        "easy": {
          "enemyHp": 46.5,
          "gateHp": 0,
          "waveSeconds": 28,
          "shotSpeed": 92.8,
          "shotInterval": 3.5,
          "raw": 35,
          "score": 6
        },
        "normal": {
          "enemyHp": 64,
          "gateHp": 0,
          "waveSeconds": 28,
          "shotSpeed": 119,
          "shotInterval": 2.9,
          "raw": 40.9,
          "score": 12
        },
        "hard": {
          "enemyHp": 86.9,
          "gateHp": 0,
          "waveSeconds": 28,
          "shotSpeed": 141.6,
          "shotInterval": 2.4,
          "raw": 47,
          "score": 17
        },
        "abyss": {
          "enemyHp": 109.4,
          "gateHp": 0,
          "waveSeconds": 28,
          "shotSpeed": 151.1,
          "shotInterval": 2.1,
          "raw": 51.1,
          "score": 21
        }
      }
    },
    {
      "dungeon": 1,
      "room": 1,
      "name": "서약의 관문",
      "mechanicWeight": 4,
      "modes": {
        "easy": {
          "enemyHp": 52.1,
          "gateHp": 1942,
          "waveSeconds": 33,
          "shotSpeed": 92.8,
          "shotInterval": 3.5,
          "raw": 51.3,
          "score": 21
        },
        "normal": {
          "enemyHp": 71.7,
          "gateHp": 2671.4,
          "waveSeconds": 33,
          "shotSpeed": 119,
          "shotInterval": 2.9,
          "raw": 60.3,
          "score": 29
        },
        "hard": {
          "enemyHp": 97.3,
          "gateHp": 3623.8,
          "waveSeconds": 33,
          "shotSpeed": 141.6,
          "shotInterval": 2.4,
          "raw": 69.5,
          "score": 37
        },
        "abyss": {
          "enemyHp": 122.6,
          "gateHp": 4928.4,
          "waveSeconds": 33,
          "shotSpeed": 151.1,
          "shotInterval": 2.1,
          "raw": 76.9,
          "score": 44
        }
      }
    },
    {
      "dungeon": 1,
      "room": 2,
      "name": "영원한 사랑의 제단",
      "mechanicWeight": 4,
      "modes": {
        "easy": {
          "enemyHp": 57.7,
          "gateHp": 5634,
          "waveSeconds": 38,
          "shotSpeed": 92.8,
          "shotInterval": 3.5,
          "raw": 64.1,
          "score": 32
        },
        "normal": {
          "enemyHp": 79.4,
          "gateHp": 7750.1,
          "waveSeconds": 38,
          "shotSpeed": 119,
          "shotInterval": 2.9,
          "raw": 74,
          "score": 41
        },
        "hard": {
          "enemyHp": 107.7,
          "gateHp": 10513.2,
          "waveSeconds": 38,
          "shotSpeed": 141.6,
          "shotInterval": 2.4,
          "raw": 83.8,
          "score": 50
        },
        "abyss": {
          "enemyHp": 135.7,
          "gateHp": 16190.3,
          "waveSeconds": 38,
          "shotSpeed": 151.1,
          "shotInterval": 2.1,
          "raw": 93.3,
          "score": 58
        }
      }
    },
    {
      "dungeon": 2,
      "room": 0,
      "name": "그림자 회랑",
      "mechanicWeight": 6,
      "modes": {
        "easy": {
          "enemyHp": 58.2,
          "gateHp": 0,
          "waveSeconds": 31,
          "shotSpeed": 103.7,
          "shotInterval": 3.5,
          "raw": 40.8,
          "score": 12
        },
        "normal": {
          "enemyHp": 80,
          "gateHp": 0,
          "waveSeconds": 31,
          "shotSpeed": 133,
          "shotInterval": 2.9,
          "raw": 47.3,
          "score": 17
        },
        "hard": {
          "enemyHp": 108.6,
          "gateHp": 0,
          "waveSeconds": 31,
          "shotSpeed": 158.3,
          "shotInterval": 2.4,
          "raw": 53.9,
          "score": 23
        },
        "abyss": {
          "enemyHp": 132.5,
          "gateHp": 0,
          "waveSeconds": 31,
          "shotSpeed": 168.9,
          "shotInterval": 2.1,
          "raw": 57.8,
          "score": 27
        }
      }
    },
    {
      "dungeon": 2,
      "room": 1,
      "name": "저주의 관문",
      "mechanicWeight": 6,
      "modes": {
        "easy": {
          "enemyHp": 65.2,
          "gateHp": 2467.4,
          "waveSeconds": 36,
          "shotSpeed": 103.7,
          "shotInterval": 3.5,
          "raw": 59.4,
          "score": 28
        },
        "normal": {
          "enemyHp": 89.6,
          "gateHp": 3394.1,
          "waveSeconds": 36,
          "shotSpeed": 133,
          "shotInterval": 2.9,
          "raw": 69.1,
          "score": 37
        },
        "hard": {
          "enemyHp": 121.6,
          "gateHp": 4604.2,
          "waveSeconds": 36,
          "shotSpeed": 158.3,
          "shotInterval": 2.4,
          "raw": 78.9,
          "score": 45
        },
        "abyss": {
          "enemyHp": 148.4,
          "gateHp": 6077.6,
          "waveSeconds": 36,
          "shotSpeed": 168.9,
          "shotInterval": 2.1,
          "raw": 86,
          "score": 52
        }
      }
    },
    {
      "dungeon": 2,
      "room": 2,
      "name": "일곱 빛의 파멸",
      "mechanicWeight": 6,
      "modes": {
        "easy": {
          "enemyHp": 72.2,
          "gateHp": 7355.5,
          "waveSeconds": 41,
          "shotSpeed": 103.7,
          "shotInterval": 3.5,
          "raw": 73.2,
          "score": 40
        },
        "normal": {
          "enemyHp": 99.2,
          "gateHp": 10118.2,
          "waveSeconds": 41,
          "shotSpeed": 133,
          "shotInterval": 2.9,
          "raw": 83.7,
          "score": 50
        },
        "hard": {
          "enemyHp": 134.6,
          "gateHp": 13725.5,
          "waveSeconds": 41,
          "shotSpeed": 158.3,
          "shotInterval": 2.4,
          "raw": 94.1,
          "score": 59
        },
        "abyss": {
          "enemyHp": 164.3,
          "gateHp": 20313.7,
          "waveSeconds": 41,
          "shotSpeed": 168.9,
          "shotInterval": 2.1,
          "raw": 102.9,
          "score": 67
        }
      }
    },
    {
      "dungeon": 3,
      "room": 0,
      "name": "꽃빛의 오솔길",
      "mechanicWeight": 7,
      "modes": {
        "easy": {
          "enemyHp": 71.1,
          "gateHp": 0,
          "waveSeconds": 34,
          "shotSpeed": 114.7,
          "shotInterval": 3.5,
          "raw": 45.6,
          "score": 16
        },
        "normal": {
          "enemyHp": 97.7,
          "gateHp": 0,
          "waveSeconds": 34,
          "shotSpeed": 147,
          "shotInterval": 2.9,
          "raw": 52.6,
          "score": 22
        },
        "hard": {
          "enemyHp": 132.6,
          "gateHp": 0,
          "waveSeconds": 34,
          "shotSpeed": 174.9,
          "shotInterval": 2.4,
          "raw": 59.6,
          "score": 28
        },
        "abyss": {
          "enemyHp": 156.5,
          "gateHp": 0,
          "waveSeconds": 34,
          "shotSpeed": 186.7,
          "shotInterval": 2.1,
          "raw": 63.3,
          "score": 31
        }
      }
    },
    {
      "dungeon": 3,
      "room": 1,
      "name": "수호목의 관문",
      "mechanicWeight": 7,
      "modes": {
        "easy": {
          "enemyHp": 79.6,
          "gateHp": 3047.7,
          "waveSeconds": 39,
          "shotSpeed": 114.7,
          "shotInterval": 3.5,
          "raw": 66.3,
          "score": 34
        },
        "normal": {
          "enemyHp": 109.5,
          "gateHp": 4192.4,
          "waveSeconds": 39,
          "shotSpeed": 147,
          "shotInterval": 2.9,
          "raw": 76.7,
          "score": 43
        },
        "hard": {
          "enemyHp": 148.5,
          "gateHp": 5687.1,
          "waveSeconds": 39,
          "shotSpeed": 174.9,
          "shotInterval": 2.4,
          "raw": 87,
          "score": 53
        },
        "abyss": {
          "enemyHp": 175.2,
          "gateHp": 7279.5,
          "waveSeconds": 39,
          "shotSpeed": 186.7,
          "shotInterval": 2.1,
          "raw": 93.5,
          "score": 58
        }
      }
    },
    {
      "dungeon": 3,
      "room": 2,
      "name": "만개하는 성소",
      "mechanicWeight": 7,
      "modes": {
        "easy": {
          "enemyHp": 88.1,
          "gateHp": 9311.7,
          "waveSeconds": 44,
          "shotSpeed": 114.7,
          "shotInterval": 3.5,
          "raw": 80.9,
          "score": 47
        },
        "normal": {
          "enemyHp": 121.2,
          "gateHp": 12809.2,
          "waveSeconds": 44,
          "shotSpeed": 147,
          "shotInterval": 2.9,
          "raw": 91.9,
          "score": 57
        },
        "hard": {
          "enemyHp": 164.4,
          "gateHp": 17375.9,
          "waveSeconds": 44,
          "shotSpeed": 174.9,
          "shotInterval": 2.4,
          "raw": 102.8,
          "score": 67
        },
        "abyss": {
          "enemyHp": 194,
          "gateHp": 24673.8,
          "waveSeconds": 44,
          "shotSpeed": 186.7,
          "shotInterval": 2.1,
          "raw": 110.9,
          "score": 74
        }
      }
    },
    {
      "dungeon": 4,
      "room": 0,
      "name": "가라앉은 회랑",
      "mechanicWeight": 9,
      "modes": {
        "easy": {
          "enemyHp": 84.8,
          "gateHp": 0,
          "waveSeconds": 37,
          "shotSpeed": 125.6,
          "shotInterval": 3.5,
          "raw": 51.3,
          "score": 21
        },
        "normal": {
          "enemyHp": 116.6,
          "gateHp": 0,
          "waveSeconds": 37,
          "shotSpeed": 161,
          "shotInterval": 2.9,
          "raw": 58.7,
          "score": 27
        },
        "hard": {
          "enemyHp": 158.2,
          "gateHp": 0,
          "waveSeconds": 37,
          "shotSpeed": 191.6,
          "shotInterval": 2.4,
          "raw": 66.1,
          "score": 34
        },
        "abyss": {
          "enemyHp": 180.3,
          "gateHp": 0,
          "waveSeconds": 37,
          "shotSpeed": 204.5,
          "shotInterval": 2.1,
          "raw": 69.5,
          "score": 37
        }
      }
    },
    {
      "dungeon": 4,
      "room": 1,
      "name": "해류의 관문",
      "mechanicWeight": 9,
      "modes": {
        "easy": {
          "enemyHp": 94.9,
          "gateHp": 3666.3,
          "waveSeconds": 42,
          "shotSpeed": 125.6,
          "shotInterval": 3.5,
          "raw": 73.9,
          "score": 41
        },
        "normal": {
          "enemyHp": 130.6,
          "gateHp": 5043.3,
          "waveSeconds": 42,
          "shotSpeed": 161,
          "shotInterval": 2.9,
          "raw": 84.8,
          "score": 51
        },
        "hard": {
          "enemyHp": 177.2,
          "gateHp": 6841.3,
          "waveSeconds": 42,
          "shotSpeed": 191.6,
          "shotInterval": 2.4,
          "raw": 95.7,
          "score": 60
        },
        "abyss": {
          "enemyHp": 202,
          "gateHp": 8483.3,
          "waveSeconds": 42,
          "shotSpeed": 204.5,
          "shotInterval": 2.1,
          "raw": 101.6,
          "score": 65
        }
      }
    },
    {
      "dungeon": 4,
      "room": 2,
      "name": "해신의 왕좌",
      "mechanicWeight": 9,
      "modes": {
        "easy": {
          "enemyHp": 105.1,
          "gateHp": 11346.2,
          "waveSeconds": 47,
          "shotSpeed": 125.6,
          "shotInterval": 3.5,
          "raw": 89,
          "score": 54
        },
        "normal": {
          "enemyHp": 144.6,
          "gateHp": 15607.8,
          "waveSeconds": 47,
          "shotSpeed": 161,
          "shotInterval": 2.9,
          "raw": 100.6,
          "score": 65
        },
        "hard": {
          "enemyHp": 196.1,
          "gateHp": 21172.3,
          "waveSeconds": 47,
          "shotSpeed": 191.6,
          "shotInterval": 2.4,
          "raw": 111.9,
          "score": 75
        },
        "abyss": {
          "enemyHp": 223.6,
          "gateHp": 28794.4,
          "waveSeconds": 47,
          "shotSpeed": 204.5,
          "shotInterval": 2.1,
          "raw": 119.2,
          "score": 81
        }
      }
    },
    {
      "dungeon": 5,
      "room": 0,
      "name": "균열의 가장자리",
      "mechanicWeight": 12,
      "modes": {
        "easy": {
          "enemyHp": 99.3,
          "gateHp": 0,
          "waveSeconds": 40,
          "shotSpeed": 136.5,
          "shotInterval": 3.5,
          "raw": 57.9,
          "score": 27
        },
        "normal": {
          "enemyHp": 136.6,
          "gateHp": 0,
          "waveSeconds": 40,
          "shotSpeed": 175,
          "shotInterval": 2.9,
          "raw": 65.7,
          "score": 34
        },
        "hard": {
          "enemyHp": 185.3,
          "gateHp": 0,
          "waveSeconds": 40,
          "shotSpeed": 208.3,
          "shotInterval": 2.4,
          "raw": 73.5,
          "score": 41
        },
        "abyss": {
          "enemyHp": 203.9,
          "gateHp": 0,
          "waveSeconds": 40,
          "shotSpeed": 222.3,
          "shotInterval": 2.1,
          "raw": 76.5,
          "score": 43
        }
      }
    },
    {
      "dungeon": 5,
      "room": 1,
      "name": "심연의 관문",
      "mechanicWeight": 12,
      "modes": {
        "easy": {
          "enemyHp": 111.2,
          "gateHp": 4323,
          "waveSeconds": 45,
          "shotSpeed": 136.5,
          "shotInterval": 3.5,
          "raw": 82.2,
          "score": 48
        },
        "normal": {
          "enemyHp": 153,
          "gateHp": 5946.7,
          "waveSeconds": 45,
          "shotSpeed": 175,
          "shotInterval": 2.9,
          "raw": 93.7,
          "score": 58
        },
        "hard": {
          "enemyHp": 207.6,
          "gateHp": 8066.8,
          "waveSeconds": 45,
          "shotSpeed": 208.3,
          "shotInterval": 2.4,
          "raw": 105,
          "score": 68
        },
        "abyss": {
          "enemyHp": 228.3,
          "gateHp": 9680.2,
          "waveSeconds": 45,
          "shotSpeed": 222.3,
          "shotInterval": 2.1,
          "raw": 110.1,
          "score": 73
        }
      }
    },
    {
      "dungeon": 5,
      "room": 2,
      "name": "검은 태양의 왕좌",
      "mechanicWeight": 12,
      "modes": {
        "easy": {
          "enemyHp": 123.2,
          "gateHp": 13302.4,
          "waveSeconds": 50,
          "shotSpeed": 136.5,
          "shotInterval": 3.5,
          "raw": 97.6,
          "score": 62
        },
        "normal": {
          "enemyHp": 169.4,
          "gateHp": 18298.8,
          "waveSeconds": 50,
          "shotSpeed": 175,
          "shotInterval": 2.9,
          "raw": 109.6,
          "score": 73
        },
        "hard": {
          "enemyHp": 229.8,
          "gateHp": 24822.7,
          "waveSeconds": 50,
          "shotSpeed": 208.3,
          "shotInterval": 2.4,
          "raw": 121.3,
          "score": 83
        },
        "abyss": {
          "enemyHp": 252.8,
          "gateHp": 32269.5,
          "waveSeconds": 50,
          "shotSpeed": 222.3,
          "shotInterval": 2.1,
          "raw": 127.6,
          "score": 89
        }
      }
    },
    {
      "dungeon": 6,
      "room": 0,
      "name": "여명의 계단",
      "mechanicWeight": 15,
      "modes": {
        "easy": {
          "enemyHp": 127,
          "gateHp": 0,
          "waveSeconds": 43,
          "shotSpeed": 147.4,
          "shotInterval": 3.5,
          "raw": 65.6,
          "score": 34
        },
        "normal": {
          "enemyHp": 174.7,
          "gateHp": 0,
          "waveSeconds": 43,
          "shotSpeed": 189,
          "shotInterval": 2.9,
          "raw": 74,
          "score": 41
        },
        "hard": {
          "enemyHp": 237,
          "gateHp": 0,
          "waveSeconds": 43,
          "shotSpeed": 224.9,
          "shotInterval": 2.4,
          "raw": 82.2,
          "score": 48
        },
        "abyss": {
          "enemyHp": 260.7,
          "gateHp": 0,
          "waveSeconds": 43,
          "shotSpeed": 240,
          "shotInterval": 2.1,
          "raw": 85.3,
          "score": 51
        }
      }
    },
    {
      "dungeon": 6,
      "room": 1,
      "name": "갈라지는 빛의 관문",
      "mechanicWeight": 15,
      "modes": {
        "easy": {
          "enemyHp": 142.2,
          "gateHp": 5555.6,
          "waveSeconds": 48,
          "shotSpeed": 147.4,
          "shotInterval": 3.5,
          "raw": 92.8,
          "score": 58
        },
        "normal": {
          "enemyHp": 195.6,
          "gateHp": 7642.2,
          "waveSeconds": 48,
          "shotSpeed": 189,
          "shotInterval": 2.9,
          "raw": 104.9,
          "score": 68
        },
        "hard": {
          "enemyHp": 265.4,
          "gateHp": 10366.8,
          "waveSeconds": 48,
          "shotSpeed": 224.9,
          "shotInterval": 2.4,
          "raw": 116.7,
          "score": 79
        },
        "abyss": {
          "enemyHp": 291.9,
          "gateHp": 12440.2,
          "waveSeconds": 48,
          "shotSpeed": 240,
          "shotInterval": 2.1,
          "raw": 122,
          "score": 84
        }
      }
    },
    {
      "dungeon": 6,
      "room": 2,
      "name": "창조의 옥좌",
      "mechanicWeight": 15,
      "modes": {
        "easy": {
          "enemyHp": 157.5,
          "gateHp": 18075.7,
          "waveSeconds": 53,
          "shotSpeed": 147.4,
          "shotInterval": 3.5,
          "raw": 109.3,
          "score": 72
        },
        "normal": {
          "enemyHp": 216.6,
          "gateHp": 24864.8,
          "waveSeconds": 53,
          "shotSpeed": 189,
          "shotInterval": 2.9,
          "raw": 121.9,
          "score": 83
        },
        "hard": {
          "enemyHp": 293.8,
          "gateHp": 33729.7,
          "waveSeconds": 53,
          "shotSpeed": 224.9,
          "shotInterval": 2.4,
          "raw": 134,
          "score": 94
        },
        "abyss": {
          "enemyHp": 323.2,
          "gateHp": 43848.6,
          "waveSeconds": 53,
          "shotSpeed": 240,
          "shotInterval": 2.1,
          "raw": 140.5,
          "score": 100
        }
      }
    },
    {
      "dungeon": 7,
      "room": 0,
      "name": "설탕빛 거리",
      "mechanicWeight": 6,
      "modes": {
        "easy": {
          "enemyHp": 107.1,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 53.4,
          "score": 23
        },
        "normal": {
          "enemyHp": 147.3,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 61.4,
          "score": 30
        },
        "hard": {
          "enemyHp": 199.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 69.3,
          "score": 37
        },
        "abyss": {
          "enemyHp": 219.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 72.4,
          "score": 40
        }
      }
    },
    {
      "dungeon": 7,
      "room": 1,
      "name": "마카롱 관문",
      "mechanicWeight": 6,
      "modes": {
        "easy": {
          "enemyHp": 119.9,
          "gateHp": 4670.3,
          "waveSeconds": 46.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 78.6,
          "score": 45
        },
        "normal": {
          "enemyHp": 165,
          "gateHp": 6424.4,
          "waveSeconds": 46.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 90.3,
          "score": 55
        },
        "hard": {
          "enemyHp": 223.8,
          "gateHp": 8714.9,
          "waveSeconds": 46.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 101.7,
          "score": 66
        },
        "abyss": {
          "enemyHp": 246.2,
          "gateHp": 10457.9,
          "waveSeconds": 46.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 106.9,
          "score": 70
        }
      }
    },
    {
      "dungeon": 7,
      "room": 2,
      "name": "하모니어스의 무대",
      "mechanicWeight": 6,
      "modes": {
        "easy": {
          "enemyHp": 132.8,
          "gateHp": 14241.4,
          "waveSeconds": 51.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 94,
          "score": 59
        },
        "normal": {
          "enemyHp": 182.7,
          "gateHp": 19590.5,
          "waveSeconds": 51.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 106.2,
          "score": 70
        },
        "hard": {
          "enemyHp": 247.8,
          "gateHp": 26574.9,
          "waveSeconds": 51.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 118,
          "score": 80
        },
        "abyss": {
          "enemyHp": 272.6,
          "gateHp": 34547.4,
          "waveSeconds": 51.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 124.4,
          "score": 86
        }
      }
    },
    {
      "dungeon": 8,
      "room": 0,
      "name": "황금빛 절벽",
      "mechanicWeight": 10,
      "modes": {
        "easy": {
          "enemyHp": 107.1,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 57.4,
          "score": 26
        },
        "normal": {
          "enemyHp": 147.3,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 65.4,
          "score": 33
        },
        "hard": {
          "enemyHp": 199.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 73.3,
          "score": 40
        },
        "abyss": {
          "enemyHp": 219.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 76.4,
          "score": 43
        }
      }
    },
    {
      "dungeon": 8,
      "room": 1,
      "name": "비늘의 관문",
      "mechanicWeight": 10,
      "modes": {
        "easy": {
          "enemyHp": 119.9,
          "gateHp": 4670.3,
          "waveSeconds": 46.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 82.6,
          "score": 49
        },
        "normal": {
          "enemyHp": 165,
          "gateHp": 6424.4,
          "waveSeconds": 46.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 94.3,
          "score": 59
        },
        "hard": {
          "enemyHp": 223.8,
          "gateHp": 8714.9,
          "waveSeconds": 46.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 105.7,
          "score": 69
        },
        "abyss": {
          "enemyHp": 246.2,
          "gateHp": 10457.9,
          "waveSeconds": 46.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 110.9,
          "score": 74
        }
      }
    },
    {
      "dungeon": 8,
      "room": 2,
      "name": "보물의 둥지",
      "mechanicWeight": 10,
      "modes": {
        "easy": {
          "enemyHp": 132.8,
          "gateHp": 14241.4,
          "waveSeconds": 51.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 98,
          "score": 62
        },
        "normal": {
          "enemyHp": 182.7,
          "gateHp": 19590.5,
          "waveSeconds": 51.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 110.2,
          "score": 73
        },
        "hard": {
          "enemyHp": 247.8,
          "gateHp": 26574.9,
          "waveSeconds": 51.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 122,
          "score": 84
        },
        "abyss": {
          "enemyHp": 272.6,
          "gateHp": 34547.4,
          "waveSeconds": 51.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 128.4,
          "score": 89
        }
      }
    },
    {
      "dungeon": 9,
      "room": 0,
      "name": "메아리의 입구",
      "mechanicWeight": 8,
      "modes": {
        "easy": {
          "enemyHp": 107.1,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 55.4,
          "score": 24
        },
        "normal": {
          "enemyHp": 147.3,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 63.4,
          "score": 32
        },
        "hard": {
          "enemyHp": 199.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 71.3,
          "score": 39
        },
        "abyss": {
          "enemyHp": 219.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 74.4,
          "score": 41
        }
      }
    },
    {
      "dungeon": 9,
      "room": 1,
      "name": "혼령의 관문",
      "mechanicWeight": 8,
      "modes": {
        "easy": {
          "enemyHp": 119.9,
          "gateHp": 4670.3,
          "waveSeconds": 46.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 80.6,
          "score": 47
        },
        "normal": {
          "enemyHp": 165,
          "gateHp": 6424.4,
          "waveSeconds": 46.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 92.3,
          "score": 57
        },
        "hard": {
          "enemyHp": 223.8,
          "gateHp": 8714.9,
          "waveSeconds": 46.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 103.7,
          "score": 67
        },
        "abyss": {
          "enemyHp": 246.2,
          "gateHp": 10457.9,
          "waveSeconds": 46.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 108.9,
          "score": 72
        }
      }
    },
    {
      "dungeon": 9,
      "room": 2,
      "name": "고대 불꽃의 방",
      "mechanicWeight": 8,
      "modes": {
        "easy": {
          "enemyHp": 132.8,
          "gateHp": 14241.4,
          "waveSeconds": 51.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 96,
          "score": 61
        },
        "normal": {
          "enemyHp": 182.7,
          "gateHp": 19590.5,
          "waveSeconds": 51.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 108.2,
          "score": 71
        },
        "hard": {
          "enemyHp": 247.8,
          "gateHp": 26574.9,
          "waveSeconds": 51.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 120,
          "score": 82
        },
        "abyss": {
          "enemyHp": 272.6,
          "gateHp": 34547.4,
          "waveSeconds": 51.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 126.4,
          "score": 88
        }
      }
    },
    {
      "dungeon": 10,
      "room": 0,
      "name": "균열의 황야",
      "mechanicWeight": 7,
      "modes": {
        "easy": {
          "enemyHp": 107.1,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 54.4,
          "score": 24
        },
        "normal": {
          "enemyHp": 147.3,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 62.4,
          "score": 31
        },
        "hard": {
          "enemyHp": 199.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 70.3,
          "score": 38
        },
        "abyss": {
          "enemyHp": 219.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 73.4,
          "score": 40
        }
      }
    },
    {
      "dungeon": 10,
      "room": 1,
      "name": "사슬의 관문",
      "mechanicWeight": 7,
      "modes": {
        "easy": {
          "enemyHp": 119.9,
          "gateHp": 4670.3,
          "waveSeconds": 46.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 79.6,
          "score": 46
        },
        "normal": {
          "enemyHp": 165,
          "gateHp": 6424.4,
          "waveSeconds": 46.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 91.3,
          "score": 56
        },
        "hard": {
          "enemyHp": 223.8,
          "gateHp": 8714.9,
          "waveSeconds": 46.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 102.7,
          "score": 66
        },
        "abyss": {
          "enemyHp": 246.2,
          "gateHp": 10457.9,
          "waveSeconds": 46.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 107.9,
          "score": 71
        }
      }
    },
    {
      "dungeon": 10,
      "room": 2,
      "name": "봉인의 심장",
      "mechanicWeight": 7,
      "modes": {
        "easy": {
          "enemyHp": 132.8,
          "gateHp": 14241.4,
          "waveSeconds": 51.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 95,
          "score": 60
        },
        "normal": {
          "enemyHp": 182.7,
          "gateHp": 19590.5,
          "waveSeconds": 51.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 107.2,
          "score": 70
        },
        "hard": {
          "enemyHp": 247.8,
          "gateHp": 26574.9,
          "waveSeconds": 51.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 119,
          "score": 81
        },
        "abyss": {
          "enemyHp": 272.6,
          "gateHp": 34547.4,
          "waveSeconds": 51.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 125.4,
          "score": 87
        }
      }
    },
    {
      "dungeon": 11,
      "room": 0,
      "name": "기억의 서가",
      "mechanicWeight": 9,
      "modes": {
        "easy": {
          "enemyHp": 107.1,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 56.4,
          "score": 25
        },
        "normal": {
          "enemyHp": 147.3,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 64.4,
          "score": 32
        },
        "hard": {
          "enemyHp": 199.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 72.3,
          "score": 39
        },
        "abyss": {
          "enemyHp": 219.8,
          "gateHp": 0,
          "waveSeconds": 41.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 75.4,
          "score": 42
        }
      }
    },
    {
      "dungeon": 11,
      "room": 1,
      "name": "시계의 관문",
      "mechanicWeight": 9,
      "modes": {
        "easy": {
          "enemyHp": 119.9,
          "gateHp": 4670.3,
          "waveSeconds": 46.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 81.6,
          "score": 48
        },
        "normal": {
          "enemyHp": 165,
          "gateHp": 6424.4,
          "waveSeconds": 46.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 93.3,
          "score": 58
        },
        "hard": {
          "enemyHp": 223.8,
          "gateHp": 8714.9,
          "waveSeconds": 46.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 104.7,
          "score": 68
        },
        "abyss": {
          "enemyHp": 246.2,
          "gateHp": 10457.9,
          "waveSeconds": 46.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 109.9,
          "score": 73
        }
      }
    },
    {
      "dungeon": 11,
      "room": 2,
      "name": "열두 시의 기록실",
      "mechanicWeight": 9,
      "modes": {
        "easy": {
          "enemyHp": 132.8,
          "gateHp": 14241.4,
          "waveSeconds": 51.1,
          "shotSpeed": 140.3,
          "shotInterval": 3.5,
          "raw": 97,
          "score": 61
        },
        "normal": {
          "enemyHp": 182.7,
          "gateHp": 19590.5,
          "waveSeconds": 51.1,
          "shotSpeed": 179.9,
          "shotInterval": 2.9,
          "raw": 109.2,
          "score": 72
        },
        "hard": {
          "enemyHp": 247.8,
          "gateHp": 26574.9,
          "waveSeconds": 51.1,
          "shotSpeed": 214.1,
          "shotInterval": 2.4,
          "raw": 121,
          "score": 83
        },
        "abyss": {
          "enemyHp": 272.6,
          "gateHp": 34547.4,
          "waveSeconds": 51.1,
          "shotSpeed": 228.5,
          "shotInterval": 2.1,
          "raw": 127.4,
          "score": 88
        }
      }
    }
  ]
};
