const VOCAB_SOURCE = [
    { w: 'amenities', m: '(명) 편의시설; (명) 예의, 기품', tm: '(명) 적, 앙숙; (명) 반대 세력', tw: 'enemies' },
    { w: 'banquet', m: '(명) 연회, 만찬', tm: '(명) 꽃다발; (명) 칭찬하는 말', tw: 'bouquet' },
    { w: 'reserve', m: '(동) 예약하다; (동) 보유하다', tm: '(동) 뒤집다; (동) 후진하다', tw: 'reverse' },
    { w: 'revenue', m: '(명) 수익, 수입; (명) 세입', tm: '(명) 장소, 개최지; (명) 현장', tw: 'venue' },
    { w: 'decline', m: '(동) 감소하다; (동) 거절하다', tm: '(동) 비스듬히 눕다; (동) (의자를) 젖히다', tw: 'recline' },
    { w: 'experiment', m: '(명) 실험; (동) 실험하다', tm: '(명) 경험, 경력; (동) 겪다', tw: 'experience' },
    { w: 'renowned', m: '(형) 유명한, 명성 있는', tm: '(형) 갱신된; (형) 재개된, 새로워진', tw: 'renewed' },
    { w: 'enhance', m: '(동) 향상시키다; (동) 강화하다', tm: '(동) 매혹하다; (동) 마법을 걸다', tw: 'enchant' },
    { w: 'premises', m: '(명) 건물과 토지, 부지', tm: '(명) 약속, 서약; (명) 장래성', tw: 'promise' },
    { w: 'relevant', m: '(형) 관련 있는; (형) 적절한', tm: '(명) 친척; (형) 비교상의, 상대적인', tw: 'relative' },
    { w: 'portable', m: '(형) 휴대할 수 있는', tm: '(형) 마셔도 되는, 식수로 적합한', tw: 'potable' },
    { w: 'refuse', m: '(동) 거절하다; (명) 쓰레기', tm: '(명) 피난처, 은신처; (명) 보호', tw: 'refuge' },
    { w: 'tenant', m: '(명) 임차인, 세입자', tm: '(명) 교리, 주의; (명) 원칙', tw: 'tenet' },
    { w: 'expense', m: '(명) 비용, 지출', tm: '(명) 넓게 트인 지역; (명) 팽창', tw: 'expanse' },
    { w: 'flaw', m: '(명) 결함, 흠', tm: '(명) 흐름; (동) 흐르다', tw: 'flow' },
    { w: 'destination', m: '(명) 목적지, 행선지', tm: '(명) 운명, 숙명', tw: 'destiny' },
    { w: 'district', m: '(명) 구역, 지역', tm: '(형) 뚜렷한, 분명한; (형) 별개의', tw: 'distinct' },
    { w: 'inclement', m: '(형) (날씨가) 궂은, 혹독한', tm: '(명) 증가, 인상; (명) 이익', tw: 'increment' },
    { w: 'exclusively', m: '(부) 단독으로, 오로지', tm: '(부) 지나치게, 과도하게', tw: 'excessively' },
    { w: 'convert', m: '(동) 변환하다; (동) 개종하다', tm: '(형) 비밀의, 은밀한; (명) 은신처', tw: 'covert' },
    { w: 'curb', m: '(동) 억제하다; (명) 제한', tm: '(명) 곡선, 커브; (동) 구부리다', tw: 'curve' },
    { w: 'deduct', m: '(동) 공제하다, 차감하다', tm: '(동) 추론하다, 연역하다', tw: 'deduce' },
    { w: 'repair', m: '(동) 수리하다; (명) 수리', tm: '(동) 손상시키다, 해치다', tw: 'impair' },
    { w: 'emphasis', m: '(명) 강조, 주안점', tm: '(명) 공감, 감정이입', tw: 'empathy' },
    { w: 'popular', m: '(형) 인기 있는; (형) 대중의', tm: '(형) 인구가 많은; (형) 붐비는', tw: 'populous' },
    { w: 'transfer', m: '(동) 이동하다; (동) 전근하다', tm: '(동) 변형시키다; (동) 성질을 바꾸다', tw: 'transform' },
    { w: 'estimate', m: '(동) 추산하다; (명) 견적서', tm: '(동) 존경하다; (명) 존경, 존중', tw: 'esteem' },
    { w: 'laboratory', m: '(명) 실험실, 연구소', tm: '(명) 화장실, 세면장', tw: 'lavatory' },
    { w: 'expire', m: '(동) 만료되다, 끝나다', tm: '(동) 고무하다, 영감을 주다', tw: 'inspire' },
    { w: 'consent', m: '(명) 동의, 허락; (동) 동의하다', tm: '(명) 내용물, 목차; (형) 만족하는', tw: 'content' },
    { w: 'retail', m: '(명) 소매; (형) 소매의', tm: '(명) 세부사항; (동) 상세히 알리다', tw: 'detail' },
    { w: 'affordable', m: '(형) 가격이 알맞은; (형) 감당할 수 있는', tm: '(형) 사랑스러운; (형) 귀여운', tw: 'adorable' },
    { w: 'valid', m: '(형) 유효한; (형) 타당한', tm: '(형) 고체의, 단단한; (형) 견고한', tw: 'solid' },
    { w: 'traffic', m: '(명) 교통(량); (명) 왕래', tm: '(형) 아주 멋진; (형) 훌륭한', tw: 'terrific' },
    { w: 'imperative', m: '(형) 필수적인; (형) 긴급한', tm: '(형) 제국의; (형) 황제의', tw: 'imperial' },
    { w: 'insurance', m: '(명) 보험; (명) 보험금', tm: '(명) 확언, 장담; (명) 보증', tw: 'assurance' },
    { w: 'ingredient', m: '(명) 재료, 성분', tm: '(명) 경사도; (명) 기울기, 비탈', tw: 'gradient' },
    { w: 'renovate', m: '(동) 개조하다, 보수하다', tm: '(동) 혁신하다; (동) 쇄신하다', tw: 'innovate' },
    { w: 'versatile', m: '(형) 다재다능한; (형) 다용도의', tm: '(형) 휘발성의; (형) 변덕스러운', tw: 'volatile' },
    { w: 'implement', m: '(동) 실행하다; (명) 도구', tm: '(동) 보충하다; (명) 부록', tw: 'supplement' },
    { w: 'commitment', m: '(명) 헌신; (명) 약속, 책무', tm: '(명) 위원회; (명) 위원', tw: 'committee' },
    { w: 'facilitate', m: '(동) 용이하게 하다; (동) 촉진하다', tm: '(동) 매혹하다; (동) 마음을 사로잡다', tw: 'fascinate' },
    { w: 'encourage', m: '(동) 격려하다; (동) 권장하다', tm: '(동) 격분하게 하다; (동) 화나게 하다', tw: 'enrage' },
    { w: 'persuade', m: '(동) 설득하다', tm: '(동) 추구하다; (동) 뒤쫓다', tw: 'pursue' },
    { w: 'launch', m: '(동) 출시하다; (동) 시작하다', tm: '(명) 점심 식사; (동) 점심을 먹다', tw: 'lunch' },
    { w: 'reliable', m: '(형) 믿을 수 있는; (형) 확실한', tm: '(형) 법적 책임이 있는; (형) ~하기 쉬운', tw: 'liable' },
    { w: 'strategy', m: '(명) 전략, 계획', tm: '(명) 비극; (명) 참사', tw: 'tragedy' },
    { w: 'remind', m: '(동) 상기시키다; (동) 생각나게 하다', tm: '(동) 되감다; (동) 다시 감다', tw: 'rewind' },
    { w: 'suitable', m: '(형) 적합한, 알맞은', tm: '(형) 안정적인; (형) 차분한', tw: 'stable' },
    { w: 'beverage', m: '(명) 음료', tm: '(형) 평균의; (명) 평균', tw: 'average' },
    { w: 'tentative', m: '(형) 잠정적인, 임시의', tm: '(형) 주의 깊은; (형) 세심한', tw: 'attentive' },
    { w: 'publicity', m: '(명) 홍보, 광고; (명) 평판', tm: '(명) 출판, 발행; (명) 출판물', tw: 'publication' },
    { w: 'procedure', m: '(명) 절차, 순서', tm: '(명) 제작자, PD; (명) 생산자', tw: 'producer' },
    { w: 'merchandise', m: '(명) 상품, 물품', tm: '(명) 상인, 무역상', tw: 'merchant' },
    { w: 'guarantee', m: '(명) 보증; (동) 보장하다', tm: '(명) 격리; (동) 격리하다', tw: 'quarantine' },
    { w: 'alleviate', m: '(동) 완화하다; (동) 경감하다', tm: '(동) (들어) 올리다; (동) 승진시키다', tw: 'elevate' },
    { w: 'solicit', m: '(동) 요청하다; (동) 간청하다', tm: '(형) 불법의; (형) 사회 통념에 어긋나는', tw: 'illicit' },
    { w: 'unprecedented', m: '(형) 전례 없는', tm: '(형) 예측할 수 없는; (형) 종잡을 수 없는', tw: 'unpredictable' },
    { w: 'deny', m: '(동) 부인하다; (동) 거절하다', tm: '(동) 반항하다; (동) 무시하다', tw: 'defy' },
    { w: 'recession', m: '(명) 불경기, 침체', tm: '(명) 접수처; (명) 환영회', tw: 'reception' },
    { w: 'grant', m: '(동) 승인하다; (동) 수여하다', tm: '(형) 웅장한; (형) 원대한', tw: 'grand' },
    { w: 'refund', m: '(명) 환불; (동) 환불하다', tm: '(동) 다시 튀어 오르다; (명) 반등', tw: 'rebound' },
    { w: 'opportunity', m: '(명) 기회; (명) 호기', tm: '(명) 반대; (명) 저항, 대립', tw: 'opposition' },
    { w: 'confidential', m: '(형) 기밀의; (형) 비밀의', tm: '(명) 자격 증명서; (명) 신임장', tw: 'credential' },
    { w: 'outstanding', m: '(형) 미해결의; (형) 뛰어난', tm: '(형) 외향적인, 사교적인; (형) 떠나가는', tw: 'outgoing' },
    { w: 'process', m: '(명) 과정, 절차; (동) 처리하다', tm: '(동) 소유하다; (동) 사로잡다', tw: 'possess' },
    { w: 'simply', m: '(부) 단순히; (부) 그저', tm: '(부) 충분히; (부) 상세하게', tw: 'amply' },
    { w: 'presence', m: '(명) 존재; (명) 참석', tm: '(명) 선호(도); (명) 애호', tw: 'preference' },
    { w: 'effective', m: '(형) 효과적인; (형) 유효한', tm: '(형) 정서적인; (형) 감정의', tw: 'affective' },
    { w: 'spacious', m: '(형) 넓은; (형) 훤히 트인', tm: '(형) 그럴듯한; (형) 겉만 번지르르한', tw: 'specious' },
    { w: 'withdraw', m: '(동) 철회하다; (동) 인출하다', tm: '(동) 견뎌내다; (동) 저항하다', tw: 'withstand' },
    { w: 'specific', m: '(형) 구체적인; (형) 특정한', tm: '(형) 평화로운; (형) 태평양의', tw: 'pacific' },
    { w: 'specialize', m: '(동) 전문화하다; (동) 특수화하다', tm: '(동) 교제하다; (동) 어울리다', tw: 'socialize' },
    { w: 'equip', m: '(동) 장비를 갖추다; (동) 채비를 하다', tm: '(명) 재치 있는 말; (명) 빈정거림', tw: 'quip' },
    { w: 'reimbursement', m: '(명) 변제, 상환; (명) 배상', tm: '(명) 지불, 지출; (명) 자금 집행', tw: 'disbursement' },
    { w: 'informed', m: '(형) 정보통인; (형) 유식한', tm: '(형) 허약한; (형) 병약한', tw: 'infirm' },
    { w: 'direct', m: '(형) 직접적인; (동) 지시하다', tm: '(동) 발견하다; (동) 감지하다', tw: 'detect' },
    { w: 'cover', m: '(동) 덮다; (동) 포함하다', tm: '(동) 맴돌다; (동) 공중 정지하다', tw: 'hover' },
    { w: 'accompany', m: '(동) 동행하다; (동) 동반하다', tm: '(동) 성취하다; (동) 완수하다', tw: 'accomplish' },
    { w: 'contribute', m: '(동) 기여하다; (동) 기부하다', tm: '(동) 분배하다; (동) 유통시키다', tw: 'distribute' },
    { w: 'motivate', m: '(동) 동기부여하다; (동) 자극하다', tm: '(동) 경작하다; (동) 재배하다', tw: 'cultivate' },
    { w: 'consider', m: '(동) 고려하다; (동) 숙고하다', tm: '(동) 인정하다; (동) 양보하다', tw: 'concede' },
    { w: 'arrange', m: '(동) 정리하다; (동) 마련하다', tm: '(동) 어지럽히다; (동) 미치게 하다', tw: 'derange' },
    { w: 'associate', m: '(동) 연관짓다; (동) 교제하다', tm: '(동) 옹호하다; (명) 지지자', tw: 'advocate' },
    { w: 'instructor', m: '(명) 강사; (명) 지도자', tm: '(명) 건설자; (명) 시공자', tw: 'constructor' },
    { w: 'weekly', m: '(형) 매주의; (부) 매주', tm: '(부) 약하게; (부) 힘없이', tw: 'weakly' },
    { w: 'reveal', m: '(동) 드러내다; (동) 폭로하다', tm: '(동) 흥청거리다; (명) 왁자지껄한 파티', tw: 'revel' },
    { w: 'assembly', m: '(명) 조립; (명) 집회', tm: '(명) 닮음; (명) 유사함', tw: 'resemblance' },
    { w: 'overdue', m: '(형) 기한이 지난; (형) 연체된', tm: '(동) 지나치게 하다; (동) 과장하다', tw: 'overdo' },
    { w: 'timely', m: '(형) 시기적절한; (형) 때맞춘', tm: '(부) 소심하게; (부) 겁먹고', tw: 'timidly' },
    { w: 'duty', m: '(명) 의무; (명) 관세', tm: '(부) 적절하게; (부) 절차에 따라', tw: 'duly' },
    { w: 'impose', m: '(동) 부과하다; (동) 강요하다', tm: '(동) 구성하다; (동) 작곡하다', tw: 'compose' },
    { w: 'merger', m: '(명) 합병; (명) 통합', tm: '(형) 빈약한; (형) 결핍된', tw: 'meager' },
    { w: 'demonstration', m: '(명) 시연; (명) 입증', tm: '(명) 파괴; (명) 철거', tw: 'demolition' },
    { w: 'fluctuate', m: '(동) 변동하다; (동) 오르내리다', tm: '(동) 구두점을 찍다; (동) 강조하다', tw: 'punctuate' },
    { w: 'deliver', m: '(동) 배달하다; (동) 연설하다', tm: '(형) 고의적인; (형) 신중한', tw: 'deliberate' },
    { w: 'devoted', m: '(형) 헌신적인; (형) 전념하는', tm: '(동) 강등시키다; (동) 좌천시키다', tw: 'demote' },
    { w: 'stock', m: '(명) 재고; (명) 주식', tm: '(동) 몰래 접근하다; (명) 줄기', tw: 'stalk' },
    { w: 'authority', m: '(명) 권한; (명) 당국', tm: '(명) 작가; (명) 저자', tw: 'author' },
    { w: 'variety', m: '(명) 다양성; (명) 품종', tm: '(명) 진실성; (명) 진리', tw: 'verity' }
];

const VOCAB_DATA = [];

VOCAB_SOURCE.forEach(item => {
    // Add Original
    VOCAB_DATA.push({
        word: item.w,
        meaning: item.m,
        trap_meaning: item.tm,
        trap_word: item.tw
    });
    // Add Trap Pair
    VOCAB_DATA.push({
        word: item.tw,
        meaning: item.tm,
        trap_meaning: item.m,
        trap_word: item.w
    });
});
