import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('playwright'),C=require('../src/core.js');
const root=path.resolve(import.meta.dirname,'..'),out=process.env.LUNA_QA_DIR||'/tmp/luna-qa';
await fs.mkdir(out,{recursive:true});
const launch={headless:true};
if(process.env.LUNA_CHROMIUM_PATH)launch.executablePath=process.env.LUNA_CHROMIUM_PATH;
if(process.env.LUNA_CHROMIUM_SINGLE_PROCESS==='1')launch.args=['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--in-process-gpu','--disable-features=AudioServiceOutOfProcess'];
const browser=await chromium.launch(launch),url=pathToFileURL(path.join(root,'dist/LunaRememberedNames.html')).href+'?qa=1',errors=[],network=[],checks=[];
const contexts=[];
async function page(options={},init){const context=await browser.newContext({viewport:{width:390,height:844},...options});contexts.push(context);await context.setOffline(true);if(init)await context.addInitScript(init);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!/^(file:|data:|blob:)/.test(r.url()))network.push(r.url());});await p.goto(url);await p.waitForFunction(()=>!!window.__LUNA_TEST__);return p;}
const state=p=>p.evaluate(()=>({screen:__LUNA_TEST__.screen(),g:__LUNA_TEST__.state(),options:__LUNA_TEST__.options(),storage:__LUNA_TEST__.storage()}));
const click=(p,name)=>p.getByRole('button',{name,exact:true}).click();
const shot=(p,name)=>p.screenshot({path:path.join(out,name+'.png')});
const fixture=(room=0,choices=['keep'])=>{const g=C.create(21);g.room=room;g.choices=choices;C.beginRoom(g);return C.checkpoint(g);};
async function load(p,room=0,choices=['keep']){await p.evaluate(raw=>__LUNA_TEST__.load(raw),fixture(room,choices));}
async function finishRoom(p){await p.evaluate(()=>{const g=__LUNA_TEST__.state();g.time=LunaCore.ROOMS[g.room][3]+.04;g.enemies=[];g.spawn=999;__LUNA_TEST__.step(1,{});});assert.equal((await state(p)).screen,'upgrade');}
try{
 const p=await page();
 assert.equal((await state(p)).screen,'title');
 await p.evaluate(async()=>{await Promise.all([...document.images].map(i=>i.decode()));});
 const bg=await p.locator('.portrait').evaluate(e=>getComputedStyle(e).backgroundImage);assert.match(bg,/data:image\/webp/);
 await shot(p,'01-mobile-title');await click(p,'이름을 따라 시작하기');assert.equal((await state(p)).screen,'story');
 await p.waitForFunction(()=>document.querySelector('.expression').naturalWidth>0);await shot(p,'02-mobile-choice');
 await click(p,'편지의 이름을 남긴다');await click(p,'알겠어. 가자');assert.equal((await state(p)).g.choices[0],'keep');
 const x=(await state(p)).g.player.x;await p.keyboard.down('d');await p.waitForTimeout(230);await p.keyboard.up('d');assert.ok((await state(p)).g.player.x>x+15,'actual keyboard movement');
 await p.keyboard.press('Space');assert.ok((await state(p)).g.dashCd>1);await p.keyboard.press('e');assert.ok((await state(p)).g.veil>1);
 await p.keyboard.down('j');await p.waitForTimeout(70);assert.ok((await state(p)).g.attack>0);await p.keyboard.up('j');
 await p.keyboard.press('Escape');assert.equal((await state(p)).screen,'pause');const t=(await state(p)).g.time;await p.waitForTimeout(170);assert.equal((await state(p)).g.time,t);
 await p.locator('#soundOption').uncheck();await p.locator('#motionOption').check();await click(p,'이어서 플레이');assert.equal((await state(p)).options.sound,false);assert.equal((await state(p)).options.reduced,true);
 await load(p);await p.keyboard.down('d');await p.keyboard.press('Escape');await p.keyboard.up('d');await click(p,'이어서 플레이');const still=(await state(p)).g.player.x;await p.waitForTimeout(100);assert.equal((await state(p)).g.player.x,still,'pause clears held input');
 await load(p,4,['keep','keep']);await p.evaluate(()=>__LUNA_TEST__.step(240,{x:0,y:-.35,attack:true}));await shot(p,'03-mobile-play');await load(p);checks.push('offline title art, original chapter choice, real keyboard movement/attack/dash/veil, pause/resume and held-input reset');
 await p.keyboard.press('Escape');const downloadPromise=p.waitForEvent('download');await click(p,'방 시작으로 저장 백업');const download=await downloadPromise;const downloaded=await fs.readFile(await download.path(),'utf8');assert.ok(C.restore(downloaded));await click(p,'이어서 플레이');
 await p.reload();assert.equal((await state(p)).screen,'title');await click(p,'이어 하기 · 분류실');assert.equal((await state(p)).g.time<1,true);assert.deepEqual((await state(p)).g.choices,['keep']);assert.equal((await state(p)).options.sound,false);checks.push('durable room checkpoint, reload/continue preserves choice/settings, downloadable valid save backup');
 await load(p);await p.evaluate(()=>{const g=__LUNA_TEST__.state();g.spawn=999;g.player={...g.player,x:g.wards[0].x,y:g.wards[0].y};__LUNA_TEST__.step(52,{});});assert.equal((await state(p)).g.names,1);assert.match(await p.locator('#toast').innerText(),/이름을 보존/);
 await finishRoom(p);const upgrade=p.locator('.upgrade').first();await upgrade.evaluate(e=>{e.click();e.click();});assert.equal((await state(p)).g.room,1);assert.equal((await state(p)).g.upgrades.length,1);await p.reload();await click(p,'이어 하기 · 종이 골목');assert.equal((await state(p)).g.names,1);checks.push('ward channel feedback, room upgrade repeated-click safety, next-room autosave and names survive reload');
 await load(p);await p.evaluate(()=>{const g=__LUNA_TEST__.state();g.hp=1;g.invuln=0;g.shots=[{x:g.player.x,y:g.player.y,vx:0,vy:0,life:1}];__LUNA_TEST__.step(1,{});});assert.equal((await state(p)).screen,'dead');await click(p,'방 시작부터 다시');assert.equal((await state(p)).g.hp,8);assert.equal((await state(p)).g.names,0);checks.push('death uses last room-start checkpoint without farming collected names');
 // Actual pointer events, including released joystick and interrupted attack.
 await load(p);const box=await p.locator('#joystick').boundingBox(),before=(await state(p)).g.player.x;await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width-3,box.y+box.height/2);await p.waitForTimeout(180);await p.mouse.up();assert.ok((await state(p)).g.player.x>before+15);const stopped=(await state(p)).g.player.x;await p.waitForTimeout(120);assert.equal((await state(p)).g.player.x,stopped);await p.locator('#attack').dispatchEvent('pointercancel',{pointerId:1});const attackBox=await p.locator('#attack').boundingBox();await p.mouse.move(attackBox.x+attackBox.width/2,attackBox.y+attackBox.height/2);await p.mouse.down();await p.evaluate(()=>__LUNA_TEST__.step(3));assert.ok((await state(p)).g.attack>0);await p.locator('#attack').dispatchEvent('pointercancel',{pointerId:1});await p.evaluate(()=>__LUNA_TEST__.step(15));assert.equal((await state(p)).g.attack,0);await p.mouse.up();checks.push('pointer joystick move/release has no stuck movement; cancellation releases an actually held attack');
 for(const v of [{width:360,height:640},{width:390,height:844},{width:1280,height:720}]){await p.setViewportSize(v);await p.keyboard.press('Escape');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no document horizontal overflow');assert.ok(await p.getByRole('button',{name:'이어서 플레이',exact:true}).isVisible());await click(p,'이어서 플레이');const hud=await p.locator('#hud').boundingBox(),controls=await p.locator('#controls').boundingBox();assert.ok(hud.y+hud.height<controls.y);if(v.width===1280)await shot(p,'04-desktop-play');}
 checks.push('360×640, 390×844 and 1280×720 responsive portrait stage; settings/action controls reachable without horizontal overflow');
 const cdp=await p.context().newCDPSession(p);await p.setViewportSize({width:360,height:640});await cdp.send('Emulation.setSafeAreaInsetsOverride',{insets:{top:44,bottom:34,left:0,right:0}});
 const safe=await p.locator('#app').boundingBox();assert.ok(safe.y>=44);assert.ok(safe.y+safe.height<=640-34+.5);const buttons=await Promise.all(['#joystick','#attack','#dash','#veil'].map(s=>p.locator(s).boundingBox()));for(let i=0;i<buttons.length;i++){assert.ok(buttons[i].y>=44&&buttons[i].y+buttons[i].height<=606);for(let j=i+1;j<buttons.length;j++){const a=buttons[i],b=buttons[j];assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,'touch buttons must not overlap '+JSON.stringify({i,j,a,b}));}}
 const actorArea=await p.locator('#scene').boundingBox(),actorBottom=actorArea.y+509/680*actorArea.height,controlTop=Math.min(...buttons.map(b=>b.y));assert.ok(actorBottom<controlTop,'player and enemy sprites stay above action controls');await shot(p,'06-notched-360-play');await cdp.send('Emulation.setSafeAreaInsetsOverride',{insets:{top:0,bottom:0,left:0,right:0}});await cdp.detach();checks.push('emulated 44px notch/34px home inset at 360×640: stage and buttons within safe area, no overlapping touch buttons or hidden combat sprites');
 for(const [ending,choices,names]of [['keep',['keep','keep','keep'],18],['mixed',['keep','release','keep'],9],['release',['release','release','release'],0]]){
  await load(p,8,choices);await p.evaluate(names=>{const g=__LUNA_TEST__.state();g.names=names;g.totalNames=names;g.player.x=g.enemies[0].x;g.player.y=g.enemies[0].y;g.damage=1000;LunaCore.act(g,'attack');__LUNA_TEST__.step(1,{});},names);assert.equal((await state(p)).screen,'ending');const titles={keep:'여기에, 루나',mixed:'남긴 것의 무게',release:'정리되지 않은 한 줄'};assert.ok(await p.getByRole('heading',{name:titles[ending]}).isVisible());if(ending==='keep'){await p.setViewportSize({width:390,height:844});await shot(p,'05-mobile-ending');}await click(p,'첫 화면으로');}
 checks.push('fixture-driven boss victory reaches all three UI endings, records outcome, clears completed checkpoint');
 const denied=await page({},()=>Object.defineProperty(window,'localStorage',{configurable:true,get(){throw new DOMException('denied','SecurityError');}}));assert.equal((await state(denied)).storage,false);await click(denied,'이름을 따라 시작하기');await click(denied,'정리 명령을 따른다');await click(denied,'알겠어. 가자');assert.equal((await state(denied)).g.wards.length,0);await denied.keyboard.press('Escape');assert.match(await denied.locator('.footnote').first().innerText(),/저장|제한/);await click(denied,'저장된 방 시작에서 첫 화면으로');await click(denied,'이어 하기 · 분류실');assert.equal((await state(denied)).g.choices[0],'release');checks.push('storage denied is explicit; current-window checkpoint supports title/continue without silently discarding run');
 const corrupt=await page({},()=>localStorage.setItem('luna-names-v2','{"version":999,"room":2}'));assert.equal((await state(corrupt)).screen,'corrupt');const rawDownload=corrupt.waitForEvent('download');await click(corrupt,'저장 원본 백업');const raw=await rawDownload;assert.equal(await fs.readFile(await raw.path(),'utf8'),'{"version":999,"room":2}');await click(corrupt,'이 저장을 초기화하고 시작');assert.equal((await state(corrupt)).screen,'title');checks.push('corrupt/future save gives explicit original export and reset recovery');
 const quota=await page();await click(quota,'이름을 따라 시작하기');await click(quota,'편지의 이름을 남긴다');await click(quota,'알겠어. 가자');await quota.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('full','QuotaExceededError');};});await finishRoom(quota);await quota.locator('.upgrade').first().click();assert.equal((await state(quota)).g.room,1);assert.equal((await state(quota)).storage,false);await quota.keyboard.press('Escape');await click(quota,'저장된 방 시작에서 첫 화면으로');await click(quota,'이어 하기 · 종이 골목');assert.equal((await state(quota)).g.room,1);checks.push('quota failure at checkpoint warns and retains newer room in memory instead of falling back silently');
 const rewards=await page();await load(rewards,8,['keep','keep','keep']);const cp=fixture(8,['keep','keep','keep']);await rewards.evaluate(cp=>{localStorage.setItem('luna-names-v2',cp);localStorage.removeItem('luna-endings-v1');const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='luna-endings-v1')throw new DOMException('full','QuotaExceededError');return original.call(this,k,v);};const g=__LUNA_TEST__.state();g.names=18;g.totalNames=18;g.player.x=g.enemies[0].x;g.player.y=g.enemies[0].y;g.damage=1000;LunaCore.act(g,'attack');__LUNA_TEST__.step(1,{});},cp);assert.equal((await state(rewards)).screen,'ending');assert.ok(await rewards.evaluate(()=>localStorage.getItem('luna-names-v2')));assert.match(await rewards.locator('.ending-screen .footnote').innerText(),/저장 실패/);await click(rewards,'첫 화면으로');assert.ok(await rewards.getByRole('button',{name:'이어 하기 · 남겨진 이름',exact:true}).isVisible());checks.push('failed ending-record write preserves resumable last-room checkpoint and discloses failure');
 const touch=await page({hasTouch:true,isMobile:true,viewport:{width:360,height:640}});await load(touch);const touchCdp=await touch.context().newCDPSession(touch),j=await touch.locator('#joystick').boundingBox(),a=await touch.locator('#attack').boundingBox(),jx=j.x+j.width/2,jy=j.y+j.height/2,ax=a.x+a.width/2,ay=a.y+a.height/2,tx=(await state(touch)).g.player.x;
 await touchCdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:jx,y:jy,id:11},{x:ax,y:ay,id:12}]});await touchCdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:jx+40,y:jy,id:11},{x:ax,y:ay,id:12}]});await touch.waitForTimeout(130);assert.ok((await state(touch)).g.player.x>tx+10);assert.ok((await state(touch)).g.attack>0);await touchCdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const released=(await state(touch)).g.player.x;await touch.evaluate(()=>__LUNA_TEST__.step(16));assert.equal((await state(touch)).g.player.x,released);assert.equal((await state(touch)).g.attack,0);await touchCdp.detach();checks.push('emulated simultaneous touch joystick+held slash move/attack together and release without stuck inputs');
 assert.deepEqual(errors,[],'page runtime errors');assert.deepEqual(network,[],'external requests from offline distributable');
 const evidence={browser:'Chromium '+browser.version(),offline:true,physicalDevices:false,externalRequests:0,checks,screenshots:['01-mobile-title','02-mobile-choice','03-mobile-play','04-desktop-play','05-mobile-ending','06-notched-360-play'].map(n=>n+'.png')};
 await fs.mkdir(path.join(root,'docs'),{recursive:true});await fs.writeFile(path.join(root,'docs/browser-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
}finally{for(const c of contexts)await c.close().catch(()=>{});await browser.close();}
