import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),C=require('../src/core.js'),S=require('../src/story.js');
const ready=(policy='keep',seed=7)=>{const g=C.create(seed);C.beginRoom(g);C.choose(g,policy);return g;};
const step=(g,n,input={})=>{for(let i=0;i<n;i++)C.update(g,.04,input);};
function bot(g){const ward=g.wards.find(w=>!w.saved),enemy=g.enemies.filter(e=>e.hp>0).sort((a,b)=>Math.hypot(g.player.x-a.x,g.player.y-a.y)-Math.hypot(g.player.x-b.x,g.player.y-b.y))[0],target=ward||enemy||{x:210,y:350};const dx=target.x-g.player.x,dy=target.y-g.player.y,d=Math.hypot(dx,dy);let x=d>20?dx/d:0,y=d>20?dy/d:0;if(enemy){const ed=Math.hypot(enemy.x-g.player.x,enemy.y-g.player.y);if(ed<g.range+10&&g.veilCd<=0)C.act(g,'veil');if(enemy.mode==='wind'&&enemy.timer<.25&&ed<160){x=-dy/(d||1);y=dx/(d||1);C.act(g,'dash');}}return{x,y,attack:true};}
function run(choices,seed=7){let g=C.create(seed),seconds=0,stats=[];C.beginRoom(g);for(let room=0;room<9;room++){if(room%3===0)assert.ok(C.choose(g,choices[room/3]));let frames=0;while(g.state==='playing'&&frames++<5000){C.update(g,.04,bot(g));g.events=[];seconds+=.04;}stats.push({room,state:g.state,hp:g.hp,names:g.names,time:g.time});assert.ok(['cleared','won'].includes(g.state),JSON.stringify(stats));assert.ok(g.hp>0);if(room<8){assert.ok(C.upgrade(g,room%3===1?'heart':'edge'));g.hp=Math.min(g.maxHp,g.hp+1);g.room++;C.beginRoom(g);}}return{g,seconds,stats};}
test('nine original rooms, three chapter choices, complete differentiated endings',()=>{assert.equal(C.ROOMS.length,9);assert.equal(S.chapters.length,3);assert.equal(Object.keys(S.endings).length,3);assert.doesNotMatch(JSON.stringify({rooms:C.ROOMS,upgrades:C.UPGRADES,story:S}),/자스민|Jasmine|언니|생일/);for(const d of S.chapters){assert.ok(d.body.length>100);assert.notEqual(d.keep,d.release);}});
test('normalized movement, arena bounds, frame delta cap',()=>{const g=ready();const x=g.player.x,y=g.player.y;C.update(g,10,{x:1,y:-1});assert.ok(Math.hypot(g.player.x-x,g.player.y-y)<=178*.04+.001);step(g,800,{x:100,y:-100});assert.equal(g.player.x,397);assert.equal(g.player.y,160);});
test('standing in a ward preserves one name exactly once and restores one health',()=>{const g=ready();g.spawn=999;g.hp=4;g.player={...g.player,x:g.wards[0].x,y:g.wards[0].y};step(g,51);assert.equal(g.names,1);assert.equal(g.totalNames,1);assert.equal(g.hp,5);step(g,80);assert.equal(g.names,1);assert.equal(g.events.filter(e=>e.type==='name').length,1);});
test('leaving a name circle makes channel progress decay',()=>{const g=ready();g.spawn=999;g.player={...g.player,x:g.wards[0].x,y:g.wards[0].y};step(g,20);assert.ok(g.wards[0].charge>.7);g.player.x=200;step(g,40);assert.ok(g.wards[0].charge<.2);assert.equal(g.names,0);});
test('erasure is a mechanical choice: no wards, +3 health, shorter rooms, cannot choose twice',()=>{const g=C.create(4);C.beginRoom(g);g.hp=3;assert.equal(C.choose(g,'release'),true);assert.equal(g.hp,6);assert.equal(g.wards.length,0);assert.equal(C.choose(g,'keep'),false);g.spawn=999;step(g,501);assert.equal(g.state,'cleared');const h=ready();h.spawn=999;step(h,501);assert.equal(h.state,'playing');h.room=1;assert.equal(C.choose(h,'release'),false);});
test('attack cooldown and concealment ambush multiplier',()=>{const g=ready();C.spawnEnemy(g,'knight',g.player.x+15,g.player.y);const e=g.enemies[0];C.act(g,'attack');assert.equal(e.hp,5);C.act(g,'attack');assert.equal(e.hp,5);g.attack=0;C.act(g,'veil');C.act(g,'attack');assert.ok(e.hp<=0);assert.equal(g.veil,0);});
test('dash and invulnerability stop contact/projectile damage; cooldown stops spam',()=>{const g=ready();g.invuln=0;C.act(g,'dash');g.shots=[{x:g.player.x,y:g.player.y,vx:0,vy:0,life:1}];C.update(g,.04);assert.equal(g.hp,8);const cooldown=g.dashCd;C.act(g,'dash');assert.equal(g.dashCd,cooldown);});
test('telegraphed enemies wind up before they strike; concealment interrupts seeking',()=>{const g=ready();g.invuln=0;C.spawnEnemy(g,'shade',g.player.x,g.player.y);const e=g.enemies[0];e.timer=.01;C.update(g,.04);assert.equal(e.mode,'wind');assert.equal(g.hp,8);C.act(g,'veil');e.mode='seek';e.timer=0;step(g,5);assert.equal(e.mode,'seek');});
test('no combat actions after death or completion; boss victory cannot be replaced by damage',()=>{const g=ready();g.state='dead';C.act(g,'dash');assert.equal(g.dash,0);g.room=8;C.beginRoom(g);g.hp=1;g.invuln=0;g.damage=999;const e=g.enemies[0];g.player.x=e.x;g.player.y=e.y;g.shots=[{x:e.x,y:e.y,vx:0,vy:0,life:1}];C.act(g,'attack');C.update(g,.04);assert.equal(g.state,'won');assert.equal(g.hp,1);});
test('all five upgrades change their documented stats; invalid upgrades cannot mutate',()=>{const g=ready();const before=JSON.stringify(g);assert.equal(C.upgrade(g,'unknown'),false);assert.equal(JSON.stringify(g),before);for(const id of ['edge','heart','step','veil','reach'])assert.ok(C.upgrade(g,id));assert.equal(g.damage,3);assert.equal(g.maxHp,10);assert.equal(g.range,84);assert.ok(g.dashMax<2.1);assert.ok(g.veilMax<8);});
test('checkpoint roundtrip restores choices/upgrades/counts, resets this room, prevents retry farming',()=>{const g=ready();g.room=4;g.choices.push('keep');C.upgrade(g,'heart');C.upgrade(g,'edge');g.hp=7;g.names=8;g.totalNames=15;C.beginRoom(g);const raw=C.checkpoint(g);g.names++;g.totalNames++;const h=C.restore(raw);assert.equal(h.room,4);assert.equal(h.time,0);assert.equal(h.hp,7);assert.equal(h.damage,3);assert.deepEqual(h.choices,['keep','keep']);assert.equal(h.names,8);assert.equal(h.totalNames,15);assert.equal(h.wards.filter(w=>w.saved).length,0);assert.equal(C.checkpoint(h),raw);});
test('reject corrupt/future/invalid saves, including impossible chapter choices',()=>{const raw=JSON.parse(C.checkpoint(ready()));for(const delta of [{version:999},{room:9},{hp:0},{upgrades:['x']},{choices:['x']},{choices:[],room:2},{choices:['keep','keep'],room:0},{seed:-1},{names:25},{totalNames:-2},{totalNames:0,names:2}])assert.equal(C.restore(JSON.stringify({...raw,...delta})),null,JSON.stringify(delta));for(const raw of ['null','not json','{}'])assert.equal(C.restore(raw),null);});
test('preserved names weaken boss, but neglected preservation choices earn the mixed ending',()=>{const g=ready();g.room=8;g.choices=['keep','keep','keep'];g.names=24;C.beginRoom(g);assert.equal(g.enemies[0].maxHp,102);assert.equal(S.endingFor(g),'keep');g.names=0;assert.equal(S.endingFor(g),'mixed');g.choices=['release','release','release'];assert.equal(S.endingFor(g),'release');});
test('three complete routes are winnable with actual movement/combat, no healing cheats',()=>{const keep=run(['keep','keep','keep']),release=run(['release','release','release']),mixed=run(['keep','release','keep']);assert.equal(keep.g.state,'won');assert.equal(keep.g.names,24);assert.equal(release.g.names,0);assert.ok(keep.seconds>release.seconds+65);assert.equal(S.endingFor(keep.g),'keep');assert.equal(S.endingFor(release.g),'release');assert.equal(S.endingFor(mixed.g),'mixed');});
test('seeded simulation is deterministic for repeated complete gameplay',()=>{const a=run(['keep','keep','keep'],17),b=run(['keep','keep','keep'],17);assert.deepEqual(a.stats,b.stats);assert.deepEqual(a.g,b.g);});
