import { HEROES,HERO,OWNER_NAMES,WEAPONS,WEAPON,RELICS,RELIC,STAGES,STAGE,META,ACHIEVEMENTS,DIFFICULTIES,clock,clamp } from './content.js';
import { Game } from './engine.js';
import { Storage,PROFILE_KEY,RUN_KEY,buyMeta,metaCost,settle,normalizeProfile,freshProfile } from './profile.js';
import { loadArt,unit,Renderer } from './render.js';
import { AudioDirector } from './audio.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>Math.round(n*100);
const portrait=(id,kind='mini-portrait',mode='face')=>`<span class="${kind}"><canvas data-hero="${id}" data-mode="${mode}" aria-label="${OWNER_NAMES[id]||id}" role="img"></canvas></span>`;
const button=(action,label,cls='secondary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const icon=(text,color)=>`<span class="icon"${color?` style="color:${color}"`:''}>${text}</span>`;

export class App {
  constructor(){
    this.root=document.getElementById('app');this.modal=document.getElementById('modal-host');this.toastNode=document.getElementById('toast');
    let local=null;try{local=globalThis.localStorage;}catch{}this.storage=new Storage(local);this.profile=this.storage.loadProfile();
    this.audio=new AudioDirector(this.profile.settings);this.tab='home';this.libraryTab='heroes';this.game=null;this.renderer=null;this.art=null;this.modalOpen=false;this.lastFocus=null;this.keys=new Set();this.pointer=null;this.input={x:0,y:0};this.accum=0;this.lastTime=0;this.hudAt=0;this.saveAt=0;this.bannerTimer=null;this.toastTimer=null;this.loopCount=0;this.startTimes=[];this.result=null;this.hudCache={};this.frameMs=0;this.resizing=null;
    this.root.addEventListener('click',e=>this.action(e));this.modal.addEventListener('click',e=>this.action(e));
    this.modal.addEventListener('input',e=>{if(e.target.id==='volume'){this.audio.unlock();this.audio.setVolume(Number(e.target.value));this.persistProfile();}});
    this.modal.addEventListener('change',e=>{if(e.target.id==='joystick-mode'){this.profile.settings.joystick=e.target.value;this.persistProfile();}if(e.target.id==='import-file')this.importBackup(e.target.files?.[0]);});
    document.addEventListener('keydown',e=>this.keyDown(e));document.addEventListener('keyup',e=>{this.keys.delete(e.code);});
    window.addEventListener('blur',()=>this.autoPause());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.autoPause();});
    window.addEventListener('resize',()=>{clearTimeout(this.resizing);this.resizing=setTimeout(()=>{this.renderer?.resize();if(this.renderer&&this.game)this.game.view={w:this.renderer.width/this.renderer.zoom,h:this.renderer.height/this.renderer.zoom};this.drawPortraits();this.resetInput();},90);});
    window.addEventListener('pagehide',()=>{this.saveRun();});
  }
  async start(){this.art=await loadArt();document.documentElement.style.setProperty('--garden',`url("${globalThis.NOCTURNE_ASSETS?.garden||''}")`);this.render();if(this.art.failed.length)this.toast('일부 그림을 불러오지 못했어요. 기본 표시로 플레이할 수 있어요.');if(this.storage.error)this.toast(this.storage.error);requestAnimationFrame(t=>this.frame(t));}
  persistProfile(){if(this.storage.corrupt)return false;return this.storage.write(PROFILE_KEY,JSON.stringify(this.profile));}
  toast(text){clearTimeout(this.toastTimer);this.toastNode.textContent=text;this.toastNode.classList.add('visible');this.toastTimer=setTimeout(()=>this.toastNode.classList.remove('visible'),3500);}
  selection(){return this.profile.selection;}
  saved(){const text=this.storage.read(RUN_KEY);if(!text)return null;try{return Game.restore(JSON.parse(text));}catch{this.invalidRun=true;return null;}}
  render(){
    this.renderer=null;const s=this.selection(),h=HERO[s.hero],nav=[['home','☾','원정'],['library','✧','도감'],['growth','❀','별의 기억'],['records','◷','밤의 기록']];
    this.root.innerHTML=`<div class="shell"><header class="topbar"><div class="wordmark">ASTRA<span>NOCTURNE</span></div><div class="top-actions"><div class="currency row"><span>♢</span><b class="num">${this.profile.crystals.toLocaleString()}</b></div>${button('how','?','small-button','aria-label="플레이 방법"')}${button('settings','⚙','small-button','aria-label="설정"')}</div></header><main class="main" id="main-content">${this.tab==='home'?this.home():this.tab==='library'?this.library():this.tab==='growth'?this.growth():this.records()}</main><nav class="nav" aria-label="주 메뉴"><div class="nav-inner">${nav.map(([id,glyph,name])=>button('tab',`<b aria-hidden="true">${glyph}</b>${name}`,this.tab===id?'active':'',`data-value="${id}" ${this.tab===id?'aria-current="page"':''}`)).join('')}</div></nav></div>`;
    document.documentElement.style.setProperty('--accent',h.color);this.drawPortraits();
  }
  home(){
    const s=this.selection(),h=HERO[s.hero],st=STAGE[s.stage],saved=this.saved();
    return `<div class="home"><section class="scene" aria-label="선택한 수호자"><div class="scene-bg"></div><div class="scene-title"><p class="series">ASTRA</p><h1>NOCTURNE</h1><p class="ko-title">별을 지키는 밤</p><div class="ornament" aria-hidden="true">— ✧ —</div></div><div class="hero-orbit">${portrait(h.id,'hero-art','full')}</div><p class="hero-quote">“${h.quote}”</p><div class="hero-name"><h2>${h.name}</h2><p>${h.title}</p></div></section><div class="home-info"><section><div class="section-label"><h2>누구와 밤을 건널까요?</h2><span class="eyebrow">GUARDIAN</span></div><div class="hero-strip" role="group" aria-label="수호자 선택">${HEROES.map(hero=>button('select-hero',`${portrait(hero.id)}<span>${hero.id==='time_ruler'?'시간':hero.name}</span>`,'hero-pick'+(hero.id===h.id?' selected':''),`data-value="${hero.id}" aria-pressed="${hero.id===h.id}" aria-label="${hero.name}"`)).join('')}</div></section><div class="selected-detail"><p>${h.trait}</p><p class="passive">${h.passive}</p><div class="skill-info">${icon(h.mark,h.color)}<div><strong>${h.skill}</strong><small>${h.skillText}</small></div></div></div><section><div class="section-label"><h2>오늘 밤의 목적지</h2><span class="eyebrow">EXPEDITION</span></div><div class="stage-list">${STAGES.map(stage=>button('select-stage',`<span class="chapter">${stage.chapter}</span><div><h3>${stage.name}</h3><p>${stage.en}</p></div><span class="duration">${stage.duration/60}분 · ${this.profile.best[stage.id]?.won?'새벽을 만남':'생존 원정'}</span>`,'stage-pick'+(stage.id===st.id?' selected':''),`data-value="${stage.id}" aria-pressed="${stage.id===st.id}"`)).join('')}</div><div class="difficulty" role="group" aria-label="난이도">${DIFFICULTIES.map(d=>button('difficulty',d.name,d.id===s.difficulty?'selected':'',`data-value="${d.id}" aria-pressed="${d.id===s.difficulty}" title="${d.text}"`)).join('')}</div></section>${saved?`<div class="resume"><span class="icon">◷</span><div><strong>아직 끝나지 않은 밤</strong><small>${HERO[saved.hero].name} · ${STAGE[saved.stage].name} · ${clock(saved.time)}</small></div>${button('resume','이어가기','')}</div>`:''}${!this.storage.available?'<p class="storage-notice">이 탭을 닫으면 기록이 사라질 수 있어요. 설정에서 기록을 파일로 보관해주세요.</p>':''}${this.invalidRun?'<p class="storage-notice">이전 원정 기록을 읽을 수 없어요. 새 원정을 시작하면 진행 기록을 새로 만들어요.</p>':''}<div class="launch">${button('start','밤을 건너기 <span aria-hidden="true">→</span>','primary')}<p class="launch-note">드래그로 이동 · 공격은 자동 · 회피와 필살기는 직접</p></div></div></div>`;
  }
  library(){
    const tabs=[['heroes','수호자'],['weapons','무기와 진화'],['relics','유물']],items=this.libraryTab==='heroes'?HEROES:this.libraryTab==='weapons'?WEAPONS:RELICS;
    return `<div class="page-intro"><p class="eyebrow">THE CONSTELLATION ARCHIVE</p><h1>우리의 별자리</h1><p>익숙한 얼굴, 새로운 밤. 수호자의 이야기와 진화의 실마리.</p></div><div class="tabs" role="tablist" aria-label="도감 분류">${tabs.map(([id,name])=>button('library-tab',name,this.libraryTab===id?'active':'',`data-value="${id}" role="tab" aria-selected="${this.libraryTab===id}"`)).join('')}</div><div class="library-grid">${items.map(item=>button('detail',`${this.libraryTab==='heroes'?portrait(item.id):this.libraryTab==='weapons'?`<span class="weapon-preview">${portrait(item.owner)}<i style="color:${item.color}">${item.icon}</i></span>`:icon(item.icon,item.color)}<div><h3>${item.name}</h3><small>${this.libraryTab==='heroes'?item.title:this.libraryTab==='weapons'?item.text:item.text}</small></div>`,'codex-card',`data-value="${item.id}" data-kind="${this.libraryTab}" style="--accent:${item.color}"`)).join('')}</div>`;
  }
  growth(){return `<div class="page-intro"><p class="eyebrow">MEMORIES THAT REMAIN</p><h1>별의 기억</h1><p>밤을 건너며 얻은 꿈의결정은, 다음 여행의 작은 힘이 됩니다.</p></div><div class="growth-grid">${META.map(m=>{const level=this.profile.meta[m.id],cost=metaCost(this.profile,m.id);return `<article class="growth-card">${icon(m.icon)}<div class="row between"><h3>${m.name}</h3><small>${level} / ${m.max}</small></div><p>${m.text} · 단계마다 적용</p><div class="growth-stars" aria-label="${level}단계">${'✦'.repeat(level)}<span style="opacity:.2">${'✧'.repeat(m.max-level)}</span></div>${button('buy-meta',level>=m.max?'모든 기억을 되찾았어요':`기억 되찾기 <span>♢ ${cost}</span>`,'secondary',`data-value="${m.id}" ${level>=m.max||this.profile.crystals<cost?'disabled':''}`)}</article>`;}).join('')}</div><p class="muted" style="font-size:11px;margin-top:18px">모든 수호자에게 적용돼요. 진행 중인 원정은 출발할 때의 기억을 사용해요.</p>`;}
  records(){return `<div class="page-intro"><p class="eyebrow">A JOURNAL OF LITTLE LIGHTS</p><h1>밤의 기록</h1><p>우리가 지나온 밤에는, 작은 별들이 남아 있어요.</p></div><div class="record-summary"><div><b>${this.profile.runs}</b><small>함께한 원정</small></div><div><b>${this.profile.wins}</b><small>만난 새벽</small></div><div><b>${this.profile.totalKills.toLocaleString()}</b><small>정화한 그림자</small></div></div><div class="section-label"><h2>별빛의 약속</h2><small>${this.profile.achievements.length} / ${ACHIEVEMENTS.length}</small></div><div class="achievement-grid">${ACHIEVEMENTS.map(a=>`<div class="achievement ${this.profile.achievements.includes(a.id)?'earned':''}"><h3>${this.profile.achievements.includes(a.id)?'✦':'✧'} ${a.name}</h3><p>${a.text}</p><small>${this.profile.achievements.includes(a.id)?'기억에 남았어요':`보상 ♢ ${a.reward}`}</small></div>`).join('')}</div><div class="section-label" style="margin-top:25px"><h2>최근의 여행</h2><span class="eyebrow">LAST 20 NIGHTS</span></div>${this.profile.history.length?this.profile.history.map(r=>`<div class="history-row">${portrait(r.hero)}<div><h3>${HERO[r.hero].name} · ${STAGE[r.stage].name}</h3><small>${r.won?'새벽을 맞이했어요':'다음 밤에 다시 만나요'} · ${clock(r.time)} · ${esc(r.date.slice(0,10))}</small></div><span class="num">${Math.floor(r.kills)} 처치<small>♢ ${r.reward}</small></span></div>`).join(''):'<div class="empty-state">첫 번째 밤을 건너면, 이야기가 여기에 남아요.</div>'}`;}
  drawPortraits(){
    if(!this.art)return;for(const canvas of document.querySelectorAll('canvas[data-hero]')){const id=canvas.dataset.hero,img=this.art.images['unit-'+id],rect=canvas.getBoundingClientRect();if(rect.width<1)continue;const dpr=2;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.setTransform(dpr,0,0,dpr,0,0);const full=canvas.dataset.mode==='full';
      if(full)unit(ctx,this.art,id,rect.width/2,rect.height-3,rect.height*1.27,0);
      else if(img){const meta=this.art.frames[id]?.portrait||{x:256,y:230,size:250},ratio=img.width/1024;ctx.drawImage(img,(meta.x-meta.size/2)*ratio,(meta.y-meta.size/2)*ratio,meta.size*ratio,meta.size*ratio,0,0,rect.width,rect.height);}else {ctx.font='20px Georgia';ctx.fillStyle=HERO[id]?.color||'#e4d1a0';ctx.fillText(HERO[id]?.mark||'✧',5,25);}
    }
  }
  openDialog({title,eye='',description='',body='',footer='',closable=true}){
    this.lastFocus=document.activeElement;this.modalOpen=true;this.root.inert=true;this.root.setAttribute('aria-hidden','true');this.resetInput();
    this.modal.innerHTML=`<div class="scrim"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div class="dialog-head">${eye?`<p class="eyebrow">${eye}</p>`:''}<h2 id="dialog-title">${title}</h2>${description?`<p>${description}</p>`:''}${closable?button('close','×','small-button dialog-close','aria-label="닫기"'):''}</div><div class="dialog-content">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}</section></div>`;this.drawPortraits();requestAnimationFrame(()=>this.modal.querySelector('button:not(:disabled),input,select')?.focus({preventScroll:true}));
  }
  closeDialog(){this.modal.innerHTML='';this.modalOpen=false;this.root.inert=false;this.root.removeAttribute('aria-hidden');if(this.lastFocus?.isConnected)this.lastFocus.focus({preventScroll:true});this.lastFocus=null;}
  showHow(){this.openDialog({title:'작은 빛으로, 긴 밤을',eye:'HOW TO CROSS THE NIGHT',description:'공격은 자동. 당신은 길과 성장을 골라주세요.',body:`<div class="how-step">${icon('➶')}<div><h3>손가락으로 길을 만들어요</h3><p>전장을 누르고 드래그하면 조이스틱이 생겨요. 손을 떼면 멈춰요. PC는 WASD / 방향키로 이동해요.</p></div></div><div class="how-step">${icon('✧')}<div><h3>별을 모으고, 힘을 골라요</h3><p>적이 남긴 별은 경험치예요. 레벨마다 세 선택지 중 하나를 골라요. 무기는 여섯 개, 유물은 네 개까지 가져갈 수 있어요.</p></div></div><div class="how-step">${icon('☾')}<div><h3>위험한 순간은 직접 넘어요</h3><p>회피 버튼 / Shift로 짧게 무적 이동. 필살기가 가득 차면 오른쪽 버튼 / Space로 발동해요. 붉은 원은 보스의 공격 예고예요.</p></div></div><div class="how-step">${icon('♢')}<div><h3>마지막 한 걸음, 진화</h3><p>무기 6단계와 대응 유물 2단계를 갖추면 레벨 선택이나 상자에서 진화를 만나요. 도감에서 조합을 볼 수 있어요. 지도의 빛나는 별자리는 회복·상자·강화 제단이에요.</p></div></div><div class="how-step">${icon('◷')}<div><h3>쉬어도, 밤은 기다려요</h3><p>일시정지하거나 다른 창으로 이동하면 원정을 저장해요. 종료 후 꿈의결정으로 영구 능력을 키워요. 제한 시간이 끝나도 마지막 보스를 쓰러뜨려야 승리해요.</p></div></div>`,footer:button('close','이제, 밤을 건너볼까요','primary')});}
  showSettings(){const s=this.profile.settings;this.openDialog({title:'밤의 온도',eye:'SETTINGS',body:`${[['music','밤의 선율','오프라인으로 연주하는 음악'],['sound','작은 소리들','공격·회피·보상의 효과음'],['effects','반짝임과 흔들림','위험 예고는 항상 표시해요'],['numbers','피해 숫자','한 화면에 적당한 수만 표시해요']].map(([key,name,desc])=>`<div class="settings-row"><div>${name}<small>${desc}</small></div><button class="toggle" role="switch" aria-checked="${s[key]}" aria-label="${name}" data-action="toggle" data-value="${key}"></button></div>`).join('')}<label class="settings-row" for="volume"><span>소리 크기</span><input type="range" id="volume" min="0" max="1" step=".05" value="${s.volume}"></label><label class="settings-row" for="joystick-mode"><span>이동 조이스틱</span><select id="joystick-mode" class="settings-select"><option value="floating" ${s.joystick==='floating'?'selected':''}>터치한 곳에서 시작</option><option value="fixed" ${s.joystick==='fixed'?'selected':''}>왼쪽 아래 고정</option></select></label><div class="rule"></div><h3>별빛 기록 보관함</h3><p class="muted" style="font-size:11px;margin-top:6px">기록은 이 브라우저에 저장돼요. 다른 기기로 옮길 때 파일로 보관할 수 있어요.</p>${this.storage.error?`<p class="storage-notice">${esc(this.storage.error)}</p>`:''}<div class="backup-actions">${button('export','기록 내보내기')}${button('import','기록 가져오기')}</div><input type="file" id="import-file" accept="application/json,.json" hidden><p class="muted" style="font-size:10px;margin-top:15px">ASTRA: NOCTURNE · v1.0<br>그림: Defense의 승인된 방향도, Shooter의 세계·적, 새 자스민 방향도.<br>음악: 이 게임을 위한 절차적 밤의 선율.</p>`,footer:button('close','이 밤으로 돌아가기','primary')});}
  showDetail(id,kind){
    if(kind==='heroes'){const h=HERO[id];if(!h)return;const w=WEAPON[h.weapon];this.openDialog({title:h.name,eye:h.en,description:h.title,body:`${portrait(id,'detail-hero','full')}<p class="detail-copy">${h.identity}</p><div class="rule"></div><p class="detail-copy"><strong>${h.passive}</strong><br>${h.trait}</p><div class="recipe">${icon(w.icon,w.color)}<div>${w.name}<small style="display:block">시작 무기</small></div></div><p class="detail-copy"><strong>${h.skill}</strong><br>${h.skillText}</p>`,footer:button('choose-hero','이 수호자와 함께하기','primary',`data-value="${id}"`)});}
    else if(kind==='weapons'){const w=WEAPON[id];if(!w)return;const r=RELIC[w.relic];this.openDialog({title:w.name,eye:'WEAPON · EVOLUTION',description:OWNER_NAMES[w.owner]+'의 별빛',body:`${portrait(w.owner,'detail-owner','full')}<div class="treasure-visual">${icon(w.icon,w.color)}</div><p class="detail-copy">${w.text}<br>강화마다 피해가 증가하고, 무기 종류에 따라 발사체·범위·연쇄가 늘어납니다.</p><div class="recipe"><div>${w.name}<small style="display:block">6단계</small></div><span>+</span><div>${r.name}<small style="display:block">2단계</small></div></div><h3 style="color:${w.color}">✦ ${w.evolution}</h3><p class="evolution-note">위 조건을 만족하면 레벨 선택과 보물상자에 등장해요. 진화 후 피해 ×1.8, 대기시간 ×0.72. 각 무기 고유 범위·연쇄·파편 효과도 강화돼요.</p><p class="evolution-note">${['frost','dream','sun'].includes(w.id)?'토끼의 공명: 눈토끼·밤토끼·은토끼 무기를 두 종류 이상 함께 사용하면, 종류 하나마다 토끼 무기의 공격속도 +10%.':''}</p>`});}
    else {const r=RELIC[id];if(!r)return;this.openDialog({title:r.name,eye:'RELIC',body:`<div class="treasure-visual">${icon(r.icon,r.color)}</div><p class="detail-copy">${r.text}<br>최대 3단계. 각 단계의 효과가 누적됩니다.</p><div class="rule"></div><h3>함께 진화하는 무기</h3>${WEAPONS.filter(w=>w.relic===id).map(w=>`<div class="recipe">${icon(w.icon,w.color)}<div>${w.name}<small style="display:block">→ ${w.evolution}</small></div></div>`).join('')}`});}
  }
  startExpedition(){const existing=this.saved();if(existing){this.openDialog({title:'새로운 밤으로 떠날까요?',eye:'A NEW NIGHT',description:`${HERO[existing.hero].name}의 ${clock(existing.time)} 원정이 남아 있어요.`,body:'<p class="detail-copy">새 원정을 시작하면 진행 중인 밤은 새 여행으로 바뀌어요. 영구 성장과 지난 원정 기록은 보존돼요.</p>',footer:button('start-confirm','새 밤으로 떠나기','primary')+button('resume','남아 있는 밤 이어가기')});}else this.launch();}
  launch(restored=null){
    this.closeDialog();this.audio.unlock();this.audio.paused=false;this.audio.playing=true;const s=this.selection();this.game=restored||new Game({...s,seed:Math.floor(Math.random()*4294967295)||1,meta:this.profile.meta,runId:`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`});
    if(this.game.mode==='paused')this.game.mode='playing';this.result=null;this.hudCache={};this.accum=0;this.saveAt=0;this.buildBattle();this.saveRun();if(this.game.mode==='choice')this.showChoices();if(this.game.mode==='treasure')this.showTreasure();this.banner(HERO[this.game.hero].quote,'THE NIGHT BEGINS',1600);
  }
  buildBattle(){const g=this.game,h=HERO[g.hero];document.documentElement.style.setProperty('--accent',h.color);this.root.innerHTML=`<div class="battle"><header class="hud"><div class="hud-top"><div class="row">${portrait(h.id,'mini-portrait hud-portrait')}<div><div class="hud-name">${h.name}</div><div class="hp"><i id="hp-fill"></i></div><div id="hp-text" class="hp-number num"></div></div></div><div class="hud-clock"><b id="timer" class="num">00:00</b><small>${STAGE[g.stage].name} · ${STAGE[g.stage].duration/60}분</small></div><div class="hud-kills"><b id="kills">0</b><small> 처치</small></div>${button('pause','Ⅱ','small-button','aria-label="일시정지"')}</div><div class="xp-row"><span id="level">LV 1</span><div class="xp-bar"><i id="xp-fill"></i></div><span id="xp-count" class="num"></span></div></header><div class="arena" id="arena"><canvas id="battle-canvas" aria-label="${h.name}의 자동 공격 생존 전장"></canvas><div class="boss-hud" id="boss-hud"><strong id="boss-name"></strong><div class="hp"><i id="boss-fill"></i></div></div><div class="arena-banner" id="arena-banner"><span id="banner-eye"></span><strong id="banner-title"></strong></div><div class="tutorial-hint" id="tutorial-hint"><b>움직이면, 별이 따라와요</b>전장을 드래그해 이동 · 공격은 자동<br>붉은 공격 예고는 회피로 넘어요</div><div class="joystick" id="joystick"><i id="joystick-knob"></i></div>${button('shrine','별빛 나누기','shrine-button','id="shrine-button"')}</div><div class="battle-controls"><div class="ability-group">${button('dash','➶ <span class="cd hide" id="dash-cd"></span>','ability','aria-label="회피"')}<span class="ability-label">회피 · Shift</span></div><div id="equipment"><div class="equipment-label">우리의 별자리</div><div class="gear-row" id="weapon-row"></div><div class="gear-row" id="relic-row"></div><div id="rabbit-bond" class="rabbit-bond"></div><div class="coin-hud">♢ <span id="gold">0</span> · <span id="battle-kills">0</span> 처치</div></div><div class="ability-group skill" id="skill-group">${button('skill',`${h.mark}<svg class="charge-ring" viewBox="0 0 72 72" aria-hidden="true"><circle id="charge-circle" cx="36" cy="36" r="34"/></svg>`,'ability','id="skill-button" aria-label="'+h.skill+'"')}<span class="ability-label" id="skill-label">필살기 · Space</span></div></div></div>`;
    this.canvas=document.getElementById('battle-canvas');this.renderer=new Renderer(this.canvas,this.art,this.profile.settings);this.renderer.camera.x=g.player.x;this.renderer.camera.y=g.player.y;
    this.game.view={w:this.renderer.width/this.renderer.zoom,h:this.renderer.height/this.renderer.zoom};
    this.canvas.addEventListener('pointerdown',e=>this.pointerDown(e));this.canvas.addEventListener('pointermove',e=>this.pointerMove(e));for(const name of ['pointerup','pointercancel','lostpointercapture'])this.canvas.addEventListener(name,e=>this.pointerUp(e));this.canvas.addEventListener('contextmenu',e=>e.preventDefault());this.drawPortraits();this.updateHUD();
  }
  pointerDown(e){if(this.game?.mode!=='playing'||this.modalOpen||this.pointer||e.button!==0)return;e.preventDefault();const rect=this.canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;
    const fixed=this.profile.settings.joystick==='fixed';this.pointer={id:e.pointerId,x:fixed?74:x,y:fixed?rect.height-76:y};this.canvas.setPointerCapture(e.pointerId);const joystick=document.getElementById('joystick');joystick.style.left=(this.pointer.x-46)+'px';joystick.style.top=(this.pointer.y-46)+'px';joystick.style.bottom='auto';joystick.classList.add('active');this.pointerMove(e);}
  pointerMove(e){if(!this.pointer||this.pointer.id!==e.pointerId)return;e.preventDefault();const rect=this.canvas.getBoundingClientRect(),dx=e.clientX-rect.left-this.pointer.x,dy=e.clientY-rect.top-this.pointer.y,dist=Math.hypot(dx,dy),r=Math.min(1,dist/42);this.input={x:dist>5?dx/dist*r:0,y:dist>5?dy/dist*r:0};const knob=document.getElementById('joystick-knob');if(knob)knob.style.transform=`translate(${this.input.x*24}px,${this.input.y*24}px)`;}
  pointerUp(e){if(this.pointer?.id===e.pointerId)this.resetInput();}
  resetInput(){this.pointer=null;this.input={x:0,y:0};this.keys.clear();document.getElementById('joystick')?.classList.remove('active');const knob=document.getElementById('joystick-knob');if(knob)knob.style.transform='';}
  keyDown(e){
    if(this.modalOpen){if(e.key==='Tab'){const focusables=[...this.modal.querySelectorAll('button:not(:disabled),input:not([hidden]),select,a[href]')].filter(el=>el.getClientRects().length),first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if(e.key==='Escape'){const close=this.modal.querySelector('[data-action="close"]');if(close){e.preventDefault();close.click();}}return;}
    if(!this.game||this.game.mode!=='playing')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','Escape'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(!e.repeat){if(e.code==='Space'){this.audio.unlock();this.game.castSkill();}if(e.code.startsWith('Shift'))this.game.dash();if(e.code==='Escape')this.pause();}
  }
  currentInput(){if(this.pointer)return this.input;return {x:(this.keys.has('ArrowRight')||this.keys.has('KeyD')?1:0)-(this.keys.has('ArrowLeft')||this.keys.has('KeyA')?1:0),y:(this.keys.has('ArrowDown')||this.keys.has('KeyS')?1:0)-(this.keys.has('ArrowUp')||this.keys.has('KeyW')?1:0)};}
  frame(timestamp){
    const dt=this.lastTime?Math.min((timestamp-this.lastTime)/1000,.12):0;this.lastTime=timestamp;this.frameMs+=(dt*1000-this.frameMs)*.03;this.loopCount++;
    if(this.game&&this.renderer){const g=this.game,input=this.currentInput(),before=g.mode;if(g.mode==='playing'&&!this.modalOpen){this.accum+=dt;let steps=0;while(this.accum>=1/60&&steps++<6){g.step(1/60,input);this.accum-=1/60;if(g.mode!=='playing'){this.accum=0;break;}}}else this.accum=0;
      const events=g.drainEvents();this.renderer.events(events);for(const e of events){this.audio.event(e);if(e.type==='boss')this.banner(e.title,'A SHADOW APPROACHES',2000);if(e.type==='rush')this.banner(e.title,'THE NIGHT DEEPENS',1700);if(e.type==='skill')this.banner(e.title,'CONSTELLATION BLOOM',1300);if(e.type==='evolution')this.toast('✦ '+e.title+' · 진화');}
      this.renderer.render(g,Math.min(dt,.04),input);this.audio.boss=g.enemies.some(e=>e.boss);this.hudAt+=dt;this.saveAt+=dt;if(this.hudAt>.1){this.hudAt=0;this.updateHUD();}
      if(g.mode!==before||!this.modalOpen&&['choice','treasure','victory','defeat'].includes(g.mode)){if(g.mode==='choice')this.showChoices();if(g.mode==='treasure')this.showTreasure();if(['victory','defeat'].includes(g.mode))this.showResult();}
      if(g.time>9)document.getElementById('tutorial-hint')?.classList.add('hide');if(this.saveAt>=5){this.saveAt=0;this.saveRun();}
    }requestAnimationFrame(t=>this.frame(t));
  }
  updateHUD(){const g=this.game;if(!g)return;const set=(id,value)=>{if(this.hudCache[id]===value)return;this.hudCache[id]=value;const el=document.getElementById(id);if(el)el.textContent=value;};
    set('timer',clock(g.time));set('kills',g.kills);set('battle-kills',g.kills);set('gold',g.gold);set('level','LV '+g.level);set('xp-count',`${Math.floor(g.xp)} / ${g.need}`);set('hp-text',`${Math.ceil(g.player.hp)} / ${g.player.maxHp}`);
    const style=(id,prop,value)=>{const key=id+prop;if(this.hudCache[key]===value)return;this.hudCache[key]=value;const el=document.getElementById(id);if(el)el.style[prop]=value;};style('hp-fill','width',`${clamp(g.player.hp/g.player.maxHp*100,0,100)}%`);style('xp-fill','width',`${clamp(g.xp/g.need*100,0,100)}%`);style('charge-circle','strokeDashoffset',String(214*(1-g.player.charge/100)));
    const dash=document.getElementById('dash-cd');dash?.classList.toggle('hide',g.player.dashCooldown<=0);set('dash-cd',g.player.dashCooldown>0?g.player.dashCooldown.toFixed(1):'');document.getElementById('skill-group')?.classList.toggle('ready',g.player.charge>=100);set('skill-label',g.player.charge>=100?'필살기 · 준비':`필살기 · ${Math.floor(g.player.charge)}%`);
    const equipment=JSON.stringify([g.weapons.map(w=>[w.id,w.level,w.evolved]),g.relics]);if(this.hudCache.equipment!==equipment){this.hudCache.equipment=equipment;document.getElementById('weapon-row').innerHTML=g.weapons.map(w=>`<span class="gear ${w.evolved?'evolved':''}" style="color:${WEAPON[w.id].color}" title="${w.evolved?WEAPON[w.id].evolution:WEAPON[w.id].name}">${WEAPON[w.id].icon}<b>${w.evolved?'✦':w.level}</b></span>`).join('')+'<span class="gear empty">·</span>'.repeat(6-g.weapons.length);document.getElementById('relic-row').innerHTML=g.relics.map(r=>`<span class="gear" style="color:${RELIC[r.id].color}" title="${RELIC[r.id].name}">${RELIC[r.id].icon}<b>${r.level}</b></span>`).join('')+'<span class="gear empty">·</span>'.repeat(4-g.relics.length);set('rabbit-bond',g.stats.rabbit>1?'✧ 토끼의 공명 +'+pct(g.stats.rabbit-1)+'%':'');}
    const boss=g.enemies.find(e=>e.boss&&e.hp>0);document.getElementById('boss-hud')?.classList.toggle('visible',!!boss);if(boss){set('boss-name',boss.name);style('boss-fill','width',`${clamp(boss.hp/boss.maxHp*100,0,100)}%`);}document.getElementById('shrine-button')?.classList.toggle('visible',!!g.nearShrine());
  }
  banner(title,eye,duration){clearTimeout(this.bannerTimer);const el=document.getElementById('arena-banner');if(!el)return;document.getElementById('banner-title').textContent=title;document.getElementById('banner-eye').textContent=eye;el.classList.add('visible');this.bannerTimer=setTimeout(()=>el.classList.remove('visible'),duration);}
  optionInfo(o){if(o.type==='weapon'||o.type==='evolution'){const w=WEAPON[o.id];return {name:o.type==='evolution'?w.evolution:w.name,icon:w.icon,color:w.color,tag:o.type==='evolution'?'✦ 무기 진화':o.level===1?'새 무기':'무기 강화',text:o.type==='evolution'?'별이 되는 순간. 피해·속도·고유 효과가 크게 강화됩니다.':o.level===1?w.text:`${w.text} 피해 +22%${o.level%2===0?' · 고유 범위/발사/연쇄 강화':''}`,level:o.type==='evolution'?'✦':`LV ${o.level}`};}if(o.type==='relic'){const r=RELIC[o.id];return {name:r.name,icon:r.icon,color:r.color,tag:o.level===1?'새 유물':'유물 강화',text:r.text,level:`LV ${o.level}`};}return {name:o.type==='heal'?'새벽의 숨결':'작은 별의 선물',icon:o.type==='heal'?'♡':'♢',color:'#e4d1a0',tag:'모든 별자리가 찼어요',text:o.type==='heal'?'최대 생명의 30% 회복':'꿈의 조각 15개 획득',level:'+'};}
  showChoices(){const g=this.game;this.audio.paused=true;this.saveRun();this.openDialog({title:'어떤 별을 이어갈까요?',eye:`LEVEL ${g.level} · A LITTLE STRONGER`,description:`무기 ${g.weapons.length}/6 · 유물 ${g.relics.length}/4${g.pending>1?' · 선택 '+g.pending+'회 남음':''}`,closable:false,body:g.options.map((o,i)=>{const info=this.optionInfo(o);return button('choice',`${icon(info.icon,info.color)}<div><small>${info.tag}</small><h3>${info.name}</h3><p>${info.text}</p></div><span class="level-mark">${info.level}</span>`,'choice-card'+(o.type==='evolution'?' evolution':''),`data-value="${i}" style="--accent:${info.color}"`);}).join(''),footer:`<div class="choice-actions">${button('reroll',`다시 펼치기 · ${g.rerolls}`, 'secondary',g.rerolls<=0?'disabled':'')}${button('banish-menu',`별 접어두기 · ${g.banishes}`,'secondary',g.banishes<=0?'disabled':'')}</div><small style="text-align:center">선택하는 동안 밤은 멈춰 있어요.</small>`});}
  showTreasure(){const info=this.optionInfo(this.game.treasure);this.audio.paused=true;this.saveRun();this.openDialog({title:this.game.treasure.type==='evolution'?'별이 피어나는 순간':'밤이 남긴 선물',eye:'CONSTELLATION TREASURE',closable:false,body:`<div class="treasure-visual"><span>${info.icon}</span><p class="eyebrow">${info.tag}</p><h3 style="color:${info.color}">${info.name}</h3><p>${info.level} · ${info.text}</p></div><p style="text-align:center;font-size:11px;color:var(--gold)">꿈의 조각 ♢ +10</p>`,footer:button('claim-treasure','빛을 가져가기','primary')});}
  saveRun(){if(!this.game||['victory','defeat'].includes(this.game.mode))return;this.storage.write(RUN_KEY,JSON.stringify(this.game.snapshot()));}
  pause(){if(!this.game||this.game.mode!=='playing')return;this.game.mode='paused';this.resetInput();this.audio.suspend();this.saveRun();this.showPause();}
  autoPause(){if(this.game?.mode==='playing')this.pause();else this.saveRun();this.resetInput();this.audio.suspend();}
  showPause(){const g=this.game;this.openDialog({title:'밤은 기다려줄 거예요',eye:'PAUSED · SAVED',description:`${HERO[g.hero].name} · ${STAGE[g.stage].name}`,closable:false,body:`<div class="pause-stats"><div><b>${clock(g.time)}</b><small>함께한 시간</small></div><div><b>${g.kills}</b><small>처치</small></div><div><b>${g.level}</b><small>레벨</small></div></div><div class="pause-gear">${g.weapons.map(w=>`<div><strong style="color:${WEAPON[w.id].color}">${WEAPON[w.id].icon} ${w.evolved?WEAPON[w.id].evolution:WEAPON[w.id].name}</strong><small>${w.evolved?'진화':'LV '+w.level} · ${Math.round(w.damage).toLocaleString()} 피해</small></div>`).join('')}</div><div class="stat-grid"><span>공격력</span><b>+${pct(g.stats.damage-1)}%</b><span>공격 대기시간</span><b>-${pct(1-g.stats.cooldown)}%</b><span>치명타</span><b>${pct(g.stats.crit)}%</b><span>이동속도</span><b>+${pct(g.stats.speed-1)}%</b><span>획득 범위</span><b>${Math.round(g.stats.magnet)}</b><span>경험치</span><b>+${pct(g.stats.xp-1)}%</b></div>`,footer:button('unpause','다시, 함께 걸어요','primary')+`<div class="row">${button('settings','설정','text-button')}${button('leave','저장하고 로비로','text-button')}${button('abandon','이번 원정 마치기','text-button')}</div>`});}
  showResult(){const g=this.game;this.result=settle(this.profile,g)||this.result||{reward:0,earned:[],total:0};const saved=this.persistProfile();if(saved)this.storage.remove(RUN_KEY);else this.toast('결과를 저장할 수 없어요. 원정 기록은 그대로 남아 있어요.');this.audio.playing=false;this.audio.paused=false;const won=g.mode==='victory',best=Math.max(...g.weapons.map(w=>w.damage),1);
    this.openDialog({title:won?'우리의 새벽이 왔어요':'이 밤의 빛은 남아 있어요',eye:won?'DAWN HAS ARRIVED':'UNTIL THE NEXT NIGHT',description:`${HERO[g.hero].name} · ${STAGE[g.stage].name}`,closable:false,body:`${portrait(g.hero,'result-hero','full')}${saved?'':'<p class="storage-notice" id="result-storage-error">결과를 저장할 수 없어요. 복구를 위해 원정 기록은 그대로 남아 있어요. 저장 공간을 비운 다음 원정을 다시 완료해주세요.</p>'}<div class="result-grid"><div><b>${clock(g.time)}</b><small>함께한 시간</small></div><div><b>${g.kills}</b><small>정화한 그림자</small></div><div><b>${g.level}</b><small>수호자 레벨</small></div></div><div class="reward-total"><b>♢ +${this.result.total}</b><p>다음 밤에 가져갈 꿈의결정</p></div>${this.result.earned.map(a=>`<div class="earned-row">✦ ${a.name} · ♢ +${a.reward}</div>`).join('')}<div class="rule"></div><h3>함께 싸운 별들</h3><div class="damage-bars">${[...g.weapons].sort((a,b)=>b.damage-a.damage).map(w=>`<div class="damage-item"><div class="row"><span style="color:${WEAPON[w.id].color}">${w.evolved?'✦ ':''}${w.evolved?WEAPON[w.id].evolution:WEAPON[w.id].name}</span><span class="num">${Math.round(w.damage).toLocaleString()}</span></div><div class="damage-bar"><i style="width:${w.damage/best*100}%;background:${WEAPON[w.id].color}"></i></div></div>`).join('')}</div>`,footer:button('retry','한 번 더, 함께','primary',saved?'':'disabled aria-describedby="result-storage-error"')+button('result-home','별빛 정원으로 돌아가기')});}
  returnHome(){this.closeDialog();this.game=null;this.renderer=null;this.audio.playing=false;this.audio.paused=false;this.audio.unlock();this.resetInput();this.tab='home';this.render();}
  exportBackup(){const contents=this.storage.corrupt||JSON.stringify(this.profile,null,2);const blob=new Blob([contents],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AstraNocturne-memories.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.toast('별빛 기록을 파일로 보관했어요.');}
  async importBackup(file){if(!file)return;if(file.size>1024*1024){this.toast('기록 파일이 너무 커요.');return;}try{const profile=normalizeProfile(JSON.parse(await file.text()));this.pendingImport=profile;this.openDialog({title:'이 기억을 가져올까요?',eye:'RESTORE MEMORIES',description:`원정 ${profile.runs}회 · 꿈의결정 ${profile.crystals}개`,body:'<p class="detail-copy">현재의 영구 성장과 기록을 파일 속 기억으로 바꿔요. 진행 중인 원정은 그대로 보존돼요.</p>',footer:button('confirm-import','기억 가져오기','primary')+button('settings','현재 기록 보존하기')});}catch{this.toast('NOCTURNE의 올바른 기록 파일을 선택해주세요.');}}
  action(event){
    const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const a=target.dataset.action,value=target.dataset.value;if(!this.game)this.audio.paused=false;this.audio.click();
    if(a==='tab'){this.tab=value;this.render();window.scrollTo(0,0);}
    if(a==='select-hero'){this.profile.selection.hero=value;this.persistProfile();this.render();}
    if(a==='select-stage'){this.profile.selection.stage=value;this.persistProfile();this.render();}
    if(a==='difficulty'){this.profile.selection.difficulty=value;this.persistProfile();this.render();}
    if(a==='library-tab'){this.libraryTab=value;this.render();}
    if(a==='detail')this.showDetail(value,target.dataset.kind);
    if(a==='choose-hero'){this.profile.selection.hero=value;this.persistProfile();this.closeDialog();this.tab='home';this.render();}
    if(a==='buy-meta'){if(buyMeta(this.profile,value)){this.persistProfile();this.render();this.toast('✦ '+META.find(m=>m.id===value).name+' · 기억을 되찾았어요.');}}
    if(a==='how')this.showHow();if(a==='settings')this.showSettings();
    if(a==='close'){this.closeDialog();if(this.game?.mode==='paused')this.showPause();}
    if(a==='toggle'){const key=value;this.profile.settings[key]=!this.profile.settings[key];target.setAttribute('aria-checked',this.profile.settings[key]);this.persistProfile();}
    if(a==='export')this.exportBackup();if(a==='import')this.modal.querySelector('#import-file')?.click();
    if(a==='confirm-import'){this.profile=this.pendingImport;this.pendingImport=null;this.storage.corrupt=null;this.storage.error='';this.audio.settings=this.profile.settings;this.audio.setVolume(this.profile.settings.volume);if(this.renderer)this.renderer.settings=this.profile.settings;this.persistProfile();this.closeDialog();if(this.game?.mode==='paused')this.showPause();else this.render();this.toast('기억을 가져왔어요.');}
    if(a==='start')this.startExpedition();if(a==='start-confirm'||a==='retry')this.launch();if(a==='resume'){const g=this.saved();if(g)this.launch(g);else this.toast('이어갈 원정이 없어요.');}
    if(a==='dash')this.game?.dash();if(a==='skill'){if(!this.game?.castSkill())this.toast('별빛이 가득 차면 필살기를 쓸 수 있어요.');}
    if(a==='pause')this.pause();if(a==='unpause'){this.closeDialog();this.game.mode='playing';this.audio.paused=false;this.audio.unlock();this.resetInput();}
    if(a==='choice'){if(this.game.choose(Number(value))){this.closeDialog();this.audio.paused=false;if(this.game.mode==='choice')this.showChoices();this.saveRun();}}
    if(a==='reroll'){if(this.game.reroll())this.showChoices();}
    if(a==='banish-menu'){const cards=this.modal.querySelector('.dialog-content');if(!cards.querySelector('.banish-row')){const row=document.createElement('div');row.className='banish-row';row.innerHTML=this.game.options.map((o,i)=>button('banish',`${i+1}번 접기`,'secondary',`data-value="${i}" ${!['weapon','relic'].includes(o.type)?'disabled':''}`)).join('');cards.append(row);row.scrollIntoView({block:'nearest'});}}
    if(a==='banish'){if(this.game.banish(Number(value)))this.showChoices();}
    if(a==='claim-treasure'){this.game.claimTreasure();this.closeDialog();this.audio.paused=false;if(this.game.mode==='choice')this.showChoices();this.saveRun();}
    if(a==='shrine')this.game?.useShrine();if(a==='leave'){this.saveRun();this.returnHome();}
    if(a==='abandon')this.openDialog({title:'이번 밤을 마칠까요?',eye:'END THIS EXPEDITION',description:'지금까지의 처치와 시간에 따른 보상을 받아요.',body:'<p class="detail-copy">현재 원정을 끝내고 결과 화면으로 이동해요. 다음 여행은 처음부터 시작해요.</p>',closable:false,footer:button('abandon-confirm','이 밤의 빛을 기억하기','primary')+button('pause-back','조금 더 함께하기')});
    if(a==='abandon-confirm'){this.game.finish(false);this.showResult();}if(a==='pause-back')this.showPause();if(a==='result-home')this.returnHome();
  }
}
const app=new App();app.start().catch(error=>{console.error(error);document.getElementById('app').innerHTML='<div class="boot"><h1>NOCTURNE</h1><p>별빛을 불러오지 못했어요. 파일을 다시 열어주세요.</p></div>';});
