// Generated by scripts/pack_defense_directions.mjs from recorded anatomical estimates and foot landmarks.
export const PORTRAIT_FRAMES = {
  "zeke": {
    "x": 256,
    "y": 209,
    "size": 250
  },
  "rumi": {
    "x": 256,
    "y": 232,
    "size": 250
  },
  "luna": {
    "x": 256,
    "y": 211,
    "size": 250
  },
  "cinderella": {
    "x": 256,
    "y": 190,
    "size": 250
  },
  "snow_rabbit": {
    "x": 256,
    "y": 228,
    "size": 250
  },
  "avalanche_maid": {
    "x": 256,
    "y": 217,
    "size": 250
  },
  "night_rabbit": {
    "x": 256,
    "y": 221,
    "size": 250
  },
  "guardian": {
    "x": 256,
    "y": 210,
    "size": 250
  },
  "storm_sage": {
    "x": 256,
    "y": 195,
    "size": 250
  },
  "lightning_sage": {
    "x": 256,
    "y": 204,
    "size": 250
  },
  "red_dragon": {
    "x": 256,
    "y": 199,
    "size": 250
  },
  "flame_sage": {
    "x": 256,
    "y": 207,
    "size": 250
  },
  "mushroom_king": {
    "x": 256,
    "y": 263,
    "size": 250
  },
  "great_detective": {
    "x": 256,
    "y": 214,
    "size": 250
  },
  "siren": {
    "x": 256,
    "y": 229,
    "size": 250
  },
  "phantom": {
    "x": 256,
    "y": 231,
    "size": 250
  },
  "queen": {
    "x": 256,
    "y": 211,
    "size": 250
  },
  "galaxy_whale": {
    "x": 256,
    "y": 203,
    "size": 250
  },
  "silver_rabbit": {
    "x": 256,
    "y": 247,
    "size": 250
  },
  "ancient_dragon": {
    "x": 256,
    "y": 185,
    "size": 250
  },
  "time_ruler": {
    "x": 256,
    "y": 208,
    "size": 250
  }
};
