import {PORTRAIT_FRAMES} from './art-frames.js';
export const VERSION = 2;
export const GRID = 5;
export const MAX_RANK = 6;
export const DEFAULT_DECK = ['zeke','snow_rabbit','rumi','siren','queen','cinderella'];
// Supplied by the author in 컨셉.txt, 2026-09-27. Height refers to anatomy;
// ears, hats, halos, weapons and trailing fabric are excluded.
export const HEIGHT_GROUPS = {
  tall:['zeke','lightning_sage','storm_sage','flame_sage','red_dragon','ancient_dragon','cherry_prince','frost_witch'],
  medium:['rumi','luna','cinderella','avalanche_maid','mushroom_king','great_detective','siren','queen','galaxy_whale','time_ruler','doom','santa','jasmine','star_boy','time_magician','aurora'],
  short:['guardian','snow_rabbit','night_rabbit','silver_rabbit','phantom','harmonious'],
};

// Four authored directions share a 512px frame and a (256,480) foot anchor.
// Scale is calibrated from anatomical heads, never from weapon/hat bounds.
const h = (id,name,title,color,atlas,row,damage,interval,attack,trait,skill) => ({
  id,name,title,color,art:{atlas,row,columns:2,foot:0.94,scale:1},
  damage,interval,attack,trait,skill,
});
export const HEROES = [
  h('zeke','지크','불굴의 용기사','#ff995c','heroes',3,23,1.2,'slash',
    {type:'burn',text:'검격이 가까운 적들을 함께 베고 3초 동안 불태웁니다.'},
    {name:'용의 맹세',cost:70,type:'inferno',text:'전장의 적을 베고 큰 화염 피해를 줍니다.'}),
  h('rumi','루미','꿈을 짓는 마법사','#7dddf1','rumi',0,10,1.05,'star',
    {type:'wild',text:'같은 등급의 어떤 영웅과도 합성할 수 있습니다.'},
    {name:'꿈의 메아리',cost:60,type:'echo',text:'8초 동안 모든 영웅의 공격에 65% 위력의 추가 공격이 따라갑니다.'}),
  h('luna','루나','달그늘의 암살자','#c5a0ff','heroes',1,32,1.25,'blade',
    {type:'execute',text:'체력이 35% 이하인 적에게 두 배의 피해를 줍니다.'},
    {name:'제노사이드 스텝',cost:80,type:'execute',text:'보스 우선 최대 5명에게 위력 16배. 체력 35% 이하(보스 40%)면 30배. 보스 추가 피해도 적용됩니다.'}),
  h('cinderella','신데렐라','한밤의 기적','#f7a5cc','heroes',2,23,1.05,'star',
    {type:'miracle',text:'세 번째 공격은 위력 1.8배의 유리 별탄으로 적의 방어를 무시합니다.'},
    {name:'자정의 기적',cost:65,type:'glassfall',text:'전장의 적들에게 위력 8배의 방어 무시 유리 별비를 내립니다.'}),
  h('snow_rabbit','눈토끼','겨울의 작은 발자국','#9bdfef','companions',0,10,.95,'ice',
    {type:'slow',text:'눈송이가 적을 느리게 합니다. 토끼 동료와 함께하면 공격이 빨라집니다.'},
    {name:'하얀 숨결',cost:65,type:'freeze',text:'모든 적을 3초 동안 얼리고 얼음 피해를 줍니다.'}),
  h('avalanche_maid','아발란체메이드','잠든 눈사태','#9fc5f7','companions',1,24,1.65,'ice',
    {type:'shatter',text:'느려진 적에게 75% 추가 피해. 얼음이 주변에 파편을 뿌립니다.'},
    {name:'백야의 눈사태',cost:85,type:'avalanche',text:'넓은 범위에 거대한 얼음 폭발. 얼어 있는 적에게 두 배 피해.'}),
  h('night_rabbit','밤토끼','별 없는 밤의 도약','#bd91e3','companions',2,17,.7,'blade',
    {type:'rabbit',text:'다른 종류의 토끼마다 공격속도 20% 증가.'},
    {name:'달그림자 도약',cost:65,type:'flurry',text:'선두의 적들을 빠르게 연속 타격합니다.'}),
  h('guardian','가디언','대륙을 옮긴 손','#e2ba75','companions',3,32,1.8,'stone',
    {type:'stun',text:'세 번째 공격마다 적을 잠시 기절시킵니다.'},
    {name:'대륙의 맥동',cost:75,type:'quake',text:'지진으로 모든 적을 뒤로 밀고 기절시킵니다.'}),
  h('storm_sage','폭풍의현자','흐름을 읽는 자','#8dd2c4','companions',4,14,.85,'wind',
    {type:'gust',text:'바람이 가까운 두 적을 타격합니다.'},
    {name:'태풍의 눈',cost:75,type:'vortex',text:'적을 전방의 한곳으로 모아 타격하고 느리게 합니다.'}),
  h('lightning_sage','번개의현자','찰나의 섬광','#f2db84','companions',5,20,1.2,'lightning',
    {type:'chain',text:'번개가 가까운 적 3명에게 연쇄됩니다.'},
    {name:'천둥의 연쇄',cost:80,type:'thunder',text:'모든 적을 연쇄 타격하고 짧게 기절시킵니다.'}),
  h('red_dragon','레드드래곤','진홍의 포효','#ff805c','companions-ember',0,30,1.75,'fire',
    {type:'splash',text:'불덩이가 폭발합니다. 불타는 적에게 40% 추가 피해.'},
    {name:'용의 숨결',cost:90,type:'dragon',text:'넓은 화염으로 전장을 휩쓸고 강하게 불태웁니다.'}),
  h('flame_sage','화염의현자','꺼지지 않는 잔불','#edab55','companions-ember',1,17,1.1,'fire',
    {type:'burn',text:'불꽃이 주변의 적에게 번져 지속 피해를 줍니다.'},
    {name:'작열의 문장',cost:75,type:'combust',text:'적을 태웁니다. 이미 불타는 적에게 큰 폭발을 일으킵니다.'}),
  h('mushroom_king','머쉬룸킹','독의 왕관','#baaf66','companions-ember',2,11,.95,'spore',
    {type:'poison',text:'독 포자가 중첩됩니다. 합성할 때 모든 적에게 독을 퍼뜨립니다.'},
    {name:'왕의 마지막 포자',cost:70,type:'plague',text:'모든 적을 중독시킵니다. 독은 방어력을 무시합니다.'}),
  h('great_detective','명탐정','진실을 비추는 빛','#f2d8a0','companions-tide',0,30,1.6,'light',
    {type:'expose',text:'가장 강한 적을 노립니다. 명중한 적의 받는 피해가 증가합니다.'},
    {name:'완벽한 추리',cost:60,type:'expose',text:'보스를 포함한 모든 적을 노출시켜 10초간 받는 피해를 60% 늘립니다.'}),
  h('siren','세이렌','물결의 노래','#91d8f7','companions-tide',1,9,1.25,'water',
    {type:'hasteAura',text:'노랫소리로 상하좌우 동료의 공격속도를 22% 높입니다.'},
    {name:'공명의 아리아',cost:65,type:'haste',text:'8초 동안 모든 영웅의 공격속도를 65% 높입니다.'}),
  h('phantom','팬텀','곰인형 속 악몽','#c9a0cb','companions-tide',2,19,1.3,'shadow',
    {type:'fear',text:'세 번째 공격마다 적을 잠시 뒤로 물립니다.'},
    {name:'깨어나지 않는 밤',cost:75,type:'nightmare',text:'적을 뒤로 돌려보내고 받는 피해를 늘립니다.'}),
  h('queen','여왕','장미의 통치자','#e9a5bb','queen',0,10,1.35,'rose',
    {type:'dividend',text:'웨이브가 끝날 때 배당을 받습니다. 높은 등급일수록 배당 증가.'},
    {name:'장미의 세금',cost:60,type:'dividend',text:'장미가 적을 타격하고 30골드를 얻습니다.'}),
  h('galaxy_whale','은하고래','별바다의 주인','#90a9ec','galaxy-whale',0,35,2,'cosmos',
    {type:'gravity',text:'무거운 별이 주변 적을 감속시킵니다.'},
    {name:'별바다의 중심',cost:100,type:'singularity',text:'거대한 중력장이 적을 끌어당긴 뒤 폭발합니다.'}),
  h('silver_rabbit','은토끼','새벽을 잇는 발자국','#c4e5df','silver-rabbit',0,14,.9,'light',
    {type:'battery',text:'공격마다 별빛을 조금 더 채웁니다. 토끼 동료와 공명합니다.'},
    {name:'은빛 행진',cost:55,type:'march',text:'6초 동안 공격속도와 별빛 획득량이 증가합니다.'}),
  h('ancient_dragon','에인션트드래곤','오랜 별의 지혜','#e1c486','ancient-dragon',0,28,1.6,'light',
    {type:'powerAura',text:'상하좌우 동료의 공격력을 25% 높입니다.'},
    {name:'태고의 약속',cost:85,type:'awaken',text:'10초 동안 모든 영웅의 공격력을 70% 높입니다.'}),
  h('time_ruler','시간의지배자','멈춘 시계의 여왕','#c4bcf4','time-ruler',0,15,1.1,'time',
    {type:'chrono',text:'명중한 적의 이동을 짧게 늦춥니다.'},
    {name:'아직 오지 않은 순간',cost:90,type:'rewind',text:'모든 적을 기본 이동 거리 6초분만큼 뒤로 보내고 2초 동안 멈춥니다.'}),
  h('doom','둠','웃음 뒤의 계약','#ad97da','',0,16,1.2,'shadow',
    {type:'sacrifice',text:'합성 재료가 되면 등급당 18골드. 훈련마다 등급당 +4골드.'},
    {name:'왕궁의 암거래',cost:60,type:'fortune',text:'전장 전체에 위력 3배의 암흑검. 즉시 25골드를 얻습니다.'}),
  h('santa','산타','성야의 배달부','#f7b994','',0,13,1.05,'gift',
    {type:'gift',text:'네 번째 공격마다 상하좌우 동료의 공격 대기를 0.6초 앞당깁니다.'},
    {name:'한밤의 선물',cost:75,type:'gift',text:'편성 동료 한 명이 2성으로 합류하고 6초간 모든 동료의 공격속도 +30%.'}),
  h('jasmine','자스민','빛을 모으는 왕녀','#ffe6a5','',0,20,1.15,'light',
    {type:'divine',text:'명중마다 성광을 쌓습니다. 성광 3중첩 대상에게 위력 +65%.'},
    {name:'여신강림',cost:80,type:'goddess',text:'전장 전체 위력 5배 피해와 성광 3중첩. 8초간 모든 동료 위력 +35%.'}),
  h('star_boy','별똥별소년','소원을 가르는 유성','#7eddfa','',0,17,.65,'comet',
    {type:'starfall',text:'다섯 번째 유성탄은 위력 2.2배. 멀리 있는 적도 빠르게 타격합니다.'},
    {name:'소원을 담은 별',cost:75,type:'starfall',text:'최대 체력이 가장 높은 적 한 명을 추적해 위력 32배의 유성을 떨어뜨립니다.'}),
  h('time_magician','시간의마술사','부서진 동화의 주인','#e093df','',0,18,1.35,'time',
    {type:'accelerate',text:'세 번째 관통마다 상하좌우 동료의 공격 대기를 0.6초 앞당깁니다.'},
    {name:'트라우마 · 어둠의 신데렐라',cost:80,type:'trauma',text:'전장 전체 위력 4배 피해. 배치된 시간의마술사들이 10초간 트라우마로 변신: 위력 +110%, 공속 +35%, 방어 무시.'}),
  h('cherry_prince','체리프린스','붉은 약속의 왕자','#ffacc4','',0,36,1.5,'blade',
    {type:'regal',text:'보스 피해 +25%. 화상 또는 성광 3중첩 대상에게 위력 +60%.'},
    {name:'체리 블로섬 · 왕자의 일격',cost:85,type:'royal',text:'최대 체력이 가장 높은 적 한 명에게 위력 34배의 방어 무시 검격. 화상·성광 3중첩이면 1.4배.'}),
  h('frost_witch','혹한의마녀','영겁의 빙관','#a8e4fa','',0,22,1.5,'ice',
    {type:'permafrost',text:'관통하는 얼음창이 서리를 쌓습니다. 3중첩은 위력 120% 추가 피해와 짧은 빙결.'},
    {name:'빙궁의 칙령',cost:80,type:'ice_court',text:'모든 적에게 위력 5배 피해와 서리 2중첩. 6초 동안 50% 감속시켜 다음 얼음창의 빙결을 준비합니다.'}),
  h('harmonious','하모니어스','달콤한 조화의 수호신','#9ce3c5','',0,10,1.3,'sugar',
    {type:'harmonyAura',text:'상하좌우의 서로 다른 동료마다 인접 동료 위력 +5%, 공속 +4%. 하모니어스는 종류 수에서 제외.'},
    {name:'디저트 앙상블',cost:70,type:'harmony',text:'모든 동료의 공격 대기를 1.5초 앞당기고 8초 동안 조화 오라를 두 배로 만듭니다.'}),
  h('aurora','아우로라','거울 너머의 미소','#d6befa','',0,14,1.3,'mirror',
    {type:'refraction',text:'직격 후 표적 뒤에 거울을 만들고 약 0.7초 뒤 위력 75%의 환영탄을 되돌립니다.'},
    {name:'천면경',cost:80,type:'mirror',text:'최대 체력이 가장 높은 적 한 명의 피해를 3초간 기록. 위력 10배와 기록한 피해의 45%(추가 최대 18배)를 되돌립니다.'}),
];
export const HERO = Object.fromEntries(HEROES.map(x=>[x.id,x]));
// Rumi's summoned world: Defense roles and play feel take precedence over source lore.
const roles = {
  zeke:['선봉 · 부채꼴','cleave',345,90,'전방 90°를 함께 베어 화상을 남깁니다.'],
  rumi:['합성 · 관통 별','beam',440,24,'일직선 관통. 같은 등급의 모든 동료와 합성합니다.'],
  luna:['보스 처형 · 단일','single',340,0,'보스 우선 · 보스 피해 +35%. 체력 35% 이하(보스 40%)면 기본 공격 두 배.'],
  cinderella:['기적 연타 · 별탄','single',480,0,'세 번째 공격은 위력 1.8배 · 방어 무시.'],
  snow_rabbit:['감속 · 작은 폭발','splash',450,48,'작은 눈보라가 주변 적을 40% 감속합니다.'],
  avalanche_maid:['빙결 연계 · 포격','splash',560,100,'넓은 얼음 파편. 감속 중인 적에게 피해 +75%.'],
  night_rabbit:['토끼 연계 · 도탄','bounce',390,135,'두 적 사이를 튑니다. 다른 토끼 종류마다 공격속도 +20%.'],
  guardian:['근접 방벽 · 타일 충격','pulse',230,230,'자신의 칸 주변 230 범위를 전부 타격. 세 번째 공격은 기절.'],
  storm_sage:['관통 · 바람길','beam',560,42,'긴 바람길을 관통하고 인근 적 하나에 바람을 보냅니다.'],
  lightning_sage:['연쇄 · 번개','chain',470,190,'가까운 세 적에게 번개가 이어집니다.'],
  red_dragon:['화상 연계 · 폭격','splash',590,88,'멀리서 넓게 폭발. 불타는 적에게 피해 +40%.'],
  flame_sage:['지속 화력 · 불바닥','zone',430,64,'명중 지점에 3초의 불바닥. 적이 지나가도 불길은 남습니다.'],
  mushroom_king:['시간 경제 · 포자밭','zone',370,66,'포자밭으로 중독. 전투 12초마다 1성 3G · 2성 4G 수확. 강화마다 +2G, 합성하면 12초부터 다시 시작.'],
  great_detective:['보스 약화 · 저격','single',900,0,'보스 우선 · 보스 피해 +25%. 직격 후 4초간 받는 피해 +18%(보스 +30%). 강화마다 +2%p.'],
  siren:['인접 지원 · 물결','splash',400,58,'상하좌우 동료 공격속도 +22%. 강화마다 오라 +3%p.'],
  phantom:['견제 · 악몽 덫','zone',460,60,'3초의 덫을 남겨 감속. 세 번째 직격은 적을 뒤로 밀칩니다.'],
  queen:['물결 경제 · 장미','single',440,0,'물결 종료 시 1성 5G · 2성 7G 배당. 4·7·10물결부터 +1G씩, 강화마다 +3G. 여왕 전체 합계 최대 45G.'],
  galaxy_whale:['밀집 제어 · 중력장','zone',550,98,'3초의 중력장으로 넓게 피해를 주고 40% 감속합니다.'],
  silver_rabbit:['별빛 지원 · 관통광','beam',500,22,'관통 공격이 별빛을 충전. 강화마다 추가 별빛 +0.1.'],
  ancient_dragon:['인접 지원 · 십자광','cross',620,55,'자신의 행·열을 관통. 상하좌우 동료 공격력 +25%, 강화마다 +3%p.'],
  time_ruler:['시간 제어 · 시계장','zone',490,72,'3초의 시간장을 남겨 25% 감속. 강화마다 감속 +3%p.'],
  doom:['합성 경제 · 관통검','beam',450,22,'재료로 소모되면 1성 18G · 2성 36G 환급. 강화마다 등급당 +4G. 루미가 재료면 환급 없음.'],
  santa:['선물 지원 · 포격','splash',510,56,'네 번째 공격마다 상하좌우 동료 공격 대기 −0.6초. 강화마다 −0.1초 추가.'],
  jasmine:['성광 연계 · 빛의 파동','splash',510,60,'6초 성광 누적. 3중첩 적에게 위력 +65%. 체리프린스와 연계.'],
  star_boy:['강적 추적 · 유성탄','single',650,0,'빠른 유성 연사. 다섯 번째 공격은 위력 2.2배.'],
  time_magician:['시간 가속 · 관통침','beam',520,28,'세 번째 관통마다 상하좌우 공격 대기 −0.6초. 강화마다 −0.1초 추가. 필살기 중 트라우마로 변신.'],
  cherry_prince:['강적 결전 · 검광','single',590,0,'보스 피해 +25%. 화상 또는 성광 3중첩 대상에게 위력 +60%.'],
  frost_witch:['서리 연계 · 얼음창','beam',550,32,'관통 직격은 2.4초간 40% 감속과 서리 1중첩. 서리 3중첩에 추가 피해와 0.9초 빙결(보스 0.45초).'],
  harmonious:['다양성 지원 · 조화','single',460,0,'상하좌우의 서로 다른 동료마다 인접 동료 위력 +5%, 공속 +4%. 같은 종류는 한 번, 하모니어스는 제외.'],
  aurora:['지연 반사 · 환영탄','single',540,0,'직격 후 위력 75% 환영탄. 시전 시 정한 표적을 추적하며 다른 적으로 옮기지 않습니다.'],
};
for(const hero of HEROES){
  hero.heightGroup=Object.entries(HEIGHT_GROUPS).find(([,ids])=>ids.includes(hero.id))[0];
  const [role,shape,range,radius,text]=roles[hero.id];
  Object.assign(hero,{role,shape,range,radius});hero.trait.text=text;
  hero.art={atlas:`unit-${hero.id}`,row:0,columns:2,foot:480/512,scale:1,directional:true,portrait:PORTRAIT_FRAMES[hero.id]};
}
HERO.luna.bossDamage=1.35;
HERO.great_detective.bossDamage=1.25;
HERO.cherry_prince.bossDamage=1.25;
export const TRANSFORM_ART={trauma:{atlas:'unit-trauma',row:0,columns:2,foot:480/512,scale:1,directional:true,portrait:PORTRAIT_FRAMES.trauma}};
export const ARTIFACTS = [
  ['hourglass','별모래 시계','합성할 때 별빛을 8 더 얻습니다.'],
  ['ember','불씨의 심장','화상 피해 +60%. 불바닥 동행과 함께하세요.'],
  ['frost','녹지 않는 꽃','감속 중인 적이 받는 피해 +25%.'],
  ['banner','홀로 선 깃발','상하좌우에 동료가 없으면 공격력 +40%.'],
  ['chorus','쌍둥이 음표','같은 영웅이 2명 이상이면 공격속도 +15%.'],
  ['lantern','꺼지지 않는 등불','필살기 사용 후 별빛을 15 돌려받습니다.'],
  ['lens','예리한 달조각','보스에게 주는 피해 +30%.'],
  ['seed','숨 쉬는 씨앗','공격·장판·합성·필살기의 독 부여량 +1중첩.'],
  ['feather','첫새벽의 깃털','유료 소환 비용 -4G. 최소 8G.'],
  ['crown','작은 왕관','3등급 이상 영웅 공격력 +25%.'],
  ['meteor','떨어진 별','12번째 공격마다 명중 지점에 위력 180%의 운석.'],
  ['prism','천 갈래 프리즘','연쇄·도탄·관통 바람의 추가 타격 +1명.'],
  ['tide','파도의 소라','감속을 걸면 주변 80 범위에 위력 25% 물보라. 장판은 0.5초마다 발동.'],
  ['roots','영원의 뿌리','불·독·악몽·중력·시간 장판 지속시간 +50%.'],
  ['guild','동행의 악수','지원 오라를 받는 영웅의 공격력 +15%.'],
  ['phoenix','돌아오는 새벽','원정에서 첫 결계 피해를 막고 체력 3 회복.'],
  ['twin','쌍성의 거울','모든 영웅의 네 번째 공격에 위력 45%의 메아리.'],
  ['constellation','삼중 성좌','서로 다른 동료 3종 이상과 인접하면 공격력 +65%.'],
  ['alchemy','별빛 연금술','합성할 때 합성 결과 영웅 위력 150%로 모든 적 타격.'],
  ['orbit','별바다의 궤도','3등급 이상 공격마다 명중 지점에 2초 별장판. 0.5초마다 위력 15% 피해.'],
  ['tempo_bell','첫막의 종','매 물결의 첫 7초 동안 모든 동료 공격속도 +45%.'],
  ['royal_seal','결전의 인장','최대 체력이 가장 높은 생존 적에게 주는 피해 +25%.'],
  ['gift_ribbon','기적의 리본','매 4번째 유료 소환은 2성으로 등장. 무료 소환은 횟수에서 제외.'],
  ['broken_clock','깨진 시간의 보석','필살기의 동료 강화와 트라우마 변신 지속시간 +2초.'],
].map(([id,name,text],icon)=>({id,name,text,icon:icon<20?icon:icon-20,atlas:icon<20?'relics':'relics-expansion',rarity:icon<10?'common':icon<16||icon===20||icon===21?'rare':'epic',color:icon<10?'#bbd5cc':icon<16||icon===20||icon===21?'#86c8ee':'#c9a0f5'}));
export const ARTIFACT = Object.fromEntries(ARTIFACTS.map(x=>[x.id,x]));
export const validArtifacts=ids=>Array.isArray(ids)&&ids.length<=3&&new Set(ids).size===ids.length&&ids.every(id=>!!ARTIFACT[id]);
export const BLESSINGS = [
  {id:'arrival',name:'빛나는 초대장',category:'즉시',text:'편성 동료 한 명이 2등급으로 합류. 빈칸이 없으면 자리가 날 때 합류합니다.'},
  {id:'surge',name:'내일의 새벽검',category:'다음 물결',text:'다음 한 물결 동안 모든 공격력 +25%.'},
  {id:'training',name:'동행의 지혜',category:'성장',text:'이 원정의 동행 강화 비용 -10%p. 최대 50% 할인.'},
  {id:'oath',name:'별들의 약속',category:'영구',text:'이번 원정의 모든 공격력 +6%p.'},
  {id:'purse',name:'여행자의 보급',category:'즉시',text:'35골드를 즉시 얻습니다.'},
  {id:'mend',name:'다시 피는 꽃',category:'회복',text:'결계 체력 3 회복, 별빛 20 충전.'},
].map((b,icon)=>({...b,icon}));
export const BLESSING=Object.fromEntries(BLESSINGS.map(b=>[b.id,b]));
export const CHAPTERS = [
  {id:0,name:'달빛 정원',caption:'처음 피어나는 별',color:'#7dbac1',bosses:['artificial_demon','love_iris','curse_iris'],hp:1,world:0},
  {id:1,name:'잠든 숲의 노래',caption:'독과 생명의 경계',color:'#a9bd80',bosses:['flora','artificial_demon','flora'],hp:1.3,world:3},
  {id:2,name:'푸른 심연',caption:'폭풍 아래의 약속',color:'#82aec7',bosses:['poseidon','love_iris','poseidon'],hp:1.65,world:4},
  {id:3,name:'황혼의 왕좌',caption:'마지막 성좌',color:'#c799ba',bosses:['curse_iris','beelzebub','beelzebub'],hp:2.05,world:5},
  {id:4,name:'뇌명의 첨탑',caption:'번개가 고른 자리에서 벗어나세요',color:'#96c9f3',bosses:['thor','poseidon','thor'],hp:2.35,world:6,background:0},
  {id:5,name:'전쟁신의 성채',caption:'가장 강한 일격으로 도전을 끊으세요',color:'#edab94',bosses:['ares','beelzebub','ares'],hp:2.7,world:7,background:1},
  {id:6,name:'창세의 성원',caption:'모든 별의 시작을 향하여',color:'#dbc5fc',bosses:['thor','ares','astea'],hp:3.05,world:8,background:2},
];
export const BOSSES = {
  artificial_demon:{name:'인조마신',color:'#8ee8ee',pattern:'seal',warning:'마력 봉인 · 한 행 3.2초 봉인',frame:0},
  love_iris:{name:'사랑의 여신 아이리스',color:'#f7b6d4',pattern:'heal',warning:'치유의 기도 · 체력 14% 회복',frame:1},
  curse_iris:{name:'저주의 여신 아이리스',color:'#bc8be0',pattern:'drain',warning:'별빛 침식 · 별빛 −25',frame:2},
  flora:{name:'꽃의 여신 플로라',color:'#c9dd8d',pattern:'heal',warning:'생명의 개화 · 체력 14% 회복',frame:3},
  poseidon:{name:'해신 포세이돈',color:'#77c9e3',pattern:'rush',warning:'밀려오는 해일 · 적 전진',frame:4},
  beelzebub:{name:'마신 벨제뷔트',color:'#dfa590',pattern:'seal',warning:'붕괴의 문장 · 한 행 3.2초 봉인',frame:5},
  thor:{name:'뇌신 토르',color:'#a9dcff',pattern:'storm',warning:'신벌의 낙뢰 · 빛나는 3칸에서 이동하세요',atlas:'bosses-expansion',frame:0},
  ares:{name:'투신 아레스',color:'#ffa88b',pattern:'duel',warning:'투신의 도전 · 2.6초 안에 최대 체력 6% 피해로 저지',atlas:'bosses-expansion',frame:1},
  astea:{name:'창조신 아스테아',color:'#e8d3ff',pattern:'creation',warning:'창세의 노래 · 2.6초 안에 최대 체력 6% 피해로 창조 저지',atlas:'bosses-expansion',frame:2},
};
export const ASSET_PATHS = {
  ...Object.fromEntries(HEROES.map(h=>[`unit-${h.id}`,`./assets/merge/units/${h.id}.webp`])),
  garden:'./assets/merge/garden.webp',bosses:'./assets/moonlit/realm-bosses.webp',
  creatures:'./assets/moonlit/creatures.webp',
  relics:'./assets/merge/relics.webp',blessings:'./assets/merge/blessings.webp',effects:'./assets/merge/effects.webp',
  'unit-trauma':'./assets/merge/units/trauma.webp',
  'effects-expansion':'./assets/merge/effects-expansion.webp',
  'finishers':'./assets/merge/finishers.webp',
  'relics-expansion':'./assets/merge/relics-expansion.webp',
  'bosses-expansion':'./assets/merge/bosses-expansion.webp',
  'realms-expansion':'./assets/merge/realms-expansion.webp',
  'effects-trio':'./assets/merge/effects-trio.webp',
};
export const ASSET_MANIFEST = Object.entries(ASSET_PATHS).map(([id,path])=>({id,path,type:'image',releaseRequired:true,hasAlpha:!['garden','effects','effects-expansion','effects-trio','finishers','realms-expansion'].includes(id)}));
