import { build, transform } from "esbuild";
import { access, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPOSITORY_ROOT = path.resolve(SCRIPT_DIR, "..");
const APP_ROOT = path.join(REPOSITORY_ROOT, "defense_hero");
const DEFAULT_OUTPUT = path.join(APP_ROOT, "dist-local", "HeroCoreDefense.html");
const MIME_TYPES = Object.freeze({
  ".avif": "image/avif",
  ".gif": "image/gif",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".mp3": "audio/mpeg",
  ".ogg": "audio/ogg",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".wav": "audio/wav",
  ".webm": "audio/webm",
  ".webp": "image/webp",
});

function escapeInlineBlock(source, closingTag) {
  return source.replace(new RegExp(`</${closingTag}`, "gi"), `<\\/${closingTag}`);
}

async function fileExists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function collectEmbeddedAssets() {
  const assetModulePath = path.join(APP_ROOT, "js", "data", "assets.js");
  const assetModule = await import(pathToFileURL(assetModulePath).href);
  const embeddedAssets = {};
  let embeddedBytes = 0;

  for (const entry of assetModule.ASSET_MANIFEST ?? []) {
    const sourcePath = path.resolve(APP_ROOT, entry.path);
    if (!(await fileExists(sourcePath))) continue;
    const mimeType = MIME_TYPES[path.extname(sourcePath).toLowerCase()];
    if (!mimeType) throw new Error(`지원하지 않는 에셋 형식입니다: ${entry.path}`);
    const bytes = await readFile(sourcePath);
    embeddedAssets[entry.path] = `data:${mimeType};base64,${bytes.toString("base64")}`;
    embeddedBytes += bytes.length;
  }

  return { embeddedAssets, embeddedBytes };
}

export async function buildHeroDefenseLocal({ outputPath = DEFAULT_OUTPUT, minify = true } = {}) {
  const [htmlTemplate, css, assetData] = await Promise.all([
    readFile(path.join(APP_ROOT, "index.html"), "utf8"),
    readFile(path.join(APP_ROOT, "css", "app.css"), "utf8"),
    collectEmbeddedAssets(),
  ]);

  const embeddedAssetBanner = [
    "globalThis.__HERO_DEFENSE_LOCAL_FILE__=true;",
    `globalThis.__HERO_DEFENSE_EMBEDDED_ASSETS__=Object.freeze(${JSON.stringify(assetData.embeddedAssets)});`,
  ].join("");
  const bundle = await build({
    absWorkingDir: APP_ROOT,
    entryPoints: ["./js/main.js"],
    bundle: true,
    charset: "utf8",
    format: "iife",
    legalComments: "none",
    minify,
    platform: "browser",
    target: ["chrome90", "safari15"],
    write: false,
    banner: { js: embeddedAssetBanner },
  });
  const javascript = bundle.outputFiles[0].text;
  const bundledCss = (await transform(css, {
    charset: "utf8",
    legalComments: "none",
    loader: "css",
    minify,
  })).code;

  const outputHtml = htmlTemplate
    .replace(
      /<link\s+rel=["']stylesheet["']\s+href=["']\.\/css\/app\.css["']\s*\/?\s*>/i,
      `<style data-bundled-from="./css/app.css">\n${escapeInlineBlock(bundledCss, "style")}\n</style>`,
    )
    .replace(
      /<script\s+type=["']module["']\s+src=["']\.\/js\/main\.js["']\s*><\/script>/i,
      `<script data-bundled-from="./js/main.js">\n${escapeInlineBlock(javascript, "script")}\n</script>`,
    )
    .replace(
      "<meta name=\"theme-color\"",
      "<meta name=\"hero-defense-distribution\" content=\"single-file-offline\" />\n    <meta name=\"theme-color\"",
    )
    .replace(
      "<!doctype html>",
      "<!doctype html>\n<!-- Generated by npm run build:defense-hero-local. Edit defense_hero source files, not this file. -->",
    );

  if (outputHtml.includes('type="module"') || outputHtml.includes('src="./js/main.js"')) {
    throw new Error("ES 모듈 진입점을 단일 파일 스크립트로 교체하지 못했습니다.");
  }
  if (outputHtml.includes('href="./css/app.css"')) {
    throw new Error("외부 스타일시트를 단일 파일에 포함하지 못했습니다.");
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, outputHtml, "utf8");
  const outputStats = await stat(outputPath);
  return {
    outputPath,
    outputBytes: outputStats.size,
    embeddedAssetCount: Object.keys(assetData.embeddedAssets).length,
    embeddedAssetBytes: assetData.embeddedBytes,
  };
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  const result = await buildHeroDefenseLocal();
  console.log(`Hero Core Defense 단일 HTML 생성: ${result.outputPath}`);
  console.log(`크기: ${(result.outputBytes / 1024).toFixed(1)} KiB · 포함 에셋: ${result.embeddedAssetCount}개`);
}
