const fs = require('fs');
const path = require('path');

const MUSIC_PREFIX = 'MUSIC_';
const DEFAULT_CARD_ROOT = path.resolve(__dirname, '..', 'card');
const DEFAULT_OUTPUT_PATH = path.join(DEFAULT_CARD_ROOT, 'music_manifest.js');

function comparePaths(left, right) {
    if (left === right) return 0;
    return left < right ? -1 : 1;
}

function toBrowserPath(filePath) {
    return filePath.replace(/\\/g, '/');
}

function collectMusicFiles(directory, cardRoot, results) {
    const entries = fs.readdirSync(directory, { withFileTypes: true });

    entries.forEach(entry => {
        const absolutePath = path.join(directory, entry.name);
        if (entry.isDirectory()) {
            collectMusicFiles(absolutePath, cardRoot, results);
            return;
        }
        if (!entry.isFile()) return;

        const extension = path.extname(entry.name);
        if (extension.toLowerCase() !== '.mp3' || !entry.name.startsWith(MUSIC_PREFIX)) return;

        const relativePath = toBrowserPath(path.relative(cardRoot, absolutePath));
        results.push({
            id: relativePath,
            title: entry.name.slice(MUSIC_PREFIX.length, -extension.length),
            artist: 'Card RPG',
            album: 'Card RPG Music',
            src: relativePath
        });
    });
}

function collectMusicTracks(cardRoot = DEFAULT_CARD_ROOT) {
    const resolvedRoot = path.resolve(cardRoot);
    const tracks = [];
    collectMusicFiles(resolvedRoot, resolvedRoot, tracks);
    return tracks.sort((left, right) => comparePaths(left.id, right.id));
}

function stringifyForJavaScript(value) {
    return JSON.stringify(value, null, 4)
        .replace(/\u2028/g, '\\u2028')
        .replace(/\u2029/g, '\\u2029');
}

function renderManifest(tracks) {
    const entries = tracks.map(track => {
        const objectLines = stringifyForJavaScript(track).split('\n');
        const indentedObject = objectLines
            .map((line, index) => index === 0 ? line : `    ${line}`)
            .join('\n');
        return `    Object.freeze(${indentedObject})`;
    });
    const body = entries.length > 0 ? `\n${entries.join(',\n')}\n` : '';

    return [
        '/* This file is generated by scripts/generate_card_music_manifest.js. */',
        "'use strict';",
        '',
        `window.CARD_MUSIC_TRACKS = Object.freeze([${body}]);`,
        ''
    ].join('\n');
}

function generateManifest(cardRoot = DEFAULT_CARD_ROOT, outputPath = DEFAULT_OUTPUT_PATH) {
    const tracks = collectMusicTracks(cardRoot);
    const content = renderManifest(tracks);
    const resolvedOutput = path.resolve(outputPath);
    const previousContent = fs.existsSync(resolvedOutput)
        ? fs.readFileSync(resolvedOutput, 'utf8')
        : null;

    if (previousContent !== content) {
        fs.mkdirSync(path.dirname(resolvedOutput), { recursive: true });
        fs.writeFileSync(resolvedOutput, content, 'utf8');
    }

    return { tracks, content, outputPath: resolvedOutput };
}

if (require.main === module) {
    try {
        const result = generateManifest();
        console.log(`Generated ${path.relative(process.cwd(), result.outputPath)} with ${result.tracks.length} track(s).`);
    } catch (error) {
        console.error(error.stack || error.message || error);
        process.exitCode = 1;
    }
}

module.exports = {
    MUSIC_PREFIX,
    collectMusicTracks,
    generateManifest,
    renderManifest
};
