import {HEROES,HERO,COMPANIONS,COMPANION,BOSSES,BOSS,ARTIFACTS,MEMORIES,ELEMENTS,STYLES,TITLES,GATES,balance,season} from '../data/catalog.js';
import {SCENES,BOND_THRESHOLDS} from '../data/scenes.js';
import {TEMP_RELICS} from '../combat/effects.js';
import {Q,HOUR,DAY,totalStage,relativeDay,occurrence,baseHourly,heroHourlyXP} from '../core/state.js';
import {clone} from '../core/rng.js';
import {settleAccrual} from '../core/clock.js';
import {snapshot,baseStats,levelCost,gearCost} from '../systems/growth.js';
import {homeLine,unreadScenes,unlocked} from '../systems/bond.js';
import {poolMemories} from '../systems/gacha.js';
import {gateAvailable} from '../systems/learning.js';
import {seasonActive} from '../systems/seasons.js';
import {eventFor} from '../systems/adventure.js';
import {landscape} from './art.js';
import {esc,fmt,compact,duration,button as btn,icon,art,progress,costs,badge} from './html.js';

const tabs=[['home','home','홈'],['expedition','path','원정'],['hero','hero','영웅'],['bond','heart','교류'],['collection','album','수집']];
const header=(title,sub,extra='')=>'<header class="page-head"><div><span class="eyebrow">Astral Companions</span><h1>'+title+'</h1><p>'+sub+'</p></div>'+extra+'</header>';
export const heroSelector=(s,action='heroSelect')=>'<div class="hero-roster">'+HEROES.map(h=>btn(action,art(h.id,'avatar',h.name)+'<b>'+h.name+'</b><small>Lv. '+s.heroes[h.id].level+'</small>',{hero:h.id},'hero-tile '+(s.ui.hero===h.id?'active':''))).join('')+'</div>';
export const sceneList=(s,list)=>'<div class="scene-list">'+list.map((c,i)=>btn('scene','<span class="scene-index">'+String(i+1).padStart(2,'0')+'</span><span><strong>'+esc(c.title)+'</strong><small>'+sceneRequirement(s,c)+'</small></span>'+badge(s.readScenes.includes(c.id)?s.skippedScenes.includes(c.id)?'다시 읽기':'읽음':unlocked(s,c)?'새 이야기':'잠김',unlocked(s,c)?'teal':'lock'),{scene:c.id},'scene-item',!unlocked(s,c))).join('')+'</div>';
function sceneRequirement(s,c){const r=c.requirements;if(s.readScenes.includes(c.id))return '언제든 다시 펼칠 수 있어요';if(r.kind==='bond')return '관계 '+fmt(s.heroes[r.heroId].bond)+' / '+r.points+(c.rewardId?' · 기억 그림':'');if(r.kind==='companion')return r.gates?'서로 다른 관문 '+s.companions[r.companionId].gates.length+' / '+r.gates:'동료 보유';if(r.kind==='season')return '시즌 활동 '+r.days+'일 · 이전 이야기 읽기';return r.group==='trauma'?'시간의마술사 기록 3편 · 영웅 원정 60 · 순서대로 열람':'루나·자스민 관계 각 210 · 원정 합계 120 · 순서대로 열람';}
export function shell(s,ui,store){
 const current=unreadScenes(s).length,content=ui.tab==='home'?home(s,ui):ui.tab==='expedition'?expedition(s,ui):ui.tab==='hero'?hero(s):ui.tab==='bond'?bond(s,ui):collection(s,ui);
 return '<div class="app-shell"><header class="topbar"><div class="brand">'+icon('star')+'별의 동행</div><div class="wallets">'+[['xp','star','EXP'],['gold','sun','골드'],['forgeOre','gem','광석']].map(([k,i,n])=>'<div class="wallet" title="'+n+' '+fmt(s.wallets[k])+'">'+icon(i)+'<b>'+compact(s.wallets[k])+'</b><small>'+n+'</small></div>').join('')+'</div>'+btn('settings',icon('settings')+'<span class="sr-only">설정</span>',{},'icon-button')+'</header>'+
 (store.mode==='memory'?'<div class="state-note">현재 기기에 자동 저장할 수 없어요. 떠나기 전에 설정에서 백업을 내려받아 주세요.</div>':store.readOnly?'<div class="state-note">저장 호환 모드 · 이 탭은 읽기 전용입니다. 다른 탭을 닫고 새로고침해 주세요.</div>':'')+
 (s.diagnostics.clockWarning?'<div class="state-note">기기 시간이 이전 기록보다 이릅니다. 이전 시점까지 기다리거나 '+btn('resetClock','시간 기준 맞추기',{},'quiet')+'</div>':'')+
 '<main class="page '+ui.tab+'-page" id="main">'+content+'</main><nav class="bottom-nav" aria-label="주 메뉴">'+tabs.map(([id,i,label])=>btn('tab',icon(i)+'<span>'+label+'</span>'+(id==='bond'&&current?'<i class="nav-dot" aria-label="새 이야기"></i>':''),{tab:id},'nav-item '+(ui.tab===id?'active':''))).join('')+'</nav></div>';
}
function home(s,ui){
 const now=Math.max(s.lastTrustedLogicalMs,Date.now()+s.clockOffsetMs),preview=clone(s);settleAccrual(preview,now);const a=preview.accrual,h=HERO[s.ui.hero],chosen=s.ui.homeArt||h.id,line=ui.line||homeLine(s,now),pinned=MEMORIES.find(x=>x.id===s.gacha.pinned),nextScene=unreadScenes(s).find(c=>c.actors.includes(h.id));
 const memory=MEMORIES.find(m=>m.id===chosen),artTitle=memory?.name||h.name,artPeople=memory?.heroIds.map(id=>(HERO[id]||COMPANION[id])?.name||id).join(' · ');
 const nextBoss=BOSSES.find(b=>!Object.values(s.bossRecords[b.id]||{}).some(r=>r.cleared)),heroData=s.heroes[h.id],nodeCost=36+12*heroData.nodes,cost=levelCost(s,h.id),canTrain=s.wallets.xp>=cost.xp&&s.wallets.gold>=cost.gold;
 const growth=heroData.nodes<60&&heroData.training>=nodeCost?{title:h.name+'의 숙련 '+(heroData.nodes+1),sub:'훈련점 '+nodeCost+' · 지금 해금할 수 있어요',action:'mastery'}:{title:h.name+'의 다음 훈련',sub:canTrain?'레벨을 올릴 자원이 모였어요':'EXP '+fmt(cost.xp)+' · 골드 '+fmt(cost.gold),action:'goHero'};
 const butterfly=s.rewards.butterfly,letter=s.rewards.letter,grace=s.gates.grace;
 return '<div class="home-layout"><div class="home-visual"><div class="portrait-wrap '+(landscape(chosen)?'landscape-wrap':'')+'" role="button" tabindex="0" data-action="viewer" data-art="'+esc(chosen)+'" aria-label="일러스트 전체 보기">'+art(chosen,'home',MEMORIES.find(m=>m.id===chosen)?.name||h.name)+'<div class="hero-nameplate"><span class="eyebrow">'+(memory?'Memory album':TITLES[h.id])+'</span><h1>'+esc(artTitle)+'</h1><small>'+(memory?esc(artPeople):ELEMENTS[h.element]+' · '+h.weapon+' &nbsp; Lv. '+heroData.level)+'</small></div></div><div class="hero-switch" aria-label="대표 영웅 선택">'+HEROES.map(v=>btn('heroSelect',art(v.id,'avatar',v.name),{hero:v.id},s.ui.hero===v.id?'selected':'')).join('')+'</div></div>'+
 '<div class="home-copy"><div class="eyebrow">Your quiet constellation</div><h2 class="greeting">돌아올 자리에,<br>별빛을 켜두었어요.</h2><p class="home-line"><span class="small muted">'+h.name+' · </span>'+esc(line.text)+'</p>'+
 (letter&&now>=letter.availableAt?'<div class="arrival">'+icon('mail')+'<p>'+HERO[letter.actor].name+'의 편지가 도착했어요.</p>'+btn('letter','열기',{},'quiet')+'</div>':'')+
 (butterfly&&!butterfly.claimed&&now>=butterfly.appearsAt?'<div class="arrival">'+icon('star')+'<p>'+(butterfly.golden?'금빛 ':'')+'별나비가 잠시 머물고 있어요.</p>'+btn('butterfly','맞이하기',{},'quiet')+'</div>':'')+
 '<section class="return-box"><div class="row between"><span class="small muted">다섯 영웅이 모은 시간</span><span class="small muted">최대 24시간</span></div><div class="return-time" data-live="duration">'+duration(a.duration)+'</div><div class="return-resources">'+['xp','gold','forgeOre'].map((k,i)=>'<span>'+['EXP','골드','광석'][i]+'<strong data-live="'+k+'">'+fmt(a.pending[k]/Q)+'</strong></span>').join('')+'</div>'+
 (a.boostQ.xp>=Q?'<p class="small muted">가호 보너스 EXP '+fmt(a.boostQ.xp/Q)+' · 골드 '+fmt(a.boostQ.gold/Q)+' 저장됨</p>':'')+
 btn('claim','원정 보상 받기 '+icon('arrow'),{},'primary wide claim-button')+'</section>'+
 '<div class="goals">'+btn(growth.action,'<span class="goal-no">01</span><span><strong>'+growth.title+'</strong><small>'+growth.sub+'</small></span>'+icon('arrow'),{hero:h.id},'goal')+
 btn('goBoss','<span class="goal-no">02</span><span><strong>'+(nextBoss?nextBoss.name+' 공략':'아스테아 합동 완성')+'</strong><small>'+(nextBoss?(totalStage(s)>=nextBoss.unlockTotalMedals?'도전 가능 · 대응 편성을 찾아보세요':'원정 합계 '+totalStage(s)+' / '+nextBoss.unlockTotalMedals):'다섯 영웅의 최고 점수를 모아보세요')+'</small></span>'+icon('arrow'),{},'goal')+
 btn(nextScene?'scene':'goMemories','<span class="goal-no">03</span><span><strong>'+(nextScene?esc(nextScene.title):esc(pinned?.name||'다음 기억 한 장'))+'</strong><small>'+(nextScene?'함께 읽을 새 이야기가 있어요':'누적 기억 소환 '+s.gacha.counts.memory%60+' / 60 · 선택권')+'</small></span>'+icon('arrow'),nextScene?{scene:nextScene.id}:{},'goal')+'</div>'+
 '<div class="bonus-invitation">'+icon('moon')+'<div><strong>원정의 가호</strong><small>'+(grace&&grace.end>now?'남은 시간 '+Math.ceil((grace.end-now)/60000)+'분 · 종료 뒤에도 보관':'단어 하나, 다음 30분 EXP·골드 두 배')+'</small></div>'+btn('gate',s.gates.used.grace===s.calendar.day?'오늘 사용함':'발동',{gate:'grace'},'quiet',!gateAvailable(s,'grace',now))+'</div>'+
 btn('season','별빛 아래의 휴식 · '+(seasonActive(s)?'시즌 '+(relativeDay(s)%28+1)+'일째':'아카이브 기간')+' '+icon('arrow'),{},'secondary wide')+'</div></div>';
}
function expedition(s,ui){
 const mode=ui.expeditionMode||'lanes',seg='<div class="segmented">'+[['lanes','다섯 원정'],['boss','보스와 유물'],['adventure','작은 모험']].map(([id,n])=>btn('expMode',n,{mode:id},mode===id?'selected':'')).join('')+'</div>';
 if(mode==='boss')return header('별길의 시험','패배해도 자원은 줄지 않아요. 편성과 순서를 바꿔보세요.')+seg+bosses(s);
 if(mode==='adventure')return header('작은 모험','여유가 있는 날, 다른 길을 걸어보세요.')+seg+adventureView(s);
 return header('다섯 갈래의 원정','전원이 함께 수익을 모으고, 각자의 다음 관문에 도전해요.',badge('합계 '+totalStage(s)+' 단계','teal'))+seg+
 '<div class="row between section-title"><p class="small muted">일괄 돌파는 영웅마다 승리하는 동안 진행해요.</p>'+btn('advanceAll','일괄 돌파 '+icon('arrow'),{},'primary')+'</div><div class="expedition-list">'+HEROES.map(h=>{const v=s.heroes[h.id],r=heroHourlyXP(v.stage);return '<article class="expedition-row"><div class="expedition-hero">'+art(h.id,'avatar',h.name)+'<div><h3>'+h.name+' <small class="muted">Lv. '+v.level+'</small></h3><p>'+ELEMENTS[h.element]+' · '+h.identity+'</p></div><div style="margin-left:auto;text-align:right"><strong>'+v.stage+'</strong><small class="muted"> / 1200</small></div></div>'+progress(v.stage%10,10,'다음 관문까지')+'<div class="row between small muted" style="margin-top:7px"><span>다음 관문 '+Math.min(1200,(Math.floor(v.stage/10)+1)*10)+'</span><span>시간당 EXP '+fmt(r)+'</span></div><div class="support-row">'+v.companions.map(id=>id?art(id,'avatar',COMPANION[id].name):'<span class="badge">빈 지원</span>').join('')+'<small class="muted">'+v.companions.filter(Boolean).map(id=>COMPANION[id].name).join(' · ')+'</small></div><div class="expedition-actions">'+btn('battle','다음 단계 관전',{hero:h.id},'primary',v.stage>=1200)+btn('advance','빠른 돌파',{hero:h.id},'secondary',v.stage>=1200)+btn('goHero',icon('settings')+'<span class="sr-only">'+h.name+' 편성</span>',{hero:h.id},'icon-button')+'</div></article>';}).join('')+'</div><div class="notice section">관문 승리는 즉시 저장됩니다. 새 레벨·장비·지원 조합으로 같은 전투를 다시 시도할 수 있어요. 관전 배속은 전투 결과를 바꾸지 않아요.</div>';
}
function hero(s){
 const id=s.ui.hero,h=HERO[id],v=s.heroes[id],stats=baseStats(snapshot(s,id)),cost=levelCost(s,id),nc=36+12*v.nodes;
 const slots=[['weapon','무기','ATK·MATK'],['armor','방어구','HP·방어'],['accessory','장신구','MP 회복·치명타']];
 return header('함께 자라는 힘','다섯 영웅은 모두 처음부터 함께해요.')+heroSelector(s)+
 '<section class="section columns"><div class="stack"><div class="paper"><div class="row between"><h2>'+h.name+' <small>Lv. '+v.level+'</small></h2>'+badge(ELEMENTS[h.element]+' · '+h.weapon,'teal')+'</div><div class="stats">'+Object.entries(stats).map(([k,n])=>'<div class="stat"><small>'+k.toUpperCase()+'</small><strong>'+fmt(n)+'</strong></div>').join('')+'</div><p class="costs">'+costs(cost)+'</p><div class="row" style="margin-top:12px">'+[1,5,399].map(n=>btn('level',n===399?'가능한 만큼':'+ '+n,{hero:id,count:n},n===1?'primary':'secondary',v.level>=400||s.wallets.xp<cost.xp||s.wallets.gold<cost.gold)).join('')+'</div></div>'+
 '<div class="paper"><div class="section-title"><h3>장비 손질</h3><small class="muted">실패 없는 강화</small></div>'+slots.map(([slot,name,sub])=>{const level=v.gear[slot],c=gearCost(level),locked=slot==='accessory'&&totalStage(s)<20,labels=slot==='weapon'?['기본 공격 강화','기술 피해 강화']:slot==='armor'?['생명력','단단한 방어']:['마나 순환','치명타 피해'];return '<div class="gear-row"><div><h4>'+name+' <span class="muted">+'+level+'</span></h4><p class="muted">'+sub+'</p><div class="costs">'+costs(c)+'</div></div>'+btn('gear',locked?'합계 20':'강화 +1',{hero:id,slot,count:1},'secondary',locked||level>=100||Object.entries(c).some(([k,n])=>s.wallets[k]<n))+(level>=5?'<div class="options" style="grid-column:1/-1">'+labels.map((name,i)=>btn('gearChoice',name,{hero:id,slot,value:i},v.gearChoices[slot]===i?'selected':'')).join('')+'</div>':'')+'</div>';}).join('')+'<p class="small muted section">강화 5에 효과 선택 · 15/30에 효과 증가. 10% 대성공은 광석 절반을 돌려줘요.</p></div>'+
 '<div class="paper"><div class="row between"><h3>숙련 '+v.nodes+' / 60</h3>'+btn('mastery','숙련 열기',{hero:id},'primary',v.nodes>=60||v.training<nc)+'</div><p class="small muted">훈련점 '+fmt(v.training)+' / '+nc+' · 원정으로 시간당 1점</p>'+progress(v.training,nc,'다음 숙련')+'<div class="options">'+STYLES[id].map((name,i)=>btn('style',name,{hero:id,value:i},v.style===i?'selected':'',v.nodes<2)).join('')+'</div><p class="small muted">스타일 2 · 고유 운용 6/12/20에 확장</p></div></div>'+
 '<div class="stack"><div class="paper"><h3>지원 동료</h3><p class="small muted">동료는 한 영웅에게만 배속돼요. 이동할 때 서로 자리를 바꿔요.</p><div class="row section">'+v.companions.map((c,i)=>btn('assignDialog',(c?art(c,'avatar',COMPANION[c].name):icon('star'))+'<span><strong>'+(c?COMPANION[c].name:'빈 지원 '+(i+1))+'</strong><small>'+(i===1&&totalStage(s)<15?'원정 합계 15에 개방':'편성 변경')+'</small></span>',{hero:id,slot:i},'support-slot',i===1&&totalStage(s)<15)).join('')+'</div><div class="section"><h4>유물</h4>'+btn('equipDialog',v.artifact?ARTIFACTS.find(a=>a.id===v.artifact).name+' · '+s.artifacts[v.artifact]+'등급':'유물 선택',{hero:id},'secondary wide',totalStage(s)<30)+'</div></div>'+
 '<div class="paper"><h3>전술</h3><div class="options">'+[['standard','기본'],['survival','생존 우선'],['burst','집중 공격']].map(([p,n])=>btn('tacticsPreset',n,{hero:id,preset:p},v.tactics.preset===p?'selected':'')).join('')+'</div><label class="settings-row"><span>적 방어 구간의 공격 보류<small>최대 4초 · 제한 5초 전에는 즉시 사용</small></span><input type="checkbox" data-setting="hold" '+(v.tactics.hold?'checked':'')+'></label><div class="section"><h4>기술 우선순위</h4><p class="small muted">아래 기술을 눌러 맨 앞으로 이동</p><div class="options">'+(v.tactics.order.length?v.tactics.order:h.skills.map(x=>x.id)).map(skillId=>{const skill=h.skills.find(x=>x.id===skillId);return btn('skillFirst',skill.name,{hero:id,skill:skillId});}).join('')+'</div></div><div class="section"><h4>용도별 편성 기록</h4>'+['expedition','boss','adventure'].map((slot,i)=>'<div class="row between small"><span>'+['원정','보스','모험'][i]+'</span><span>'+btn('savePreset','저장',{hero:id,slot},'quiet')+btn('loadPreset','불러오기',{hero:id,slot},'quiet',!v.presets[slot])+'</span></div>').join('')+'</div></div>'+
 '<div class="paper"><h3>고유 기술</h3><p class="small muted section">'+h.passive+'</p><div class="skills section">'+h.skills.map(sk=>'<div class="skill-row"><h4>'+sk.name+' '+badge(sk.p&&sk.m?'혼합':sk.p?'물리':sk.m?'마법':'보조')+'</h4><small>MP '+sk.mp+' · '+sk.cd+'초'+(sk.p||sk.m?' · 물리 '+(sk.p||0)+' / 마법 '+(sk.m||0)+'배':'')+'</small><p>'+esc(sk.effect||'피해를 주는 공격 기술')+'</p></div>').join('')+'</div></div></div></section>';
}
function bond(s,ui){
 const id=s.ui.hero,v=s.heroes[id],next=BOND_THRESHOLDS.find(x=>x>v.bond),mode=ui.bondMode||'hero';
 return header('함께한 시간','천천히 쌓이는 신뢰, 언제든 다시 읽을 이야기.')+'<div class="segmented">'+[['hero','영웅과 대화'],['special','특별한 기록'],['season','저녁의 이야기']].map(([id,n])=>btn('bondMode',n,{mode:id},mode===id?'selected':'')).join('')+'</div>'+
 (mode==='special'?'<p class="notice">트라우마는 시간의마술사의 같은 기록을 공유하는 변주예요. 루나와 자스민의 공동 기억도 새 전투 인원으로 추가되지 않아요.</p>'+sceneList(s,SCENES.filter(c=>c.category==='special')):mode==='season'?'<p class="notice">시즌 활동 1·7·14·21일에 한 장씩 열립니다. 열린 이야기는 시즌이 지나도 남아 있어요.</p>'+sceneList(s,SCENES.filter(c=>c.category==='season')):heroSelector(s)+
 '<div class="columns section"><div><div class="bond-portrait" data-action="viewer" data-art="'+id+'" role="button" tabindex="0" aria-label="'+HERO[id].name+' 그림 전체 보기">'+art(id,'scene')+'</div><div class="bond-meter"><div class="row between"><h3>'+HERO[id].name+'과의 관계</h3><strong>'+fmt(v.bond)+'</strong></div>'+progress(v.bond,next||1200,'다음 이야기')+'<p class="small muted" style="margin-top:9px">'+(next?'다음 이야기까지 '+fmt(next-v.bond)+'점':'모든 주역 이야기를 열었어요')+'</p><div class="row section">'+btn('interactDialog','이야기 나누기 +12',{hero:id},'primary',s.calendar.interactionCharges<1)+btn('gift','선물 +4',{hero:id},'secondary',s.wallets.gifts<1)+'</div><p class="small muted" style="margin-top:10px">교류 '+s.calendar.interactionCharges+' / 2 · 선물 '+s.wallets.gifts+' / 6<br>원정으로 시간당 0.25점이 쌓여요.</p></div></div><div>'+sceneList(s,SCENES.filter(c=>c.category==='hero'&&c.actors.includes(id)))+'</div></div>');
}
function collection(s,ui){
 const mode=ui.collectionMode||'companion',mem=mode==='memory';
 const base=header('동행의 앨범','수집은 새로운 조합과 이야기로 이어져요.',btn('season',icon('star')+' 시즌',{},'secondary'))+
 '<div class="segmented">'+[['companion','동료'],['memory','기억'],['album','감상 앨범']].map(([id,n])=>btn('collectionMode',n,{mode:id},mode===id?'selected':'')).join('')+'</div>';
 if(mode==='album')return base+'<div class="album-records">'+badge('다섯 원정 기록 '+s.decor.filter(x=>x.startsWith('chapter-')).length,'teal')+badge('연구 인장 '+s.wallets.decorTokens,'gold')+(s.decor.some(x=>x.startsWith('astea-'))?badge('아스테아 완전 기록','gold'):'')+'</div>'+'<p class="notice">모든 기억은 전투력에 영향을 주지 않아요. 가로 공동 장면은 두 인물이 보이는 원본 구도로 감상할 수 있어요.</p><div class="collection-grid memory-grid section">'+MEMORIES.map(m=>memoryCard(s,m)).join('')+'</div><div class="audio-player">'+btn('audio',icon('play'),{},'icon-button',true)+'<p>대표곡 감상 <span class="badge">제작 중</span><br><small class="muted">음악 파일은 아직 준비되지 않았어요.</small></p></div>'+btn('learningReview','학습 기록 · 오답 '+s.learning.mistakes.length+'개',{},'quiet');
 const pending=s.gacha.batches.find(b=>!b.revealed),threshold=mem?60:30,pool=mem?'memory':'companion',tickets=s.wallets[pool+'Tickets'],count=s.gacha.counts[pool],owned=mem?s.memories.length:Object.values(s.companions).filter(c=>c.owned).length;
 return base+(pending?'<div class="arrival">'+icon('star')+'<p>아직 펼치지 않은 소환 결과가 있어요.</p>'+btn('resumeSummon','이어서 보기',{batch:pending.id},'quiet')+'</div>':'')+
 '<section class="summon-banner"><span class="eyebrow" style="color:#cebc96">'+(mem?'Moments to keep':'Companions on your journey')+'</span><h2>'+(mem?'시간이 남긴 한 장면':'새로운 별과 만나기')+'</h2><p>'+(mem?'수집한 기억은 홈과 앨범에. '+(seasonActive(s)?'현재 시즌의 두 기억도 함께 열려 있어요.':'지금은 상시 기억을 만나는 아카이브 기간이에요.'):'24명의 동료가 서로 다른 방식으로 곁을 지켜요.')+'</p><div class="row between"><strong>'+(mem?'기억권':'동료권')+' '+fmt(tickets)+'</strong><small>선택까지 '+count%threshold+' / '+threshold+'</small></div>'+progress(count%threshold,threshold,'누적 선택권')+'<div class="row">'+btn('summon','1회',{pool,count:1},'secondary',tickets<1)+btn('summon','10회 펼치기',{pool,count:10},'primary',tickets<10)+btn('summon','보유권 사용',{pool,count:Math.min(100,tickets)},'secondary',tickets<1)+'</div><div class="row between" style="margin-top:14px"><small>보유 '+owned+' / '+(mem?15:24)+'</small>'+btn('probabilities','확률과 선택 보장',{pool},'quiet',false).replace('class="quiet"','class="quiet" style="color:#dfd6c1"')+'</div></section>'+
 '<div class="row between section-title"><h3>지정해서 만나기</h3><small class="muted">'+(mem?'기억가루 '+fmt(s.wallets.memoryDust):'인연토큰 '+fmt(s.wallets.bondTokens))+' · 선택권 '+s.wallets[pool+'Selectors']+'</small></div>'+
 (mem?'<div class="collection-grid memory-grid">'+MEMORIES.map(m=>memoryCard(s,m,true)).join('')+'</div>':'<div class="collection-grid">'+COMPANIONS.map(c=>'<button class="collect-card '+(!s.companions[c.id].owned?'unowned':'')+'" data-action="companion" data-companion="'+c.id+'">'+art(c.id,'avatar',c.name)+badge(s.companions[c.id].owned?'보유 · '+s.companions[c.id].rank+'등급':'미보유',s.companions[c.id].owned?'teal':'lock')+'<span class="card-copy"><strong>'+c.name+'</strong><small>'+ELEMENTS[c.canonicalElement]+' · 지원 '+c.cooldown+'초</small></span></button>').join('')+'</div>')+
 (!mem&&Object.values(s.companions).every(c=>c.owned)&&s.wallets.companionSelectors?btn('selectorTokens','남은 동료 선택권 → 인연토큰 120',{},'secondary section'):'');
}
function memoryCard(s,m,details=false){const owned=s.memories.includes(m.id);return '<button class="collect-card '+(owned?'':'unowned ')+(landscape(m.id)?'shared':'')+'" data-action="memory" data-memory="'+m.id+'">'+art(m.id,'memory',m.name)+badge(owned?'보유':m.type==='bond'?'관계 이야기':m.type==='special'?'특별한 기록':m.acquisition==='season_track_240'?'시즌 240점':'미보유',owned?'teal':'lock')+'<span class="card-copy"><strong>'+m.name+'</strong><small>'+(owned?'전체 그림 보기':poolMemories(s).includes(m.id)?'소환 · 기억가루 200 · 선택권':'해금 조건 보기')+'</small></span></button>';}
function bosses(s){
 return heroSelector(s)+'<div class="boss-grid section">'+BOSSES.map(b=>{const rows=s.bossRecords[b.id]||{},tier=Math.min(50,Math.max(0,...Object.keys(rows).filter(t=>rows[t].cleared).map(Number))+1),locked=totalStage(s)<b.unlockTotalMedals,score=Object.values(rows[tier]?.heroes||{}).reduce((n,r)=>n+r.score,0);return '<article class="boss-card '+(locked?'locked':'')+'">'+art(b.id,'memory',b.name)+'<div class="boss-copy"><h3>'+b.name+'</h3><small class="muted">'+ELEMENTS[b.element]+' · 티어 '+tier+(b.id==='astea'?' · 합계 '+score.toFixed(2)+'/3.50':'')+'</small><p>'+esc(b.counterplay)+'</p>'+btn('bossInfo',locked?'원정 합계 '+b.unlockTotalMedals:'패턴과 도전',{boss:b.id,tier},'primary',locked)+(Object.values(rows).some(r=>r.cleared)?btn('research','흔적 연구 ('+s.wallets.researchPermits+'장)',{boss:b.id},'quiet wide',s.wallets.researchPermits<1):'')+'</div></article>';}).join('')+'</div><div class="section"><div class="section-title"><h3>관문에서 남은 유물</h3><small class="muted">원정 합계 30에 제작</small></div><div class="artifact-list">'+ARTIFACTS.map(a=>{const rank=s.artifacts[a.id],cost=rank===0?12:[20,35,55,80][rank-1];return '<article class="artifact"><div class="row between"><h4>'+a.name+'</h4>'+badge(rank?'등급 '+rank:'미보유',rank?'teal':'lock')+'</div><p>'+a.effect+'</p><div class="row between"><small class="muted">흔적 '+fmt(s.bossTraces[a.bossId]||0)+(rank<5?' / '+cost:'')+'</small>'+btn(rank===5?'traceDecor':'artifact',rank===5?'장식 교환':rank?'승급':'제작',{artifact:a.id,boss:a.bossId},'secondary',totalStage(s)<30||(s.bossTraces[a.bossId]||0)<(rank===5?20:cost))+'</div></article>';}).join('')+'</div></div>';
}
const eventText={signpost:'서로 다른 방향을 가리키는 오래된 표식. 지도를 펴보니 느리지만 안전한 길과 좁은 지름길이 보인다.',rest:'바람이 닿지 않는 낮은 벽 뒤에 잠시 몸을 기댄다. 지금의 쉼을 체력에 쓸지, 다음 마법을 위해 쓸지 고른다.',maintenance:'전투의 흔적을 살피며 장비를 내려놓았다. 손질할 시간은 짧지만 한 가지는 확실히 준비할 수 있다.',record:'앞서 지나간 이가 남긴 짧은 기록이다. 작은 글씨 아래에는 움직임을 정리한 도식이 남아 있다.',fork:'완만하게 도는 길과 거친 돌을 넘어가는 길. 멀리 보이는 작은 보관함은 험한 길에 놓여 있다.',chest:'쓰러진 기둥 아래 상자를 발견했다. 꼭 쥐고 있던 손을 풀고 쉬어갈 수도 있다.',spirit:'희미한 빛이 돌 틈에서 고요하게 맴돈다. 조용히 지나가거나, 조금의 기운을 나눌 수 있을 것 같다.',stage:'지금은 비어 있는 작은 무대. 바닥의 발자국을 기록할지, 이 공간에서 몸을 풀지 잠시 생각한다.',rain:'빗소리가 회랑을 채운다. 처마 아래는 편안하고, 젖은 길 너머로는 다음 관문이 보인다.',suggestion:'동료가 다음 길을 보며 손짓한다. 다른 관점에서 건넨 두 제안 중 하나를 이번 전투에 담는다.',trace:'벽에 남은 큰 흔적이 마지막 상대의 움직임을 알려준다. 지킬 곳과 노릴 곳이 하나씩 보인다.',vista:'갈림길 끝에서 넓은 하늘이 열렸다. 오늘 걸어온 길이 한눈에 들어온다. 이 풍경은 모험 기록에 남을 것이다.'};
function adventureView(s){
 if(totalStage(s)<60)return '<div class="paper empty">'+icon('path')+'<h2>조금 더 멀어진 뒤에</h2><p>다섯 원정 합계 60단계에서 작은 모험이 열려요.<br>현재 '+totalStage(s)+' / 60</p></div>';
 const r=s.adventure,slots=s.adventureSlots[Math.floor(relativeDay(s)/7)]||[],done=slots.filter(x=>x.cleared).length;
 if(!r||r.finished||r.failed)return heroSelector(s)+'<div class="ink-panel section"><span class="eyebrow" style="color:#d2bf99">Eight steps, a new story</span><h2 style="margin:5px 0 12px">준비된 힘보다,<br>고르는 길이 중요할 때.</h2><p class="small muted">레벨 50 · 장비 +20 · 숙련 스탯 6으로 맞춰져요.<br>실제 보유 동료와 해금한 운용으로 여덟 노드를 지나갑니다.</p><div class="section row between"><span>이번 주 보상 '+done+' / 3</span>'+btn('adventureStart',r?.failed?'같은 길 다시 걷기':done>=3?'연습 모험 시작':'모험 시작',{hero:s.ui.hero},'primary')+'</div></div>'+decorStore(s);
 const selected=eventFor(r),battle=[1,3,5,8].includes(r.node);
 return '<div class="row between"><h2>'+HERO[r.heroId].name+'의 여정</h2>'+badge(r.practice?'연습 · 배지 없음':'보상 모험 '+(r.slot+1),'gold')+'</div><div class="map-path">'+Array.from({length:8},(_,i)=>'<span class="map-node '+(i+1===r.node?'current':i+1<r.node?'done':'')+'">'+([1,3,5,8].includes(i+1)?icon(i===7?'hero':'path','sm'):icon('book','sm'))+'</span>').join('')+'</div><div class="row between small"><span>남은 HP '+Math.round(r.hpRatio*100)+'%</span><span>노드 '+r.node+' / 8</span></div>'+progress(r.hpRatio,1,'모험 체력','hp')+
 (r.offer.length?'<section class="event-scene section"><h2>길 위에서 만난 힘</h2><p>이번 모험 동안 곁에 둘 유물을 하나 골라주세요.</p><div class="event-choices">'+r.offer.map(id=>btn('adventureRelic','<strong>'+TEMP_RELICS[id].name+'</strong><small>'+TEMP_RELICS[id].effect+'</small>',{item:id},'event-choice')).join('')+'</div></section>':battle?'<section class="event-scene section"><span class="eyebrow">Node '+r.node+'</span><h2>'+(r.node===8?'마지막 시험':'다음 길을 지키는 정령')+'</h2><p>이 길에서 고른 힘을 모아, 한 걸음 더 나아갑니다.</p>'+btn('adventureBattle','전투 관전 '+icon('arrow'),{},'primary')+'</section>':'<section class="event-scene section"><span class="eyebrow">A moment on the path</span><h2>'+selected.name+'</h2><p>'+eventText[selected.id]+'</p><div class="event-choices">'+selected.choices.map((c,i)=>btn('adventureEvent','<strong>'+c.label+'</strong><small>'+c.effect+'</small>',{choice:i},'event-choice')).join('')+'</div></section>')+
 '<section class="section"><h3>이번 길의 유물</h3><div class="row section">'+r.items.map(id=>badge(TEMP_RELICS[id].name,'teal')).join('')+(r.items.length?'':'<p class="small muted">첫 전투 뒤에 만날 수 있어요.</p>')+'</div></section>'+btn('adventureAbandon','모험을 마치고 돌아가기',{},'quiet section');
}
function decorStore(s){return '<section class="section"><h3>거점에 남길 작은 기념</h3><p class="small muted">탐험배지 '+s.wallets.adventureBadges+'개 · 주간 활동 2/4/6일에도 받을 수 있어요.</p><div class="row section">'+[['frame','초상 테두리',6],['desk','거점 소품',12],['album','앨범 장식',18]].map(([id,name,cost])=>btn('buyDecor',name+' · '+cost,{item:id},'secondary',s.decor.includes(id)||s.wallets.adventureBadges<cost)).join('')+'</div></section>';}
export function seasonView(s){
 const day=relativeDay(s),occ=occurrence(s),points=s.calendar.seasonPoints[occ]||0,w=s.calendar.weeks[Math.floor(day/7)]||{days:0},end=(s.epochDay+(occ+1)*28)*DAY-4*HOUR,formatDate=ms=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',hour:'numeric',hour12:false}).format(ms),rewards=['프로필 장식','인연토큰 20','기억가루 20','홈 배경','인연토큰 40','기억가루 40','루미와 은하고래 · 저녁의 기록'];
 return '<span class="eyebrow">'+(occ===0?'Season 01':occ>=4?'Season 01 · 복각':'Archive interval')+'</span><h2 style="margin-top:5px">'+(seasonActive(s)?season.name:'추억을 다시 펼치는 시간')+'</h2><p class="small muted">'+formatDate(end)+' 종료 · 한국·일본 시간 매일 05:00 갱신</p><div class="section">'+art('s01_lumi_whale','memory',season.name)+'</div><div class="week-stars">'+Array.from({length:7},(_,i)=>'<span class="'+(i<w.days?'lit':'')+'">✦<small>'+(i===1||i===3||i===5?'기억권 +3':i+1+'일')+'</small></span>').join('')+'</div><p class="small muted">이번 주 활동 '+w.days+' / 7일. 연속 출석이 아니라 누적한 날을 셉니다.</p><div class="paper section"><h3>오늘의 시간</h3><p class="small muted">접속 · 수령 · 정비를 하면 하루가 기록돼요. 소환은 필요 없어요.</p><div class="row section">'+[['login','돌아오기'],['claim','원정 수령'],['maintain','훈련·전투·정비']].map(([id,n])=>badge((s.calendar.bits.includes(id)?'✓ ':'')+n,s.calendar.bits.includes(id)?'teal':'lock')).join('')+'</div>'+btn('maintain','장비를 살피고 오늘 기록하기',{},'secondary wide section')+'</div><div class="section"><h3>'+points+' / 240 별빛</h3>'+progress(points,240,'시즌 트랙','gold')+season.trackRewardPointThresholds.map((n,i)=>'<div class="track-row '+(points>=n?'completed':'')+'"><strong>'+n+'</strong><span>'+rewards[i]+'</span>'+badge(points>=n?'지급됨':'활동 '+n/10+'일',points>=n?'teal':'lock')+'</div>').join('')+'</div><p class="notice section">28일 중 24일 활동으로 마지막 그림. 하루 쉬어도 기본 활동 기억권으로 누적 선택 2번에 도달할 수 있어요. 다음 세 주기는 상시 아카이브, 다섯 번째 주기부터 이 시즌이 복각됩니다. 복각 그림 중복은 기억가루로 바뀌어요.</p>';
}
