const VOCAB_SOURCE = [
    { w: 'amenities', m: '(명) 편의시설; (명) 예의, 기품', tm: '(명) 적, 앙숙; (명) 반대 세력', tw: 'enemies' },
    { w: 'banquet', m: '(명) 연회, 만찬', tm: '(명) 꽃다발; (명) 칭찬하는 말', tw: 'bouquet' },
    { w: 'reserve', m: '(동) 예약하다; (동) 보유하다', tm: '(동) 뒤집다; (동) 후진하다', tw: 'reverse' },
    { w: 'revenue', m: '(명) 수익, 수입; (명) 세입', tm: '(명) 장소, 개최지; (명) 현장', tw: 'venue' },
    { w: 'decline', m: '(동) 감소하다; (동) 거절하다', tm: '(동) 비스듬히 눕다; (동) (의자를) 젖히다', tw: 'recline' },
    { w: 'experiment', m: '(명) 실험; (동) 실험하다', tm: '(명) 경험, 경력; (동) 겪다', tw: 'experience' },
    { w: 'renowned', m: '(형) 유명한, 명성 있는', tm: '(형) 갱신된; (형) 재개된, 새로워진', tw: 'renewed' },
    { w: 'enhance', m: '(동) 향상시키다; (동) 강화하다', tm: '(동) 매혹하다; (동) 마법을 걸다', tw: 'enchant' },
    { w: 'premises', m: '(명) 건물과 토지, 부지', tm: '(명) 약속, 서약; (명) 장래성', tw: 'promise' },
    { w: 'relevant', m: '(형) 관련 있는; (형) 적절한', tm: '(명) 친척; (형) 비교상의, 상대적인', tw: 'relative' },
    { w: 'portable', m: '(형) 휴대할 수 있는', tm: '(형) 마셔도 되는, 식수로 적합한', tw: 'potable' },
    { w: 'refuse', m: '(동) 거절하다; (명) 쓰레기', tm: '(명) 피난처, 은신처; (명) 보호', tw: 'refuge' },
    { w: 'tenant', m: '(명) 임차인, 세입자', tm: '(명) 교리, 주의; (명) 원칙', tw: 'tenet' },
    { w: 'expense', m: '(명) 비용, 지출', tm: '(명) 넓게 트인 지역; (명) 팽창', tw: 'expanse' },
    { w: 'flaw', m: '(명) 결함, 흠', tm: '(명) 흐름; (동) 흐르다', tw: 'flow' },
    { w: 'destination', m: '(명) 목적지, 행선지', tm: '(명) 운명, 숙명', tw: 'destiny' },
    { w: 'district', m: '(명) 구역, 지역', tm: '(형) 뚜렷한, 분명한; (형) 별개의', tw: 'distinct' },
    { w: 'inclement', m: '(형) (날씨가) 궂은, 혹독한', tm: '(명) 증가, 인상; (명) 이익', tw: 'increment' },
    { w: 'exclusively', m: '(부) 단독으로, 오로지', tm: '(부) 지나치게, 과도하게', tw: 'excessively' },
    { w: 'convert', m: '(동) 변환하다; (동) 개종하다', tm: '(형) 비밀의, 은밀한; (명) 은신처', tw: 'covert' },
    { w: 'curb', m: '(동) 억제하다; (명) 제한', tm: '(명) 곡선, 커브; (동) 구부리다', tw: 'curve' },
    { w: 'deduct', m: '(동) 공제하다, 차감하다', tm: '(동) 추론하다, 연역하다', tw: 'deduce' },
    { w: 'repair', m: '(동) 수리하다; (명) 수리', tm: '(동) 손상시키다, 해치다', tw: 'impair' },
    { w: 'emphasis', m: '(명) 강조, 주안점', tm: '(명) 공감, 감정이입', tw: 'empathy' },
    { w: 'popular', m: '(형) 인기 있는; (형) 대중의', tm: '(형) 인구가 많은; (형) 붐비는', tw: 'populous' },
    { w: 'transfer', m: '(동) 이동하다; (동) 전근하다', tm: '(동) 변형시키다; (동) 성질을 바꾸다', tw: 'transform' },
    { w: 'estimate', m: '(동) 추산하다; (명) 견적서', tm: '(동) 존경하다; (명) 존경, 존중', tw: 'esteem' },
    { w: 'laboratory', m: '(명) 실험실, 연구소', tm: '(명) 화장실, 세면장', tw: 'lavatory' },
    { w: 'expire', m: '(동) 만료되다, 끝나다', tm: '(동) 고무하다, 영감을 주다', tw: 'inspire' },
    { w: 'consent', m: '(명) 동의, 허락; (동) 동의하다', tm: '(명) 내용물, 목차; (형) 만족하는', tw: 'content' },
    { w: 'retail', m: '(명) 소매; (형) 소매의', tm: '(명) 세부사항; (동) 상세히 알리다', tw: 'detail' },
    { w: 'affordable', m: '(형) 가격이 알맞은; (형) 감당할 수 있는', tm: '(형) 사랑스러운; (형) 귀여운', tw: 'adorable' },
    { w: 'valid', m: '(형) 유효한; (형) 타당한', tm: '(형) 고체의, 단단한; (형) 견고한', tw: 'solid' },
    { w: 'traffic', m: '(명) 교통(량); (명) 왕래', tm: '(형) 아주 멋진; (형) 훌륭한', tw: 'terrific' },
    { w: 'imperative', m: '(형) 필수적인; (형) 긴급한', tm: '(형) 제국의; (형) 황제의', tw: 'imperial' },
    { w: 'insurance', m: '(명) 보험; (명) 보험금', tm: '(명) 확언, 장담; (명) 보증', tw: 'assurance' },
    { w: 'ingredient', m: '(명) 재료, 성분', tm: '(명) 경사도; (명) 기울기, 비탈', tw: 'gradient' },
    { w: 'renovate', m: '(동) 개조하다, 보수하다', tm: '(동) 혁신하다; (동) 쇄신하다', tw: 'innovate' },
    { w: 'versatile', m: '(형) 다재다능한; (형) 다용도의', tm: '(형) 휘발성의; (형) 변덕스러운', tw: 'volatile' },
    { w: 'implement', m: '(동) 실행하다; (명) 도구', tm: '(동) 보충하다; (명) 부록', tw: 'supplement' },
    { w: 'commitment', m: '(명) 헌신; (명) 약속, 책무', tm: '(명) 위원회; (명) 위원', tw: 'committee' },
    { w: 'facilitate', m: '(동) 용이하게 하다; (동) 촉진하다', tm: '(동) 매혹하다; (동) 마음을 사로잡다', tw: 'fascinate' },
    { w: 'encourage', m: '(동) 격려하다; (동) 권장하다', tm: '(동) 격분하게 하다; (동) 화나게 하다', tw: 'enrage' },
    { w: 'persuade', m: '(동) 설득하다', tm: '(동) 추구하다; (동) 뒤쫓다', tw: 'pursue' },
    { w: 'launch', m: '(동) 출시하다; (동) 시작하다', tm: '(명) 점심 식사; (동) 점심을 먹다', tw: 'lunch' },
    { w: 'reliable', m: '(형) 믿을 수 있는; (형) 확실한', tm: '(형) 법적 책임이 있는; (형) ~하기 쉬운', tw: 'liable' },
    { w: 'strategy', m: '(명) 전략, 계획', tm: '(명) 비극; (명) 참사', tw: 'tragedy' },
    { w: 'remind', m: '(동) 상기시키다; (동) 생각나게 하다', tm: '(동) 되감다; (동) 다시 감다', tw: 'rewind' },
    { w: 'suitable', m: '(형) 적합한, 알맞은', tm: '(형) 안정적인; (형) 차분한', tw: 'stable' },
    { w: 'beverage', m: '(명) 음료', tm: '(형) 평균의; (명) 평균', tw: 'average' },
    { w: 'tentative', m: '(형) 잠정적인, 임시의', tm: '(형) 주의 깊은; (형) 세심한', tw: 'attentive' },
    { w: 'publicity', m: '(명) 홍보, 광고; (명) 평판', tm: '(명) 출판, 발행; (명) 출판물', tw: 'publication' },
    { w: 'procedure', m: '(명) 절차, 순서', tm: '(명) 제작자, PD; (명) 생산자', tw: 'producer' },
    { w: 'merchandise', m: '(명) 상품, 물품', tm: '(명) 상인, 무역상', tw: 'merchant' },
    { w: 'guarantee', m: '(명) 보증; (동) 보장하다', tm: '(명) 격리; (동) 격리하다', tw: 'quarantine' },
    { w: 'alleviate', m: '(동) 완화하다; (동) 경감하다', tm: '(동) (들어) 올리다; (동) 승진시키다', tw: 'elevate' },
    { w: 'solicit', m: '(동) 요청하다; (동) 간청하다', tm: '(형) 불법의; (형) 사회 통념에 어긋나는', tw: 'illicit' },
    { w: 'unprecedented', m: '(형) 전례 없는', tm: '(형) 예측할 수 없는; (형) 종잡을 수 없는', tw: 'unpredictable' },
    { w: 'deny', m: '(동) 부인하다; (동) 거절하다', tm: '(동) 반항하다; (동) 무시하다', tw: 'defy' },
    { w: 'recession', m: '(명) 불경기, 침체', tm: '(명) 접수처; (명) 환영회', tw: 'reception' },
    { w: 'grant', m: '(동) 승인하다; (동) 수여하다', tm: '(형) 웅장한; (형) 원대한', tw: 'grand' },
    { w: 'refund', m: '(명) 환불; (동) 환불하다', tm: '(동) 다시 튀어 오르다; (명) 반등', tw: 'rebound' },
    { w: 'opportunity', m: '(명) 기회; (명) 호기', tm: '(명) 반대; (명) 저항, 대립', tw: 'opposition' },
    { w: 'confidential', m: '(형) 기밀의; (형) 비밀의', tm: '(명) 자격 증명서; (명) 신임장', tw: 'credential' },
    { w: 'outstanding', m: '(형) 미해결의; (형) 뛰어난', tm: '(형) 외향적인, 사교적인; (형) 떠나가는', tw: 'outgoing' },
    { w: 'process', m: '(명) 과정, 절차; (동) 처리하다', tm: '(동) 소유하다; (동) 사로잡다', tw: 'possess' },
    { w: 'simply', m: '(부) 단순히; (부) 그저', tm: '(부) 충분히; (부) 상세하게', tw: 'amply' },
    { w: 'presence', m: '(명) 존재; (명) 참석', tm: '(명) 선호(도); (명) 애호', tw: 'preference' },
    { w: 'effective', m: '(형) 효과적인; (형) 유효한', tm: '(형) 정서적인; (형) 감정의', tw: 'affective' },
    { w: 'spacious', m: '(형) 넓은; (형) 훤히 트인', tm: '(형) 그럴듯한; (형) 겉만 번지르르한', tw: 'specious' },
    { w: 'withdraw', m: '(동) 철회하다; (동) 인출하다', tm: '(동) 견뎌내다; (동) 저항하다', tw: 'withstand' },
    { w: 'specific', m: '(형) 구체적인; (형) 특정한', tm: '(형) 평화로운; (형) 태평양의', tw: 'pacific' },
    { w: 'specialize', m: '(동) 전문화하다; (동) 특수화하다', tm: '(동) 교제하다; (동) 어울리다', tw: 'socialize' },
    { w: 'equip', m: '(동) 장비를 갖추다; (동) 채비를 하다', tm: '(명) 재치 있는 말; (명) 빈정거림', tw: 'quip' },
    { w: 'reimbursement', m: '(명) 변제, 상환; (명) 배상', tm: '(명) 지불, 지출; (명) 자금 집행', tw: 'disbursement' },
    { w: 'informed', m: '(형) 정보통인; (형) 유식한', tm: '(형) 허약한; (형) 병약한', tw: 'infirm' },
    { w: 'direct', m: '(형) 직접적인; (동) 지시하다', tm: '(동) 발견하다; (동) 감지하다', tw: 'detect' },
    { w: 'cover', m: '(동) 덮다; (동) 포함하다', tm: '(동) 맴돌다; (동) 공중 정지하다', tw: 'hover' },
    { w: 'accompany', m: '(동) 동행하다; (동) 동반하다', tm: '(동) 성취하다; (동) 완수하다', tw: 'accomplish' },
    { w: 'motivate', m: '(동) 동기부여하다; (동) 자극하다', tm: '(동) 경작하다; (동) 재배하다', tw: 'cultivate' },
    { w: 'consider', m: '(동) 고려하다; (동) 숙고하다', tm: '(동) 인정하다; (동) 양보하다', tw: 'concede' },
    { w: 'arrange', m: '(동) 정리하다; (동) 마련하다', tm: '(동) 어지럽히다; (동) 미치게 하다', tw: 'derange' },
    { w: 'associate', m: '(동) 연관짓다; (동) 교제하다', tm: '(동) 옹호하다; (명) 지지자', tw: 'advocate' },
    { w: 'instructor', m: '(명) 강사; (명) 지도자', tm: '(명) 건설자; (명) 시공자', tw: 'constructor' },
    { w: 'weekly', m: '(형) 매주의; (부) 매주', tm: '(부) 약하게; (부) 힘없이', tw: 'weakly' },
    { w: 'reveal', m: '(동) 드러내다; (동) 폭로하다', tm: '(동) 흥청거리다; (명) 왁자지껄한 파티', tw: 'revel' },
    { w: 'assembly', m: '(명) 조립; (명) 집회', tm: '(명) 닮음; (명) 유사함', tw: 'resemblance' },
    { w: 'overdue', m: '(형) 기한이 지난; (형) 연체된', tm: '(동) 지나치게 하다; (동) 과장하다', tw: 'overdo' },
    { w: 'timely', m: '(형) 시기적절한; (형) 때맞춘', tm: '(부) 소심하게; (부) 겁먹고', tw: 'timidly' },
    { w: 'duty', m: '(명) 의무; (명) 관세', tm: '(부) 적절하게; (부) 절차에 따라', tw: 'duly' },
    { w: 'impose', m: '(동) 부과하다; (동) 강요하다', tm: '(동) 구성하다; (동) 작곡하다', tw: 'compose' },
    { w: 'merger', m: '(명) 합병; (명) 통합', tm: '(형) 빈약한; (형) 결핍된', tw: 'meager' },
    { w: 'demonstration', m: '(명) 시연; (명) 입증', tm: '(명) 파괴; (명) 철거', tw: 'demolition' },
    { w: 'fluctuate', m: '(동) 변동하다; (동) 오르내리다', tm: '(동) 구두점을 찍다; (동) 강조하다', tw: 'punctuate' },
    { w: 'deliver', m: '(동) 배달하다; (동) 연설하다', tm: '(형) 고의적인; (형) 신중한', tw: 'deliberate' },
    { w: 'devoted', m: '(형) 헌신적인; (형) 전념하는', tm: '(동) 강등시키다; (동) 좌천시키다', tw: 'demote' },
    { w: 'stock', m: '(명) 재고; (명) 주식', tm: '(명) (식물의) 줄기, 대; (동) 몰래 접근하다', tw: 'stalk' },
    { w: 'authority', m: '(명) 권한; (명) 당국', tm: '(명) 작가; (명) 저자', tw: 'author' },
    { w: 'variety', m: '(명) 다양성; (명) 품종', tm: '(명) 진실성; (명) 진리', tw: 'verity' },
    { w: 'access', m: '(명) 접근, 이용 권한; (동) 접근하다', tm: '(동) 평가하다; (동) 가늠하다, 재다', tw: 'assess' },
    { w: 'resume', m: '(동) 재개하다; (명) 이력서', tm: '(동) 가정하다; (동) (책임을) 떠맡다', tw: 'assume' },
    { w: 'complementary', m: '(형) 상호보완적인; (형) 보충하는', tm: '(형) 무료의; (형) 칭찬의', tw: 'complimentary' },
    { w: 'inventory', m: '(명) 재고, 재고 목록; (명) 재고 조사', tm: '(명) 발명품; (명) 발명, 창작력', tw: 'invention' },
    { w: 'feature', m: '(명) 특징, 특색; (명) 특집 기사', tm: '(명) 미래, 장래; (형) 미래의', tw: 'future' },
    { w: 'contractor', m: '(명) 계약자, 도급업자', tm: '(명) 수축, 축소; (명) (단어의) 축약형', tw: 'contraction' },
    { w: 'issue', m: '(명) 문제, 이슈; (동) 발행하다', tm: '(명) 조직, 화장지; (동) (휴지로) 닦다', tw: 'tissue' },
    { w: 'eligible', m: '(형) 자격이 있는; (형) 적격의', tm: '(형) 읽기 어려운; (형) 판독이 불가능한', tw: 'illegible' },
    { w: 'confirm', m: '(동) 확인하다; (동) 승인하다', tm: '(동) 따르다, 순응하다; (동) 일치하다', tw: 'conform' },
    { w: 'affect', m: '(동) 영향을 미치다; (명) 정서, 감정', tm: '(명) 효과, 영향; (명) 결과', tw: 'effect' },
    { w: 'attribute', m: '(명) 속성, 특질; (동) ~의 탓으로 돌리다', tm: '(동) 기여하다; (동) 기부하다', tw: 'contribute' },
    { w: 'facility', m: '(명) 시설; (명) 쉬움, 유창함', tm: '(명) 교수진, 교직원; (명) (타고난) 능력', tw: 'faculty' },
    { w: 'appraisal', m: '(명) 평가; (명) 감정', tm: '(명) 승인, 인가; (명) 찬성, 동의', tw: 'approval' },
    { w: 'commission', m: '(명) 수수료; (명) 위원회', tm: '(명) 허락, 허가; (명) 승인', tw: 'permission' },
    { w: 'delinquent', m: '(형) 연체된, 체납된; (형) 태만한', tm: '(형) 성실한, 부지런한; (형) 끈기 있는', tw: 'diligent' },
    { w: 'precede', m: '(동) ~에 앞서다; (동) 선행하다', tm: '(동) 계속하다, 진행하다; (동) 나아가다', tw: 'proceed' },
    { w: 'personal', m: '(형) 개인적인; (형) 사적인', tm: '(명) 직원, 인원; (명) 인사부서', tw: 'personnel' },
    { w: 'extensive', m: '(형) 광범위한; (형) 대규모의', tm: '(형) 비싼, 고가의; (형) 돈이 많이 드는', tw: 'expensive' },
    { w: 'liability', m: '(명) 법적 책임; (명) 부채, 빚', tm: '(명) 능력, 재능; (명) 할 수 있음', tw: 'ability' },
    { w: 'perspective', m: '(명) 관점, 시각; (명) 원근법', tm: '(형) 장래의, 유망한; (형) 예비의', tw: 'prospective' },
    { w: 'stationery', m: '(명) 문구류, 편지지', tm: '(형) 정지된; (형) 움직이지 않는', tw: 'stationary' },
    { w: 'vacation', m: '(명) 휴가, 방학', tm: '(명) 직업, 천직; (명) 소명', tw: 'vocation' },
    { w: 'expand', m: '(동) 확장하다; (동) 팽창하다', tm: '(동) (돈, 시간을) 쓰다; (동) 소비하다', tw: 'expend' },
    { w: 'wander', m: '(동) 돌아다니다; (동) 헤매다', tm: '(동) 궁금해하다; (명) 경이로움', tw: 'wonder' },
    { w: 'principal', m: '(명) 교장, 학장; (형) 주요한, 주된', tm: '(명) 원칙, 원리; (명) 신조', tw: 'principle' },
    { w: 'confident', m: '(형) 자신감 있는; (형) 확신하는', tm: '(형) 기밀의, 비밀의; (형) 신뢰를 요하는', tw: 'confidential' },
    { w: 'diary', m: '(명) 일기, 수첩', tm: '(명) 유제품; (형) 유제품의, 우유의', tw: 'dairy' },
    { w: 'collaborate', m: '(동) 협력하다; (동) 공동 작업하다', tm: '(동) 기념하다, 축하하다; (동) 찬양하다', tw: 'celebrate' },
    { w: 'auditor', m: '(명) 회계 감사관; (명) 청강생', tm: '(명) 오디션; (명) 청력, 청각', tw: 'audition' },
    { w: 'physics', m: '(명) 물리학', tm: '(명) 의사, 내과 의사; (동) 치료하다', tw: 'physician' },
    { w: 'adapt', m: '(동) 적응하다; (동) 각색하다', tm: '(동) 입양하다; (동) 채택하다', tw: 'adopt' },
    { w: 'attitude', m: '(명) 태도, 자세; (명) 사고방식', tm: '(명) 고도, 높이; (명) 해발', tw: 'altitude' },
    { w: 'commute', m: '(동) 통근하다; (동) 감형하다', tm: '(동) 계산하다, 산출하다; (동) 추정하다', tw: 'compute' },
    { w: 'subscription', m: '(명) 구독(료); (명) 기부금', tm: '(명) 처방전; (명) 처방, 규정', tw: 'prescription' },
    { w: 'morale', m: '(명) 사기, 의욕; (명) 기세', tm: '(형) 도덕적인; (명) 교훈', tw: 'moral' },
    { w: 'contact', m: '(명) 연락, 접촉; (동) 연락하다', tm: '(명) 계약, 계약서; (동) 계약하다', tw: 'contract' },
    { w: 'sensitive', m: '(형) 예민한, 민감한; (형) 세심한', tm: '(형) 분별 있는, 합리적인; (형) 실용적인', tw: 'sensible' },
    { w: 'economic', m: '(형) 경제의, 경제학의', tm: '(형) 경제적인; (형) 절약하는, 실속 있는', tw: 'economical' },
    { w: 'conversation', m: '(명) 대화, 회화', tm: '(명) 보존, 보호; (명) (에너지) 절약', tw: 'conservation' },
    { w: 'waive', m: '(동) (권리를) 포기하다; (동) 철회하다', tm: '(동) 손을 흔들다; (명) 파도, 물결', tw: 'wave' },
    { w: 'require', m: '(동) 필요로 하다; (동) 요구하다', tm: '(동) 문의하다, 묻다; (동) 조사하다', tw: 'inquire' },
    { w: 'conscious', m: '(형) 의식하는, 지각 있는; (형) 의도적인', tm: '(형) 양심적인; (형) 성실한, 꼼꼼한', tw: 'conscientious' },
    { w: 'dessert', m: '(명) 디저트, 후식', tm: '(명) 사막; (동) 버리다, 떠나다', tw: 'desert' },
    { w: 'custom', m: '(명) 관습, 풍습; (형) 맞춤의', tm: '(명) 의상, 복장; (명) (무대) 의상', tw: 'costume' },
    { w: 'simultaneous', m: '(형) 동시의; (형) 동시에 일어나는', tm: '(형) 자발적인; (형) 즉흥적인', tw: 'spontaneous' },
    { w: 'object', m: '(명) 물건, 대상; (동) 반대하다', tm: '(명) 주제, 과목; (형) 지배를 받는', tw: 'subject' },
    { w: 'propose', m: '(동) 제안하다; (동) 청혼하다', tm: '(명) 목적, 목표; (명) 용도, 의도', tw: 'purpose' },
    { w: 'allocate', m: '(동) 할당하다, 배분하다', tm: '(동) (위치를) 찾아내다; (동) 위치시키다', tw: 'locate' },
    { w: 'favorable', m: '(형) 호의적인; (형) 유리한', tm: '(형) 가장 좋아하는; (명) 마음에 드는 것', tw: 'favorite' },
    { w: 'bald', m: '(형) 대머리의; (형) 단조로운', tm: '(형) 대담한, 용감한; (형) 굵은(글씨체)', tw: 'bold' },
    { w: 'collision', m: '(명) 충돌, 부딪침; (명) 대립', tm: '(명) 공모, 결탁; (명) 유착', tw: 'collusion' },
    { w: 'valuable', m: '(형) 소중한, 귀중한; (명) 귀중품', tm: '(형) 이용 가능한; (형) 시간이 나는', tw: 'available' },
    { w: 'loose', m: '(형) 헐거운, 풀린; (동) 놓아주다', tm: '(동) 잃어버리다; (동) 지다, 패배하다', tw: 'lose' },
    { w: 'evolution', m: '(명) 진화; (명) 점진적 발전', tm: '(명) 혁명; (명) 갑작스런 변화', tw: 'revolution' },
    { w: 'cooperation', m: '(명) 협력, 협동', tm: '(명) 기업, 회사; (명) 법인', tw: 'corporation' },
    { w: 'through', m: '(전) ~을 통하여; (형) 끝난', tm: '(형) 철저한, 빈틈없는; (형) 완전한', tw: 'thorough' },
    { w: 'assure', m: '(동) 장담하다, 안심시키다', tm: '(동) 보험에 들다; (동) 보장하다', tw: 'insure' },
    { w: 'meditation', m: '(명) 명상, 묵상', tm: '(명) 중재, 조정; (명) 매개', tw: 'mediation' },
    { w: 'notify', m: '(동) 통지하다, 알리다', tm: '(동) 알아차리다, 주목하다; (명) 공고문', tw: 'notice' },
    { w: 'vague', m: '(형) 모호한, 희미한', tm: '(명) 유행; (형) 유행하는', tw: 'vogue' },
    { w: 'account', m: '(명) 계좌; (명) 설명', tm: '(동) 세다; (동) 계산하다', tw: 'count' },
    { w: 'address', m: '(명) 주소; (동) 문제를 다루다', tm: '(명) 의복, 드레스', tw: 'dress' },
    { w: 'attention', m: '(명) 주의, 집중', tm: '(명) 출석; (명) 수행원', tw: 'attendance' },
    { w: 'balance', m: '(명) 균형; (명) 잔액', tm: '(명) 투표용지; (명) 투표', tw: 'ballot' },
    { w: 'charge', m: '(명) 요금; (명) 책임', tm: '(명) 변화; (명) 잔돈', tw: 'change' },
    { w: 'consumer', m: '(명) 소비자', tm: '(명) 의상 제작자; (명) 의상 담당', tw: 'costumer' },
    { w: 'produce', m: '(동) 생산하다; (명) 농산물', tm: '(동) 줄이다, 감소시키다', tw: 'reduce' },
    { w: 'remain', m: '(동) 계속 ~이다; (동) 남아 있다', tm: '(동) 되찾다; (동) 회복하다', tw: 'regain' },
    { w: 'replace', m: '(동) 교체하다, 대신하다', tm: '(동) 위치시키다; (동) 두다', tw: 'place' },
    { w: 'supply', m: '(명) 공급; (동) 공급하다', tm: '(형) 나긋나긋한; (형) 유연한', tw: 'supple' },
    { w: 'executive', m: '(명) 경영진, 임원; (형) 경영의', tm: '(형) 연속적인; (형) 연이은', tw: 'consecutive' },
    { w: 'deposit', m: '(명) 예치금, 보증금; (동) 맡기다', tm: '(명) 창고; (명) (버스/기차) 정류소', tw: 'depot' },
    { w: 'candidate', m: '(명) 후보자, 지원자', tm: '(형) 솔직한; (형) 숨김없는', tw: 'candid' },
    { w: 'fiscal', m: '(형) 재정의, 회계의', tm: '(형) 신체의; (형) 물리적인', tw: 'physical' },
    { w: 'promptly', m: '(부) 지체 없이, 즉시', tm: '(부) 적절하게; (부) 알맞게', tw: 'properly' },
    { w: 'coverage', m: '(명) 보상 범위; (명) 보도', tm: '(명) 용기; (명) 대담함', tw: 'courage' },
    { w: 'policy', m: '(명) 정책, 방침', tm: '(명) 경찰; (명) 치안', tw: 'police' },
    { w: 'manual', m: '(형) 수동의; (명) 안내서', tm: '(형) 매년의; (명) 연감', tw: 'annual' },
    { w: 'obtain', m: '(동) 얻다, 획득하다', tm: '(동) 포함하다; (동) 억제하다', tw: 'contain' },
    { w: 'stagnant', m: '(형) 정체된, 흐르지 않는', tm: '(형) 충격적인; (형) 믿기 어려운', tw: 'staggering' },
    { w: 'tenure', m: '(명) 재임 기간; (명) 종신 재직권', tm: '(명) 취지, 대의; (명) 테너 가수', tw: 'tenor' },
    { w: 'arrival', m: '(명) 도착', tm: '(명) 경쟁자; (명) 라이벌', tw: 'rival' },
    { w: 'pension', m: '(명) 연금', tm: '(명) 긴장; (명) 갈등', tw: 'tension' },
    { w: 'attire', m: '(명) 의복, 옷차림', tm: '(형) 전체의; (형) 온전한', tw: 'entire' },
    { w: 'fatigue', m: '(명) 피로; (동) 피곤하게 하다', tm: '(동) 흥미를 끌다; (명) 음모', tw: 'intrigue' },
    { w: 'surplus', m: '(명) 잉여, 흑자; (형) 과잉의', tm: '(명) 표면; (형) 겉보기의', tw: 'surface' },
    { w: 'predecessor', m: '(명) 전임자; (명) 이전 모델', tm: '(명) 후임자; (명) 계승자', tw: 'successor' },
    { w: 'exquisite', m: '(형) 매우 아름다운; (형) 정교한', tm: '(형) 꼬치꼬치 캐묻는; (형) 탐구적인', tw: 'inquisitive' },
    { w: 'bulk', m: '(명) 대량; (명) 대부분', tm: '(동) 망설이다; (동) 멈칫거리다', tw: 'balk' },
    { w: 'acquire', m: '(동) 얻다, 습득하다', tm: '(동) 묻다, 문의하다; (동) 조사하다', tw: 'inquire' },
    { w: 'compliance', m: '(명) 준수, 따름', tm: '(명) 공모; (명) 연루', tw: 'complicity' },
    { w: 'summary', m: '(명) 요약, 개요', tm: '(명) 정상회담; (명) 산꼭대기', tw: 'summit' },
    { w: 'harvest', m: '(명) 수확물; (동) 수확하다', tm: '(동) 투자하다', tw: 'invest' },
    { w: 'convenience', m: '(명) 편리함; (명) 편의 시설', tm: '(명) 관습; (명) 협약, 회의', tw: 'convention' },
    { w: 'approximately', m: '(부) 대략, 거의', tm: '(부) 적절하게; (부) 알맞게', tw: 'appropriately' },
    { w: 'aid', m: '(명) 도움; (동) 돕다', tm: '(명) 측근, 보좌관', tw: 'aide' },
    { w: 'eliminate', m: '(동) 제거하다; (동) 탈락시키다', tm: '(동) 비추다; (동) 계몽하다', tw: 'illuminate' },
    { w: 'skeptical', m: '(형) 의심 많은; (형) 회의적인', tm: '(동) 추측하다; (동) 투기하다', tw: 'speculate' },
    { w: 'debut', m: '(명) 데뷔, 첫 등장', tm: '(명) 토론, 논쟁; (동) 숙고하다', tw: 'debate' },
    { w: 'suburb', m: '(명) 교외, 근교', tm: '(형) 최고의, 최상의; (형) 대단한', tw: 'superb' },
    { w: 'agenda', m: '(명) 의제, 안건; (명) 비망록', tm: '(명) 대리점; (명) 대행사', tw: 'agency' },
    { w: 'property', m: '(명) 재산, 소유물; (명) 부동산', tm: '(명) 예절; (명) 적절성', tw: 'propriety' },
    { w: 'culinary', m: '(형) 요리의, 음식의', tm: '(형) 예비의; (형) 임시의', tw: 'preliminary' },
    { w: 'significantly', m: '(부) 상당히; (부) 중요하게', tm: '(부) 장엄하게; (부) 훌륭하게', tw: 'magnificently' },
    { w: 'suppose', m: '(동) 가정하다; (동) 추측하다', tm: '(동) 반대하다; (동) 대항하다', tw: 'oppose' },
    { w: 'initiative', m: '(명) 주도권; (명) 진취성', tm: '(명) 직관; (명) 직감', tw: 'intuition' },
    { w: 'figure', m: '(명) 수치; (명) 인물', tm: '(명) 활기, 기력; (명) 정력', tw: 'vigor' },
    { w: 'audience', m: '(명) 청중, 관객', tm: '(명) 동맹, 연합', tw: 'alliance' },
    { w: 'occupy', m: '(동) 차지하다; (동) 점유하다', tm: '(동) 일어나다, 발생하다', tw: 'occur' },
    { w: 'substantial', m: '(형) 상당한; (형) 실질적인', tm: '(형) 지속 가능한', tw: 'sustainable' },
    { w: 'preserve', m: '(동) 보존하다; (동) 지키다', tm: '(동) 인내하다; (동) 꾸준히 계속하다', tw: 'persevere' },
    { w: 'inform', m: '(동) 알리다, 통지하다', tm: '(동) 개혁하다; (동) 개선하다', tw: 'reform' },
    { w: 'essential', m: '(형) 필수적인; (형) 본질적인', tm: '(형) 순차적인; (형) 잇따라 일어나는', tw: 'sequential' },
    { w: 'respective', m: '(형) 각각의, 각자의', tm: '(형) 존경심을 표하는; (형) 공손한', tw: 'respectful' },
    { w: 'imply', m: '(동) 암시하다, 넌지시 비치다', tm: '(동) 적용하다; (동) 지원하다', tw: 'apply' },
    { w: 'capacity', m: '(명) 용량; (명) 수용 능력', tm: '(명) 감금; (명) 억류', tw: 'captivity' },
    { w: 'conduct', m: '(동) 수행하다; (동) 지휘하다', tm: '(동) 지시하다; (동) 가르치다', tw: 'instruct' },
    { w: 'transaction', m: '(명) 거래; (명) 매매', tm: '(명) 변천, 이행; (명) 과도기', tw: 'transition' },
    { w: 'due', m: '(형) ~할 예정인; (형) 기한이 된', tm: '(명) 이인조; (명) 듀오', tw: 'duo' },
    { w: 'responsibility', m: '(명) 책임, 의무', tm: '(명) 가능성; (명) 가망', tw: 'possibility' },
    { w: 'release', m: '(동) 공개하다; (동) 석방하다', tm: '(동) 깨닫다; (동) 실현하다', tw: 'realize' },
    { w: 'prosperous', m: '(형) 번영하는, 성공한', tm: '(형) 터무니없는; (형) 말도 안 되는', tw: 'preposterous' },
    { w: 'loan', m: '(명) 대출, 융자', tm: '(명) 잔디; (명) 잔디밭', tw: 'lawn' },
    { w: 'admit', m: '(동) 인정하다; (동) 입장시키다', tm: '(동) 생략하다; (동) 빠뜨리다', tw: 'omit' },
    { w: 'ascribe', m: '(동) ~의 탓으로 돌리다', tm: '(동) 묘사하다; (동) 설명하다', tw: 'describe' },
    { w: 'statement', m: '(명) 성명서; (명) 명세서', tm: '(명) 정서, 감정', tw: 'sentiment' },
    { w: 'regulation', m: '(명) 규제, 규정', tm: '(명) 규칙성; (명) 정기적임', tw: 'regularity' },
    { w: 'material', m: '(명) 재료, 자료', tm: '(형) 어머니의; (형) 모성의', tw: 'maternal' },
    { w: 'critical', m: '(형) 비판적인; (형) 대단히 중요한', tm: '(형) 임상의; (형) 병원의', tw: 'clinical' },
    { w: 'draft', m: '(명) 초안; (명) 징병', tm: '(동) 표류하다; (동) 떠가다', tw: 'drift' },

    // [추가] 신규 대체 항목 (토익 빈출 부사 쌍)
    { w: 'formally', m: '(부) 정식으로, 공식적으로', tm: '(부) 이전에, 예전에', tw: 'formerly' },
    { w: 'fare', m: '(명) (교통) 요금; (동) 해내다', tm: '(형) 공정한; (명) 박람회', tw: 'fair' },

    // [명사 혼동 어휘]
    { w: 'recipe', m: '(명) 요리법, 조리법; (명) 비결', tm: '(명) 영수증; (명) 수령, 받음', tw: 'receipt' },
    { w: 'application', m: '(명) 지원서, 신청; (명) 적용', tm: '(명) 가전제품, 기구', tw: 'appliance' },
    { w: 'investment', m: '(명) 투자; (명) 투자금', tm: '(명) 조사, 수사; (명) 연구', tw: 'investigation' },
    { w: 'transportation', m: '(명) 수송, 운송; (명) 교통수단', tm: '(명) 변화, 변신; (명) 개혁', tw: 'transformation' },
    { w: 'reputation', m: '(명) 평판, 명성', tm: '(명) 반복; (명) 암송', tw: 'repetition' },
    { w: 'plumber', m: '(명) 배관공', tm: '(명) 목재', tw: 'lumber' },
    { w: 'satisfaction', m: '(명) 만족; (명) 배상', tm: '(명) (시장) 포화; (명) 포화 상태', tw: 'saturation' },
    { w: 'corrosion', m: '(명) 부식, 녹', tm: '(명) 침식; (명) (가치) 하락', tw: 'erosion' },
    { w: 'ascent', m: '(명) 상승; (명) 오르막길', tm: '(명) 동의, 찬성; (동) 동의하다', tw: 'assent' },
    { w: 'council', m: '(명) 의회, 위원회', tm: '(명) 조언; (명) 변호인단', tw: 'counsel' },
    { w: 'reality', m: '(명) 현실, 실재', tm: '(명) 부동산, 부동산 물건', tw: 'realty' },
    { w: 'award', m: '(명) 상, 상품; (동) 수여하다', tm: '(명) 보상, 사례금; (동) 보답하다', tw: 'reward' },
    { w: 'addition', m: '(명) 추가, 덧셈; (명) 증축 건물', tm: '(명) (출간물의) 판, 호; (명) (방송의) 회', tw: 'edition' },

    // [동사 혼동 어휘]
    { w: 'compete', m: '(동) 경쟁하다, 겨루다', tm: '(동) 완료하다; (형) 완전한', tw: 'complete' },
    { w: 'negotiate', m: '(동) 협상하다; (동) (도로를) 뚫고 나아가다', tm: '(동) 길을 찾다; (동) 항해하다', tw: 'navigate' },
    { w: 'accrue', m: '(동) 축적되다; (동) (이자가) 붙다', tm: '(동) 고발하다, 기소하다; (동) 비난하다', tw: 'accuse' },
    { w: 'retain', m: '(동) 유지하다, 보유하다', tm: '(동) 구금하다; (동) 지체시키다', tw: 'detain' },
    { w: 'remit', m: '(동) 송금하다; (동) 면제하다', tm: '(동) 제출하다; (동) 항복하다', tw: 'submit' },
    { w: 'cite', m: '(동) 인용하다; (동) 소환하다', tm: '(명) 현장, 부지; (명) 웹사이트', tw: 'site' },
    { w: 'inhabit', m: '(동) 살다, 거주하다', tm: '(동) 억제하다; (동) 금지하다', tw: 'inhibit' },
    { w: 'defer', m: '(동) 미루다, 연기하다; (동) 따르다', tm: '(동) 다르다; (동) 의견을 달리하다', tw: 'differ' },
    { w: 'persecute', m: '(동) 박해하다, 괴롭히다', tm: '(동) 기소하다; (동) 추진하다', tw: 'prosecute' },
    { w: 'abolish', m: '(동) (제도를) 폐지하다', tm: '(동) 설립하다; (동) 확고히 하다', tw: 'establish' },
    { w: 'commence', m: '(동) 시작되다, 개시하다', tm: '(동) 칭찬하다; (동) 추천하다', tw: 'commend' },
    { w: 'comprise', m: '(동) 구성하다; (동) 포함하다', tm: '(동) 타협하다; (명) 타협', tw: 'compromise' },
    { w: 'lay', m: '(동) (물건을) 놓다, 두다; (동) 낳다', tm: '(동) 눕다; (동) 거짓말하다', tw: 'lie' },
    { w: 'rise', m: '(동) 오르다, 상승하다; (동) 뜨다', tm: '(동) (들어) 올리다; (동) 모으다', tw: 'raise' },

    // [형용사 및 부사 혼동 어휘]
    { w: 'beneficial', m: '(형) 유익한, 이로운', tm: '(명) 수혜자, 수령인', tw: 'beneficiary' },
    { w: 'permanent', m: '(형) 영구적인, 정규직의', tm: '(형) 저명한; (형) 눈에 띄는', tw: 'prominent' },
    { w: 'considerable', m: '(형) 상당한, 많은', tm: '(형) 사려 깊은, 배려하는', tw: 'considerate' },
    { w: 'later', m: '(부) 나중에; (형) 더 뒤의', tm: '(형) 후자의; (명) 후자', tw: 'latter' },
    { w: 'comprehensible', m: '(형) 이해할 수 있는', tm: '(형) 포괄적인, 종합적인', tw: 'comprehensive' },
    { w: 'human', m: '(형) 인간의; (명) 인간', tm: '(형) 인도적인; (형) 자비로운', tw: 'humane' },
    { w: 'imaginary', m: '(형) 가상의, 상상의', tm: '(형) 창의적인, 상상력이 풍부한', tw: 'imaginative' },
    { w: 'industrial', m: '(형) 산업의, 공업의', tm: '(형) 근면한, 부지런한', tw: 'industrious' },
    { w: 'loyal', m: '(형) 충성스러운, 충실한', tm: '(형) 왕실의; (명) 왕족', tw: 'royal' },
    { w: 'momentary', m: '(형) 순간적인, 찰나의', tm: '(형) 중대한, 중요한', tw: 'momentous' },
    { w: 'negligent', m: '(형) 태만한, 부주의한', tm: '(형) 무시해도 될 정도의', tw: 'negligible' },
    { w: 'successful', m: '(형) 성공적인, 성공한', tm: '(형) 연속적인, 연이은', tw: 'successive' },
    { w: 'continual', m: '(형) 빈번한, 되풀이되는', tm: '(형) (끊김 없이) 계속되는', tw: 'continuous' }
];

const VOCAB_DATA = [];

VOCAB_SOURCE.forEach(item => {
    // Add Original
    VOCAB_DATA.push({
        word: item.w,
        meaning: item.m,
        trap_meaning: item.tm,
        trap_word: item.tw
    });
    // Add Trap Pair
    VOCAB_DATA.push({
        word: item.tw,
        meaning: item.tm,
        trap_meaning: item.m,
        trap_word: item.w
    });
});
