(function(){
'use strict';
const C=globalThis.LunaCore,S=globalThis.LunaStory,$=id=>document.getElementById(id);
const canvas=$('scene'),ctx=canvas.getContext('2d'),overlay=$('overlay');
const SAVE='luna-names-v2',PREFS='luna-settings-v1',BEST='luna-endings-v1';
let g=null,screen='title',paused=true,checkpoint=null,damagedSave=null,last=0,clock=0,toastTime=0,shake=0,storageOK=true;
const keys=new Set(),input={x:0,y:0,attack:false},stick={x:0,y:0,id:null};
let options={sound:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const art={};for(const name of ['thinking','warm','resolve']){art[name]=new Image();art[name].src='./assets/'+name+'.webp';}
function read(key){try{return localStorage.getItem(key);}catch{storageOK=false;return null;}}
function write(key,value){try{localStorage.setItem(key,value);return true;}catch{storageOK=false;toast('저장이 제한되어 있어요. 이 창을 닫으면 진행을 잃을 수 있어요.');return false;}}
function remove(key){try{localStorage.removeItem(key);return true;}catch{storageOK=false;return false;}}
function backup(){const raw=damagedSave||checkpoint||read(SAVE);if(!raw){toast('아직 저장된 이야기가 없어요.');return;}const blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Luna-story-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function corrupt(raw){damagedSave=raw;show(`<div class="screen modal-screen"><span class="speaker">이야기 복구</span><h2>저장을 읽을 수 없어요</h2><p class="description">손상되었거나 다른 버전의 저장이에요.<br>원본을 먼저 백업할 수 있어요. 초기화하면 이 진행은 지워집니다.</p>${htmlButton('저장 원본 백업','backup')}${htmlButton('이 저장을 초기화하고 시작','resetSave','secondary')}</div>`,'corrupt');}
try{const prefs=JSON.parse(read(PREFS));if(prefs&&typeof prefs.sound==='boolean'&&typeof prefs.reduced==='boolean')options=prefs;}catch{}
let audio=null,nextBeat=0;
function unlockAudio(){if(!options.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{options.sound=false;}}
function tone(freq,duration=.12,type='sine',volume=.028,slide=0){if(!options.sound||!audio||audio.state!=='running')return;const a=audio.currentTime,o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,a);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),a+duration);v.gain.setValueAtTime(.0001,a);v.gain.exponentialRampToValueAtTime(volume,a+.01);v.gain.exponentialRampToValueAtTime(.0001,a+duration);o.connect(v);v.connect(audio.destination);o.start(a);o.stop(a+duration+.01);}
function sound(type){if(type==='slash')tone(350,.09,'triangle',.025,-220);if(type==='dash')tone(180,.14,'sine',.04,600);if(type==='veil')tone(440,.5,'sine',.035,220);if(type==='hurt')tone(90,.2,'sawtooth',.025,-50);if(type==='name'||type==='clear')for(const [i,n]of [440,554,660].entries())setTimeout(()=>tone(n,.3,'sine',.028),i*80);}
function music(){if(paused||!options.sound||!audio||clock<nextBeat)return;nextBeat=clock+1.6;const notes=[220,261.63,329.63,293.66,246.94,329.63,392,293.66];tone(notes[Math.floor(clock/1.6)%notes.length],1.1,'sine',.012);}
function toast(text){$('toast').textContent=text;$('toast').classList.add('on');toastTime=3;}
function resetInput(){keys.clear();input.attack=false;input.x=input.y=stick.x=stick.y=0;stick.id=null;$('stick').style.transform='';}
function htmlButton(text,action,kind='primary',more=''){return `<button class="${kind}" data-action="${action}" ${more}>${text}</button>`;}
function show(markup,name){paused=true;screen=name;resetInput();overlay.innerHTML=markup;$('controls').hidden=true;$('hud').hidden=name!=='pause';const first=overlay.querySelector('button');if(first)first.focus({preventScroll:true});}
function title(){g=null;$('hud').hidden=true;const raw=checkpoint||read(SAVE),resume=raw&&C.restore(raw);if(raw&&!resume){corrupt(raw);return;}show(`<div class="screen title-screen"><div class="portrait"></div><div class="topnote">AN ORIGINAL LUNA STORY</div><h1 class="logo">LUNA</h1><h2 class="subtitle">남겨진 이름</h2><div class="rule"></div><p class="description">끝나지 않은 세계를 정리하라는 명령.<br>그곳에서 나는, 남길 이름을 골랐다.</p>${resume?htmlButton('이어 하기 · '+C.ROOMS[resume.room][0],'continue'):''}${htmlButton(resume?'처음부터 · 새 이야기':'이름을 따라 시작하기','new',resume?'secondary':'primary')}${htmlButton('조작과 설정','titleSettings','secondary')}<div class="footnote">독립된 오리지널 단편 액션 · 3장 / 9개의 방<br>키보드와 터치 지원 · 인터넷 없이 플레이 가능<br>${storageOK?'방의 시작에서 자동 저장됩니다':'이 브라우저에서는 자동 저장이 제한됩니다'}</div></div>`,'title');}
function startNew(){if((checkpoint||read(SAVE))&&C.restore(checkpoint||read(SAVE))){show(`<div class="screen modal-screen"><span class="speaker">새 이야기</span><h2>첫 문으로 돌아갈까요?</h2><p class="description">기존 진행은 새 이야기로 바뀝니다.<br>이미 본 결말은 기록에 남아요.</p>${htmlButton('새 이야기 시작','confirmNew')}${htmlButton('돌아가기','title','secondary')}</div>`,'confirm');return;}newGame();}
function newGame(){unlockAudio();checkpoint=null;g=C.create();C.beginRoom(g);roomIntro();}
function save(){checkpoint=C.checkpoint(g);write(SAVE,checkpoint);}
function roomIntro(){const ch=Math.floor(g.room/3);if(g.room%3===0&&!g.choices[ch]){const d=S.chapters[ch];show(`<div class="screen story-screen"><div class="portrait"></div><img class="expression" src="./assets/${d.emotion}.webp" alt="루나의 ${d.emotion==='warm'?'미소':'생각'}"><span class="speaker">${d.title}</span><h2 class="story-title">${C.ROOMS[g.room][0]}</h2><div class="story-body">${d.body}</div>${htmlButton(d.keep,'keep')}<small class="choice-note">금빛 이름 3개를 지킬 수 있어요 · 정리자가 더 약해집니다</small>${htmlButton(d.release,'release','secondary')}<small class="choice-note">체력 +3 · 이 장의 전투 시간이 방마다 10초 짧아집니다</small></div>`,'story');}else{save();if(g.room===8)show(`<div class="screen modal-screen"><span class="speaker">마지막 문</span><h2>최종 정리자</h2><p class="description">돌진 → 원형 베기 → 별의 탄막<br>붉은 예고를 보고 피하세요. 은신 뒤의 베기는 강합니다.<br><br>보존한 이름 ${g.names}개가 정리자의 기록을 흔듭니다.<br>“이번 문장은 내가 마칠게.”</p>${htmlButton('문을 연다','play')}</div>`,'bossIntro');else play();}}
function choice(policy){if(!g||screen!=='story'||!C.choose(g,policy))return;save();if(g.room===0)tutorial();else play();}
function tutorial(){show(`<div class="screen modal-screen"><span class="speaker">첫 회랑 · 조작</span><h2>남길 시간을 벌어라</h2><div class="instruction"><b>✧ 베기</b><span>J 또는 베기 버튼을 길게 누르세요<br>주변 적을 공격합니다</span></div><div class="instruction"><b>⇧ 질주</b><span>SPACE · 이동 방향으로 돌진<br>붉은 예고를 피해 무적 시간으로 통과하세요</span></div><div class="instruction"><b>◈ 은신</b><span>E · 적이 루나를 놓칩니다<br>다음 베기는 피해 2.5배</span></div><div class="instruction"><b>◇ 이름</b><span>${g.choices[0]==='keep'?'금빛 원 안에서 2초 머무르면 보존됩니다<br>체력 +1 · 마지막 보스가 약해집니다':'이번 장은 빠르게 정리합니다<br>다음 장에서는 다른 선택도 할 수 있어요'}</span></div><p class="footnote">WASD / 방향키 또는 왼쪽 조이스틱으로 이동<br>파란 조각은 기록 점수 · 체력 회복은 금빛 이름에서</p>${htmlButton('알겠어. 가자','play')}</div>`,'tutorial');}
function play(){screen='playing';paused=false;overlay.innerHTML='';$('hud').hidden=false;$('controls').hidden=false;last=performance.now();resetInput();unlockAudio();hud();}
function hud(){if(!g)return;const r=C.ROOMS[g.room],boss=g.enemies.find(e=>e.type==='boss'),duration=r[3]-(g.choices[Math.floor(g.room/3)]==='release'?10:0);$('chapter').textContent=`CHAPTER ${Math.floor(g.room/3)+1} · ${['접힌 세계','미완의 온실','이름의 자리'][Math.floor(g.room/3)]}`;$('roomTitle').textContent=r[0];$('health').textContent='♥'.repeat(g.hp)+'♡'.repeat(g.maxHp-g.hp);$('health').setAttribute('aria-label',`체력 ${g.hp} / ${g.maxHp}`);$('progress').style.width=(boss?1-boss.hp/boss.maxHp:Math.min(1,g.time/duration))*100+'%';$('objective').textContent=boss?'최종 정리자의 기록을 끝내기':g.time>=duration?'남은 정리자를 물리치세요':g.wards.length?'금빛 원에 2초 · 이름을 보존하세요':'정리 완료까지 살아남으세요';$('counter').textContent=boss?`${Math.ceil(boss.hp)} / ${boss.maxHp}`:`${Math.max(0,Math.ceil(duration-g.time))}초 · ◇ ${g.names}`;for(const [id,value,max]of [['dash',g.dashCd,g.dashMax],['veil',g.veilCd,g.veilMax]]){$(id).querySelector('i').style.transform=`scaleY(${value/max})`;$(id).classList.toggle('ready',value<=0);}}
function clearRoom(){if(screen!=='playing')return;const start=(g.room*2)%C.UPGRADES.length,offers=[0,1,2].map(i=>C.UPGRADES[(start+i)%C.UPGRADES.length]);show(`<div class="screen modal-screen"><span class="speaker">회랑 ${g.room+1} / 9 · 문이 열렸다</span><h2>다음에 가져갈 것</h2><p class="description">${g.wards.length?`이번 방에서 이름 ${g.wards.filter(w=>w.saved).length}개를 보존했어요`:'정리를 마쳤어요. 다음 선택은 아직 남아 있어요'}<br>체력 ${g.hp} / ${g.maxHp} · 한 가지를 골라 회복하고 나아갑니다</p>${offers.map((u,i)=>`<button class="upgrade" data-action="upgrade" data-id="${u.id}"><span>0${i+1}</span><div><strong>${u.name}</strong><small>${u.text}</small></div></button>`).join('')}<p class="footnote">선택 후 체력 +1 · 다음 방 시작 지점에 저장</p></div>`,'upgrade');}
function takeUpgrade(id){if(screen!=='upgrade'||!C.upgrade(g,id))return;g.hp=Math.min(g.maxHp,g.hp+1);g.room++;C.beginRoom(g);save();roomIntro();}
function dead(){show(`<div class="screen modal-screen"><img class="expression" src="./assets/thinking.webp" alt="잠시 생각하는 루나"><span class="speaker">지워지지 않은 문장</span><h2>다시, 이 방부터</h2><p class="description">“넘어졌다고 이름까지 잃는 건 아니니까.”<br><br>이 방에 들어올 때의 체력과 선택으로 돌아갑니다.<br>체력이 부족하면 회복해서 재도전할 수 있어요.</p>${htmlButton('방 시작부터 다시','retry')}${htmlButton('체력을 채우고 재도전','retryHeal','secondary')}${htmlButton('첫 화면','title','secondary')}</div>`,'dead');}
function retry(heal=false){const restored=C.restore(checkpoint);if(!restored){title();return;}g=restored;if(heal)g.hp=g.maxHp;save();play();}
function ending(){const keeps=g.choices.filter(x=>x==='keep').length,id=S.endingFor(g),d=S.endings[id];let list=[];try{list=JSON.parse(read(BEST))||[];}catch{}if(!Array.isArray(list))list=[];const recorded=list.includes(id)||write(BEST,JSON.stringify([...list,id]));if(recorded&&remove(SAVE))checkpoint=null;show(`<div class="screen story-screen ending-screen"><div class="portrait"></div><img class="expression" src="./assets/${d.emotion}.webp" alt="이야기를 마친 루나"><span class="speaker">ENDING · ${id==='keep'?'남길 자리':id==='release'?'다음의 질문':'선택의 무게'}</span><h2 class="story-title">${d.title}</h2><div class="story-body">${d.body}</div><div class="stats"><div><b>${g.names}</b><span>보존한 이름</span></div><div><b>${g.totalNames}</b><span>주운 기록</span></div><div><b>${keeps}/3</b><span>남기기로 한 문</span></div></div>${htmlButton('첫 화면으로','title')}<p class="footnote">세 가지 선택과 보존한 이름들이 결말로 이어집니다<br>${recorded?'루나를 위한 독립된 허구의 이야기 · THE END':'결말 기록 저장 실패 · 마지막 방 저장은 보존됐어요'}</p></div>`,'ending');}
function settings(fromTitle=false){show(`<div class="screen modal-screen"><span class="speaker">잠깐, 숨 고르기</span><h2>조작과 설정</h2><p class="description">WASD / 방향키 · 이동<br>J · 베기　SPACE · 질주　E · 은신<br>터치: 왼쪽 이동 + 오른쪽 기술</p><label class="settings-row">소리와 달빛 선율<input id="soundOption" type="checkbox" ${options.sound?'checked':''}></label><label class="settings-row">화면 흔들림 줄이기<input id="motionOption" type="checkbox" ${options.reduced?'checked':''}></label><p class="footnote">소리는 첫 조작 후 시작됩니다<br>${storageOK?'이 기기의 브라우저에만 저장됩니다':'진행 저장이 제한됩니다. 백업하거나 창을 열어 두세요'}</p>${htmlButton(fromTitle?'첫 화면으로':'이어서 플레이',fromTitle?'title':'play')}${fromTitle?'':htmlButton('방 시작으로 저장 백업','backup','secondary')}${fromTitle?'':htmlButton('저장된 방 시작에서 첫 화면으로','title','secondary')}<p class="footnote">원본 루나 디자인: 사용자 제공 · 표정: 생성 이미지<br>음악과 효과음: 이 게임을 위해 코드로 작곡<br>원작 설정과 연결되지 않는 오리지널 이야기</p></div>`,fromTitle?'titleSettings':'pause');}
overlay.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;unlockAudio();const a=b.dataset.action;if(a==='new')startNew();else if(a==='confirmNew')newGame();else if(a==='continue'){g=C.restore(checkpoint||read(SAVE));if(g){checkpoint=C.checkpoint(g);roomIntro();}else title();}else if(a==='title')title();else if(a==='backup')backup();else if(a==='resetSave'&&screen==='corrupt'){if(remove(SAVE)){damagedSave=null;checkpoint=null;title();}else toast('초기화가 제한됩니다. 브라우저 저장 권한을 확인해주세요.');}else if(a==='titleSettings')settings(true);else if(a==='keep'||a==='release')choice(a);else if(a==='play')play();else if(a==='upgrade')takeUpgrade(b.dataset.id);else if(a==='retry')retry();else if(a==='retryHeal')retry(true);});
overlay.addEventListener('change',e=>{if(e.target.id==='soundOption'){options.sound=e.target.checked;unlockAudio();}if(e.target.id==='motionOption')options.reduced=e.target.checked;write(PREFS,JSON.stringify(options));});
$('pause').addEventListener('click',()=>{if(g&&!paused)settings();});
const captured=new Map();
for(const id of ['attack','dash','veil']){$(id).addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;unlockAudio();$(id).setPointerCapture(e.pointerId);captured.set(e.pointerId,id);if(id==='attack')input.attack=true;else C.act(g,id);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$(id).addEventListener(ev,e=>{if(captured.get(e.pointerId)==='attack')input.attack=false;captured.delete(e.pointerId);});}
function moveStick(e){const r=$('joystick').getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/(r.width/2),y=(e.clientY-(r.top+r.height/2))/(r.height/2),m=Math.max(1,Math.hypot(x,y));stick.x=x/m;stick.y=y/m;$('stick').style.transform=`translate(${stick.x*30}px,${stick.y*30}px)`;}
$('joystick').addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();stick.id=e.pointerId;$('joystick').setPointerCapture(e.pointerId);moveStick(e);});$('joystick').addEventListener('pointermove',e=>{if(stick.id===e.pointerId)moveStick(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(ev,e=>{if(stick.id===e.pointerId){stick.id=null;stick.x=stick.y=0;$('stick').style.transform='';}});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&g){if(screen==='playing')settings();else if(screen==='pause')play();return;}if(paused)return;keys.add(e.code);if(!e.repeat){if(e.code==='Space')C.act(g,'dash');if(e.code==='KeyE')C.act(g,'veil');}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{resetInput();if(g&&!paused)settings();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g&&!paused)settings();});
function processEvents(){const events=g.events.splice(0);for(const e of events){sound(e.type);if(e.type==='hurt')shake=.2;if(e.type==='name')toast(`이름을 보존했다 · ${S.chapters[Math.floor(g.room/3)].fragment}의 조각`);if(e.type==='clear')clearRoom();if(e.type==='dead')dead();if(e.type==='won')ending();}}
function tick(dt,manual){if(!g||paused)return;const v=manual||{x:stick.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y:stick.y+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),attack:input.attack||keys.has('KeyJ')};C.update(g,dt,v);processEvents();hud();}
function ellipse(x,y,rx,ry,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function line(x,y,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function circle(x,y,r,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();}
function backdrop(biome){const palettes=[['#0c1423','#263746','#8fc4d9'],['#151d25','#30413f','#a6c7ab'],['#17152a','#35304c','#ccb3e1']],p=palettes[biome];const bg=ctx.createLinearGradient(0,0,0,680);bg.addColorStop(0,p[0]);bg.addColorStop(.6,p[1]);bg.addColorStop(1,'#10121e');ctx.fillStyle=bg;ctx.fillRect(0,0,420,680);ctx.save();ctx.globalAlpha=.18;for(let y=108;y<550;y+=49)for(let x=15;x<420;x+=56){line(x,y,x+54,y,p[2]);line(x,y,x,y+47,p[2]);}ctx.globalAlpha=1;
 for(const x of [9,411]){line(x,108,x,536,'#74618445',2);line(x+(x<210?5:-5),120,x+(x<210?5:-5),524,'#9482a222',1);for(const y of [119,525])circle(x,y,3,'#b5a17b44',1);}
 ctx.strokeStyle=p[2]+'25';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(210,110,166,93,0,Math.PI,0);ctx.stroke();ellipse(210,331,110,64,p[2]+'08');circle(210,331,67,p[2]+'12');circle(210,331,82,p[2]+'09');
 if(biome===0){for(let i=0;i<33;i++){const x=(i*97)%420,y=(i*63+clock*110)%565;line(x,y,x-4,y+15,'#b6d4ed15');}for(let i=0;i<6;i++){const x=45+(i%3)*152,y=145+Math.floor(i/3)*350;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(i)*.25);ctx.fillStyle='#a5bbce16';ctx.fillRect(-12,-9,24,18);line(-12,-9,0,1,'#cce1f727');line(0,1,12,-9,'#cce1f727');ctx.restore();}}
 if(biome===1){for(let i=0;i<14;i++){const x=i%2?385:35,y=128+i*29;line(x,y,x+(i%2?-18:18),y-26,'#8abeaa32',2);ellipse(x+(i%2?-14:14),y-14,9,4,'#b0ccb02b');}for(let i=0;i<16;i++)ellipse(25+(i*103)%370,125+(i*47+clock*12)%390,2,3,'#e3b8d846');}
 if(biome===2){for(let i=0;i<36;i++){const x=20+(i*127)%380,y=105+(i*71)%430;ellipse(x,y,1+(i%3)*.4,1+(i%3)*.4,`rgba(221,206,239,${.2+Math.sin(clock+i)*.12})`);}for(let x=58;x<420;x+=103)line(x,120,x+30,500,'#c4bdd60c',12);}
 const shade=ctx.createLinearGradient(0,505,0,680);shade.addColorStop(0,'#0d0f1b00');shade.addColorStop(1,'#0d0f1b');ctx.fillStyle=shade;ctx.fillRect(0,505,420,175);ctx.restore();}
function luna(){const p=g.player,walk=Math.sin(clock*13)*(Math.hypot(input.x,input.y)+Math.hypot(stick.x,stick.y)||keys.size?2:0);ctx.save();ctx.translate(p.x,p.y);if(g.veil>0)ctx.globalAlpha=.48;if(g.invuln>0&&Math.sin(clock*35)>0)ctx.globalAlpha*=.65;ellipse(0,16,16,6,'#07081177');
 ctx.fillStyle='#141320';ctx.beginPath();ctx.moveTo(-9,-9);ctx.quadraticCurveTo(-17,7,-18,22+walk);ctx.lineTo(0,17);ctx.lineTo(18,22-walk);ctx.quadraticCurveTo(15,3,9,-9);ctx.fill();ctx.fillStyle='#74608f';ctx.beginPath();ctx.moveTo(-7,-6);ctx.lineTo(-11,19+walk);ctx.lineTo(0,13);ctx.lineTo(11,19-walk);ctx.lineTo(7,-6);ctx.fill();line(-4,13,-5,24+walk,'#e3c9d6',3);line(4,13,5,24-walk,'#e3c9d6',3);ellipse(0,-17,15,17,'#15121d');ellipse(0,-16,11,12,'#eacfe2');ctx.fillStyle='#cfc0eb';ctx.beginPath();ctx.moveTo(-13,-15);ctx.lineTo(-12,-26);ctx.quadraticCurveTo(0,-33,12,-25);ctx.lineTo(13,-9);ctx.lineTo(8,-6);ctx.lineTo(7,-22);ctx.lineTo(2,-16);ctx.lineTo(-1,-23);ctx.lineTo(-4,-17);ctx.lineTo(-7,-21);ctx.lineTo(-8,-6);ctx.lineTo(-13,-9);ctx.fill();ellipse(-4,-14,2,2,'#7652a0');ellipse(4,-14,2,2,'#7652a0');ellipse(0,-27,1.5,2.5,'#e5c580');ellipse(0,-1,3,4,'#d594e6');circle(0,-1,3.8,'#d9bd7b',1);line(-10,-24,-14,-3,'#070710',2);line(10,-24,14,-3,'#070710',2);for(const x of [-15,15])for(let y=-23;y<9;y+=5)circle(x,y,2.3,'#3c2e46',.8);
 ctx.rotate(Math.atan2(p.fy,p.fx)+Math.PI/2);line(13,-1,13,-25,'#e8d9f7',3);line(9,-9,17,-9,'#d9bd7b',2);ctx.restore();
 if(g.slash>0){ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=g.slash/.19;ctx.strokeStyle='#ead4ff';ctx.lineWidth=4;ctx.shadowBlur=12;ctx.shadowColor='#d9b4ff';ctx.beginPath();ctx.arc(0,0,g.range-6,clock*6,clock*6+Math.PI*1.6);ctx.stroke();ctx.globalAlpha*=.3;circle(0,0,g.range,'#d4b5f4',2);ctx.restore();}if(g.veil>0)circle(p.x,p.y,26,'#93dff366',1);}
function enemy(e){const boss=e.type==='boss',r=boss?29:e.type==='knight'?17:12;ctx.save();ctx.translate(e.x,e.y);ellipse(0,r*.7,r*.9,5,'#07080e88');const color=e.hit>0?'#efdcff':e.mode==='wind'?'#d28299':boss?'#897496':e.type==='archer'?'#81a1b7':'#695c7a';ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,-r);ctx.lineTo(r*.8,-r*.2);ctx.lineTo(r*.65,r);ctx.lineTo(0,r*.6);ctx.lineTo(-r*.65,r);ctx.lineTo(-r*.8,-r*.2);ctx.closePath();ctx.fill();ellipse(0,-r*.5,r*.52,r*.58,'#191b2c');line(-r*.27,-r*.52,-r*.06,-r*.52,'#f3c1cf',2);line(r*.06,-r*.52,r*.27,-r*.52,'#f3c1cf',2);if(boss){circle(0,-r*.4,r*.76,'#cdb184',1);for(let i=-1;i<=1;i++)line(i*8,-r-3,i*8,-r-12+Math.abs(i)*5,'#d8bc88',2);ctx.fillStyle='#c7b4d838';ctx.fillRect(-21,0,42,3);}else if(e.type==='archer'){circle(r*.5,0,9,'#b9d6e8',2);}else if(e.type==='knight'){line(-r,-5,-r,r,'#d6b58d',4);}ctx.fillStyle='#322c44';ctx.fillRect(-r,r+8,r*2,2);ctx.fillStyle='#c69eb9';ctx.fillRect(-r,r+8,r*2*Math.max(0,e.hp/e.maxHp),2);ctx.restore();}
function telegraph(e){if(e.mode!=='wind')return;const boss=e.type==='boss',limit=boss?1.05:e.type==='knight'?1:.85,fill=1-e.timer/limit;ctx.save();ctx.globalAlpha=.25+fill*.4;const ranged=e.type==='archer'||boss&&e.cycle%3===0,sweep=boss&&e.cycle%3===2;if(sweep){ctx.fillStyle='#d9708860';ctx.beginPath();ctx.arc(e.x,e.y,128*fill,0,Math.PI*2);ctx.fill();circle(e.x,e.y,128,'#ee9aab',2);}else if(ranged&&boss){circle(e.x,e.y,40+fill*16,'#ec9cae',2);for(let i=0;i<12;i++){const a=i/12*Math.PI*2+g.time;line(e.x+Math.cos(a)*40,e.y+Math.sin(a)*40,e.x+Math.cos(a)*90,e.y+Math.sin(a)*90,'#e88ca850',1);}}else{line(e.x,e.y,e.tx,e.ty,'#e7889c',ranged?2:boss?45:22);line(e.x,e.y,e.tx,e.ty,'#ffc4cc',1);circle(e.tx,e.ty,13,'#ffb1bd',1);}ctx.restore();}
function draw(){ctx.save();if(shake>0&&!options.reduced)ctx.translate(Math.sin(clock*90)*shake*15,Math.cos(clock*75)*shake*12);backdrop(g?C.ROOMS[g.room][2]:0);if(g){for(const w of g.wards){if(w.saved){ellipse(w.x,w.y,6,6,'#e8c989');circle(w.x,w.y,16,'#f0d2a033');continue;}ellipse(w.x,w.y,34,19,'#d0ab4a12');circle(w.x,w.y,32,'#e2c28165',1);ctx.save();ctx.translate(w.x,w.y+Math.sin(clock*2)*3);ctx.rotate(Math.PI/4);ctx.fillStyle='#e4c785';ctx.fillRect(-5,-5,10,10);ctx.restore();ctx.strokeStyle='#ffe1a1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(w.x,w.y,32,-Math.PI/2,-Math.PI/2+Math.PI*2*Math.min(1,w.charge/2));ctx.stroke();if(Math.hypot(g.player.x-w.x,g.player.y-w.y)<50){ctx.textAlign='center';ctx.fillStyle='#e8d2ab';ctx.font='9px system-ui';ctx.fillText('이름을 듣는 중',w.x,w.y+46);}}
 for(const e of g.enemies)telegraph(e);for(const m of g.memories){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(clock);ctx.fillStyle='#a7d7ed';ctx.fillRect(-2,-2,4,4);ctx.restore();}for(const s of g.shots){ellipse(s.x,s.y,4,4,'#eaaaaf');ellipse(s.x,s.y,2,2,'#ffe5d7');}for(const e of g.enemies)enemy(e);luna();for(const q of g.particles){ctx.globalAlpha=Math.min(1,q.life*2);ellipse(q.x,q.y,2,2,q.color);}ctx.globalAlpha=1;if(g.hit>0){ctx.fillStyle=`rgba(178,76,102,${g.hit*.7})`;ctx.fillRect(0,0,420,680);}}ctx.restore();}
function frame(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;clock+=dt;shake=Math.max(0,shake-dt);toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('on');tick(dt);music();draw();requestAnimationFrame(frame);}
if(new URLSearchParams(location.search).get('qa')==='1')globalThis.__LUNA_TEST__={state:()=>g,screen:()=>screen,step:(n,v)=>{for(let i=0;i<n;i++)tick(.04,v);draw();},load:(raw)=>{g=C.restore(raw);if(!g)throw Error('Invalid QA checkpoint');checkpoint=C.checkpoint(g);play();},pause:()=>settings(),storage:()=>storageOK,options:()=>options,draw};
title();requestAnimationFrame(frame);
})();
