import {adventure,HEROES} from '../data/catalog.js';
import {TEMP_RELICS,SUPPORTS} from '../combat/effects.js';
import {generator,hash,random,requireThat,clamp} from '../core/rng.js';
import {relativeDay,totalStage} from '../core/state.js';
import {snapshot} from './growth.js';
import {expeditionEncounter,bossEncounter} from '../combat/encounter.js';
export function startAdventure(s,heroId){requireThat(totalStage(s)>=60,'모험은 원정 합계 60에서 열립니다.');requireThat(!s.adventure||s.adventure.finished||s.adventure.failed,'진행 중인 모험을 먼저 마쳐 주세요.');const week=Math.floor(relativeDay(s)/7),slots=s.adventureSlots[week]||[],index=slots.findIndex(x=>!x.cleared),slot=index>=0?index:slots.length,practice=slot>=3;let seed=slots[slot]?.seed;if(seed===undefined){seed=Math.floor(random(s,'adventure')*4294967296);if(!practice)slots[slot]={seed,cleared:false};}s.adventureSlots[week]=slots;
 const rng=generator(seed),pool=adventure.events.filter(x=>!['rest','vista'].includes(x.id)).map(x=>x.id);for(let i=pool.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}
 const path=['rest',...pool.slice(0,3)];if(rng()<.12)path[1+Math.floor(rng()*3)]='vista';
 s.adventure={id:`adventure:${week}:${slot}:${seed}`,heroId,week,slot,practice,seed,node:1,path,items:[],hpRatio:1,eventBonus:{},bossBonus:{},choices:[],offer:[],finished:false,failed:false};return s.adventure;
}
export function adventureLoadout(s){const run=s.adventure,l=snapshot(s,run.heroId);l.level=50;l.gear={weapon:20,armor:20,accessory:20};l.statNodes=6;l.companionRanks=Object.fromEntries(Object.keys(l.companionRanks).map(k=>[k,0]));l.artifact=null;l.artifactRank=0;l.temporaryItems=run.items;l.startHPRatio=run.hpRatio;l.eventBonus=run.eventBonus;return l;}
export function adventureEncounter(s){const run=s.adventure,e=run.node===8?bossEncounter('pharaoh',1):expeditionEncounter(run.heroId,148);const f=(1+.05*49)**2;e.hp=(run.node===8?9000:2000)*f*(1+clamp((run.node===8?run.bossBonus.hp:0)||run.eventBonus.enemyHP||0,-.3,.3));e.atk=(run.node===8?60:28.8)*f*(1+clamp((run.node===8?run.bossBonus.atk:0)||run.eventBonus.enemyATK||0,-.3,.3));e.def=e.mdef=60*(1+.015*49);e.id=run.id+':'+run.node;e.maxTicks=1200;e.stage=148;return e;}
export function offerRelics(run,count=3){const available=Object.keys(TEMP_RELICS).filter(x=>!run.items.includes(x)),rng=generator(hash([run.seed,run.node,run.choices.length,run.items]));for(let i=available.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[available[i],available[j]]=[available[j],available[i]];}run.offer=available.slice(0,count);if(!run.offer.length)run.hpRatio=Math.min(1,run.hpRatio+.2);}
export function adventureResult(s,result){const r=s.adventure;requireThat(r&&!r.finished&&!r.failed&&[1,3,5,8].includes(r.node)&&result.encounterId===r.id+':'+r.node,'모험 전투가 현재 노드와 다릅니다.');requireThat(hash(adventureLoadout(s))===result.loadoutHash,'모험 편성이 바뀌었습니다.');r.hpRatio=result.heroHP/result.heroMaxHP;r.eventBonus={};if(result.winner!=='hero'){r.failed=true;return {failed:true};}if(r.items.includes('warm_return'))r.hpRatio=Math.min(1,r.hpRatio+.2);if(r.node===8){r.finished=true;if(!r.practice&&!s.adventureSlots[r.week][r.slot].cleared){s.adventureSlots[r.week][r.slot].cleared=true;s.wallets.adventureBadges++;}}else {r.node++;offerRelics(r);}return r;}
export const eventFor=r=>adventure.events.find(x=>x.id===r.path[[2,4,6,7].indexOf(r.node)]);
export function chooseEvent(s,index){const r=s.adventure;requireThat(r&&!r.failed&&!r.finished&&!r.offer.length&&[2,4,6,7].includes(r.node)&&[0,1].includes(index),'현재 사건의 선택을 확인해 주세요.');const event=eventFor(r),b=r.eventBonus,heal=n=>{r.hpRatio=Math.min(1,r.hpRatio+n);},hurt=n=>{r.hpRatio=Math.max(.001,r.hpRatio*(1-n));},record=()=>{if(!s.adventureRecords.includes(event.id))s.adventureRecords.push(event.id);},offer=n=>offerRelics(r,n);
 const effects={signpost:[()=>b.enemyHP=-.15,()=>{hurt(.1);b.enemyATK=-.25;}],rest:[()=>heal(.25),()=>{heal(.1);b.mp=(b.mp||0)+20;}],maintenance:[()=>b.atk=.15,()=>b.matk=.15],record:[()=>{record();heal(.1);},()=>b.regen=1],fork:[()=>heal(.15),()=>{hurt(.15);offer(3);}],chest:[()=>offer(2),()=>heal(.2)],spirit:[()=>heal(.15),()=>{hurt(.1);b.shield=.25;}],stage:[()=>{record();b.mp=(b.mp||0)+10;},()=>b.normal=.2],rain:[()=>heal(.2),()=>{hurt(.1);b.direct=.15;}],suggestion:[()=>{const id=s.heroes[r.heroId].companions[0];if(['guardian','great_detective','siren','time_magician','galaxy_whale','cherry_prince'].includes(id)||!id)b.shield=.15;else b.support0=.3;},()=>{const id=s.heroes[r.heroId].companions[1];if(['guardian','great_detective','siren','time_magician','galaxy_whale','cherry_prince'].includes(id)||!id)b.mp=(b.mp||0)+15;else b.support1=.3;}],trace:[()=>r.bossBonus.atk=-.15,()=>r.bossBonus.hp=-.1],vista:[()=>{record();heal(.3);},()=>{record();offer(3);} ]};
 effects[event.id][index]();r.choices.push({node:r.node,event:event.id,index});r.node++;return r;
}
