import {HERO,balance} from '../data/catalog.js';
import {requireThat,random} from '../core/rng.js';
export const F=level=>(1+.05*(level-1))**2;
export function levelCost(s,id){const l=s.heroes[id].level,max=Math.max(...Object.values(s.heroes).map(h=>h.level)),xp=Math.ceil((20+4*l+l*l)*(max+l)/(2*max));return {xp,gold:Math.ceil(1.5*xp)};}
export const gearCost=g=>({forgeOre:10+4*g,gold:120+40*g+10*g*g});
export function purchaseLevels(s,id,count){requireThat(HERO[id]&&Number.isInteger(count)&&count>0&&count<=399,'영웅과 훈련 수량을 확인해 주세요.');const h=s.heroes[id],receipt={levels:0,xp:0,gold:0};for(let i=0;i<count&&h.level<400;i++){const c=levelCost(s,id);if(s.wallets.xp<c.xp||s.wallets.gold<c.gold)break;for(const k of ['xp','gold']){s.wallets[k]-=c[k];receipt[k]+=c[k];}h.level++;receipt.levels++;}requireThat(receipt.levels>0,'훈련할 자원이 부족하거나 최고 레벨입니다.');return receipt;}
export function upgradeGear(s,id,slot,count=1){const h=s.heroes[id];requireThat(Number.isInteger(count)&&count>0&&count<=100,'강화 수량을 확인해 주세요.');requireThat(h&&['weapon','armor','accessory'].includes(slot),'장비를 확인해 주세요.');requireThat(slot!=='accessory'||Object.values(s.heroes).reduce((a,h)=>a+h.stage,0)>=20,'장신구는 원정 합계 20에서 열립니다.');const result={levels:0,refund:0,great:0};for(let i=0;i<Math.min(count,100)&&h.gear[slot]<100;i++){const c=gearCost(h.gear[slot]);if(Object.entries(c).some(([k,v])=>s.wallets[k]<v))break;for(const [k,v]of Object.entries(c))s.wallets[k]-=v;h.gear[slot]++;result.levels++;if(random(s,'reward')<.1){const refund=c.forgeOre/2;s.wallets.forgeOre+=refund;result.refund+=refund;result.great++;}s.rewards.counters.gear=(s.rewards.counters.gear||0)+1;}requireThat(result.levels>0,'강화할 자원이 부족하거나 최고 단계입니다.');return result;}
export function buyNode(s,id){const h=s.heroes[id],cost=36+12*h.nodes;requireThat(h.nodes<60&&h.training>=cost,'훈련점이 더 필요합니다.');h.training-=cost;h.nodes++;return {node:h.nodes,cost};}
export function snapshot(s,id){const h=s.heroes[id];return structuredClone({heroId:id,level:h.level,nodes:h.nodes,style:h.style,gear:h.gear,gearChoices:h.gearChoices,companions:h.companions,artifact:h.artifact,tactics:h.tactics,companionRanks:Object.fromEntries(h.companions.filter(Boolean).map(k=>[k,s.companions[k].rank])),artifactRank:s.artifacts[h.artifact]||0});}
export function baseStats(loadout){const b=HERO[loadout.heroId].stats,h=loadout,nodes=h.statNodes??h.nodes,attack=(1+.025*h.gear.weapon)*(1+.03*nodes+.02*Math.max(0,(h.artifactRank||0)-1));return {hp:b.hp*F(h.level)*(1+.03*h.gear.armor),atk:b.atk*F(h.level)*attack,matk:b.matk*F(h.level)*attack,def:b.def*(1+.015*(h.level-1))*(1+.015*h.gear.armor),mdef:b.mdef*(1+.015*(h.level-1))*(1+.015*h.gear.armor)};}
