import library from '../data/learning.json' with {type:'json'};
import {GATES} from '../data/catalog.js';
import {random,requireThat,hash} from '../core/rng.js';
import {HOUR,rates} from '../core/state.js';
import {resolveSummon} from './gacha.js';
export {library};
export function makeQuestion(s,kind){const pick=a=>a[Math.floor(random(s,'learning')*a.length)];if(kind==='grammar'){const list=library.grammar.flatMap(l=>(l.quizzes||[]).map((q,i)=>({...q,id:`g:${l.id}:${i}`,lecture:library.grammar.find(x=>x.id===q.lecture_id)||l}))),q=pick(list);return {...q,kind,prompt:q.question,explanation:q.desc};}if(kind==='collocation'){const q=pick(library.collocation);return {id:'c:'+q.id,kind,prompt:q.question,options:q.options,answer:q.answer,explanation:q.expression+' — '+q.meaning+'\n'+(q.translation||'')};}const q=pick(library.vocab),wrong=[...new Set(library.vocab.map(x=>x.m).filter(x=>x!==q.m))],options=[q.m];while(options.length<4){const word=pick(wrong);if(!options.includes(word))options.push(word);}for(let i=options.length-1;i>0;i--){const j=Math.floor(random(s,'learning')*(i+1));[options[i],options[j]]=[options[j],options[i]];}return {id:'v:'+q.w,kind:'vocab',prompt:q.w,options,answer:q.m,explanation:q.w+' — '+q.m+(q.tw?'\n혼동 주의: '+q.tw+' — '+q.tm:'')};}
export function gateAvailable(s,gate,now,batchId){if(s.gates.used[gate]===s.calendar.day)return false;if(gate==='return')return !!s.gates.claim&&!s.gates.claim.amplified&&s.gates.claim.amounts.xp>0;if(gate==='echo'){const b=s.gacha.batches.find(x=>x.id===batchId);return s.gates.echoCharge&&!!b&&b.count===10&&b.revealed&&!b.echoed;}if(gate==='grace')return !s.gates.grace||s.gates.grace.end<=now;return false;}
export function beginGate(s,gate,now,batchId){requireThat(gateAvailable(s,gate,now,batchId),'현재 사용할 수 없는 보너스입니다.');const previous=s.gates.challenge;if(previous&&previous.gate===gate&&previous.day===s.calendar.day&&previous.batchId===(batchId||null)&&(gate!=='return'||previous.claimId===s.gates.claim?.id))return previous;const q=makeQuestion(s,GATES[gate].kind);s.gates.challenge={id:'quiz-'+hash([s.profileId,s.revision,gate]),gate,day:s.calendar.day,batchId:batchId||null,claimId:s.gates.claim?.id,question:q,lectureRead:false,answered:false,wrong:false};return s.gates.challenge;}
export function answerGate(s,id,answer,now){const c=s.gates.challenge;requireThat(c&&c.id===id&&!c.answered&&c.day===s.calendar.day,'새 학습 보너스를 열어 주세요.');requireThat(c.question.kind!=='grammar'||c.lectureRead,'관련 강의를 먼저 확인해 주세요.');requireThat(c.question.options.includes(answer),'선택지를 확인해 주세요.');requireThat(gateAvailable(s,c.gate,now,c.batchId),'보너스 상태가 변경되었습니다.');if(c.gate==='return')requireThat(s.gates.claim.id===c.claimId,'새 수령 내역에 맞춰 보너스를 다시 열어 주세요.');s.learning.total++;const correct=answer===c.question.answer;c.wrong=!correct;if(!correct){if(!s.learning.mistakes.some(x=>x.id===c.question.id))s.learning.mistakes.push(c.question);s.learning.mistakes=s.learning.mistakes.slice(-100);return {correct:false,explanation:c.question.explanation};}s.learning.correct++;s.learning.mistakes=s.learning.mistakes.filter(x=>x.id!==c.question.id);c.answered=true;s.gates.used[c.gate]=s.calendar.day;let reward;
 if(c.gate==='return'){reward=s.gates.claim.amounts;for(const k of ['xp','gold'])s.wallets[k]+=reward[k];s.gates.claim.amplified=true;}
 if(c.gate==='echo'){const b=s.gacha.batches.find(x=>x.id===c.batchId);b.echoed=true;s.gates.echoCharge=false;reward=resolveSummon(s,b.pool,1,id+':echo',{free:true});}
 if(c.gate==='grace'){const r=rates(s),sum={xp:0,gold:0};for(const v of Object.values(r)){sum.xp+=v.xp;sum.gold+=v.gold;}s.gates.grace={start:now,end:now+HOUR/2,rates:sum};reward={minutes:30};}
 return {correct:true,reward};
}
